### ISSUE TITLE
I am unable to create anything

### ISSUE THREAD

**Issue by tkembo** [akaunting/akaunting#1015]
### Steps to reproduce the issue

I have installed akaunting on a shared hosting platform. I have the latest version installed. When I try to create a new company, or vendor or a lot of other things, the page just reloads and nothing is created. I can't find anything help in my apache log but in DevTools, I see the following two errors (I don't know if this is helpful). Any idea what is going on?:

```
companies.js?v=2.0.1:1 Uncaught SyntaxError: Unexpected token '<'
search.js?v=2.0.1:1 Uncaught SyntaxError: Unexpected token '<'
```

### System information (Akaunting, PHP versions)

```
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2019-09-16T12:58:48

PHP 7.2.24-0ubuntu0.18.04.1 (cli) (built: Oct 28 2019 12:07:07) ( NTS )
```

**Comment by denisdulici** [comment]
Make sure you've followed the installation steps:

https://github.com/akaunting/akaunting#installation
