### ISSUE TITLE
Exception thrown with artisan commands

### ISSUE THREAD

**Issue by alex-phillips** [akaunting/akaunting#1016]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Fresh install, run `php artisan optimize`

### Expected result
Success message or exit code

### Actual result
```
root@89319601a2db:/app/akaunting# php artisan optimize

   Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Modules\PaypalStandard\Providers\PaypalStandardServiceProvider' not found

  at /app/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208
    204|      * @return \Illuminate\Support\ServiceProvider
    205|      */
    206|     public function createProvider($provider)
    207|     {
  > 208|         return new $provider($this->app);
    209|     }
    210| }
    211|

  Exception trace:

  1   Illuminate\Foundation\ProviderRepository::createProvider("Modules\PaypalStandard\Providers\PaypalStandardServiceProvider")
      /app/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:144

  2   Illuminate\Foundation\ProviderRepository::compileManifest()
      /app/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:61

  Please use the argument -v to see more details.
```

### System information (Akaunting, PHP versions)
php 7.2.22
akaunting 2.0.1

**Comment by alex-phillips** [comment]
I can't perform any artisan commands or view the web UI on a fresh install. Did I miss an install step? There is no `PaypalStandardServiceProvider` class in the codebase that I can find.

**Comment by denisdulici** [comment]
Alex, make sure you've followed the installation steps:

https://github.com/akaunting/akaunting#installation

**Comment by krystalcode** [comment]
I have the same issue. I had a `1.3.17` installation working fine and I'm getting this error after upgrading to `2.0.1`. Are there any special upgrade instructions for upgrading from `1+` to `2+`?

**Comment by krystalcode** [comment]
After renaming the `modules/PaypalStandard/Providers/Main.php` file to `modules/PaypalStandard/Providers/PaypalStandardServiceProvider.php`, that error went away as the file exists.

Now I get the following which I'm not sure how it needs to be resolved as I'm not sure what this `start.php` file is meant to be. Removing the `PaypalStandard` module from the filesystem resolves the issue, if you don't need it.

```
@php artisan package:discover --ansi

ErrorException  : include(/var/www/html/modules/PaypalStandard/start.php): failed to open stream: No such file or directory

  at /var/www/html/vendor/akaunting/module/src/Module.php:315
    311|      */
    312|     protected function registerFiles()
    313|     {
    314|         foreach ($this->get('files', []) as $file) {
  > 315|             include $this->path . '/' . $file;
    316|         }
    317|     }
    318| 
    319|     /**

  Exception trace:

  1   include()
      /var/www/html/vendor/akaunting/module/src/Module.php:315

  2   Akaunting\Module\Module::registerFiles()
      /var/www/html/vendor/akaunting/module/src/Module.php:277

  Please use the argument -v to see more details.
```

**Comment by alex-phillips** [comment]
Any update on this?
