### ISSUE TITLE
[Vue warn]: Error in render: "TypeError: Cannot read property 'hostname' of undefined"

### ISSUE THREAD

**Issue by mwkcoding** [akaunting/akaunting#1022]
Hello I was going to try out Akaunting 2.0 by setting it up on a local webserver but it keeps hanging after submitting database information.

### Steps to reproduce the issue
1. Install 2.0.1 from GitHub release
2. Setup local webserver
3. Attempt to complete setup steps.

### Expected result

Successful install configuration, no errors

### Actual result

Setup hangs after submitting database information.
Screenshot of browser console after submitting:
![image](https://user-images.githubusercontent.com/16936030/71328683-973e2b00-251b-11ea-8c62-69eed86f3c18.png)

### System information (Akaunting, PHP versions)

Akaunting 2.0.1
(Wampserver version 3.0.2)
 - PHP 7.3.12
 - Apache 2.4.41
 - MariaDB 10.4.10

### Additional comments

Virtual Host setup:
```
<VirtualHost *:80>
  ServerName akaunt.test
  ServerAlias akaunt.test
  DocumentRoot "C:/repositories/akaunting_2"
  <Directory "C:/repositories/akaunting_2">
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    Require local
  </Directory>
</VirtualHost>
```

**Comment by denisdulici** [comment]
Fixed in latest master.
