### ISSUE TITLE
akaunting2.0.1  [FatalThrowableErrorUndefined class constant 'XLSX']

### ISSUE THREAD

**Issue by amittechelp** [akaunting/akaunting#1027]
Hello,

akaunting 2.0.1 - Whoops, looks like something went wrong.

This issue occurred while setup installation. while installation I have faced the following issue :

(1/1) FatalThrowableErrorUndefined class constant 'XLSX'
![Capture](https://user-images.githubusercontent.com/28892776/71431646-f64a9e00-26db-11ea-8a32-a8b36a5a7cb2.JPG)

--
in excel.php line 91
at require()in LoadConfiguration.php line 71
at LoadConfiguration->loadConfigurationFiles(object(Application), object(Repository))in LoadConfiguration.php line 39
at LoadConfiguration->bootstrap(object(Application))in Application.php line 208
at Application->bootstrapWith(array('Illuminate\\Foundation\\Bootstrap\\LoadEnvironmentVariables', 'Illuminate\\Foundation\\Bootstrap\\LoadConfiguration', 'Illuminate\\Foundation\\Bootstrap\\HandleExceptions', 'Illuminate\\Foundation\\Bootstrap\\RegisterFacades', 'Illuminate\\Foundation\\Bootstrap\\RegisterProviders', 'Illuminate\\Foundation\\Bootstrap\\BootProviders'))in Kernel.php line 162
at Kernel->bootstrap()in Kernel.php line 146
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 27

**Comment by denisdulici** [comment]
I was not able to reproduce such an issue. Furthermore, there is no `XLSX` constant in `config/excel.php` file. Follow the installation instructions https://github.com/akaunting/akaunting#installation
