### ISSUE TITLE
2.0.0 [npm run dev  ... Error]

### ISSUE THREAD

**Issue by amittechelp** [akaunting/akaunting#1034]
Please suggest ...

# npm run dev

> akaunting@2.0.0 dev /temp/akaunting/akaunting-2.0.0
> npm run development

> akaunting@2.0.0 development /temp/akaunting/akaunting-2.0.0
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

98% after emitting SizeLimitsPlugin

 ERROR  Failed to compile with 2 errors                                                                                                                                             9:43:52 AM

 error  in ./resources/assets/sass/argon.scss

Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

  @include form-control-focus($ignore-warning: true);
          ^
      Wrong number of arguments (1 for 0) for `form-control-focus'
      in /temp/akaunting/akaunting-2.0.0/node_modules/bootstrap/scss/_forms.scss (line 40, column 12)
    at runLoaders (/temp/akaunting/akaunting-2.0.0/node_modules/webpack/lib/NormalModule.js:316:20)
    at /temp/akaunting/akaunting-2.0.0/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /temp/akaunting/akaunting-2.0.0/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/temp/akaunting/akaunting-2.0.0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (/temp/akaunting/akaunting-2.0.0/node_modules/sass-loader/dist/index.js:89:7)
    at Object.done [as callback] (/temp/akaunting/akaunting-2.0.0/node_modules/neo-async/async.js:8067:18)
    at options.error (/temp/akaunting/akaunting-2.0.0/node_modules/node-sass/lib/index.js:294:32)

 error  in ./resources/assets/sass/argon.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

  @include form-control-focus($ignore-warning: true);
          ^
      Wrong number of arguments (1 for 0) for `form-control-focus'
      in /temp/akaunting/akaunting-2.0.0/node_modules/bootstrap/scss/_forms.scss (line 40, column 12)

 @ ./resources/assets/sass/argon.scss 2:14-267

                                                                                      Asset      Size                       Chunks             Chunk Names
                                                                         /js/auth/forgot.js  4.33 MiB              /js/auth/forgot  [emitted]  /js/auth/forgot
                                                                          /js/auth/login.js  4.33 MiB               /js/auth/login  [emitted]  /js/auth/login
                                                                    /js/auth/permissions.js  4.33 MiB         /js/auth/permissions  [emitted]  /js/auth/permissions
                                                                          /js/auth/reset.js  4.33 MiB               /js/auth/reset  [emitted]  /js/auth/reset
                                                                          /js/auth/roles.js  4.34 MiB               /js/auth/roles  [emitted]  /js/auth/roles
                                                                          /js/auth/users.js  4.33 MiB               /js/auth/users  [emitted]  /js/auth/users
                                                                    /js/banking/accounts.js  4.34 MiB         /js/banking/accounts  [emitted]  /js/banking/accounts
                                                             /js/banking/reconciliations.js  4.33 MiB  /js/banking/reconciliations  [emitted]  /js/banking/reconciliations
                                                                /js/banking/transactions.js  4.33 MiB     /js/banking/transactions  [emitted]  /js/banking/transactions
                                                                   /js/banking/transfers.js  4.33 MiB        /js/banking/transfers  [emitted]  /js/banking/transfers
                                                                    /js/common/companies.js  4.33 MiB         /js/common/companies  [emitted]  /js/common/companies
                                                                    /js/common/dashboard.js  4.39 MiB         /js/common/dashboard  [emitted]  /js/common/dashboard
                                                                        /js/common/items.js  4.33 MiB             /js/common/items  [emitted]  /js/common/items
                                                                      /js/common/reports.js  4.34 MiB           /js/common/reports  [emitted]  /js/common/reports
                                                                       /js/common/search.js  1.19 MiB            /js/common/search  [emitted]  /js/common/search
                                                                      /js/expenses/bills.js  4.34 MiB           /js/expenses/bills  [emitted]  /js/expenses/bills
                                                                   /js/expenses/payments.js  4.33 MiB        /js/expenses/payments  [emitted]  /js/expenses/payments
                                                                    /js/expenses/vendors.js  4.33 MiB         /js/expenses/vendors  [emitted]  /js/expenses/vendors
                                                                   /js/incomes/customers.js  4.34 MiB        /js/incomes/customers  [emitted]  /js/incomes/customers
                                                                    /js/incomes/invoices.js  4.34 MiB         /js/incomes/invoices  [emitted]  /js/incomes/invoices
                                                                    /js/incomes/revenues.js  4.33 MiB         /js/incomes/revenues  [emitted]  /js/incomes/revenues
                                                                             /js/install.js  3.97 MiB                  /js/install  [emitted]  /js/install
                                                                        /js/modules/item.js  4.32 MiB             /js/modules/item  [emitted]  /js/modules/item
                                                                    /js/portal/dashboard.js  4.33 MiB         /js/portal/dashboard  [emitted]  /js/portal/dashboard
                                                                     /js/portal/invoices.js  4.33 MiB          /js/portal/invoices  [emitted]  /js/portal/invoices
                                                                     /js/portal/payments.js  4.33 MiB          /js/portal/payments  [emitted]  /js/portal/payments
                                                                      /js/portal/profile.js  4.33 MiB           /js/portal/profile  [emitted]  /js/portal/profile
                                                                 /js/portal/transactions.js  4.33 MiB      /js/portal/transactions  [emitted]  /js/portal/transactions
                                                                 /js/settings/categories.js  4.34 MiB      /js/settings/categories  [emitted]  /js/settings/categories
                                                                 /js/settings/currencies.js  4.34 MiB      /js/settings/currencies  [emitted]  /js/settings/currencies
                                                                    /js/settings/modules.js  4.33 MiB         /js/settings/modules  [emitted]  /js/settings/modules
                                                                   /js/settings/settings.js  4.33 MiB        /js/settings/settings  [emitted]  /js/settings/settings
                                                                      /js/settings/taxes.js  4.33 MiB           /js/settings/taxes  [emitted]  /js/settings/taxes
                                                                      /js/wizard/company.js  4.33 MiB           /js/wizard/company  [emitted]  /js/wizard/company
                                                                   /js/wizard/currencies.js  4.34 MiB        /js/wizard/currencies  [emitted]  /js/wizard/currencies
                                                                        /js/wizard/taxes.js  4.34 MiB             /js/wizard/taxes  [emitted]  /js/wizard/taxes
                                    fonts/nucleo-icons.eot?c1733565b32b585676302d4233c39da8  18.1 KiB                               [emitted]
                                    fonts/nucleo-icons.svg?0b8a30b10cbe7708d5f3a4b007c1d665   123 KiB                               [emitted]
                                    fonts/nucleo-icons.ttf?f82ec6ba2dc4181db2af35c499462840  17.9 KiB                               [emitted]
                                  fonts/nucleo-icons.woff2?426439788ec5ba772cdf94057f6f4659  8.38 KiB                               [emitted]
                                   fonts/nucleo-icons.woff?2569aaea6eaaf8cd210db7f2fa016743  9.98 KiB                               [emitted]
 fonts/vendor/element-ui/lib/theme-chalk/element-icons.ttf?732389ded34cb9c52dd88271f1345af9  54.6 KiB                               [emitted]
fonts/vendor/element-ui/lib/theme-chalk/element-icons.woff?535877f50039c0cb49a6196a5b7517cd  27.5 KiB                               [emitted]

ERROR in ./resources/assets/sass/argon.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

  @include form-control-focus($ignore-warning: true);
          ^
      Wrong number of arguments (1 for 0) for `form-control-focus'
      in /temp/akaunting/akaunting-2.0.0/node_modules/bootstrap/scss/_forms.scss (line 40, column 12)
    at runLoaders (/temp/akaunting/akaunting-2.0.0/node_modules/webpack/lib/NormalModule.js:316:20)
    at /temp/akaunting/akaunting-2.0.0/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /temp/akaunting/akaunting-2.0.0/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/temp/akaunting/akaunting-2.0.0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (/temp/akaunting/akaunting-2.0.0/node_modules/sass-loader/dist/index.js:89:7)
    at Object.done [as callback] (/temp/akaunting/akaunting-2.0.0/node_modules/neo-async/async.js:8067:18)
    at options.error (/temp/akaunting/akaunting-2.0.0/node_modules/node-sass/lib/index.js:294:32)
 @ ./resources/assets/sass/argon.scss

ERROR in ./resources/assets/sass/argon.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/dist/cjs.js??ref--5-5!./resources/assets/sass/argon.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

  @include form-control-focus($ignore-warning: true);
          ^
      Wrong number of arguments (1 for 0) for `form-control-focus'
      in /temp/akaunting/akaunting-2.0.0/node_modules/bootstrap/scss/_forms.scss (line 40, column 12)
 @ ./resources/assets/sass/argon.scss 2:14-267

npm ERR! Linux 4.15.0-50-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "development"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! akaunting@2.0.0 development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the akaunting@2.0.0 development script 'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the akaunting package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs akaunting
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls akaunting
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /temp/akaunting/akaunting-2.0.0/npm-debug.log

npm ERR! Linux 4.15.0-50-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! akaunting@2.0.0 dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the akaunting@2.0.0 dev script 'npm run development'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the akaunting package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run development
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs akaunting
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls akaunting
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /temp/akaunting/akaunting-2.0.0/npm-debug.log

**Comment by ysfkaya** [comment]
Change `"bootstrap": "^4.3.1"` to `"bootstrap": "4.3"` in `package.json`and remove bootstrap in `devDependencies`.

**Comment by amittechelp** [comment]
thank you.

Solved on pc having Ubuntu 18.04.3 LTS.

I tried this solution. I was able to solve this by upgrading npm to 5.0.3 and same package.json @ 6d50fa844252a4d2325d7ad0362db5389fefc52b

**Comment by cherif-bayo** [comment]
have the same error . followed instructions by changing bootstrap ^4.3.1 to 4.3 et removing it from devDependencies. Still get the same error. 
any idea ? 
thank you

**Comment by denisdulici** [comment]
This is fixed in the latest master.
