### ISSUE TITLE
Cannot create invoice: Items The name field is required

### ISSUE THREAD

**Issue by ph00lt0** [akaunting/akaunting#1056]
### Steps to reproduce the issue
I have a clean setup. 
I added one item and a customer and then tried to create an invoice. However I am receiving the following error. 

![Screenshot 2019-12-30 at 18 06 05](https://user-images.githubusercontent.com/15004290/71592086-23111200-2b2f-11ea-92e5-de54ba89f706.png)

### Expected result
It should create a new invoice, or tell me which field is missing.

### Actual result
This is the response in the network. Which is not displayed on the frontend. 
`{"message":"The given data was invalid.","errors":{"items.0.name":["The name field is <strong>required<\/strong>."]}}`
Error comes from incomes/invoices

### System information
Latest version of Akaunting from master.
PHP 7.4

**Comment by amittechelp** [comment]
Similar Problem.

version: 2.0.1 
revision: 2.0.1-393-g5be4eb73
Head: 5be4eb73110fff7bcc5f29e64c3fba17ed3e65ff

While creating new invoice 
1. for selected item price is not appearing.
2. If give force price then invoice can be created.

**Comment by denisdulici** [comment]
This has been fixed in master.
