### ISSUE TITLE
Column not found: 1054 Unknown column 'dashboard_id' in 'where clause' 

### ISSUE THREAD

**Issue by tkembo** [akaunting/akaunting#1073]
### Steps to reproduce the issue

- Run ```git pull``` to sync an existing akaunting instalation with the latest code repo and then run ```php artisan migrate``` and ```php artisan seed``` 
- Then log in

### Expected result

When you open your akaunting installation's URL from a browser, the page should load fine

### Actual result

The website shows a 500 error, and if you have ```APP_DEBUG``` set to true, the following error is displayed:

    Illuminate\Database\QueryException
    SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dashboard_id' in 'where clause' (SQL: select * from `dlp_widgets` where `dashboard_id` = 1 and `dlp_widgets`.`deleted_at` is null and `dlp_widgets`.`company_id` = 1 order by `sort` asc)

### System information (Akaunting, PHP versions)

- PHP 7.2.24-0ubuntu0.18.04.1 (cli)
- Apache/2.4.29 (Ubuntu)

**Comment by tognit** [comment]
Same for me :+1:

**Comment by denisdulici** [comment]
You should make a clean installation https://github.com/akaunting/akaunting#installation
