### ISSUE TITLE
[2.0.1] companies.js?v=2.0.1:113681 [Vue warn]: Error compiling template:

### ISSUE THREAD

**Issue by amittechelp** [akaunting/akaunting#1074]
Please suggest 

Code version:
git tag = 2.0.1-322-g83b3e9cf:

I am facing the following Problems on :
1. First time Wizard -> Currency setting page disappears after few second (1 or even less).
2. Manage Companies from drop down after login ->  Add new -> the new company form disappears within few seconds
3. Sales:Revenue -> Add/Create  Revenue ->  the new revenue form disappears within few seconds
4. Purchase -> Payment ->  Add/create New Payment ->  the new payment form disappears within few seconds
5. Banking -> Transfers ->  Add/create New Transfer: the new Transfer form disappears within few seconds
6. Reports -> Add New -> Form appears and then immediately disappears

Attachment:
[VuwError-1578023110596.log](https://github.com/akaunting/akaunting/files/4018081/VuwError-1578023110596.log)

**Comment by tognit** [comment]
Same for me :+1:

**Comment by amittechelp** [comment]
Thank you

This problem is solved after changing dev dependencies vue version to 2.6.11
I hope there is no changes in code during this time.
