### ISSUE TITLE
Vue Error - Dashboard / Create Invoice / Setting Invoice

### ISSUE THREAD

**Issue by tognit** [akaunting/akaunting#1076]
### Steps to reproduce the issue

Dashboard / Create Invoice / Setting Invoice

### Actual result

![Bildschirmfoto 2020-01-03 um 12 28 03](https://user-images.githubusercontent.com/1794459/71721261-b9da1900-2e24-11ea-9446-56b86a0ce018.png)

![Bildschirmfoto 2020-01-03 um 12 32 40](https://user-images.githubusercontent.com/1794459/71721413-379e2480-2e25-11ea-8f57-32153e8ecf56.png)

![Bildschirmfoto 2020-01-03 um 12 33 40](https://user-images.githubusercontent.com/1794459/71721432-54d2f300-2e25-11ea-8d5c-6f8b7e44e3c7.png)

![Bildschirmfoto 2020-01-03 um 12 34 24](https://user-images.githubusercontent.com/1794459/71721454-6b794a00-2e25-11ea-843e-61b5e07747d6.png)

### System information (Akaunting, PHP versions)

Akaunting master form 02.01.2019
PHP 7.2.24

**Comment by amittechelp** [comment]
I am also getting same problem.

**Comment by tognit** [comment]
The error messages are of course no longer visible after the "npm run dev"

**Comment by denisdulici** [comment]
Fixed in the latest master.
