### ISSUE TITLE
Version 2.0 not compatible with PAID APP "double entry accounting"

### ISSUE THREAD

**Issue by irvine48** [akaunting/akaunting#1080]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
fresh install 2.* not compatible with double entry account.

### Expected result
install successful

### Actual result
error 500

**Comment by denisdulici** [comment]
GitHub is not for app support.

**Comment by irvine48** [comment]
so where do i get help? official forum and ticket all not replied by anyone? is this paid app is 3rd party?
