### ISSUE TITLE
[Create Invoice Error] [master code sha: e418ecfa7e3eeb833ec189c657cd4264450b0eb8]

### ISSUE THREAD

**Issue by amittechelp** [akaunting/akaunting#1104]
Please Suggest 

## Steps to reproduce the issue
CASE1
Login->Sales->Invoices->Add New->Select Customer
then
Select item Name from drop down

CASE 2:
then
forcefully add price (say 6000) and select tax 12% -> select category -> Save Invoice 
go to Reports
check Income summary/Profit & Loss/Income and Expenses 

### Expected result
1. New Invoice number may appear
2. Item price and tax may load automatically.

CASE 2:
3. Income summary/Profit & Loss/Income and Expenses should not take price of item twice.

### Actual result
1.Invoice number not increments 
2.price and tax not updated as per created items details

CASE 2:
3. reports shows double of item price (this is problem). Taxes are not doubled as expected

### System information (Akaunting, PHP versions)
Hosted on PHP-7.3
Akaunting 2.0.1 master @ e418ecfa7e3eeb833ec189c657cd4264450b0eb8
Vue@2.6.10

### Additional comments
Please see attached log and screenshots of akaunting
![CreateInvoiceIssue](https://user-images.githubusercontent.com/28892776/72084272-dafea600-330b-11ea-8491-c7edb361ab4b.JPG)
![ItemPresencewith priceandTax](https://user-images.githubusercontent.com/28892776/72084799-d8508080-330c-11ea-99a8-b51444b03aff.JPG)

[Create Invoice Error akaunting.com-1578584769214.log](https://github.com/akaunting/akaunting/files/4041320/Create.Invoice.Error.akaunting.com-1578584769214.log)

**Comment by denisdulici** [comment]
Fixed in latest master.
