### ISSUE TITLE
Settings are saving duplicate data

### ISSUE THREAD

**Issue by menezesbr** [akaunting/akaunting#1105]
Settings are saving duplicate data to database when used with radioGroup

![settings - 0](https://user-images.githubusercontent.com/17728642/72115701-bebc3280-3326-11ea-9fad-0767d8b0acce.jpg)
![settings - 1](https://user-images.githubusercontent.com/17728642/72115702-bebc3280-3326-11ea-9889-4bd82fc381ae.jpg)
![settings - 2](https://user-images.githubusercontent.com/17728642/72115703-bf54c900-3326-11ea-8392-69d024249d82.jpg)
![settings - 3](https://user-images.githubusercontent.com/17728642/72115705-bf54c900-3326-11ea-979e-255ffbdd640c.jpg)

**Comment by denisdulici** [comment]
I can confirm, somehow vue is not posting radioGroup correctly
