### ISSUE TITLE
[question] why using dev pacakges in production

### ISSUE THREAD

**Issue by linuxjuggler** [akaunting/akaunting#111]
Hey,
I was going to submit a PR which move dev packages to the `require-dev` section, but then I thought to myself its best to ask if you guys have any reasons for putting dev packages inside `require` not `require-dev` section in composer.

thanks

**Comment by denisdulici** [comment]
Hi Zaher,

Sure, because you can turn the app into dev mode by just changing the `APP_ENV` value in `.env` file. Let me know if I'm missing your point plz.

Regards

**Comment by linuxjuggler** [comment]
Hey Denis,

Can you explain to me about your idea, what is the need for a *production* system to have for example `ide-helper` installed? even for debugging.

those packages for example:
```
        "barryvdh/laravel-ide-helper": "2.3.*",
        "fzaninotto/faker": "1.6.*"
```

I can understand that `laravel-debugbar` can be good for end user debugging, but not sure about the other two.

correct me if am wrong

**Comment by denisdulici** [comment]
You're right about `faker`. About `laravel-ide-helper`, where/how should we add the service provider:
https://github.com/barryvdh/laravel-ide-helper#install

**Comment by linuxjuggler** [comment]
I know you are loading it conditionally but am asking why the user has to install it on a production server if they are going to use it only for development.

**Comment by denisdulici** [comment]
Because there was no other choice. Your idea of how to use it differently, without breaking the system after changing the `APP_DEV` value, is welcome.
