### ISSUE TITLE
Current financial year issue.

### ISSUE THREAD

**Issue by biholaindrasinh** [akaunting/akaunting#1113]
### Steps to reproduce the issue
Go to **settings -> general -> localization** and set **financial year start** to **01-04**. 

### Expected result
It should consider the current financial year 1 April 2019 to 31 March 2020 because the current date is 12-Jan-2020 in the dashboard's cashflow chart date picker.

### Actual result
It is considering the current financial year 1 April 2020 to 31 March 2021 in the dashboard's cashflow chart date picker.

### System information (Akaunting, PHP versions)
Cloud application

Let me know if I am using it correctly.

Thanks,
Indra Bihola

**Comment by denisdulici** [comment]
This has been fixed in 2.0 version.
