### ISSUE TITLE
Invoice problem with price as 0

### ISSUE THREAD

**Issue by Jackatron** [akaunting/akaunting#1114]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Go to incomes > invoices > create new
Type 0.00 into the price box of an item 

### Expected result
It should multiply the price by the quantity and then should show zero as the current price for the product, in turn making it free.

### Actual result
When you type 0 nothing happens. When looking at the developer console, it outputs a JavaScript error and then doesn't output the correct price

It says unprocessable entity 422

### System information (Akaunting, PHP versions)

Akaunting 2.0.1
PHP 7.4.1

**Comment by Jackatron** [comment]
![test](https://user-images.githubusercontent.com/5952232/72390245-26f18680-3722-11ea-9592-2c88759c58d0.PNG)

**Comment by jashk** [comment]
Hello,
I check this issue and is related with a validation rule, the *amount* rule expects a value greater than 0 but the error does not display.

```'items.*.price' => 'required|amount',```

**Comment by aliuysal60** [comment]
Yes i have this problem too

**Comment by cuneytsenturk** [comment]
This item price validation message issue solved on latest package (2.0.7) and item price cannot be 0.

If you want to invoice for free, you can apply 100% discount.

Thanks your feed back.
