### ISSUE TITLE
No /server.php file

### ISSUE THREAD

**Issue by runninguru** [akaunting/akaunting#116]
I tried to install according to the instructions, and it is missing the server.php file. 

I copied the server.php file from one of my other laravel projects (a Laravel version 5.5 project), and I noticed that you moved /public/index.php to /index.php (or maybe that's just different from a previous Laravel version. I'm not sure). Once I added server.php and changed the path in server.php from /public/index.php to /index.php, it worked, and I was able to start installing it.

I will set up a pull request, but just in case my server.php file is wrong for any reason or from a wrong version, I wanted to create this issue we it can be addressed.

**Comment by linuxjuggler** [comment]
@runninguru did you downloaded the `Akaunting_x.x.x-Stable.zip`?
if so I dont think you will find it as the guys said that this file is for end users so they have stripped few files from it

**Comment by runninguru** [comment]
I followed the installation instructions in the readme in the repo. It downloads 'akaunting-master.zip', which doesn't contain server.php. Also, the repo doesn't have it either. 

If the 1 branch on the repo doesn't have server.php, and the readme's instructions has me download a copy of the project that doesn't have server.php, then i'm really confused.

Either way, i'm looking to contribute, and i'm currently very confused. i'm looking to get a developer-ready version downloaded and working on my machine, How do I do that?

**Comment by linuxjuggler** [comment]
I dont think `server.php` is so important all it does is to run php internal server which is not good for production (nor development in my Opinion)

**Comment by runninguru** [comment]
In that case, the readme needs to be updated to indicate that the project isn't designed to use the internal php server for dev purposes..

**Comment by denisdulici** [comment]
Akaunting uses Laravel 5.4 version. We've moved the `/public/index.php` file to `/index.php` because that is what makes sense for an end-user CMS, check out Joomla, WordPress, Drupal etc.

As for `server.php`, I've never used it tbh but if your solution fixes it then your PR is welcome 😉

**Comment by denisdulici** [comment]
I'm closing this issue. Feel free to set up a pull request.
