### ISSUE TITLE
Lang FR : space required before a colon, semicolon, question mark or exclamation point (: ; ? !)

### ISSUE THREAD

**Issue by Marc-oO** [akaunting/akaunting#117]
Hello,
First of all, thanks for your work ! 

all is in the title, in French, a space is required before signs like : ; ? !

**Currently**
Numéro de facture:

**Expected**
Numéro de facture :

A quick fix would be to add a space after each strings in those files : https://github.com/akaunting/akaunting/tree/master/resources/lang/fr-FR but i guess there is maybe a more elegant fix.. ?

Regards

**Comment by denisdulici** [comment]
Hello,

We use Crowdin as translation platform, would appreciate your contributions here: https://crowdin.com/project/akaunting

Regards
