### ISSUE TITLE
cloud/users Profile Picture link is coming as a full json object.

### ISSUE THREAD

**Issue by om3rcitak** [akaunting/akaunting#1179]
Repro steps:
- Register akaunting cloud
- Go to user edit page `cloud/users/{id}/edit`
- Upload new profile picture
- Go to users page `cloud/users`

Profile picture link is coming as a full json object.

![Capture](https://user-images.githubusercontent.com/5197413/73026817-3455f180-3e43-11ea-8612-a39aa118c68d.PNG)

**Comment by denisdulici** [comment]
Thanks @om3rcitak will fix it on cloud asap 😉
