### ISSUE TITLE
Addresses don't keep line break

### ISSUE THREAD

**Issue by Marc-oO** [akaunting/akaunting#118]
Hello,

on multiple pages like `/incomes/invoices/1` addresses don't keep line break :

**Currently**

> 10, avenue des Champs Elysées 75008 Paris

**Expected**

> 10, avenue des Champs Elysées
> 75008 Paris
> 

Maybe replace
`{{ setting('general.company_address') }}`
by
`{!! nl2br(setting('general.company_address')) !!}`
?

Regards

**Comment by denisdulici** [comment]
Thanks Marc.
