### ISSUE TITLE
Cannot upload assets/logo

### ISSUE THREAD

**Issue by bmelman** [akaunting/akaunting#1195]
### Steps to reproduce the issue

Try to upload company logo or invoice atttachment, nothing happens

### Expected result

image/asset is uploaded and shown

### Actual result

nothing happens

### System information (Akaunting, PHP versions)

pulled master, ran composer update, npm run developer, artisan update + cache clean etc. tried different browsers.
No related errors in browser console or laravel debug bar

**Comment by tognit** [comment]
I think that the upload function does not work in the whole akaunting.

**Comment by lutpiero** [comment]
Not the whole upload function, the import function on purchase/sales is working.
For me the logo problem occurred because when submitting XHR there is no file submitted.
The fix should be on ajax form upload.

**Comment by tognit** [comment]
For me it's not like akaunting!
Where exactly should it put the files?

### System information (Akaunting, PHP versions)
Akaunting = master 07.02.2020
PHP = 7.2

**Comment by lutpiero** [comment]
I fix the problem by re-assigning formdata to FormData 
```php
submit() {
    this.loading = true;
    let modifiedFormData = new FormData();
    for(let key in this.data()) {
        modifiedFormData.append(key,formData[key])
    }
    axios({
        method: this.method,
        url: this.action,
        data: modifiedFormData,
        headers: {'Content-Type': 'multipart/form-data' }
    })
    .then(this.onSuccess.bind(this))
    .catch(this.onFail.bind(this));
}
```

**Comment by cuneytsenturk** [comment]
Thak you @lutpiero .
