### ISSUE TITLE
Invoice uses purchase price when assigning items

### ISSUE THREAD

**Issue by bmelman** [akaunting/akaunting#1196]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

When an item is added/assigned in an invoice the purchase price is used as sales price. Also Tax is not applied

### Expected result

Use purchase price and tax from item

### Actual result

purchase price us used

### System information (Akaunting, PHP versions)

master/latest

**Comment by denisdulici** [comment]
Confirmed, thanks for reporting

**Comment by denisdulici** [comment]
Fixed here https://github.com/akaunting/akaunting/commit/072b0725283c8a768882d80524a59d6972f178a5
