### ISSUE TITLE
Possible sub categories

### ISSUE THREAD

**Issue by khaerul10056** [akaunting/akaunting#121]
Possible sub categories in Setting/Categories as like item

**Comment by denisdulici** [comment]
I'm sorry Khaerul but that's not possible atm.

**Comment by khaerul10056** [comment]
Is there's plan to add it?

**Comment by khaerul10056** [comment]
And also integrated item with vendor. When user add item, automatically assign to the vendor.
The logics are : 
- Add vendor
- Add item, detail, price and stock also will generate bill.
- Then admin make payment to vendor depend on how many item bought from vendor

**Comment by denisdulici** [comment]
I'm sorry but there is no such a plan atm. However, you may create an app to extend it https://akaunting.com/docs/developer-manual/modules
