### ISSUE TITLE
Is import/export a planned feature?

### ISSUE THREAD

**Issue by bam-tbf** [akaunting/akaunting#122]
Akaunting looks great! Do you plan to allow importing and exporting of transactions/data in either csv or quickbooks formats in the future? If so, please provide the expected timeline. Thank you.

**Comment by denisdulici** [comment]
You can already import CSV for items, invoices, customers, revenues etc Brendan. Export is planned.

**Comment by bam-tbf** [comment]
Great! Didn't see it in the docs...must have missed it.

**Comment by vigneshpalanivel** [comment]
When can we expect Export feature?
