### ISSUE TITLE
I got error 

### ISSUE THREAD

**Issue by yanchhuong** [akaunting/akaunting#1220]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

> php artisan sample-data:seed

### Expected result

  at C:\xampp\htdocs\akaunting\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:302
    298|         $pipes = [];
    299|         $this->stream = proc_open($command, $descriptorSpec, $pipes);
    300|         stream_set_blocking($pipes[2], 0);
    301|         if ($err = stream_get_contents($pipes[2])) {
  > 302|             throw new Swift_TransportException(
    303|                 'Process could not be started ['.$err.']'
    304|                 );
    305|         }
    306|         $this->in = &$pipes[0];

  Exception trace:
php artisan sample-data:seed

**Comment by denisdulici** [comment]
You should change `MAIL_DRIVER=log` in `.env` file.
