### ISSUE TITLE
Tekrar Eden Ödemeler

### ISSUE THREAD

**Issue by tolgahand** [akaunting/akaunting#1230]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

**Giderler** altında aylık 1 defa tekrarlayan **Yeni Ödeme** ekledim. Ocak ayında eklediğim ödeme Şubat ayında tekrarladı ancak "Giderler>Ödemeler" kısmında bu ödemeyi göremiyorum. Sadece **"Gider Özeti"** kısmında gözüküyor. 

### Expected result

Tekrarlayan ödemeler "Giderler>Ödemeler" altında yeniden oluşturulmalı. Aidat'ıma şubat ayında zam yapıldı ve bu Şubat Ödemesi sistemde gözükmediği için düzenleyemedim. Yeni ödeme eklediğimde de tekrarlayan ödemenin  üzerine ekliyor ve aidatım yanlış gözüküyor.

### Actual result
Tekrarlayan ödemeler **"Giderler>Ödemeler"** altında yeniden oluşturulduğunda en son oluşturulan bir ödemede yapılan değişiklik ondan sonraki yenilemeleri etkilesin ya da etkileyip etkilememesi sorulsun.

### System information (Akaunting, PHP versions)
https://app.akaunting.com/
Sürüm 1.3.17

**Comment by denisdulici** [comment]
Closed due to out of date.
