### ISSUE TITLE
If you want to process an invoice, the name of the article is no longer visible

### ISSUE THREAD

**Issue by tognit** [akaunting/akaunting#1240]
### Steps to reproduce the issue

first create a new invoice and then edit the invoice

### Expected result

Name and description of the article can be seen

### Actual result

if you want to process an invoice, the name of the article is no longer visible

### System information (Akaunting, PHP versions)

Akaunting = master 07.02.2020
PHP = 7.2

**Comment by denisdulici** [comment]
It's fixed in the latest master.
