### ISSUE TITLE
Vue is Running in Development Mode

### ISSUE THREAD

**Issue by SethX3** [akaunting/akaunting#1252]
### Steps to reproduce the issue
Go to https://app.akaunting.com/ on any page.

### Expected result
No message regarding Vue should appear what so ever.

### Actual result
```
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools

You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

### System information (Akaunting, PHP versions)
Cloud Hosted Akaunting

### Additional comments
It appears it was built and deployed in development mode instead of production.
The site should be a lot smaller and perform faster in production mode.

**Comment by denisdulici** [comment]
It's prod now, thanks @SethX3 for reporting.
