### ISSUE TITLE
Visual Bug when Setting Tax for Invoice Item

### ISSUE THREAD

**Issue by SethX3** [akaunting/akaunting#1253]
### Steps to reproduce the issue
Under `Sales`, click `+ Add New` and try to set the tax.

### Expected result
The tax should be set successfully and the UI should show the new price with the new tax amount and total.

### Actual result
The tax amount displayed if off by one step, for example if I try to remove the tax, I now see the tax amount.

![image](https://user-images.githubusercontent.com/22801583/74410393-40791180-4e39-11ea-8ec3-ddac0a38d042.png)

### System information (Akaunting, PHP versions)
Cloud Hosted Akaunting

**Comment by cuneytsenturk** [comment]
I've solve this issue here => https://github.com/akaunting/akaunting/commit/151248281a2ea32cf3b81b410bf89205f15debac
