### ISSUE TITLE
Route [http://app.akaunting.com/settings/settings] not defined.

### ISSUE THREAD

**Issue by tognit** [akaunting/akaunting#1255]
### Steps to reproduce the issue

Settings -> then company = no error message.
Settings -> localization, invoice, etc. = error message

### Actual result

> Facade\Ignition\Exceptions\ViewException
Route [http://app.akaunting.com/settings/settings] not defined. (View:/home/public_html/app/resources/views/partials/form/save_buttons.blade.php)

```
@php
if (\Str::contains($cancel, ['.'])) {
    $url = route($cancel);
} else {
    $url = url($cancel);
}
@endphp
```

why is there an if / else query?
what is the difference between route($cancel) and url($cancel)?

### System information (Akaunting, PHP versions)

Akaunting = master 07.02.2020
PHP = 7.2

**Comment by denisdulici** [comment]
This is fixed in master so please, get the latest one.
