### ISSUE TITLE
[V2] Disable currency during installation doesn't work

### ISSUE THREAD

**Issue by rjrodriguezalvarez97** [akaunting/akaunting#1258]
### Steps to reproduce the issue
1.Configure Akaunting on Cloud Hosting
2. On Step 2. try to disable some currencies.

### Expected result
Currency is disabled

### Actual result
Currency is not disabled.
A warning notification appears without text

**Comment by denisdulici** [comment]
I just tried this and it worked fine. Linked currencies got the proper warning notification, with text. Others got disabled.

**Comment by rjrodriguezalvarez97** [comment]
Just tested again
![](https://i.imgur.com/3wih21m.gif)

No errors on console. Default currency was set to EUR and default language to English GB
