### ISSUE TITLE
Menu Toggle Not Working

### ISSUE THREAD

**Issue by hmert** [akaunting/akaunting#1266]
### Steps to reproduce the issue

![bug](https://user-images.githubusercontent.com/182906/74686296-22693380-51e2-11ea-887c-f2fca0177cda.gif)

### System information (Akaunting, PHP versions)

live on https://app.akaunting.com/

**Comment by rjrodriguezalvarez97** [comment]
You have to hover out from the menu after toggling it in order to the menu to hide

**Comment by denisdulici** [comment]
As @rjrodriguezalvarez97 said, you should hover out from the menu. That's how Argon works https://www.creative-tim.com/product/vue-argon-dashboard-pro
