### ISSUE TITLE
Updating problem 1.3.17➝2.0.2

### ISSUE THREAD

**Issue by jaredhowland** [akaunting/akaunting#1271]
### Steps to reproduce the issue
1. Click on check updates button
2. It shows an update available to 1.3.18
3. Update to 1.3.18
4. It shows another update available to version 2.0.2
5. Click to update and it kicks me back to the main dashboard–nothing ever happens
6. Turn on debug mode in `.env` and try again
7. Get "Internal Server Error 500" (The server encountered an internal error or misconfiguration and was unable to complete your request.)

The final URL it is attempting to reach is https://mydomain.com/install/updates/update/core/2.0.2

### Expected result
1. Update to 2.0.2 completes and I'm able to run the database migration to newest version

### Actual result
1. Continues to show an update to 2.0.2 is available but never lets me update

### System information (Akaunting, PHP versions)
1. Akaunting: 1.3.18 (yes, it says 1.3.18 even though I can't find that version number anywhere else in the documentation or on Github)
2. Apache: 2.4.41
3. PHP: 7.2.27
4. MySQL: 5.7.29

### Additional comments

This also spawns a lot of `php-cgi` processes (>70) that sends my CPU usage to 99% and eats up physical memory storage. I have to manually kill these processes from the command line.

**Comment by denisdulici** [comment]
Akaunting 1.3.18 is a ghost version that allows updating to 2.0 version.

Do you have any custom module installed?

Try the following command: `php artisan update:terminal`

**Comment by jaredhowland** [comment]
No custom modules or edits to any code. Just a plain, out-of-the-box implementation.

Running that command from the terminal took about 30 seconds and it fixed everything an upgraded directly to 2.0.2. Thanks!
