### ISSUE TITLE
Failure to auto-upgrade from version 1.3.17 to version 2.0

### ISSUE THREAD

**Issue by mbeinder** [akaunting/akaunting#1278]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Click the "Upgrade Akaunting to Verison 1.3.18" button on the upgrade screen

### Expected result
Software updates to the new version

### Actual result
Get an error stating "Whoops, looks like something went wrong..."

### System information (Akaunting, PHP versions)
Akaunting 1.3.17
PHP 7.1

### Additional comments
There should be a way to manually update the software without the automatic process in the case of an automatic update failure.

**Comment by jaredhowland** [comment]
See issue #1271 for a possible solution

**Comment by denisdulici** [comment]
You can enable debug to see more details https://akaunting.com/docs/developer-manual/debug

Use this command for manual update: `php artisan update:terminal`

**Comment by pifiuk** [comment]
When I run the php artisan update:terminal command I get the following. 

 ```
Command "update:terminal" is not defined.

  Did you mean one of these?
      update
      update:finish
```

Any ideas?

**Comment by mbeinder** [comment]
> You can enable debug to see more details https://akaunting.com/docs/developer-manual/debug
> 
> Use this command for manual update: `php artisan update:terminal`

This command returns the message of no commands available in update namespace.
