### ISSUE TITLE
partial invoice cant mark as paid

### ISSUE THREAD

**Issue by emrahcetiner** [akaunting/akaunting#128]
when i mark as paid, adding 0 amount in payments table and cant mark as paid

**Comment by denisdulici** [comment]
I just tried and it worked fine for me.

**Comment by emrahcetiner** [comment]
i explain step by step

1. add new invoice, eg. total = $100
2. in details, more actions > mark send
3. in details, more actions > add payment with $70
4. in details, more actions > add payment with $30
5. in details, more actions > mark paid

After last step, automatically adding a new rows
- with $0 amount in payments table
- with Partial status and "$0" description in history table
in invoice detail page.
