### ISSUE TITLE
When the transfer is made between the cases with different currencies, the exchange is incorrect.

### ISSUE THREAD

**Issue by aliuysal60** [akaunting/akaunting#1280]
### Steps to reproduce the issue
When the transfer is made between the cases with different currencies, the exchange is incorrect.

### Expected result

$ case = 127.50 $
TL case = 120 TL

### Actual result

Sample;
Default  = TL
** Exchange Dollars **: 6
** $ Cash Balance ** = $ 147.50
** TL Cash Balance ** = 0
** 20 transfers were made from $ safe to TL safe. **
Latest Status;
** $ Cash Balance ** = $ 127.50
** TL Cash Balance ** = 3.33 TL

### System information (Akaunting, PHP versions)

Akaunting 2.0.2
PHP 7.3

### Additional comments

When the transfer is made between the cases with different currencies, the exchange is incorrect.

Kindly review the below:
Exchange rate of TL is 6,80.
Transfer amount that will be made from TL to EUR is 68 TL.
Before the transfer;
Case TL is 100 TL.
Case EUR is 0 EUR.
After the transfer;
Case TL is 32 TL (it is true)
Case EUR is 462,40 EUR (it is wrong. It should be 10 EUR. calculation is made as 68 TL x 6.80 instead of 68 TL / 6,8.

Accounts page;
![image](https://user-images.githubusercontent.com/6507261/75337321-cff0dc80-589d-11ea-8eb9-457fa1338297.png)

Transactions page;

![image](https://user-images.githubusercontent.com/6507261/75337343-dd0dcb80-589d-11ea-910c-0c1795458f16.png)

**Comment by denisdulici** [comment]
Your USD exchange rate is not correct:

https://www.xe.com/currencyconverter/convert/?Amount=1&From=TRY&To=USD

**Comment by aliuysal60** [comment]
@denisdulici 
But, my default currency TL
Isn't there anything wrong?
