### ISSUE TITLE
Error Report Deletion

### ISSUE THREAD

**Issue by aliuysal60** [akaunting/akaunting#1285]
### Steps to reproduce the issue

Create a new Report and detele this report.

### Expected result

The report should be deleted successfully

### Actual result

Failed to load resource: the server responded with a status of 403 (Forbidden)
reports.js?v=2.0.2:1 Error: Request failed with status code 403
    at e.exports (reports.js?v=2.0.2:1)
    at e.exports (reports.js?v=2.0.2:1)
    at XMLHttpRequest.h.onreadystatechange (reports.js?v=2.0.2:1)

### System information (Akaunting, PHP versions)

Akaunting : 2.0.3
PHP: 7.3

**Comment by denisdulici** [comment]
I'm not able to reproduce this issue but have you tried with [debug enabled](https://akaunting.com/docs/developer-manual/debug)?

**Comment by aliuysal60** [comment]
Hi, 
I checked again, worked at the local.
There is a problem with the remote host ver I found that there is a problem in apachi config
Sorry

To fix, add
Require all granted

In Directory section of VirtualHost, updated VirtualHost configuration is

![image](https://user-images.githubusercontent.com/6507261/75252699-3dddcb00-57ee-11ea-91b4-c5db08d3584e.png)
