### ISSUE TITLE
Add new product on the purchase or sales invoice

### ISSUE THREAD

**Issue by aliuysal60** [akaunting/akaunting#1296]
### Steps to reproduce the issue
Create a purchase or sales invoice.
Product selection - Add New

### Expected result
Add new product form opens

### Actual result
no action

### System information (Akaunting, PHP versions)
Akaunting : 2.0.3
PHP: 7.3

### Additional comments
On the Sales & Purchase Invoice pages, When you click Add New button, registration form does not open and the system does not give any error or warning

![image](https://user-images.githubusercontent.com/6507261/75334960-c5344880-5899-11ea-9518-259b41d09d9e.png)

**Comment by denisdulici** [comment]
There is no need for any extra form, the item is created directly.
