### ISSUE TITLE
When the payment is made in a different currency, the Paid Amount is shown incorrectly in the invoice detail

### ISSUE THREAD

**Issue by aliuysal60** [akaunting/akaunting#1298]
### Steps to reproduce the issue

Default Case is TL
Default Currency is TL
Exchange rate of TL is 6,80
100 TL
Payment from the Case EUR is 10 EUR

### Actual result
When the payment is made in a different currency, the Paid Amount is shown incorrectly in the invoice detail. Suppose we got the exchange rate of 6.8 TL. While the amount paid for the 10 € payment should show 68 TL, it shows 1.47 TL. In other words, calculation is made as 10 / 6.80 instead of 10 X 6.80.
But the information in the Paid and Open Invoices section of the supplier page is correct.

### System information (Akaunting, PHP versions)
2.0.3
PHP 7.3

### Additional comments

Invoice;
![image](https://user-images.githubusercontent.com/6507261/75337672-7fc64a00-589e-11ea-91c3-23aea545316a.png)

Supplier Page;

![image](https://user-images.githubusercontent.com/6507261/75337725-910f5680-589e-11ea-986d-e12613b4d7b0.png)

**Comment by denisdulici** [comment]
Same as https://github.com/akaunting/akaunting/issues/1280#issuecomment-592491651
