### ISSUE TITLE
Could not be uploaded

### ISSUE THREAD

**Issue by aliuysal60** [akaunting/akaunting#1299]
### Steps to reproduce the issue

Go to Settings / Company 
Add Company Logo

### Expected result
Displaying the company logo on invoices

### Actual result

no action and no errors

### System information (Akaunting, PHP versions)
2.0.3
PHP: 7.3

### Additional comments
Upload operations such as adding Logo on the Company Information edit screen and Adding files on the invoice screens do not work and do not give any errors. Nothing changes when choosing a file or logo. In other words, the logo information we choose does not write anywhere. When we save it, it records all other information except the logo.
There is no problem with upload on the server side, the file selected in import operations is uploaded and the records in it are added.

**Comment by denisdulici** [comment]
Fixed in master.
