### ISSUE TITLE
Company Seeding Always uses USD

### ISSUE THREAD

**Issue by dwkitchen** [akaunting/akaunting#1300]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Add a new company by UI or API and set currency to NOK

### Expected result

The new company only has NOK currency and the seeded cash account is in NOK

### Actual result

The company has USD, EUR, GBP and TRY - but not NOK. The seeded cash account is in USD.

### System information (Akaunting, PHP versions)

**Currencies Seed**
https://github.com/akaunting/akaunting/blob/cd649a4e213bba07e1d6d69484f8dc4372f10a7f/database/seeds/Currencies.php#L25-L75

**Accounts Seed**
https://github.com/akaunting/akaunting/blob/cd649a4e213bba07e1d6d69484f8dc4372f10a7f/database/seeds/Accounts.php#L35

### Additional comments

`Seeder/Currencies` should load company currency from `Config/Money` and use this for the company.

`Seeder/Accounts` should use the company currency when creating the cash account.

**Comment by denisdulici** [comment]
Do you mean that we should create ALL currencies for each company by default?

**Comment by dwkitchen** [comment]
No, just the currency selected when creating the company.

**Comment by denisdulici** [comment]
But that's out of the scope of seeds. I mean their purpose is to create static data.
