### ISSUE TITLE
warning message when deleting a bank transfer

### ISSUE THREAD

**Issue by aliuysal60** [akaunting/akaunting#1308]
### Steps to reproduce the issue

Go to Bank / Transfer
Delete any transfer

### Expected result

![image](https://user-images.githubusercontent.com/6507261/75470445-c0f35280-59a1-11ea-8b7f-fcae85b4d342.png)

### Actual result

![image](https://user-images.githubusercontent.com/6507261/75470842-5bec2c80-59a2-11ea-817b-4d451db6170b.png)

### System information (Akaunting, PHP versions)
2.0.3
PHP 7.3

### Additional comments

need to change
![image](https://user-images.githubusercontent.com/6507261/75470953-876f1700-59a2-11ea-83ae-8f4777333b6e.png)

Also, the headers of delete confirmation windows are incorrect
![image](https://user-images.githubusercontent.com/6507261/75471032-aa99c680-59a2-11ea-934a-898d391a5b9d.png)

**Comment by denisdulici** [comment]
Not able to reproduce such an issue.

![screenshot_1582891737](https://user-images.githubusercontent.com/5254835/75547639-6a872200-5a3c-11ea-94b1-3caa6a60b2d7.jpg)

**Comment by aliuysal60** [comment]
@denisdulici 
https://app.akaunting.com/

![image](https://user-images.githubusercontent.com/6507261/75556919-256ceb00-5a50-11ea-83f1-94cb4fcfecaa.png)

**Comment by denisdulici** [comment]
This seems to be applicable to Bulk Actions delete, not the normal one.

**Comment by aliuysal60** [comment]
@denisdulici 
The message title is displayed as "Product / Service" in the whole Bulk Actions delete.

Sample; 
Invoices
![image](https://user-images.githubusercontent.com/6507261/75771473-19886e00-5d5b-11ea-88f3-0904961a7699.png)
