### ISSUE TITLE
warning message when deleting a bank transfer #1308

### ISSUE THREAD

**Issue by aliuysal60** [akaunting/akaunting#1314]
@denisdulici 
https://app.akaunting.com/

![image](https://user-images.githubusercontent.com/6507261/75556919-256ceb00-5a50-11ea-83f1-94cb4fcfecaa.png)

_Originally posted by @aliuysal60 in https://github.com/akaunting/akaunting/issues/1308#issuecomment-592538397_

**Comment by denisdulici** [comment]
Duplicate.

**Comment by aliuysal60** [comment]
@denisdulici 
The issue you closed is also available on the akaunting cloud platform.
I commented to report this, 
Have you checked again?

**Comment by aliuysal60** [comment]
> Duplicate.

@denisdulici 
The issue you closed is also available on the akaunting cloud platform.
I commented to report this,
Have you checked again?
