### ISSUE TITLE
Customer currency not updating

### ISSUE THREAD

**Issue by WOLFI3654** [akaunting/akaunting#1315]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Create a new invoice, select customer

### Expected result

Currency of invoice should change to customer's default version

### Actual result

Currency stays as default

### System information (Akaunting, PHP versions)
Akaunting Version 2.0.3, PHP 2.4

### Additional comments
Worked like this in the past versions and saved a bit effort.

**Comment by denisdulici** [comment]
This is fixed in master, can you please try and confirm?
