### ISSUE TITLE
Error when running akaunting 1.3.18 to 2.0.3.

### ISSUE THREAD

**Issue by mrcssilvasouza** [akaunting/akaunting#1316]
After updating through the app, I am unable to log in with any registered account.

**Comment by WOLFI3654** [comment]
Are you having the problem that you get an internal server error?
For me it was due to the fact that the database didnt get updated.
I fixed it by running the following command
`php /your/akaunting/directory/artisan update:db`

**Comment by denisdulici** [comment]
Please, use the forum for support not related to development.
