### ISSUE TITLE
Invoice doesn't save

### ISSUE THREAD

**Issue by hexclann** [akaunting/akaunting#1317]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create an invoice with several items. Fill out all the fields. Click save

### Expected result
Invoice should be saved and should appear on the invoice page.

### Actual result
Upon clicking the save invoice, I get 500 internal server error, however the invoice will be saved but i cannot proceed further because it always results in 500 internal server error

### System information (Akaunting, PHP versions)
Akaunting version: 2.0.3
PHP Version: 7.4
Installed on cPanel

**Comment by hexclann** [comment]
I was able to create an invoice but it results in 500 error showing this error message upon debug

Unable to init from given url (https://example.com/public/img/company.png)./home/path/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php#84Intervention\Image\Exception\NotReadableException

**Comment by denisdulici** [comment]
That error has been fixed in master.

**Comment by hexclann** [comment]
@denisdulici Do i need to wait for next release? maybe 2.0.4?

**Comment by hexclann** [comment]
@denisdulici a little bit of explanation would be helpful
