### ISSUE TITLE
Invoice doesn't save, it is fixed in master branch. Do I need to wait for the next release i.e 2.0.4?

### ISSUE THREAD

**Issue by hexclann** [akaunting/akaunting#1319]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create an invoice with several items. Fill out all the fields. Click save

### Expected result
Invoice should be saved and should appear on the invoice page.

### Actual result
Upon clicking the save invoice, I get 500 internal server error, however the invoice will be saved but i cannot proceed further because it always results in 500 internal server error

### System information (Akaunting, PHP versions)
Akaunting version: 2.0.3
PHP Version: 7.4
Installed on cPanel

**Comment by denisdulici** [comment]
@hexclann GitHub is for developers you should be able to apply [such changes](https://github.com/akaunting/akaunting/commit/9696bedb03a65aa059e3d495345c28729e9cee93)  or use the forum for user-based information.
