### ISSUE TITLE
Attachments gone after upgrade

### ISSUE THREAD

**Issue by alex-phillips** [akaunting/akaunting#1323]
### Steps to reproduce the issue
Upgrade from 1.3.18 to 2.0.3

### Expected result
Attachments should still be visible / downloadable from the `payments` view of an individual payment

### Actual result
Attachment upload field is there, but no existing attachment visible. If I re-upload an attachment, it saves successfully but viewing the `payment` view again still shows no attachment.

### System information (Akaunting, PHP versions)
php 7.3.14
akaunting 2.0.3

**Comment by batuhawk** [comment]
Thanks! @alex-phillips 
https://github.com/akaunting/akaunting/pull/1325
