### ISSUE TITLE
Future payments are deducted from current account balance

### ISSUE THREAD

**Issue by blackpidgeon** [akaunting/akaunting#1328]
### Steps to reproduce the issue
Create a revenue or expense that will happen in the future.

### Expected result
The current account balance will reflect the payment only when it has actually happened.

### Actual result
The account balance is reduced by the payment immidiately.

### System information (Akaunting, PHP versions)
Akaunting 5.0.3, PHP 7.2

**Comment by denisdulici** [comment]
This is not really an issue but a concept. Feel free to use the forum to discuss this further.

**Comment by blackpidgeon** [comment]
Would you accept a PR that changes this behaviour?
