### ISSUE TITLE
Invoice will not be created if the price is zero

### ISSUE THREAD

**Issue by hexclann** [akaunting/akaunting#1330]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create an invoice, add items, make the cost of any one item as zero

### Expected result
User should be able to create an invoice with zero price

### Actual result
Invoice cannot be created and displays the error as 'The amount is invalid'

### System information (Akaunting, PHP versions)
Akaunting 2.0.4
Php 7.4

**Comment by denisdulici** [comment]
Please, use the Ideas category on forum for future requests.
