### ISSUE TITLE
The items in the invoice will be erased if the user tries to edit it

### ISSUE THREAD

**Issue by hexclann** [akaunting/akaunting#1331]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create an invoice, save it and click on edit

### Expected result
The items in the invoice should not be deleted

### Actual result
The items will be cleared after clicking in edit

### System information (Akaunting, PHP versions)
Akaunting 2.0.4
Php 7.4

### Additional comments
The users needs to add all the items again and again in each edit which is time consuming and not a good way to edit the invoice

**Comment by aliuysal60** [comment]
No, the items on the invoice are not deleted. But invoice items are deleted taxes

**Comment by denisdulici** [comment]
This has been fixed in master.
