### ISSUE TITLE
Error While installation

### ISSUE THREAD

**Issue by zowhair** [akaunting/akaunting#1334]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
After installing dependencies and all other requirements when we start setting the environment, First step where we have to choose language goes fine, But in second step (The Database) there comes and error which produces even after putting the right values.

### Expected result
Proceed to the next step which is Admin, but error still remains there

### Actual result
Error: Could not connect to the database! Please, make sure the details are correct.

### System information (Akaunting, PHP versions)
"php": "^7.2",
        "ext-bcmath": "*",
        "akaunting/firewall": "1.2.*",
        "akaunting/language": "1.0.*",
        "akaunting/menu": "1.0.*",
        "akaunting/module": "1.0.*",
        "akaunting/money": "1.0.*",
        "akaunting/setting": "1.1.*",
        "akaunting/version": "1.0.*",

**Comment by sarriaroman** [comment]
Same error here with version 2.0.3/2.0.4:

Access denied for user '...'@'localhost' (using password: YES) (SQL: insert into `tqp_companies` (`domain`, `enabled`, `updated_at`, `created_at`) values (, 1, 2020-03-08 00:33:05, 2020-03-08 00:33:05))

Everything else works but not that and the installation is broken. Seems like the domain is not being populated.

If I check the Database is being created with all the tables, so, the connection works even when the Error says "Access Denied"

**Comment by rmsaitam** [comment]
@sarriaroman 

The problem in this case is in the database access credentials. In MySQL DBMS from version 5.7, root user authentication is via Socket Unix TCP, by default, only root access is localhost (directly on the server). It is necessary to create a user and apply GRANT to the user with INSERT, UPDATE, SELECT, DELETE, CREATE, DROP permissions.

CREATE is required to perform migrations (tables).
DROP, if you are going to do a roolback, however it is optional.

CREATE USER `newuser` @` IPServer` IDENTIFIED BY `password`;

GRANT ALL PRIVILEGES ON *. * TO `newuser` @ `IPServer` IDENTIFIED BY `password` WITH GRANT OPTION;

**Comment by sarriaroman** [comment]
The user has all the permissions over the Database and the error is still the same.
![Screen Shot 2020-03-07 at 22 27 17](https://user-images.githubusercontent.com/370885/76154905-efb8a980-60c2-11ea-839d-43e3de256022.png)

**Comment by denisdulici** [comment]
Not able to reproduce such an issue, feel free to use the forum for further support.
