### ISSUE TITLE
Dashboard Error after making entry in Income or Expense Tab. 

### ISSUE THREAD

**Issue by gajendrazts** [akaunting/akaunting#134]
Hi
I have installed akaunting(1.1.1) using softaculous which is not working properly after making entry in expense and income tab.
If i am adding some entry in payments or revenues then it's adding successfully but after that i can't access dashboard or income report. It's showing some error (attached). If i delete that entry then it's working fine.

Kindly fix this issue.

Thanks

![error](https://user-images.githubusercontent.com/34093931/33704185-74b802f6-db51-11e7-9216-765030fd341a.png)

**Comment by denisdulici** [comment]
Hello.

There is no such a known/common issue so plz, enable debugging to see what's going wrong there: https://akaunting.com/docs/developer-manual/debug

Regards

**Comment by gajendrazts** [comment]
Please find the  error message .

[Debug-msg.pdf](https://github.com/akaunting/akaunting/files/1538428/Debug-msg.pdf)

**Comment by drik** [comment]
Same as #112

**Comment by gajendrazts** [comment]
Currencies rate is by default going to 1.00000000 even after setting it to 1 .

![currencies edit](https://user-images.githubusercontent.com/34093931/33793236-27cf40e6-dcda-11e7-8250-fce7a39cb6d3.png)

![currencies rate after edit](https://user-images.githubusercontent.com/34093931/33793243-4961046a-dcda-11e7-8e3a-196763b9b305.png)

**Comment by denisdulici** [comment]
This is what I get on my local/web server: https://akaunting.com/docs/user-manual/settings/currencies

Can you please share more info about your PHP/MySQL?

**Comment by drik** [comment]
I think you must look closer to the script responsible for the database creation. 
Because in my case, the rate fields are created like double(5, 8).... Which cause the problem

Rolling through the code, I saw :
 - $table->float('rate', 15, 8); in version 1.0.0 tag (https://github.com/akaunting/akaunting/blob/1.0.0/database/migrations/2017_09_01_000000_create_currencies_table.php)
 - $table->double('rate', 15, 8); in version 1.0.7 tag (https://github.com/akaunting/akaunting/blob/1.0.7/database/migrations/2017_09_01_000000_create_currencies_table.php)

The problem must be arround how the db fields are realy created with those instructions ($table->float and $table->double)

**Comment by crackermania** [comment]
I do have same issue on 1.1.1. However, tested using 1.1.2, this issue gone.

**Comment by gajendrazts** [comment]
the issue remain same even after updating the version 1.1.4

 [11:38:48] LOG.error: exception 'InvalidArgumentException' with message 'Operand "1.00000000" should be an integer or a float' in /home/user**/public_html/url**/vendor/akaunting/money/src/Money.php:372
Stack trace:

I am using php 5.6

**Comment by denisdulici** [comment]
Can any of you guys send me an admin account via email at denis[at]akaunting[dot]com so I could see what is different in your environment?

**Comment by denisdulici** [comment]
Guys, can you please change those lines with the following and try again?

```php
if (!is_int($operand) && !is_float($operand) && !is_double($operand)) {
   throw new InvalidArgumentException('Operand "' . $operand . '" should be an integer or a float or a double');
}
```

**Comment by gajendrazts** [comment]
No changes...same error

it's working fine if line 372 commented  but currency rate is still 1.000000



if (!is_int($operand) && !is_float($operand) && !is_double($operand)) {
   //   throw new InvalidArgumentException('Operand "' . $operand . '" should be an integer or a float or a double');
}
