### ISSUE TITLE
Update from 1.3.18 to 2.0.4 not possible

### ISSUE THREAD

**Issue by jleu84** [akaunting/akaunting#1348]
Auto-Update from 1.3.18 to 2.0.4 not working for local installation. Tested with xamp. 

Same problem like them:
https://akaunting.com/forum/discussion/installation-update/moduleserrorsfinish-error-updating-to-202

### Expected result
Auto-Update updating latest version 1.3.x to 2.0.x

### Actual result
Update failing with error -> Check above link

The problem is within the code. It seems the auto-update is checking if 2.0.x is already installed and then throws error. Tried with different PHP versions before. Always same result. Why is the update from 1.3.18 to 2.0.4 not made with a update step to 2.0.0 made in between?

**Comment by denisdulici** [comment]
Not able to reproduce such an issue so please, continue in forum.
