### ISSUE TITLE
Internet Explorer Login Form Problem

### ISSUE THREAD

**Issue by aliuysal60** [akaunting/akaunting#1354]
### Steps to reproduce the issue

Open Login Form with Internet Explorer
Login Form cannot be displayed

"""This problem is only "Internet Explorer"

Works the way it should be with Mozilla, Chrome, Edge

### Expected result

Login Form is displayed

### Actual result
Login Form cannot be displayed

### System information (Akaunting, PHP versions)

2.0.4

### Additional comments

![image](https://user-images.githubusercontent.com/6507261/76683575-44ee4100-6616-11ea-8a52-8390623bb82f.png)

**Comment by denisdulici** [comment]
Thanks for the feedback but we're not interested in fixing it.
