### ISSUE TITLE
Invoice/Bill's contact change not update currency

### ISSUE THREAD

**Issue by cuneytsenturk** [akaunting/akaunting#1360]

**Comment by aliuysal60** [comment]
@cuneytsenturk
Bu değişiklik, contact seçiminde para birimini güncelliyor fakat items ve alt toplarda bir değişiklik yapmıyor. Aynı para birimini tekrar manuel seçersek bu alanlar güncelleniyor. Sorun sadece görüntülenme de sanırım, kaydettiğimiz de müşterinin para birimi ile kayıt yapıyor.

![image](https://user-images.githubusercontent.com/6507261/76757839-74798680-6799-11ea-9986-c3ee722efb18.png)
