### ISSUE TITLE
Saving edits no longer works

### ISSUE THREAD

**Issue by alex-phillips** [akaunting/akaunting#1363]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Upgrade to 2.0.6

### Expected result
Editing a payment and hitting 'save' should save the payment

### Actual result
Nothing happens

### System information (Akaunting, PHP versions)
Akaunting 2.0.6
PHP 7.3.14

### Additional comments
This worked with the initial 2.0 upgrade

**Comment by denisdulici** [comment]
I just tried with master and it worked fine.

**Comment by alex-phillips** [comment]
@denisdulici Upgraded to 2.0.7 (released after this comment), so not sure if whatever fixed got pushed into this release, but this is still an issue in 2.0.7.
