### ISSUE TITLE
Search filtering does nothing

### ISSUE THREAD

**Issue by alex-phillips** [akaunting/akaunting#1364]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Upgrade to 2.0.6
Go to Purchases > Payments or Purchases > Vendors
Type something into the search field that should have results. Says 'No Data'

### Expected result
Data should be filtered / show results

### Actual result
'No data' is shown

### System information (Akaunting, PHP versions)
Akaunting 2.0.6
PHP 7.3.14

**Comment by denisdulici** [comment]
Duplicate of #1346
