### ISSUE TITLE
Reports are incorrect while using multiple currencies

### ISSUE THREAD

**Issue by komodoinnovations** [akaunting/akaunting#1365]
Hi,
I have some issues in reports while adding multiple currencies. For example if there are invoices one in USD and another in INR, the report is only showing the data in the default currency. It won't convert the currency.

### Steps to reproduce the issue

![screenshot-komodoinnovations com-2020 03 18-12_27_48](https://user-images.githubusercontent.com/52604259/76934129-8d5a7700-6914-11ea-8b83-022970cc24d7.png)

![screenshot-komodoinnovations com-2020 03 18-12_29_08](https://user-images.githubusercontent.com/52604259/76934154-9c412980-6914-11ea-8f4e-11e266425974.png)

![screenshot-komodoinnovations com-2020 03 18-12_30_37](https://user-images.githubusercontent.com/52604259/76934158-9e0aed00-6914-11ea-8778-e829fac086d0.png)

### Expected result

The report should convert the currencies and show the report

### System information (Akaunting, PHP versions)

Akaunting 2.0.6

**Comment by denisdulici** [comment]
That depends on the currency rates, check the [documentation](https://akaunting.com/docs/user-manual/settings/currencies) for more details. Feel free to use the forum for further support.
