### ISSUE TITLE
Date Format Doesnt Changing after Define a Date Format in Settings

### ISSUE THREAD

**Issue by siegteshelos** [akaunting/akaunting#1370]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

1- Go to settings and then localisation
2- Change date format from yyyy-mm-dd to dd-mm-yyyy
3- Go to invoice or bills
4- Fields like invoiced at and due at still displaying info as yyyy-mm-dd instead of dd-mm-yyyy

### Expected result

Should be expected that date format change according location settings. Most of the latin countries, by example use dd-mm-yyyy

### Actual result

All date fields still displaying input field as yyyy-mm-dd instead of dd-mm-yyyy

### System information (Akaunting, PHP versions)

This issue occur from version 1.3.17 until 2.0.6. Probably this issue started before 1.3.17, but I didnt tested

PHP 7.1

### Additional comments

**Comment by denisdulici** [comment]
I just tried and it worked fine for me.

![screenshot_1584982615](https://user-images.githubusercontent.com/5254835/77341922-79fa4200-6d40-11ea-9919-f3f4433d5891.jpg)

**Comment by siegteshelos** [comment]
Hello,

I am attaching three screenshots about this issue:

1- The first is from locatisation tab: ![Print 1](https://user-images.githubusercontent.com/5342341/77358776-3a742b80-6d29-11ea-96e0-1c38e5babee3.png)
2- The second is from the language pack:
![Print 2](https://user-images.githubusercontent.com/5342341/77358804-4b24a180-6d29-11ea-9620-90b61219f51b.png)
3- The third is from the screen where you add or edit a invoice:
![Print 3](https://user-images.githubusercontent.com/5342341/77358833-58da2700-6d29-11ea-939d-1b112aaed2aa.png)

I used an old version as example, but newer versions also display the same issue. I imagine that in this case when changing the date, the fields where we insert the date information should follow the adopted date pattern.

**Comment by siegteshelos** [comment]
@denisdulici this seems to be an old issue, since in the akaunting forum other users asked about how to change the date format for date input fields. The format yyyy-mm-dd is not common for most of the countries.
