### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by xtechgamer735** [akaunting/akaunting#1371]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Updating from 1.7 to 2.0.3

### Expected result
Update works

### Actual result
System is entirely broken

Error is produced in log: [20-Mar-2020 21:47:28 UTC] PHP Fatal error:  Uncaught Symfony\Component\Routing\Exception\RouteNotFoundException: Route [] not defined. in /home/.../vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:420
Stack trace:
#0 /home//...//vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(776): Illuminate\Routing\UrlGenerator->route(NULL, Array, true)
#1 /home//...//storage/framework/views/003b2ed383d34cd8465829be04a5806a4301dcd6.php(11): route(NULL)
#2 /home/.../vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/home//.../..')
#3 /home//...//vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/...//...', Array)
#4 /home//.../vendor/laravel/framework/src/Illuminate/View/View.php(143): Illuminate\View\Engines\CompilerEngine->get('/home//...//...', Array)
#5 /home//...//pay in /home//.../m/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 420

### System information (Akaunting, PHP versions)
2.0.3 - 7.3

### Additional comments
I have tried both re installing and re connecting database and the steps here https://akaunting.com/forum/discussion/installation-update/update-203-not-working-on-my-server of which do not work.

**Comment by denisdulici** [comment]
Feel free to use the forum for update issues.

**Comment by xtechgamer735** [comment]
@denisdulici Posted on the forum but it's been completely ignored. Please advise how I should invoice clients?
