### ISSUE TITLE
[Error Responsive] Menu display some errors

### ISSUE THREAD

**Issue by bctechjsc** [akaunting/akaunting#1376]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

when i view on mobile browser
<img width="493" alt="Screen Shot 2020-03-23 at 21 58 42" src="https://user-images.githubusercontent.com/61673430/77330384-e0d42700-6d51-11ea-89da-00a3c2e7b23c.png">

### Expected result

The menu likes below:
<img width="427" alt="Screen Shot 2020-03-23 at 22 36 56" src="https://user-images.githubusercontent.com/61673430/77334028-dbc5a680-6d56-11ea-9ccb-f2065bed019d.png">

**Comment by ph00lt0** [comment]
Another screenshot of menu not properly sizing on desktop.
This happens if you 'unhover' the menu while loading another page.

![Uploading Screenshot 2020-03-31 at 20.31.22.png…]()

**Comment by denisdulici** [comment]
Fixed in master.
