### ISSUE TITLE
Item discount edit issue (Sale Invoice)

### ISSUE THREAD

**Issue by aliuysal60** [akaunting/akaunting#1381]
### Steps to reproduce the issue
New create sale invoice,
add item discount
Save
edit invoice

### Expected result

discount must be displayed on the line

### Actual result

no discount

![image](https://user-images.githubusercontent.com/6507261/77735593-e8c6ec00-701b-11ea-9e76-d8b8471561dc.png)

![image](https://user-images.githubusercontent.com/6507261/77735736-21ff5c00-701c-11ea-94f3-b4586a4d5dab.png)

### Additional comments
no problem on the purchases bill

**Comment by denisdulici** [comment]
Not able to replicate this on master.
