### ISSUE TITLE
Recurring count always set as 0

### ISSUE THREAD

**Issue by marcofons** [akaunting/akaunting#1384]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. Menu purchases, option payments
2. Button Add new, complete all obligatory fields
3. Select Recurring = monthly and 3 for recurrences
4. Save button
5. Edit the newly added payment and Recurring field will be equal to zero 

### Expected result
[printscreens.docx](https://github.com/akaunting/akaunting/files/4398167/printscreens.docx)
Recurrence of payment set to 3 when editing payment

### Actual result
[printscreens.docx](https://github.com/akaunting/akaunting/files/4398167/printscreens.docx)
Recurrence is set to zero when editing payment

### System information (Akaunting, PHP versions)
Akaunting 2.0.7

**Comment by denisdulici** [comment]
In fact, the problem is not with showing but saving the recurrences as the `recurring_count` field is **always** sent as `0` to the backend. @cuneytsenturk
