### ISSUE TITLE
Adding user and user overview

### ISSUE THREAD

**Issue by ph00lt0** [akaunting/akaunting#1387]
### Steps to reproduce the issue
Go to:
1 Create two companies
2 /auth/users
3 press: add user

### Expected result
A grid that is not scalled out side of the window
A form to add a user. 

### Actual result

User overview looks like this:

![image](https://user-images.githubusercontent.com/15004290/78062791-7f363d00-738f-11ea-8a80-c32e09d3b59d.png)

Then when navigating to 'add new user' I get the following error:
```
Facade\Ignition\Exceptions\ViewException
Call to undefined function array_except() (View: ... /resources/views/auth/users/create.blade.php)
... /auth/users/create 
```

### System information (Akaunting, PHP versions)
PHP 7.4.4, nginx, Accounting 2.0.7

**Comment by federicogodan** [comment]
it happens on cloud version too.

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue. Feel free to use the forum for further support.

![Screenshot (18)](https://user-images.githubusercontent.com/5254835/78220898-0fc56800-74cb-11ea-9e7c-867ae4071bb9.png)

![Screenshot (19)](https://user-images.githubusercontent.com/5254835/78220917-1653df80-74cb-11ea-8c16-6e5589bcd986.png)
