### ISSUE TITLE
Cannot open view of single payment when state is received

### ISSUE THREAD

**Issue by ph00lt0** [akaunting/akaunting#1390]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Go to payments
Open a payment that has been received, and does not have a payment

### Expected result
Viewing payment

### Actual result
```
Facade\Ignition\Exceptions\ViewException
Undefined variable: rand (View: ... /resources/views/modals/bills/payment.blade.php)
... /purchases/bills/10 
```

### System information (Akaunting, PHP versions)
php 7.4.4, nginx, accounting 2.0.7

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue.

![Screenshot (21)](https://user-images.githubusercontent.com/5254835/78221733-97f83d00-74cc-11ea-8207-5ed1e42ca6d2.png)
