### ISSUE TITLE
Date Input Fields Doesnt Change After Setting Being Updated

### ISSUE THREAD

**Issue by dungeonist** [akaunting/akaunting#1391]
This is an old issue that occur in different versions from Akaunting at least this occur from version 1.3.7 until 2.0.6. All date input fields use the pattern yyyy-mm-dd even when the date format setting is changed in localisation page. This format of date is not common for all countries, latin countries like Brazil, Spain, Italy, Portugal and Mexico by example use dd-mm-yyyy and english countries like USA and UK use mm-dd-yyyy. 

A good example of this problem is the invoice creation page. Invoice date and invoice due input fields are always display using the format yyyy-mm-dd.

I am attaching three screenshots about this issue:

1- The first is from locatisation tab: ![Print 1](https://user-images.githubusercontent.com/5342341/77358776-3a742b80-6d29-11ea-96e0-1c38e5babee3.png)
2- The second is from the language pack:
![Print 2](https://user-images.githubusercontent.com/5342341/77358804-4b24a180-6d29-11ea-9620-90b61219f51b.png)
3- The third is from the screen where you add or edit a invoice:
![Print 3](https://user-images.githubusercontent.com/5342341/77358833-58da2700-6d29-11ea-939d-1b112aaed2aa.png)

Steps to reproduce the issue
1- Go to settings and then localisation
2- Change date format from yyyy-mm-dd to dd-mm-yyyy
3- Go to invoice or bills
4- Fields like invoiced at and due at still displaying info as yyyy-mm-dd instead of dd-mm-yyyy

Expected result
Should be expected that date format change according location settings. Most of the latin countries, by example use dd-mm-yyyy

Actual result
All date fields still displaying input field as yyyy-mm-dd instead of dd-mm-yyyy

System information (Akaunting, PHP versions)
This issue occur from version 1.3.17 until 2.0.6. Probably this issue started before 1.3.17, but I didnt tested

PHP 7.1

**Comment by denisdulici** [comment]
Inputs always use ISO 8601 international date format. The date format setting is used in the index, show, and print pages.
