### ISSUE TITLE
upgrade from 1.3.18 to 2.0.6 fails due to foreign key checks

### ISSUE THREAD

**Issue by baradhili** [akaunting/akaunting#1398]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
have 1.3.18 installed, check for updates, run updates or force updates if you have incompatible modules

### Expected result
upgraded

### Actual result
app refuses login, laravel logs gives

`[2020-04-08 16:32:09] production.ERROR: SQLSTATE[23000]: Integrity constraint vi
olation: 1217 Cannot delete or update a parent row: a foreign key constraint fai
ls (SQL: drop table `7cn_vendors`) {"exception":"[object] (Illuminate\\Database\
\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1
217 Cannot delete or update a parent row: a foreign key constraint fails (SQL: d
rop table `7cn_vendors`) at /var/www/yubaba/current/vendor/laravel/framework/src
/Illuminate/Database/Connection.php:669)
`

### System information (Akaunting, PHP versions)
1.3.18, php 7.3

### Additional comments
looks like the upgrade script does not properly check for foreign key violations and does not do any catching when they do fail..

**Comment by baradhili** [comment]
digging around.. yes it was related to the "force update" function when there are apps in the 1.3.18 version that are not apparently v2 compatible.. it looks like the installer simply deletes the modules, it doesn't run a module:migrate-rollback nicely.. so fails when it attempts delete tables that have foreign key relationships..

**Comment by denisdulici** [comment]
This has nothing to do with the code in this repository so please, feel free to use the forum.
