### ISSUE TITLE
Can't run npm scripts

### ISSUE THREAD

**Issue by blackpidgeon** [akaunting/akaunting#1400]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Clone the repository.
Run npm install
Run npm run dev

### Expected result
Exit code 0

### Actual result

ERROR in ./resources/assets/sass/argon.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

  @include bg-variant(".bg-#{$color}", $value, true);
          ^
      Wrong number of arguments (3 for 2) for `bg-variant'
      in /var/www/akaunting/node_modules/bootstrap/scss/utilities/_background.scss (line 4, column 12)
    at runLoaders (/var/www/akaunting/node_modules/webpack/lib/NormalModule.js:316:20)
    at /var/www/akaunting/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /var/www/akaunting/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/var/www/akaunting/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (/var/www/akaunting/node_modules/sass-loader/dist/index.js:89:7)
    at Object.done [as callback] (/var/www/akaunting/node_modules/neo-async/async.js:8067:18)
    at options.error (/var/www/akaunting/node_modules/node-sass/lib/index.js:294:32)
 @ ./resources/assets/sass/argon.scss

ERROR in ./resources/assets/sass/argon.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/dist/cjs.js??ref--5-5!./resources/assets/sass/argon.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

  @include bg-variant(".bg-#{$color}", $value, true);
          ^
      Wrong number of arguments (3 for 2) for `bg-variant'
      in /var/www/akaunting/node_modules/bootstrap/scss/utilities/_background.scss (line 4, column 12)
 @ ./resources/assets/sass/argon.scss 2:14-267

**Comment by aliuysal60** [comment]
https://github.com/akaunting/akaunting/pull/1375/commits/335616f3e94c5b742768dfb58f92d420ff8c746a

**Comment by blackpidgeon** [comment]
Exactly, there is a PR #1375

**Comment by cuneytsenturk** [comment]
Merged https://github.com/akaunting/akaunting/pull/1375
