### ISSUE TITLE
Currency problem in wizard

### ISSUE THREAD

**Issue by aliuysal60** [akaunting/akaunting#1410]
### Steps to reproduce the issue

New create company
Select the company and open the wizard on first login

### Expected result
Currencies should be updated in steps

### Actual result

- Editing is not possible in currencies. Save button does not operate on the currency edit screen

### System information (Akaunting, PHP versions)

PHP 7.3
Akaunting 2.0.8

### Additional comments

![image](https://user-images.githubusercontent.com/6507261/79609591-b03c9e80-80ff-11ea-9819-73a84bd93883.png)

**Comment by cuneytsenturk** [comment]
This issue solved here => https://github.com/akaunting/akaunting/pull/1417
