### ISSUE TITLE
Can someone please explain....

### ISSUE THREAD

**Issue by AnnaLisik** [akaunting/akaunting#1411]
https://github.com/akaunting/akaunting/blob/cd5d4cd3d132a0ded15334bfee21b559a4b3ca85/tests/TestCase.php#L14

why do need blank like there? Thank you.

**Comment by denisdulici** [comment]
Because of [PSR](https://www.php-fig.org/psr).

**Comment by AnnaLisik** [comment]
> Because of [PSR](https://www.php-fig.org/psr).

This made me laugh..... PSR....seriously someone stick to this shit?
