### ISSUE TITLE
Creating new invoice "Column not found"

### ISSUE THREAD

**Issue by rdrane** [akaunting/akaunting#1419]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Fresh installation. Create a new invoice. 

### Expected result
Invoice created successfully. 

### Actual result
Red error popup saying: 
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'discount_rate' in 'field list' (SQL: insert into `cae_invoice_items` (`company_id`, `invoice_id`, `item_id`, `name`, `quantity`, `price`, `tax`, `discount_rate`, `total`, `updated_at`, `created_at`) values (1, 1, 1, Music composition, 1, 140, 0, 0, 140, 2020-04-19 18:29:16, 2020-04-19 18:29:16))"

An invoice is actually created, however clearly not properly. If I try to create a second invoice, the invoice number has not incremented (it is still INV-00001) and the popup error comes up again when saving. 

### System information (Akaunting, PHP versions)
2.0.8, PHP 7.3

**Comment by denisdulici** [comment]
It seems you've not performed the update but uploaded files manually. Try `php artisan migrate` command. Feel free to use the forum for further help.

**Comment by rdrane** [comment]
Thanks, I updated via the update page rather than manually doing the files, so something must have gone wrong there. I'll do a clean reinstall again since I'm on shared hosting and don't can't do SSH
