### ISSUE TITLE
Invoice Status remains unpaid after payment confirmation

### ISSUE THREAD

**Issue by weddingjuma** [akaunting/akaunting#1425]
**I am integrating Mpesa, MTN and TIGO mobile payments**

So far  I have integrated Mpesa successfully  but the invoice status is not changed to Paid  

When payments are made for an Invoice I get confirmation from Mpesa that the payments have been made so at this point I want to automatically update the invoice status to paid but seem

`event(new PaymentReceived($invoice, $request));`   is not working

I am following below sample modules
https://github.com/akaunting/akaunting/tree/master/modules/PaypalStandard/
https://github.com/akaunting/akaunting/tree/master/modules/OfflinePayments

I suspect that there might be a bug in akaunting module package for listeners and Event
Could it be related to https://github.com/akaunting/akaunting/pull/1392/commits/026b6494110c7a30f02023042f9a4871f148b818

Kindly help

### Expected result
Invoice marked as paid

### Actual result
Invoice status remains unpaid

### System information (Akaunting, PHP versions)
I am using akaunting  version 2.0.9
Php 7.3

### Additional comments
Payment Integration Mpesa Kenya, MTN and TIGO, Mpesa Tanzania mobile payments

**Comment by denisdulici** [comment]
I just tested with another payment module and it worked fine. Feel free to post this in the Development category of the forum and I'd be more than happy to help further.
