### ISSUE TITLE
Bug # add new item from ( yourdomain/Akaunting_2/sales/invoices/create )

### ISSUE THREAD

**Issue by hicham-alsayed-ahmad** [akaunting/akaunting#1430]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
click on sales -> Invoices -> add new invoice :

Items table - > click on " type an item name "  -> + add new 

Example: 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12430517/80305752-e351f280-87cf-11ea-92f5-a1596b6c75b3.gif)

### Expected result
add new item

### Actual result
Does not working 

### System information (Akaunting, PHP versions)
Akaunting Version 2.0.10
PHP 7.3
macOS Catalina 
Safari Version 13.1

**Comment by aliuysal60** [comment]
![test](https://user-images.githubusercontent.com/6507261/80309820-f076dd80-87df-11ea-808e-8dd590f74cee.gif)

**Comment by hicham-alsayed-ahmad** [comment]
sorry for misunderstand how the functionalists works .
It's working fine now .
thanks a lot.
