### ISSUE TITLE
When switching to Ukrainian language you will have error 500 instead of a dashboard

### ISSUE THREAD

**Issue by Acvarium** [akaunting/akaunting#1437]
### Steps to reproduce the issue
Go to Settings -> Default and select Language - Українська.
Press Save.
Now click on Dashboard and you will have error 500

### System information (Akaunting, PHP versions)
Akaunting 2.0.11. PHP 7.3

**Comment by denisdulici** [comment]
This is not caused by Akaunting itself but Carbon package and reported to its developers https://github.com/briannesbitt/Carbon/issues/2081

**Comment by kylekatarnls** [comment]
Please double-check your side. I will handle the point if you can reproduce it in https://try-carbon.herokuapp.com/

**Comment by kylekatarnls** [comment]
This will be fixed in Carbon 2.34 (released planned for Wednesday) but you can yet test it requiring `"nesbot/carbon": "dev-master"` in your **composer.json**.

**Comment by denisdulici** [comment]
Thanks @kylekatarnls for your help, really appreciated.
