### ISSUE TITLE
Entering numeric characters (only) into description for payment and/or sale breaks

### ISSUE THREAD

**Issue by happyclan** [akaunting/akaunting#1440]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1.  Create a new payment (or sale).
2.  Complete required fields
3.  Add an attachment
4.  (breaking step) enter ONLY numeric characters into the description
5.  hit save
6.  Watch infinite "dots" run on save 

### Expected result
Payment or revenue entry should save.

### Actual result
Infinite progress on the save button

### System information (Akaunting, PHP versions)
Version 2.0.11 Akaunting
Version 7.2 PHP

### Additional comments
If I put in only alphabetic characters, the description is fine.

**Comment by denisdulici** [comment]
It seems to be a problem with file upload, not numeric characters. Still evaluating...

**Comment by denisdulici** [comment]
This was not caused by Akaunting itself and has been fixed [here](https://github.com/plank/laravel-mediable/pull/177).
