### ISSUE TITLE
Fatal error: Unknown: Failed opening required

### ISSUE THREAD

**Issue by harshitbhatt26** [akaunting/akaunting#1443]
As I installed fresh version from github to my xampp localhost, my installation completed successfully but  when I run command php artisan serve then below error is displaying.

Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Unknown: Failed opening required 'D:\xampp\htdocs\fas\server.php' (include_path='D:\xampp\php\PEAR') in Unknown on line 0

For more detail see the attachment.

![error_1](https://user-images.githubusercontent.com/64131479/81696039-0bed1400-9481-11ea-88ee-7559729c5f43.png)
![error_2](https://user-images.githubusercontent.com/64131479/81696044-0db6d780-9481-11ea-91cf-189bdab280e8.png)

Kindly give me solution for same.

Thanks & Regards,

**Comment by denisdulici** [comment]
Akaunting doesn't ship with serve command, it works fine on your xampp server.

**Comment by harshitbhatt26** [comment]
> Akaunting doesn't ship with serve command, it works fine on your xampp server.

Its not working, give the proper solution.

**Comment by jimoheokoh** [comment]
You are getting that error because you are trying to serve it. If you are using WAMP, you can create a virtual host with the directory path of the installation on localhost and access it directly.

**Comment by dasider41** [comment]
simply run with `php -S localhost:8000`
