### ISSUE TITLE
Apps All Categories not working

### ISSUE THREAD

**Issue by gilbertlici** [akaunting/akaunting#1444]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
When you go to Apps page and click on "All Categories" the page goes down and I got "500 Internal Server Error". I've installed Akaunting on local and I thought it is due to my local, but same thing happens on cloud too.

### Expected result
It should show all categories filtered there.

### Actual result
I've enabled debug mode and this is the error:

Trying to get property 'status_type' of non-object

Check this screenshot:
![Screenshot from 2020-05-12 20-49-19](https://user-images.githubusercontent.com/10884768/81727793-2b406d00-9492-11ea-9997-459badbd5a03.png)

### System information (Akaunting, PHP versions)
Version 2.0.11
PHP 7.2

### Additional comments
When I tried debugging that page it is getting all categories in an array, but down there it is executing that variable like an object. Check the screenshot pls:
![Screenshot from 2020-05-12 20-29-33](https://user-images.githubusercontent.com/10884768/81727612-ea485880-9491-11ea-9b7d-49117398014c.png)

**Comment by denisdulici** [comment]
Confirmed. The problem is with the URL, currently, it redirects to `apps/categories` which should be `apps/home`.

Furthermore, the selected category doesn't come as selected on the redirected page.
