### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by harshitbhatt26** [akaunting/akaunting#1445]
I had successfully fresh install akaunting on centos 7 as per given installation step but when I go to browse and hit the url then its give me 500 Internal Server Error.

Please let me solution for same, why this happens as same steps I follow on xampp windows platform and its working fine but on my VPS sever its not working.
![fas_error](https://user-images.githubusercontent.com/64131479/81800676-d142b480-9530-11ea-9c28-d802e5bddf6e.png)

**Comment by denisdulici** [comment]
Feel free to use the forum for such issues.
