### ISSUE TITLE
Style problem with date field after validation

### ISSUE THREAD

**Issue by simkea** [akaunting/akaunting#1453]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

use this in a template:

`{{ Form::dateGroup('started_at', trans('geno-manager::general.label.started_at'), 'calendar', ['required' => 'required', 'id' => 'started_at', 'class' => 'form-control datepicker', 'date-format' => 'd.m.Y', 'autocomplete' => 'off'], null, 'col-md-4') }}
`
Define this Field as required in the RequestRules; then push the Submit Button...

### Actual result

![image](https://user-images.githubusercontent.com/612913/82751348-d0264880-9db6-11ea-8cd6-b8de3c079f04.png)

### System information (Akaunting, PHP versions)

2.0.12, PHP 7.3.x

**Comment by denisdulici** [comment]
Confirmed, thanks @simkea for reporting.
