### ISSUE TITLE
Impossible to Filter Report Using Only One Criteria

### ISSUE THREAD

**Issue by dungeonist** [akaunting/akaunting#1454]
Since the update to version 2.0 is not possible to filter reports using only one criteria.  

### Steps to reproduce the issue

1- Visit a report like income summary (www.yoursite.com/common/reports/1)
2- Check the filters available. There is no more an option to filter based on all categories or all bank accounts
![screenshot-www dungeonist org-2020 05 24-20_49_27](https://user-images.githubusercontent.com/5342341/82767777-65016400-9e00-11ea-9e6e-e1e370c6e8b6.png)

### Expected result

Previously there is a default options that include all clients, categories and bank account.
![screenshot-old dungeonist org-2020 05 24-20_53_54](https://user-images.githubusercontent.com/5342341/82767834-d50fea00-9e00-11ea-8e01-4f3d2d385be4.png)

### Actual result

Is impossible to have a report with all revenue categories since there is an option to display all categories.

![screenshot-www dungeonist org-2020 05 24-20_55_45](https://user-images.githubusercontent.com/5342341/82768065-d17d6280-9e02-11ea-8981-64eccde7d9e4.png)

### System information (Akaunting, PHP versions)

Akaunting 2.0.12

**Comment by denisdulici** [comment]
Will be fixed #1346
