### ISSUE TITLE
Amount is erased when changing account in payments

### ISSUE THREAD

**Issue by javilemp** [akaunting/akaunting#1456]
### Steps to reproduce the issue
Go to: /purchases/payments/create
Write an amount in the default currency
Change account with a different currency

### Expected result
Account is changed
Currency is changed
The amount isn't erased

### Actual result
Account is changed
Currency is changed
The amount is erased

### System information (Akaunting, PHP versions)
Akaunting 2.0.13

**Comment by denisdulici** [comment]
Confirmed, thanks @javilemp for reporting.
