### ISSUE TITLE
Changing favicon doesn't propagate

### ISSUE THREAD

**Issue by michaesc** [akaunting/akaunting#1457]
### Steps to reproduce the issue

1. Replace the file 'public/favicon.ico' with a more suitable (customised) icon.
2. Open a web browser, navigate to Akaunting, and observe the favicon in the URL bar.

### Expected result

The Akaunting server sends the new favicon file on HTTP requests.

### Actual result

The Akaunting server sends the old favicon file that has since been replaced.

### System information (Akaunting, PHP versions)

Akaunting 2.0.13
Ubuntu 18.04 AMD64
Nginx 1.14.0-0ubuntu1.7
PHP-FPM 1:7.2+60ubuntu1

### Additional comments

It's obvious what is happening, that Akaunting is optimising the HTTP request and response flow by precompiling public HTML files. Thank you for this optimisation.

I didn't find any user guide that explains how to force this precompilation, for example once a file in public is modified. I looked in the forums as well, and couldn't find the information. Sorry to make this information request here in the bug tracking area.

**Comment by denisdulici** [comment]
Unfortunately, this is not related to Akaunting itself.
