### ISSUE TITLE
Error when viewing records with attachments

### ISSUE THREAD

**Issue by boumanb** [akaunting/akaunting#1458]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Can be read here: https://akaunting.com/forum/discussion/general/error-when-viewing-bills-with-attachments

URL describes enough.

### Expected result
A working page. 

### Actual result
A TypeError causing Akaunting to stop working. 

### System information (Akaunting, PHP versions)
Akaunting 2.0.13 

### Additional comments
Fixed in https://github.com/plank/laravel-mediable/issues/180

Released in https://github.com/plank/laravel-mediable/releases/tag/4.2.3

**Comment by denisdulici** [comment]
Thanks @boumanb. It will be available in the next version.
