### ISSUE TITLE
Unauthorized access to invoices and bills (pdf / print) 

### ISSUE THREAD

**Issue by tognit** [akaunting/akaunting#1461]
### Steps to reproduce the issue
Users without authorization for invoices/bills can use the link
_"sales/invoices/1/print"_ or _"sales/invoices/1/pdf"_
access the invoices/bills.

### Expected result
no access!!!

### Actual result
access to all invoices or bills

### System information (Akaunting, PHP versions)
Version 2.0.13
PHP 7.2.31

### Additional comments
access to print and pdf must also be protected according to authorizations!

**Comment by denisdulici** [comment]
Not able to reproduce!!!

**Comment by tognit** [comment]
OK?

**Comment by tognit** [comment]
Access to PDF and print can be protected with the following addition in the Invoices Controller.

`$this->middleware('permission:read-sales-invoices')->only(['printInvoice', 'pdfInvoice']);`

or your own permission: "print-sales-invocies"
