### ISSUE TITLE
Password resets don't work

### ISSUE THREAD

**Issue by julianheusel** [akaunting/akaunting#1462]
### Steps to reproduce the issue
- Reset your password in the login mask

### Expected result
- Should send reset link
### Actual result
- Loading button is displayed all the time
- No reset link sent

### System information (Akaunting, PHP versions)
Akaunting 2.0.13 // PHP 7.4.3

**Comment by denisdulici** [comment]
You should enter the `MAIL_` details in `.env` file as there is no company at that point.
