### ISSUE TITLE
"Income vs Expense"-report gives wrong sum with recurring invoice

### ISSUE THREAD

**Issue by ali106uit** [akaunting/akaunting#1471]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. Create a recurring invoice
- Test case has 1 item priced at 200, taxes 0% -> invoice total of 200, with 6 as the Recurring number. Both daily and monthly tested.
- Check value reported by "Income vs Expense" under Reports

### Expected result
With test case: 200 + 6x200 = 1400

### Actual result
(200 + 6x200) + 6x200 = 2600

### System information (Akaunting, PHP versions)
Akaunting 2.0.13
PHP 7.3

### Additional comments
Non-recurring invoices seem to work as expected.

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue.

![Screenshot - 2020-06-23T014928 643](https://user-images.githubusercontent.com/5254835/85342918-53d96f00-b4f4-11ea-8d3a-7f13dac71f4c.png)
