### ISSUE TITLE
Side nav on mobile not visible. 

### ISSUE THREAD

**Issue by chistel** [akaunting/akaunting#1473]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Visit app on mobile

### Expected result

Show side nav

### Actual result

![Screenshot_20200607-082410](https://user-images.githubusercontent.com/46791424/83962811-6dde4500-a898-11ea-847a-9af5f382fed0.png)

### Additional comments
The side nav does not show on mobile. It makes it difficult to use all the features as there's no means of seeing them.

**Comment by cuneytsenturk** [comment]
Thank you your feed back @chistel . This issue fixed next version.

**Comment by chistel** [comment]
Alright @cuneytsenturk
