### ISSUE TITLE
Not able to create newline in email templates

### ISSUE THREAD

**Issue by denisdulici** [akaunting/akaunting#1475]
### Steps to reproduce the issue

Go to *Settings > Email* and hit enter for newline in any template

### Expected result

Create a new line

### Actual result

Create a paragraph (two lines)

### System information (Akaunting, PHP versions)

Akaunting 2.0.13

### Additional comments

https://akaunting.com/forum/discussion/general/whitespace-on-newlines-in-custom-email-templates

**Comment by quangbahoa** [comment]
Yea me too.
