### ISSUE TITLE
 Update from Akaunting 2.08 to 2.015 cause GuzzleHTTP Error

### ISSUE THREAD

**Issue by buzzy3** [akaunting/akaunting#1484]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Update on Debian 9 and Debian 10 the Akaunting 2.08 to the latest over WebGUI.

### Expected result

Expected to run a smooth upgrade

### Actual result

Stuck on 80 Prozent, HTTP Upstream on NGINX and GuzzleHTTP Errors
WebGUI Gives Print of: The stream or file "/var/www/akaunting/storage/logs/laravel-2020-06-15.log" could not be opened: failed to open stream: Permission denied

and the URL /install/updates/run/core/2.0.15 is not responding. A cookie delete let you login into an blank page after.

production.ERROR: Uncaught Error: Call to undefined function GuzzleHttp_idn_uri_convert() in /var/www/akaunting/modules/Stripe/vendor/guzzlehttp/guzzle/src/Client.php:220

### System information (Akaunting, PHP versions)

PHP 7.3.16-1+0~20200320.56+debian9~1.gbp370a75 (cli) (built: Mar 20 2020 14:36:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.16, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.16-1+0~20200320.56+debian9~1.gbp370a75, Copyright (c) 1999-2018, by Zend Technologies

### Additional comments

It seems, that GuzzleHTTP is being added to the required PHP Package list, without any requirement notification in the built-in Changelog Description. It raises plenty of other permission error.
![Bildschirmfoto 2020-06-15 um 22 39 16](https://user-images.githubusercontent.com/265888/84707291-bcf23d00-af5e-11ea-986d-048f93d9fdfb.png)
![Bildschirmfoto 2020-06-15 um 22 43 12](https://user-images.githubusercontent.com/265888/84707297-bf549700-af5e-11ea-90e0-7fa460ad15d3.png)
![Bildschirmfoto 2020-06-15 um 22 43 26](https://user-images.githubusercontent.com/265888/84707300-c085c400-af5e-11ea-97b2-c3057f674c79.png)

**Comment by denisdulici** [comment]
It seems you've permission problems with storage/logs directory. Feel free to use the forum for such queries.
