### ISSUE TITLE
Customer search doesn't works

### ISSUE THREAD

**Issue by fatihalp** [akaunting/akaunting#1489]
Customer search doesnt works

### Steps to reproduce the issue
Create customer
Search in listing

### Actual result
No data error

![image](https://user-images.githubusercontent.com/219454/85005262-706e5380-b150-11ea-92ac-6a3f4e80e610.png)

### System information (Akaunting, PHP versions)
https://app.akaunting.com

**Comment by denisdulici** [comment]
Duplicate of https://github.com/akaunting/akaunting/issues/1346
