### ISSUE TITLE
API Key incorrect

### ISSUE THREAD

**Issue by jamescumming** [akaunting/akaunting#1491]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create new company
Go to "Apps" menu item
Click on "Click here to get your API key"
Copy API key from website and paste
Save

Get Error message "Error: The API Key entered is invalid!"

**Comment by denisdulici** [comment]
Feel free to use the forum for such queries.
