### ISSUE TITLE
Flow of multselect blade

### ISSUE THREAD

**Issue by chistel** [akaunting/akaunting#1492]
this is really not a code issue, it more of understanding how it works. I tried to get answers via doc or forum, but nothing came through. 

am working on an akanunting module where I need to use the multiselect partial blade. 
but I can't seem to get it working on selected values. can the UI have documentation for easy flow??

Here is what I tried

`{{ Form::multiSelectGroup('tags', 'tags', null, $objectToSelect->pluck('name','id')->toJson(), $objectsSelected->pluck('tag.name','id')->toJson()) }}
`

**Comment by denisdulici** [comment]
Replied on forum.

**Comment by chistel** [comment]
Thanks, also responded
