### ISSUE TITLE
Drop-downs not sorted alphabetically

### ISSUE THREAD

**Issue by denisdulici** [akaunting/akaunting#1495]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Go to invoice/bill create page and try to select a customer/vendor.

### Expected result

Sorted alphabetically

### Actual result

Sorted by id

![Z80wBeJB](https://user-images.githubusercontent.com/5254835/85229300-91a19f00-b3f1-11ea-9d17-0c6bbf9d8eea.png)

### System information (Akaunting, PHP versions)

Akaunting 2.0.15

### Additional comments

https://akaunting.com/forum/discussion/ideas/sort-dropdowns

**Comment by cuneytsenturk** [comment]
ref commit -> https://github.com/akaunting/akaunting/commit/683b2a372dc009497c5f8a3a82c94e301ea869a9
