### ISSUE TITLE
- Feature Request - Integrate in SuiteCRM

### ISSUE THREAD

**Issue by bd8392** [akaunting/akaunting#1497]
As stated above =). This software seems to be amazing! It maybe would ease your work, if you integrate with other amazing opensource-software instead of developing yourself =) If I can be of any help, let me know =)

**Comment by bd8392** [comment]
Oh no why is this closed? :-( have I done something wrong? Should I ask for features somewhere else? Or is it simply not on roadmap/planed to integrate into other crm?

**Comment by denisdulici** [comment]
While creating an issue, it clearly states:

> Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

**Comment by bd8392** [comment]
Oh I'm sorry... thanks for the help :-). And thank you for all the effort you put into accounting :-)
