### ISSUE TITLE
\Akaunting\Module\Commands\InstallCommand should check if already installed

### ISSUE THREAD

**Issue by dwkitchen** [akaunting/akaunting#1499]
### Steps to reproduce the issue

```
php artisan module:install double-entry 1
php artisan module:install double-entry 1
```

### Expected result

```
Module [double-entry] installed!
Module [double-entry] already installed!
```

### Actual result

```
Module [double-entry] installed!
Module [double-entry] installed!
```

This results in multiple entries in the `modules` table

### Additional comments

Currently working on adding module install/enable/disable to the API

**Comment by denisdulici** [comment]
How are you exactly trying to add that? Any code to show may help.

**Comment by dwkitchen** [comment]
I'm not, but using that artisan command will install the same module twice on a company.

Your code calls the command in app/Traits/Modules.php L433

Calling a command like this seems non-standard practice to me, but I'm not a Laravel developer.
