### ISSUE TITLE
Can't make payment due to rounding issues

### ISSUE THREAD

**Issue by spronych** [akaunting/akaunting#1500]
### Steps to reproduce the issue

Create a new bill and create an item for $46.58 and apply 15% tax. The tax ($6.99) and total ($53.57) are calculated as expected.

### Expected result

Bill payment error checks should be calculated using 2 decimals and not use the 4 decimals as they are currently stored in the database.

### Actual result

When you go to pay the bill for $53.57 you get the error message that "the amount you entered passes the total". The only way to pay the bill is to enter $53.56. On the paid screen and on the general ledger the amounts are now off by $0.01. 

### System information (Akaunting, PHP versions)

Akaunting 2.0.15, PHP 7.3.19

### Additional comments

In the database the totals are being stored as double(15,4) and in this case the "53.5670" appears to be what the error calculation is using (not the rounded number).

_Sample bills screen_
![1-bills-screen](https://user-images.githubusercontent.com/4835538/85447709-4bbd1600-b56c-11ea-85fd-fcf7646807ab.png)

_Payment error sample_
![2-payments-screen](https://user-images.githubusercontent.com/4835538/85447721-5081ca00-b56c-11ea-8ac2-37bf40daf180.png)

_Bill marked as paid although it is $0.01 short_
![3-paid-screen](https://user-images.githubusercontent.com/4835538/85447728-54155100-b56c-11ea-83a0-8a20f60c30e5.png)

**Comment by denisdulici** [comment]
You should change the precision from settings page https://akaunting.com/docs/user-manual/settings/currencies

**Comment by spronych** [comment]
Currency is already set to 2 decimal places so this is still a bug unless I am missing something? This also affects things such bank account reconciliation.

![Currency-precision](https://user-images.githubusercontent.com/4835538/85453765-9b9edb80-b572-11ea-9faa-94b679707ebd.png)

**Comment by spronych** [comment]
I just looked at your source code and the problem is that the PHP function bccomp does not round numbers. No arbitrary precision libraries do it this way. It stops calculating after reaching the "scale" of decimal places, which means that your value is cut off after the scale number of digits, and is not rounded. 

This error occurs on line 107 of the CreateDocumentTransaction.php file and line 40 of the BcMathCalculator.php file.

You can test this by running the following code:

```
<?php

$number2 = "54.66";
$number4= "54.6571";

$compare1 = bccomp($number2, $number4, 1);
$compare2 = bccomp($number2, $number4, 2);
$compare3 = bccomp($number2, $number4, 3);

echo '1 decimal = ' . $compare1 . ' | 2 decimals = ' . $compare2 . ' | 3 decimals = ' . $compare3;
```
