### ISSUE TITLE
General Ledger inaccurate calculation of totals (double-entry module)

### ISSUE THREAD

**Issue by spronych** [akaunting/akaunting#1501]
### Steps to reproduce the issue

Create 3 invoices as per the attached file (item cost $15.35 with 15% tax for an invoice total of $17.65).

Next view the General Ledger report that is provided by the double-entry module. 

### Expected result

The total of the 3 invoices should be $52.95 (3 x 17.65).

### Actual result

The accounts receivable the says $52.96 ($0.01 higher than expected).

### System information (Akaunting, PHP versions)

Akaunting 2.0.15, PHP 7.3.19

### Additional comments

The calculations are being based on the 4 decimal number as stored in the database and aren't being rounded properly to 2 decimal places.

_Sample invoice_
![invoice-inv-00001](https://user-images.githubusercontent.com/4835538/85451611-74dfa580-b570-11ea-970b-6f69ea8c2357.png)

_Sample general ledger_
![general-ledger-1](https://user-images.githubusercontent.com/4835538/85451621-7741ff80-b570-11ea-84d6-bcb5bbee0709.png)

**Comment by denisdulici** [comment]
Not related to the code in this repository.

**Comment by spronych** [comment]
This module is developed by you though so I assume you will pass this bug along to whoever is responsible? These rounding errors are a major issue since we rely on the reports to give accurate financial statements.
