### ISSUE TITLE
BC Math functions don't use rounded numbers

### ISSUE THREAD

**Issue by spronych** [akaunting/akaunting#1502]
The PHP function bccomp does not round numbers. No arbitrary precision libraries do it this way. It stops calculating after reaching the "scale" of decimal places, which means that your value is cut off after the scale number of digits, and is not rounded. 

This error occurs on line 107 of the CreateDocumentTransaction.php file and line 40 of the BcMathCalculator.php file.

You can test this by running the following code:

```
<?php

$number2 = "54.66";
$number4= "54.6571";

$compare1 = bccomp($number2, $number4, 1);
$compare2 = bccomp($number2, $number4, 2);
$compare3 = bccomp($number2, $number4, 3);

echo '1 decimal = ' . $compare1 . ' | 2 decimals = ' . $compare2 . ' | 3 decimals = ' . $compare3;
```

The same problem also occurs where you are using the bcadd function. It is adding values that aren't properly rounded. If the numbers are properly rounded you should expect to see results of 3.0, 2.99, and 2.987 but instead bcadd gives the results of 2.9, 2.98 and 2.987.

```
<?php

$number2 = "1.49";
$number4= "1.4971";

$add1 = bcadd($number2, $number4, 1);
$add2 = bcadd($number2, $number4, 2);
$add3 = bcadd($number2, $number4, 3);

echo '1 decimal = ' . $add1 . ' | 2 decimals = ' . $add2 . ' | 3 decimals = ' . $add3;
```

_Originally posted by @spronych in https://github.com/akaunting/akaunting/issues/1500#issuecomment-648410256_

**Comment by denisdulici** [comment]
Arbitrary precision means no rounding but I'm not sure to which `BcMathCalculator.php` file are you referring to?

**Comment by spronych** [comment]
That file is part of the MoneyPHP library (vendor/moneyphp/money/src/Calculator/BcMathCalculator.php) so if you are relying on that library to do any calculations then that would explain why some numbers aren't being rounded correctly. I didn't really dig through your code to see what you use that library for so those functions may not be relevant. 

However the usage of the bccomp function in the CreateDocumentTransaction.php does explain why you can get a payment error if the underlying bill total has multiple decimal places.

![payment-error](https://user-images.githubusercontent.com/4835538/86041159-a1d20380-ba1b-11ea-96b9-78d4a8d77a96.png)

**Comment by spronych** [comment]
Here's an example of a reconciliation screen where it is impossible to reconcile an account due to numbers not being rounded correctly (I can provide other examples of reports that show these rounding discrepancies as well). The currency precision is set to 2 decimals so the error isn't because of that.

![reconiliation-error](https://user-images.githubusercontent.com/4835538/86041770-8b787780-ba1c-11ea-9aa9-ebee44e7fd62.png)

**Comment by jamescumming** [comment]
I have encountered the same problems as above

**Comment by christopher-john-czettel** [comment]
Same problem here.

**Comment by denisdulici** [comment]
Working on this issue.

**Comment by spronych** [comment]
Thanks @denisdulici for re-working the rounding calculations. The payment bug is fixed! I'm still having issues getting things to reconcile however. It may be related to the Javascript as things go weird when I click on the "Clear" checkboxes. The cleared amount stays at $0.00 but if I uncheck everything the cleared amount goes to $20.00?

![reconcile-2 0 16](https://user-images.githubusercontent.com/4835538/86956125-fcabdf00-c12e-11ea-9c14-75fc71d6693a.png)
