### ISSUE TITLE
Unable to Delete Dashboards

### ISSUE THREAD

**Issue by yuvraj131** [akaunting/akaunting#1506]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Go To Dashboard > Three Dots Menu > Manage Dashboards > Check Mark the dashboard which was newly created > Select Bulk Actions > Select Delete > Confirm > Confirm the Dialogue Box

### Expected result

The record should get deleted

### Actual result

Error occurs saying the last record cannot be deleted. First Create a new Dashboard and then try again.

### System information (Akaunting, PHP versions)

Php 7.03

### Additional comments

Any help in this regard would be highly appreciated. Thanks!

**Comment by denisdulici** [comment]
I just tried and was able to delete the newly created one. Makes sure that the one you're trying to delete is not assigned to another user that doesn't have another dashboard. Feel free to use the forum for further help.
