### ISSUE TITLE
Wrong indexing of invoices in customer profile

### ISSUE THREAD

**Issue by javilemp** [akaunting/akaunting#1513]
### Steps to reproduce the issue
Go to Sales > Customers
Select a customer with Invoices
Select the Invoices tab

### Expected result
Only get invoices from the selected customer

### Actual result
Some of the invoices of the list are not from the selected customer.

### System information (Akaunting, PHP versions)
PHP 7.3
Akaunting Version 2.0.15

### Additional Comments
![Screen Shot 2020-07-03 at 13 19 08](https://user-images.githubusercontent.com/21262602/86485773-fa611380-bd2f-11ea-906c-d219b4b87840.png)
These 2 invoices are from different customers!

**Comment by denisdulici** [comment]
I'm not sure how you've created them but from the UI I wasn't able to reproduce such an issue. Feel free to use the forum for further help.
