### ISSUE TITLE
Marking invoice of a different currency as paid does not reflect correct amount in the account

### ISSUE THREAD

**Issue by dkyeremeh** [akaunting/akaunting#1514]
First of all, good work for such a great app

### Steps to reproduce the issue
1. Open `Banking > Accounts` and take note of the balance of the default account
1. Add a different currency with a rate which is more or less than 1
1. Create an invoice in the new currency we created
1. Open invoice and mark as paid

### Expected result
If the invoice amount was 100, and the currency has a rate of 2, you will expect the default account to have increased by 50

### Actual result
However, no currency conversion will be applied, the difference will still be 100

### System information
- I'm using the Akaunting cloud
- Akaunting version 2.0.15
- Couldn't determine PHP version 

### Additional comments
It'll also be noted that the currency conversion is not applied in the dashboard and reports as well

**Comment by denisdulici** [comment]
This should be fixed in Akaunting 2.0.16
