### ISSUE TITLE
Can't update to 2.0.16 - cannot download core

### ISSUE THREAD

**Issue by jamescumming** [akaunting/akaunting#1519]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Tried upgrade from 2.0.15 to 2.0.16 on the upgrade page.
Tried upgrading from terminal too: php artisan update:all

### Expected result
Successful upgrade to 2.0.16

### Actual result
Error: not able to download core

### System information (Akaunting, PHP versions)
Akaunting 2.0.15
PHP 7.3.19

**Comment by denisdulici** [comment]
Just tried and was able to update with success. Feel free to use the forum for further help.
