### ISSUE TITLE
Active menu indicator does not change on portal

### ISSUE THREAD

**Issue by seferdemirci** [akaunting/akaunting#1520]
### Steps to reproduce the issue

While browsing between the menu links on the customer portal, the active menu indicator does not change.

### Expected result

Whichever menu is active, it must be marked.

### Actual result

![image](https://user-images.githubusercontent.com/63615719/86826060-dc314580-c098-11ea-81ab-96b10e479017.png)

### System information (Akaunting, PHP versions)

Akaunting 2.0.16, PHP 7.4.2

**Comment by denisdulici** [comment]
`composer update` is also required.
