### ISSUE TITLE
Reconciliation form input values are not set

### ISSUE THREAD

**Issue by spronych** [akaunting/akaunting#1526]
### Steps to reproduce the issue

Create a Banking Reconciliation and click the "Clear" checkbox.

### Expected result

The cleared amount should change the value that is calculated in the totals for "Cleared Amount" and the "Difference". 

### Actual result

Values remain at $0.00. If you uncheck the "Clear" checkbox then the cleared amount and difference are calculated. But if you click one of the "Clear" boxes the totals reset to 0.

![reconcile-2 0 16](https://user-images.githubusercontent.com/4835538/87165175-2c2e2900-c2a0-11ea-83bc-d3f8b71af64a.png)

### System information (Akaunting, PHP versions)

Akaunting 2.0.16, PHP 7.4.6

### Additional comments

In your Javascript the Vue app is looking for the values associated with the checkbox inputs but there is actually no value assigned to those inputs. Additionally the Javascript is using parseFloat() to calculate whether the totals match without taking into account the currency precision (which explains the reconciliation issues referred to  in #1502). So either the values that get embedded in the form either need to be properly rounded or you'll need to use something like parseFloat(t).toFixed($precision).

**Example of input HTML:**

`<input data-field="transactions" v-model="form.transactions.expense_4" id="transaction-4-expense" class="custom-control-input" @change="onCalculate" checked="checked" name="expense_4" type="checkbox">`

**Relevant Javascript code from reconciliations.js:**

```
if (e[t]) {
var n = t.split("_");
"income" == n[0] ? r += parseFloat(document.getElementById("transaction-" + n[1] + "-" 
+ n[0]).value) : o += parseFloat(document.getElementById("transaction-" + n[1] + "-" + n[0]).value)
 }
```

**Comment by denisdulici** [comment]
Confirmed. Would you mind sending a PR @spronych
