### ISSUE TITLE
Hooking Engine

### ISSUE THREAD

**Issue by ankleslapper** [akaunting/akaunting#1527]
Would the project admins be open to the idea of adding this package:
https://github.com/esemve/Hook

Hooks could then added into the models/controllers/views to allow app modules to much more easily custom core functionality.

I'd be happy to work on this and make some pull requests if the admins are open to the idea.

**Comment by denisdulici** [comment]
There are already [such](https://akaunting.com/docs/developer-manual/overriding-output) [features](https://akaunting.com/docs/developer-manual/hooking-models) in Laravel. Feel free to use the forum for further discussion.
