### ISSUE TITLE
Installation from release zip in fails in step 3 of config

### ISSUE THREAD

**Issue by searchfilter** [akaunting/akaunting#1529]
I've attempted installing the latest release 2.0.16, and the previous 2.0.15 by extracting the zip file into my Nginx root folder (public_html). However, after entering database connection details, the site becomes unresponsive and only returns a blank white page from any endpoint.

### Steps to reproduce the issue
0. Install php dependencies as follows:

    sudo apt install php-imagick php7.3-common php7.3-gd php7.3-json php7.3-curl php7.3-zip php7.3-xml php7.3-mbstring php7.3-bz2 php7.3-intl

1. Create a new database for akaunting in MariaDB
2. Download release zip to root Nginx folder (most likely public_html)
3. extract release zip, leaving index.php etc in the root folder
4. Access the website through a web browser
5. Complete step 1 (Language selection)
6. Complete step 2 (database selection/configuration)
7. Wait a little while as the database is configured, and finally get redirected to a blank white page

### Expected result
7. Should allow continuing to configure and use Akaunting

### Actual result
7. Breaks the installation and the whole site is just a white page regardless of the endpoint (/, or /install/settings which is where I got redirected to at first).

### System information (Akaunting, PHP versions)
Akaunting 2.0.16-Stable
PHP 7.3
Nginx 1.14.2-2 (debian 10)

### Additional comments
I didn't create any .env file, I just started the fresh installation. It seems by doing that, the .env.testing gets copied, and I can see that the site is in debug mode during configuration step 1 and 2. I can't find any relevant logs in laravel or nginx outputs.

I can also see that 46 tables have been created in the database, and the .env file has been updated with the database connection parameters.

**Comment by denisdulici** [comment]
Please, use the forum for such issues.
