### ISSUE TITLE
Accounts filter not working in Reports

### ISSUE THREAD

**Issue by developerlafl** [akaunting/akaunting#1532]
### Steps to reproduce the issue
Go to Reports->expense summary

### Expected result
Account filter is not working

### Actual result
![error1](https://user-images.githubusercontent.com/68267189/87391501-81cc4380-c5c8-11ea-9be5-c455076b2e7a.PNG)
![error2](https://user-images.githubusercontent.com/68267189/87391503-8264da00-c5c8-11ea-84e0-4cc75434d0c5.PNG)

 

### System information (Akaunting, PHP versions)
Akaunting :2.0.16
php versions: 7.2

**Comment by denisdulici** [comment]
Duplicated of #1346

**Comment by o---** [comment]
@denisdulici, I doubt that this is a duplicate, since #1346 is closed, however the filter feature is still not working.
