### ISSUE TITLE
Possibly wrong `permission` middleware for a module's controller that is placed in a folder.

### ISSUE THREAD

**Issue by pavel-mironchik** [akaunting/akaunting#1533]
Hello.
I'm working on adding my module in the "Portal" section and stumbled upon such a behavior.

If a module's controller is placed in a folder like `modules/CreditDebitNotes/Http/Controllers/Portal/CreditNotes.php` then the code in the line 53 will reference wrong parts of such a path (wrong array's items):
https://github.com/akaunting/akaunting/blob/a067866de5bed295e613a8a0866da2ab265036d5/app/Abstracts/Http/Controller.php#L47-L55

And therefore, that controler will get wrong `permission` middlewares. To make this code work properly it will need to adjust an index by 1 in case there is a folder: 

![2020-07-15 01-15-28 Ubuntu Mate 19 10 249) - Oracle VM VirtualBox   1](https://user-images.githubusercontent.com/7408605/87466917-ecb56300-c638-11ea-86f4-3539cb26aaad.png)

To quickly reproduce the issue you can use the code from my module's repository.

**Comment by denisdulici** [comment]
Just pushed a fix so in your case the permission would be like `read-credit-debit-notes-portal-credit-notes`
