### ISSUE TITLE
app.akaunting.com Apps Page has Broken Links

### ISSUE THREAD

**Issue by SethiPandi** [akaunting/akaunting#1534]
### Steps to reproduce the issue
1. Head to the Akaunting instance, such as https://app.akaunting.com/.
2. Click `Apps` on the navigation menu.
3. Try access one of the links.

You'll notice they take you to `https://app.akaunting.com/apps/APP_NAME`, but it should be `https://akaunting.com/apps/APP_NAME`. 

### Expected result
When we click the link, we should be taken to the store page, to the app we clicked.

### Actual result
We get taken to the list of apps available.  
https://app.akaunting.com/apps/home

### System information (Akaunting, PHP versions)
Public cloud instance, version 2.0.16.

**Comment by denisdulici** [comment]
That is how it's supposed to work.

**Comment by SethiPandi** [comment]
Are you 100% sure this is how it should work?  

![Peek 2020-07-16 11-11](https://user-images.githubusercontent.com/22801583/87652982-2da29a00-c755-11ea-8d65-aa007d6edfab.gif)

**Comment by denisdulici** [comment]
200% https://screencast-o-matic.com/watch/cYiDQ5Ef3F

You should disable any ad, js, etc. blocker of your browser.

**Comment by SethiPandi** [comment]
Weird :thinking:  
I've disabled AdBlock Origin, that made the Matomo logo appear again, but that GIF I sent is still what I experience when I click one of the app names.

I've also gone to Chromium (no extensions installed) and experience the same behavior.

I've also gone to a private browsing window in Chromium, which I still experience the behavior in the GIF I sent.

Even if I try to go to `https://app.akaunting.com/apps/double-entry` manually I just get redirected back.

![image](https://user-images.githubusercontent.com/22801583/87666876-b3c8db80-c769-11ea-9c12-7026be1e18bc.png)
