### ISSUE TITLE
Partial paid bills could not editable and didn't show original amount

### ISSUE THREAD

**Issue by seferdemirci** [akaunting/akaunting#1537]
### Steps to reproduce the issue

When we want to edit partially paid bills, the editing page is empty.

### Expected result

For sure we should be able to edit the bills whenever we want. Paid partial or not, it doesn't matter.

### Actual result

![akaunting](https://user-images.githubusercontent.com/63615719/87722113-31b7d180-c7c0-11ea-921f-f2913295a805.gif)

### System information (Akaunting, PHP versions)

Akaunting 2.0.16, PHP 7.4

**Comment by denisdulici** [comment]
Fixed here #1547
