### ISSUE TITLE
htmlspecialchars() expects parameter 1 to be string

### ISSUE THREAD

**Issue by quangbahoa** [akaunting/akaunting#1538]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
- Add non-english to invoice note and footer `/settings/invoice` ex `Thông tin thanh toán` and `Thông tin hỗ trợ:`

### Expected result
- Show to invoice pdf

### Actual result
- Cannot view/edit invoice 
`htmlspecialchars() expects parameter 1 to be string, object given (View: /home/***/resources/views/sales/invoices/show.blade.php)`

### System information (Akaunting, PHP versions)
- Version 2.0.16
- PHP-FPM 7.4

### Additional comments
- This happen also effect to your cloud version.

**Comment by quangbahoa** [comment]
@denisdulici I cannot view invoice after upgrade to 2.0.19 even footer & notes are blank.

**Comment by cuneytsenturk** [comment]
I've sent setting form missing default value [fields](https://github.com/akaunting/akaunting/commit/e6f2075eefe37ebdb73b1834c7e233dd8cc8410a) before test it.
I couldn't see the error, look screenshots

1- Invoice shot
![invoice-notes](https://user-images.githubusercontent.com/10936547/91014809-b7664280-e5f2-11ea-8b72-a97dcecff476.PNG)


2- Invoice print
![invoice-print-notes-footer](https://user-images.githubusercontent.com/10936547/91014771-a61d3600-e5f2-11ea-8098-0d8493f8e763.PNG)

**Comment by quangbahoa** [comment]
I've test it on cloud https://app.akaunting.com/sales/invoices/288175
```
  500 Internal Server Error
```
When try to view invoce.

**Comment by cuneytsenturk** [comment]
This issue reason missing fields I've test it.
![missing-field](https://user-images.githubusercontent.com/10936547/91286785-8c692380-e797-11ea-9390-81c40e6db5d2.PNG)
if you select this field everything works.
