### ISSUE TITLE
clickTab is not defined

### ISSUE THREAD

**Issue by quangbahoa** [akaunting/akaunting#1539]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
- Visit `/settings/invoice` 
- Chrome dev errors show `ReferenceError: clickTab is not defined`

### Expected result
- Custom `Item Name`, `Price Name`, `Quantity Name`

### Actual result
- Set it to custom but no addition input show.

### System information (Akaunting, PHP versions)
- Version 2.0.16
- PHP 7.4

### Additional comments
- This also can be reproduce on your cloud version.

**Comment by cuneytsenturk** [comment]
You can do it `npm run prod` or `npm run dev`. it works but. I've delete this line.
