### ISSUE TITLE
Incorrect amount when precision is 0

### ISSUE THREAD

**Issue by quangbahoa** [akaunting/akaunting#1540]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
- Create a new currency and set `Precision` to `0`
- Create a new item eg `my_test_item` then set sale price to `10`
- Create a new invoice then select item `my_test_item`
- Now you can see price show `1000`

### Expected result
- My local currency wiith 0 precision

### Actual result
- Incorrect item price

### System information (Akaunting, PHP versions)
- Version 2.0.16
- PHP 7.4

### Additional comments
- Both cloud and self-host

**Comment by denisdulici** [comment]
Confirmed, it seems JS is not using `precision` correctly.
