### ISSUE TITLE
Tables not responsive

### ISSUE THREAD

**Issue by seferdemirci** [akaunting/akaunting#1541]
### Steps to reproduce the issue

Add any long text such as Vendor or Customer name in the table.

### Expected result

**All texts are intertwined and cannot be read**

![image](https://user-images.githubusercontent.com/63615719/88042052-fae11300-cb53-11ea-8a8c-fa71571ca105.png)

### Actual result

![image](https://user-images.githubusercontent.com/63615719/88042073-03d1e480-cb54-11ea-846e-f6e2314b3031.png)

### System information (Akaunting, PHP versions)

Akaunting Version 2.0.16, Akaunting Cloud App

**Comment by denisdulici** [comment]
Feel free to send the code of correct screenshot as PR.
