### ISSUE TITLE
Creating or editing a company fails with an invalid data input

### ISSUE THREAD

**Issue by emperorjm** [akaunting/akaunting#1548]
### Steps to reproduce the issue

Entered the following:

Name: Test Company
Email: test@test.com
Enabled: Yes

Then click the Save button.

### Expected result

The creation of a new company.

### Actual result

I am getting the following error:

**The given data was invalid.
/home/vagrant/fiwimarket_accounting/vendor/laravel/framework/src/Illuminate/Foundation/Http/FormRequest.php#130
Illuminate\Validation\ValidationException
     */
    protected function failedValidation(Validator $validator)
    {
        throw (new ValidationException($validator))
                    ->errorBag($this->errorBag)
                    ->redirectTo($this->getRedirectUrl());
    }**

### System information (Akaunting, PHP versions)
- PHP 7.4.1
- Akaunting 2.0.16

**Comment by denisdulici** [comment]
Not able to reproduce such an issue, you may have not run npm. Feel free to use the forum for further help.
