### ISSUE TITLE
Format long numbers

### ISSUE THREAD

**Issue by locvfx** [akaunting/akaunting#1549]
### Steps to reproduce the issue
Go to Menu Report, select any report to view details

### Expected result
The report should display the formatted number, easy-to-read numbers. Prefer in the format : 100K, 1M, 1B

### Actual result
The number is very long due to the local currency (VND).  The numbers overlap each other
Kindly look at this screenshot : https://prnt.sc/toe4rb

### System information (Akaunting, PHP versions)
Docker container PHP 7.3
Akauting Version 2.0.15

### Additional comments
The display of numbers in the report is critical for a business owner to track the business's performance. I'm using this App for my personal usage but I can't read the report due to issue
I have tried to find the template in folder resources/common/reports but I can't determine which file I should edit.

**Comment by locvfx** [comment]
hi,
Any update on this request please...

**Comment by denisdulici** [comment]
It's not easy to set that for different languages. Feel free to send a PR in case you know a solution.
