### ISSUE TITLE
Cannot read property 'company_name' of undefined.

### ISSUE THREAD

**Issue by jcphgames** [akaunting/akaunting#1550]
Hi, I need Help.

I'm currently installing akaunting in IIS but I get an error in Admin.

I'm currently use SQL Server for my database.

Help me for this thanks

![image](https://user-images.githubusercontent.com/67801074/88521379-adc4cd00-cfa9-11ea-9612-da2f3446b2e5.png)

**Comment by denisdulici** [comment]
Not able to reproduce it. Feel free to create a new issue according to the template.
