### ISSUE TITLE
Not possible to stop active recurring invoices

### ISSUE THREAD

**Issue by swordf1zh** [akaunting/akaunting#1553]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Set a recurring invoice with repetition number 0 or greater than 1.

### Expected result
Possibility to stop active recurring invoices before reaching the numbers of repetitions set when created.

### Actual result
There is no way to do this.

### Additional comments
This is not a feature request, it's an issue with the recurring invoice subsystem

**Comment by denisdulici** [comment]
Atm, you can stop the recurring by editing the invoice and change the recurring settings.
