### ISSUE TITLE
Item autocomplete/search not working in invoice/bill

### ISSUE THREAD

**Issue by jay4rrrr** [akaunting/akaunting#1554]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Creating or editing Bills (Purchases>Bills) in the field if "Name" that connected to items, the auto filling is not working (you need manually select the item / when you have many items it's difficult to select the right item.

heres the link: https://drive.google.com/file/d/1lLy3wTmbgTqjH4ga9xBQpF4qNVd3JZp8/view?usp=sharing

### Expected result
When start to type in the field, it will auto suggest the field

### Actual result
Not working

### System information (Akaunting, PHP versions)
i experience the issue on the following Akaunting versions from 2.0.16 to 2.0.19, PHP version 7.4

**Comment by denisdulici** [comment]
Confirmed, thanks for reporting.

**Comment by asafov** [comment]
The same problem is at ACL page.
Search box don't search anything.
Locale - ru-RU
Version - last avaiable.
