### ISSUE TITLE
Manager can only view the entered data if read only permission given.

### ISSUE THREAD

**Issue by gajendrazts** [akaunting/akaunting#156]
If read only permission given to manager then the entry should not be editable(click disable on the data) . Manager can open the entry and view the data. There should be View option in Action instead of Edit. 

**It would be nice if edit option will be highlighted inside the entry instead of action tab that to be if that user has rights to edit/modify or else view/read only** .

**Comment by denisdulici** [comment]
They can access edit page (but not submit) because there is no view page atm.

**Comment by gajendrazts** [comment]
it would be better if possible to make how bills tab has option. First click is view then edit(if user has rights).
