### ISSUE TITLE
500 Internal Server Error on Profile

### ISSUE THREAD

**Issue by SethiPandi** [akaunting/akaunting#1565]
### Steps to reproduce the issue
1. Login to Akaunting as normal.
2. Click your username at the top right.
3. Click "Profile"

Or alternatively, just visit: https://app.akaunting.com/auth/users/{VALUE}/edit

### Expected result
For the respective page to load.

### Actual result
![image](https://user-images.githubusercontent.com/22801583/89804876-10cf6b80-db35-11ea-985e-114c9694d987.png)

### System information (Akaunting, PHP versions)
Live instance at app.akaunting.com
Version 2.0.19

**Comment by denisdulici** [comment]
Not able to reproduce: 

![Screenshot_177](https://user-images.githubusercontent.com/5254835/89827797-c663e400-db60-11ea-99ed-5fa6a4520f0b.jpg)

Feel free to use the forum for issues not related to the code in this repository.
