### ISSUE TITLE
Don´t validate Customer password field if "Allow login" isn´t checked

### ISSUE THREAD

**Issue by merylen** [akaunting/akaunting#158]
Hi,

i´m on a fresh installation (Version 1.1.5).

I discovered an strange behavior when i tried to add an customer.
Adding all required information and hitting "Save" didn´t Save the new customer. In fact i didn´t get any response.  

APP_Debug = true shows:

The given data failed to pass validation.
/var/www/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/FormRequest.php#125

All must-have-field have been filled, but i wasn´t able to save.
Adding an customer when writing an Invoice is possible, but then editing wasn´t possible.

After a longer research i hit the bug. 

I´m using a password-Manager which autofills password-fields. 
In this case, the "hidden" field under "Allow login" [Which was not marked by me!] was partial (only the first), auto-filled and this hits the "validation".

In my opinion, the passwort-field shouldn´t be validated when the "Allow login"-field isn´t checked.

Greetings

**Comment by denisdulici** [comment]
I can confirm this Markus, thanks for reporting.

**Comment by sweisgerber-dev** [comment]
To hop on this train, it would be cool to auto-generate the passwords for users if fields are left blank or a checkbox is set.

The password is then only stored in the DB and not sent to anyone.

Users could then reset their password via the reset form.
