### ISSUE TITLE
I can't edit any transaction with attachment!

### ISSUE THREAD

**Issue by seferdemirci** [akaunting/akaunting#1584]
### Steps to reproduce the issue

Go to any transaction like as Payments, Revenues or Invoices with attachment

### Expected result

I expect that I can edit the Payments, Revenues, or Invoices as normally. But it can't open, then the server goes down.

### Actual result

![image](https://user-images.githubusercontent.com/63615719/91646390-5063e600-ea57-11ea-880c-d2406da7e5c6.png)

### System information (Akaunting, PHP versions)

Akaunting V2.0.20, Akaunting Cloud App

### Additional comments

It's a major bug, please intervene as quickly as you can.

**Comment by kamitanw** [comment]
but even without attachment I still get error 500 in bill page
![20200831153716](https://user-images.githubusercontent.com/46672312/91689867-ec006e00-eb9f-11ea-812d-22deecd96509.jpg)

**Comment by denisdulici** [comment]
You can apply this fix https://github.com/akaunting/akaunting/pull/1583

**Comment by kamitanw** [comment]
@denisdulici 

After fixing according to #1583, the error will still occur, when open the billing page(domain/purchases/bills/*), the error will display.

I cannot found anything from php log,or web server log...

env-
litespeed
php7.4

how could I do for it, thank you!
