### ISSUE TITLE
Transaction Attachment upload_max_filesize limit

### ISSUE THREAD

**Issue by seferdemirci** [akaunting/akaunting#1585]
### Steps to reproduce the issue

Add attachment file to any transaction which is more than upload_max_filesize limit.

### Expected result

A notification like "File size should be less than XX MB"

### Actual result

I got error notification like that. And for sure the file not saved.

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `db_name`.`fn_mediables`.`media_id` at row 1 (SQL: insert into `fn_mediables` (`media_id`, `mediable_id`, `mediable_type`, `order`, `tag`) values (, 241, App\Models\Banking\Transaction, 1, attachment))

### System information (Akaunting, PHP versions)

Akaunting V2.0.20, PHP 7.4, upload_max_filesize 2 MB

**Comment by denisdulici** [comment]
You can set the max file size in your [env](https://github.com/akaunting/akaunting/blob/master/config/filesystems.php#L46)

**Comment by seferdemirci** [comment]
For sure I know to increase the max file size limit but the notification error which I got is not suitable. I see SQL error in the notification. Do you think this is a good thing?
