### ISSUE TITLE
Incoherent currency in new invoice when customer selected

### ISSUE THREAD

**Issue by LucaDiba** [akaunting/akaunting#1589]
### Steps to reproduce the issue
1. Add a customer with Euro as default currency (I think it is the same for all currencies that are not USD).
2. Go to the page New Invoice
3. Select that customer

### Expected result
The currency for all items changes to Euro.

### Actual result
The currency for all items remains USD. I have to manually set the currency to USD and then set it back to Euro.

### System information (Akaunting, PHP versions)
Akaunting version 2.0.21
PHP version 7.4.9

**Comment by denisdulici** [comment]
Confirmed, thanks for reporting.
