### ISSUE TITLE
Items are not shown in Edit Invoice page

### ISSUE THREAD

**Issue by LucaDiba** [akaunting/akaunting#1590]
### Steps to reproduce the issue
1. Create a new invoice with some items
2. Edit that invoice

### Expected result
All the added items are in the page and I can edit them one by one.

### Actual result
No item is shown. It is like I didn't add any item when I was creating the invoice.

### System information (Akaunting, PHP versions)
Akaunting version 2.0.21
PHP version 7.4.9

**Comment by denisdulici** [comment]
Confirmed, thanks for reporting.

**Comment by cuneytsenturk** [comment]
https://github.com/akaunting/akaunting/commit/becbcfa1e6e751d4f6f96233b25f86b7f7da55d5
