### ISSUE TITLE
€10,00 becomes €100.000,00 when visualized

### ISSUE THREAD

**Issue by LucaDiba** [akaunting/akaunting#1591]
There are serious problems when amounts in EUR are visualized. 

### Steps to reproduce the issue
1. Go to New Payment (there is the same bug with invoices too, and I think everywhere at this point)
2. Select as Account one with EUR currency
3. Insert as Amount any number (€10,00 for instance)
4. Save

### Expected result
In the Payments page you will see the payment just added with "€10,00" as amount.

### Actual result
In the Payments page you will see the payment just added with "€100.000,00" as amount.

### System information (Akaunting, PHP versions)
Akaunting version 2.0.21
PHP version 7.4.9

### Additional comments
If you come back to the Edit Payment page, the amount is correctly shown in the input (€10,00).
The problem is only when the amount is visualized.
I think that it is because EUR uses a comma instead of a dot.

If you insert "€123,45", Akaunting will show "€1.234.500,00".
If you insert "€1.234,56", Akaunting will show "€12.345.600,00".

**Comment by pavel-mironchik** [comment]
One of my tests fails with EUR, USD, and MTn currencies, $100 becomes $1.000,00, $101 becomes $1.010,00, and so on.

**Comment by denisdulici** [comment]
Not able to reproduce it https://screencast-o-matic.com/watch/cYQiQMHANn

Feel free to use the forum for further help.

**Comment by LucaDiba** [comment]
Thank you.
I opened a thread in the forum.
Anyway, I just recorded the issue, maybe you can find some different setting that contributed to the bug: https://youtu.be/h0jghVuxr0s

Note that:
- at 0:19 there is a little bug with floating points, but I don't care much about it
- at 0:29 you can see that the subtotal shows the amount with the dot and without the € symbol ("xx.yy"), while the total shows the opposite ("€xx,yy"). I think this could be related with the problem, since only the subtotal has this problem
- do not mind about the dashboard at 0:48, it's not related with the invoice

**Comment by LucaDiba** [comment]
I "fixed" the bug by changing the separator symbol on EUR.
So the bug is somewhere in the amount formatting when visualizing it.

Screen recording of the bug and how to fix it: https://youtu.be/Kd9KGVkMXF4
