### ISSUE TITLE
Individual items cannot be deleted

### ISSUE THREAD

**Issue by phungnmit** [akaunting/akaunting#1596]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/35552307/92669201-150cc580-f33b-11ea-8079-181997a45a3a.png)
![image](https://user-images.githubusercontent.com/35552307/92669236-2950c280-f33b-11ea-9590-fb427e6afb63.png)

### Expected result
Each item will be deleted
### Actual result

The delete operation failed, waited a long time but still could not be deleted.
This issue occurs in all categories

### System information (Akaunting, PHP versions)

The latest is 2.0.22

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue. Feel free to use the forum for further help.
