### ISSUE TITLE
New module "bulk_actions" and pagination "limits" variables are undefined

### ISSUE THREAD

**Issue by shanakaperera** [akaunting/akaunting#1597]
I created a new module and declare a class **Reading** inside a folder named **BulkActions** as defined below:

```
class Reading extends BulkAction
{
    public $model = PKReading::class;

    public $actions = [
        'delete' => [
            'name' => 'general.delete',
            'message' => 'bulk_actions.message.delete',
            'permission' => 'delete-pk-readings',
        ],
    ];
}
```
As soon as I included the variable **bulk_actions** inside my module view, I gives me an undefined variable **bulk_actions** error. And same undefined variable **limits** error occurs, once I included the **partials.admin.pagination** view inside my blade as well.

It would be grateful if someone can suggest me how to get rid of these undefined variable errors as I could not find any solution in the Akunting docs as well. 

My akaunting Version 2.0.21

**Comment by cuneytsenturk** [comment]
I've fixed send pull-request so then I've closed this issue. Thank you @shanakaperera for feedback
