### ISSUE TITLE
New tax ignored when adding new items

### ISSUE THREAD

**Issue by LucaDiba** [akaunting/akaunting#1602]
### Steps to reproduce the issue
1. Create a new invoice
2. Add an item
3. When adding a new tax, click "+ Add New"
4. Create a new tax, and save
5. The tax will be assigned to the itam
6. Add a new item

### Expected result
I can select the tax that I've just added.

### Actual result
The tax that I've just added doesn't appear.

### System information (Akaunting, PHP versions)
Akaunting version 2.0.22
PHP version 7.4.9

### Additional comments
Additional bugs:
- when adding a new tax, if you press "Save" twice you add the tax twice (the form should be cleared and the popup disappear when the new tax has been saved)
- if a new tax has been added, it is impossible to create new taxes from that item

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue.

![Screenshot_257](https://user-images.githubusercontent.com/5254835/94272574-e6ead080-ff4b-11ea-84b0-b7b8e9850317.jpg)
