### ISSUE TITLE
installation fails if locale is tr_TR-UTF8 

### ISSUE THREAD

**Issue by ekare** [akaunting/akaunting#1603]
# Steps to reproduce the issue
export LANG=tr_TR.UTF-8
export LC_ALL=tr_TR.UTF-8
php artisan install ... 

### Expected result

Setting locale en-GB

 What is the admin email? [my@company.com]:
 >

 What is the admin password?:
 >

Creating database tables
Connecting to database testdb@localhost:3306
Creating company
Creating admin
Applying the final touches

### Actual result

In MySqlSchemaManager.php line 66:

  Undefined index: index_type

### System information (Akaunting, PHP versions)

on debian 10, both mariadb and mysql ce are tested.

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue. Feel free to use the forum for further help.
