### ISSUE TITLE
Sqlite Database won't support 

### ISSUE THREAD

**Issue by satheeshdomainindia** [akaunting/akaunting#1606]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
 What is the database name?:
 > sqlite(so dont need to provide database name right !!)

 What is the database password?:
 > 

### Actual result

Creating database tables
Connecting to database @localhost:3306
Error: Could not connect to the database! Please, make sure the details are correct.

**Comment by denisdulici** [comment]
It's the password of what you set.
