### ISSUE TITLE
Not able to access payment module at customer side.

### ISSUE THREAD

**Issue by rashmie17** [akaunting/akaunting#1607]
### Steps to reproduce the issue
1. Go to Settings -> Offline Payments and delete any offline payments method which is already used in invoice.
2. Now login using customer email and password and open payment module.

### Expected result
Display list of payments done by customer.

### Actual result
500 Internal Server Error page is displayed.

**Comment by cuneytsenturk** [comment]
thank you your  feedback @rashmie17
