### ISSUE TITLE
Issue in updating bill 

### ISSUE THREAD

**Issue by mhaisumali** [akaunting/akaunting#1608]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
While creating a bill we select an account in table with the respected items it is created perfectly but having an issue in updating it because we again have to select the account in order to save the updated bill. It just shows an id of the account and an error is shown on submitting "undefined index: account_id". I'm adding a screenshot below of the problem in edit bill

### Expected result
I should see the selected account name there and should not be required to reselect an account again

### Actual result
Just gettting an id in that input field and bill is not saved shows an error undefined index: account_id

### System information (Akaunting, PHP versions)
Php version: 7.3
Akaunting version: 1.0.0

**Comment by denisdulici** [comment]
There is no account_id in that form, feel free to use the forum for further help.

**Comment by mhaisumali** [comment]
@denisdulici it is because we have purchased double-entry module also, you can check with that module

**Comment by denisdulici** [comment]
You can use the ticket system for app support. This repo is only for the core.
