### ISSUE TITLE
adding item when creating an invoice

### ISSUE THREAD

**Issue by minusplusminus** [akaunting/akaunting#161]
Hi,

I'm trying to add an item to an invoice I add thru the api, it's not possible for me to send JSON arrays by using common libraries like `Request.js` and `superagent`. 

Is it possible to decode when the item key is string in `app/Http/Controllers/Api/Incomes/InvoicePayments.php`?

Something like this on line 70:
` if(is_string($request['item']))
	        	$request['item'] = json_decode($request['item'],true);
`

**Comment by denisdulici** [comment]
Hello Martijn. JSON is not used for the post data but can check in details if you could send a PR.
