### ISSUE TITLE
Invoice pdf design issue

### ISSUE THREAD

**Issue by rashmie17** [akaunting/akaunting#1614]
### Steps to reproduce the issue
1. Go to Setting -> Invoice and choose template type modern and save.
2. Download invoice. Footer overrides the content of Subtotal and Total.

### Additional comments
[inv-00002-1600838644.pdf](https://github.com/akaunting/akaunting/files/5265742/inv-00002-1600838644.pdf)
![invoice](https://user-images.githubusercontent.com/49587599/93970435-b78d6580-fd8b-11ea-9dc0-e963893c1a7b.png)

**Comment by denisdulici** [comment]
Try to use a wider screen.
