### ISSUE TITLE
Dashboards do not do multi-currency conversions

### ISSUE THREAD

**Issue by giray** [akaunting/akaunting#1616]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
- ) set Main Currency to Euro
- ) enter bill in Euro
- ) enter bill in TRY
- ) enter bill in USD

### Expected result
- ) Dashboard showing the correct Total Expenses in € (euro) with TRY and USD being converted to Euros

### Actual result
- ) SUM of all numbers as Euro

### System information (Akaunting, PHP versions)
- ) Akaounting version 2.0.22 and 2.0.23
- ) PHP 7.4
- ) Apache 2.4.29
- ) Ubuntu 18.04

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue.

![Screenshot_253](https://user-images.githubusercontent.com/5254835/94271560-7abb9d00-ff4a-11ea-8e4e-84f10493ae76.jpg)

![Screenshot_254](https://user-images.githubusercontent.com/5254835/94271579-7e4f2400-ff4a-11ea-9ccf-b61a4026f6a7.jpg)

![Screenshot_255](https://user-images.githubusercontent.com/5254835/94271592-814a1480-ff4a-11ea-8c8c-f9944c144981.jpg)
