### ISSUE TITLE
No way to account for exchange rate changes over time

### ISSUE THREAD

**Issue by giray** [akaunting/akaunting#1617]
### Steps to reproduce the issue
There is no way to set the exchange rate at a given time.  Either automatically or manually.
- ) set Euro as primary 
- ) set exchange rates for TRY and USD
- ) put in bill with TRY or USD 

### Expected result
- ) Use exchange rate based on billing date 
OR
- ) Manually enter exchange rate of that date

### Actual result
- ) static exchange rate is used for conversion no matter the date of the bill

### System information (Akaunting, PHP versions)
- ) Akaounting version 2.0.22 and 2.0.23
- ) PHP 7.4
- ) Apache 2.4.29
- ) Ubuntu 18.04

**Comment by denisdulici** [comment]
I sent the screenshots in the other issue that this is also working fine.
