### ISSUE TITLE
Item with Invalid or Comma Separated Sale or Purchase Price Saves Incorrectly

### ISSUE THREAD

**Issue by SethFalco** [akaunting/akaunting#1618]
### Steps to reproduce the issue
1. Open the Items page.
2. Click "+ Add New" to create a new item.
3. 
    * Complete the form, but for "Sale Price", or "Purchase Price", put in any character that isn't `[0-9,.]`, for example `£36`.
    * Complete the form, but for "Sale Price", or "Purchase Price", put a number with the thousand separator, such as `1,000` for £1,000. 
4. Save the item and observe the new row in the items table.

### Expected result
The form could either:
* Accept the input if it's logical, for example £36 instead of 36, or at least mark this as invalid.
* Display an error to the user that the form was not filled in correctly.

### Actual result
Where an invalid character is used, the item is saved successfully, but the Sale Price and Purchase Price becomes 0 instead of the value specified by the user.

Where a thousand separator is used, it only reads up to the first comma, for example: `1231.13,21313,13213.12313,1313` is read as `1,231.13` and the rest seems to be ignored, and this value is saved to the item _successfully_.

### System information (Akaunting, PHP versions)
Cloud Instance at app.akaunting.com
Version: 2.0.23

**Comment by Samkit-shah** [comment]
@denisdulici can i take this and enable inputs just as number? @denisdulici
