### ISSUE TITLE
Problem when creating new transfer

### ISSUE THREAD

**Issue by jonashellmann** [akaunting/akaunting#1619]
When I want to create a new transfer, I cannot modify the input field for how much money I want to transfer. Instead it shows "NaN" and can't be changed. I got this error after upgrading to version 2.0.22 and it still occurs in the latest version 2.0.23.

### Steps to reproduce the issue
Open Akaunting version 2.0.22 or higher and navigate to _/banking/transfers/create_.

### Expected result
It is possible to enter a money value while creating a new transfer when one account to another.

### Actual result
The input field is prefilled with "NaN" (Not a Number) by default instead of "0,00" and can't be changed.
![2020_09_24_19_00_41_Neu_Transfer_Jonas_Hellmann](https://user-images.githubusercontent.com/15215648/94176395-569f8380-fe98-11ea-872c-d1972011cb1c.png)

### System information

- PHP version: 7.4.4
- Akaunting version: 2.0.7

**Comment by Samkit-shah** [comment]
You need to select Acocunt of FROM and TO you want to make the transaction.
Hope this helps.

**Comment by denisdulici** [comment]
As @Samkit-shah said, you should select the accounts first.
