### ISSUE TITLE
Frontend sidebar bug

### ISSUE THREAD

**Issue by assman** [akaunting/akaunting#1623]
The drawer on the left hand side is extremely unfriendly, it just doesn't dismiss itself on a tablet. Tried this on Safari and Chrome and the issue persists. It works alright on desktop/laptop.

![image](https://user-images.githubusercontent.com/14093665/94678047-78917e00-0350-11eb-965a-078a307c60c8.jpeg)

**Comment by cuneytsenturk** [comment]
We've solved this issue, Thanks @burakcakirel

**Comment by assman** [comment]
Are you 100% sure? I just opened it in my tablet and it is exactly the same behavior as before.
