### ISSUE TITLE
Frontend sidebar bug, Duplicate Names 

### ISSUE THREAD

**Issue by saad-masood** [akaunting/akaunting#1626]
When I add the project section, it lists down on the sidebar list when I uninstall and then installs it again I show the duplicate entry. 
https://akaunting.com/forum

### Steps to reproduce the issue
![errr](https://user-images.githubusercontent.com/43984213/94807349-f4e79800-0408-11eb-84e7-9ed8c3843c8a.PNG)

### Expected result
It should be not duplicate and list down 1 time

**Comment by cuneytsenturk** [comment]
You can use the ticket system for app support. This repo is only for the core.
