### ISSUE TITLE
After caching configuration using php artisan, system redirects to installation page.

### ISSUE THREAD

**Issue by shahalpk** [akaunting/akaunting#1638]
### Steps to reproduce the issue
After completing the installation, validate the login, logout etc. Now cache the configuration.

```
php artisan config:cache
```

Visit the login page again.

### Expected result

System should work as usual.

### Actual result

System redirects to installation page.

### System information (Akaunting, PHP versions)

Akaunting Version: 2.0.16
PHP: 7.1

### Additional comments

In [RedirectIfNotInstalled](https://github.com/akaunting/akaunting/blob/272905decc014541757dc86343f971bfe16406f3/app/Http/Middleware/RedirectIfNotInstalled.php#L20) middleware, env() is referred to access the environment variable `APP_INSTALLED`. Laravel returns `null` for `env()` requests outside config files in a cached context (https://github.com/laravel/framework/issues/21727).

**Comment by denisdulici** [comment]
Config cache is not available atm.
