### ISSUE TITLE
Edit offline payment method issue

### ISSUE THREAD

**Issue by rashmie17** [akaunting/akaunting#1639]
### Steps to reproduce the issue
1) Go to setting -> Offline payment and Create one offline payment method.
2) Edit newly created method but dont update it.
3) Delete that method from list and then click on save button.

### Actual result
Submit button is disabled.

### Additional comments
![1](https://user-images.githubusercontent.com/49587599/95958505-d927bd00-0e1e-11eb-8630-b8420cb28ccd.png)
![2](https://user-images.githubusercontent.com/49587599/95958515-ddec7100-0e1e-11eb-8fe5-40fe946a44c9.png)
![3](https://user-images.githubusercontent.com/49587599/95958520-dfb63480-0e1e-11eb-8c31-4e7cdf59e324.png)
![4](https://user-images.githubusercontent.com/49587599/95958528-e17ff800-0e1e-11eb-9ef1-13b39b120d65.png)

**Comment by denisdulici** [comment]
This is not a user case but feel free to send a PR.
