### ISSUE TITLE
Cant add Bank Account due to "NaN" opening Balance Fresh Install v2.0.23-Stable

### ISSUE THREAD

**Issue by n1ete** [akaunting/akaunting#1640]
This happens on Fresh Install with pgsql php7.3 with Akaunting v2.0.23-Stable on Debian Buster. 
Installations and connection to external DB went fine.
Everything seems to work except for adding a new Bank Account.
When i click on "create new", the new page appears where to put my bank account details. The Value for the Entry "opening_balance" appears for short time correctly with "0" then the page seems to reload and the Value changes to "NaN" and cant be altered.

Any Ideas?

**Comment by denisdulici** [comment]
You should select the accounts.

**Comment by n1ete** [comment]
@denisdulici  Sorry but this doesnt help at all! And if your looking for a Customers to Buy Modules, you should invest a little more Time  in Customer Support.

How should i "select the accounts" if i cant even create one!?

I checked this against the cloud version and it doesnt happen there..... so something is wrong. 

I also switched databases just to make sure that this isnt related to postgresql and it happens with mysql aswell.
So my guess is that something is wrong with my nginx config?

```
server {
    listen 80;
    listen 443 ssl http2;
    server_name akaunting.core;
    ssl_certificate ssl/nginx.crt;
    ssl_certificate_key ssl/nginx.key;
    
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    access_log  /var/log/nginx/akaunting_access.log;
    error_log   /var/log/nginx/akaunting_error.log;

    root  /var/www/html/akaunting/;
    index  index.php index.html;
    charset utf-8;

    # Prevent Direct Access To Protected Files
    location ~ \.(env|log) {
        deny all;
    }

    # Prevent Direct Access To Protected Folders
    location ~ ^/(^app$|bootstrap|config|database|resources|routes|storage|tests|artisan) {
        deny all;
    }
 
    # Prevent Direct Access To modules/vendor Folders Except Assets
    location ~ ^/(modules|vendor)/(.*).((?!ico|gif|jpg|jpeg|png|js|css|less|sass|font|woff|woff2|eot|ttf|svg).)*$ {
        deny all;
    }
 
    location / {
            try_files $uri /index.php;
    }

    location ~ \.php$ {
            try_files $uri =404;
	    fastcgi_split_path_info ^(.+.php)(/.*)$;
            fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_index index.php;
            include fastcgi_params;
    }

    location ~ /\. {
             return 404;
    }

    location ~ (?:composer.json|composer.lock|bower.json)$ {
             return 404;
    }
}
```


If I Buy a Module now do i get support for this Issue aswell? I usually Buy stuff if i know it works well and runs reliable. I am in need of two Modules that i am willing to pay for, but only if the akaunting Server runs stable.
