### ISSUE TITLE
Can't add a new user

### ISSUE THREAD

**Issue by NOLANKANGYI** [akaunting/akaunting#1643]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Add a new user

### Expected result

a new user

### Actual result

POST http://localhost:83/auth/roles 500 (Internal Server Error)
TypeError: Cannot read property 'name' of undefined

### System information (Akaunting, PHP versions)
PHP: 7.4
Akaunting: the latest version (stable)

### Additional comments
<img width="1370" alt="Screenshot 2020-10-19 at 09 58 44" src="https://user-images.githubusercontent.com/42437228/96417526-af411280-11f1-11eb-8151-01e5e0ce5827.png">

**Comment by cuneytsenturk** [comment]
Please update latest version and test it. I've create clean install **Akaunting**
