### ISSUE TITLE
Create new Item page displayed

### ISSUE THREAD

**Issue by rashmie17** [akaunting/akaunting#1649]
### Steps to reproduce the issue
1) Go to Sales->items, there are total 26 items.
2) Jump to last the page.
3) Change page limit to 100.

### Expected result
Display all Items.

### Actual result
Create new item page displayed.

### Additional comments
![create_page](https://user-images.githubusercontent.com/49587599/97165663-0cb50080-17aa-11eb-9606-0bc0b1ee389c.png)
![create_page2](https://user-images.githubusercontent.com/49587599/97165720-235b5780-17aa-11eb-849d-4e1eb62af2c7.png)

**Comment by denisdulici** [comment]
Not able to reproduce.

**Comment by domkrm** [comment]
This is the default behaviour of Laravel. If a non existing page is requested then Laravel returns zero records. There are many discussions on the web about this "problem". But the general opinion is that this is not a framework problem. Rather the application itself should handle this, e.g. jump to first or last page.
