### ISSUE TITLE
Option to adjust size of the cards in dashboard

### ISSUE THREAD

**Issue by pmjcreations** [akaunting/akaunting#165]
Hello Awesome people,

Currently, my Expenses By Category card in the dashboard not showing full categories and the chart.
The reason is that I have many categories to show than the allocated size for the card.
https://prnt.sc/hrgbvf

Do you think to add an option to set the card width to 100% width to give more rooms to all the categories?
This is just a feature request and no need to prioritise high.

**Comment by denisdulici** [comment]
Make the dashboard widgets customizable sounds like a good idea @pmjcreations. Can you please post this request to our forum https://akaunting.com/forum/category/ideas

The issue has been fixed for now https://github.com/akaunting/akaunting/issues/168
