### ISSUE TITLE
Currencies Edit page info disappears after load

### ISSUE THREAD

**Issue by pythondev1** [akaunting/akaunting#1650]
### Steps to reproduce the issue
Brand new install from stable release also from git release, rebuilt node modules.
Video of issue
https://akaunting.axihost.net/akaunting-error.mkv

### Expected result
Expected to see all editable information

### Actual result
Editable information appears in page load at beginning, but after ajax load of config all other information disappears.
See video for exact info

### System information (Akaunting, PHP versions)
Akaunting 2.0.24
PHP 7.4
mysql 8.0

### Additional comments
call to /settings/currencies/config?code=USD 
returns: {}

**Comment by denisdulici** [comment]
Not able to reproduce.
