### ISSUE TITLE
Update file download timesout

### ISSUE THREAD

**Issue by jamescumming** [akaunting/akaunting#1652]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
If the internet connection is slow, the download of the version update file timesout. Error on the console than reads: Unable to download core. 

### Additional comments
Please extend the timeout to 75 seconds or more:

app/Utilities/Updater.php
Line 46

Thanks

**Comment by denisdulici** [comment]
That causes other issues so I'd suggest installing Akaunting on a live server.
