### ISSUE TITLE
mail.php is respected only, not ENV variables or settings from UI

### ISSUE THREAD

**Issue by jhughes2112** [akaunting/akaunting#1653]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Installed docker version from woahbase,  I spent a whole day tracking down issues with ENV variables not being set properly, and after all was said and done, I absolutely do have ENV variables showing up in phpinfo(), but when it comes to MAIL settings, there is a Smtp driver created and cached in "vendor/laravel/framework/src/Illuminate/Support/Manager.php" created from mail.php, which is created on app startup.  If you were to attempt to create a new driver of the same type from DB values, it would only re-fetch this already-created driver, which may have different host, user, password set.  This makes the UI page where you pick port and host useless.  Since it can be set via ENV variable, it can come from there, but the whole point of the UI is to override whatever is in the environment.

### Expected result
UI should always work, or remove UI

### Actual result
mail.php overrides everything else, can't be removed, can't be commented out.   I don't want to edit any files to make my install work properly.  That's bad form.

### System information (Akaunting, PHP versions)
1.3.17

**Comment by denisdulici** [comment]
Can't say anything about docker usage but feel free to send a PR if there is any possible fix.
