### ISSUE TITLE
Whoops, looks like something went wrong

### ISSUE THREAD

**Issue by superstarrajini** [akaunting/akaunting#166]
After Fresh  softaculous Installation on cpanel unable to login to example.com/akaunting/auth/login
(2/2) QueryException
SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `ak_users` where `email` = example@gmail.com and `ak_users`.`deleted_at` is null limit 1)

in Connection.php (line 647)
--
at Connection->runQueryCallback('select * from `ak_users` where `email` = ? and `ak_users`.`deleted_at` is null limit 1', array('example@gmail.com'),object(Closure))in Connection.php (line 607)

**Comment by denisdulici** [comment]
It seems the installation has not succeeded. I would suggest to uninstall and install again.
