### ISSUE TITLE
Automatically create invoices for ongoing jobs

### ISSUE THREAD

**Issue by tognit** [akaunting/akaunting#1665]
# Steps to reproduce the issue 
Automatically create invoices for ongoing jobs

Recurring -> monthly -> 12 executions

### Expected result
An invoice is created automatically every month, max. 12 repetitions

### Actual result
All 12 repetitions are generated at once and sent by e-mail.

WebMail:
![WebMail](https://user-images.githubusercontent.com/1794459/99146976-3cef1100-267d-11eb-8038-efefea3063be.png)

Akaunting:
![Akaunting](https://user-images.githubusercontent.com/1794459/99146986-5abc7600-267d-11eb-8a8e-df36e485bb00.png)

### System information (Akaunting, PHP versions)
Version 2.0.26
PHP 7.2.31

### Additional comments
The same for daily, weekly or yearly.
And times = 0 has no function.

**Comment by denisdulici** [comment]
I just tried on a clean installation and it worked fine for me:

![Screenshot_346](https://user-images.githubusercontent.com/5254835/99772883-a73fff80-2b1c-11eb-8375-8300542625cf.jpg)

0 = unlimited.
