### ISSUE TITLE
Tables seems intertwined

### ISSUE THREAD

**Issue by seferdemirci** [akaunting/akaunting#1668]
# Steps to reproduce the issue

Go to any table and add any text

### Expected result

![image](https://user-images.githubusercontent.com/63615719/99237178-31c8ec00-2809-11eb-8e55-2e417ce944bd.png)

### Actual result

![image](https://user-images.githubusercontent.com/63615719/99237042-034b1100-2809-11eb-89cd-e2d68f7ee598.png)

### System information (Akaunting, PHP versions)

Independent of versions

### Additional comments

The tables are not responsive

**Comment by denisdulici** [comment]
Feel free to send the code of the expected screenshot as PR.
