### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ddlidded** [akaunting/akaunting#1669]
### Steps to reproduce the issue

Added this repository via cPanel
Ran composer install
Proceed to set up, after selecting language instead of bringing me to the next screen this error appears.

### Actual result

{"redirect":"https:\/\/mydomain.com\/install\/database"} displayed in the browser

### System information (Akaunting, PHP versions)

PHP version 7.3

**Comment by denisdulici** [comment]
Follow the [instructions](https://github.com/akaunting/akaunting#installation) for dev version.
