### ISSUE TITLE
Four extra Zero digits on specific components

### ISSUE THREAD

**Issue by toxicos** [akaunting/akaunting#1670]
I tried to test the Akaunting in with a dummy data and dummy account in a self-host environment. However, even with production data, the same issue will occur. 

### Steps to reproduce the issue
I went to create an invoice on a previous date. 
the current date is 19/Nov/2020, and the invoice number was 1/may/2019
I inserted a dummy company and the amount of 15.000,00 euro as for one service.
When I made confirm it and the system put it as "draft", the invoiced amount was different.. It was 150.000.000,00 euro

Apart from that, I inserted a "payment" in order to "clear" the invoice, in the amount of 15.000,00 euro. 
The invoice was full-paid, but some components and reports show 15.000.000,00 euro as payment and as invoice amount.

I attach screenshots

### Expected result

expected results should be 
invoiced amount 15.000,00
payment amount 15.000,00

### Actual result

in reports and some components:
invoiced amount 150.000.000,00
payment amount 150.000.000,00

in other components the amounts are correct

### System information (Akaunting, PHP versions)

Akaunting Version 2.0.26
PHP 7.2
MariaDB Server: 10.3.23-MariaDB-cll-lve
Installed by "Softaculous apps installer"

### Additional comments

Screenshots:

<img width="1412" alt="Screenshot 2020-11-19 at 12 12 58" src="https://user-images.githubusercontent.com/12893701/99653767-1f95ba80-2a62-11eb-9b8e-a70d652378e6.png">
<img width="1410" alt="Screenshot 2020-11-19 at 12 13 18" src="https://user-images.githubusercontent.com/12893701/99653771-21f81480-2a62-11eb-8fbb-3cced5e790f5.png">
<img width="1126" alt="Screenshot 2020-11-19 at 12 10 58" src="https://user-images.githubusercontent.com/12893701/99653795-291f2280-2a62-11eb-9cf7-958f2fc26ce1.png">
<img width="1156" alt="Screenshot 2020-11-19 at 12 10 49" src="https://user-images.githubusercontent.com/12893701/99653802-2c1a1300-2a62-11eb-8c16-06bbc34e466c.png">
<img width="779" alt="Screenshot 2020-11-19 at 12 10 52" src="https://user-images.githubusercontent.com/12893701/99653807-2e7c6d00-2a62-11eb-98bf-2c68f14c84be.png">

**Comment by toxicos** [comment]
in DB the entry is saved correctly as 15000.0000 in the amount column

**Comment by denisdulici** [comment]
Check [this topic](https://akaunting.com/forum/discussion/development/double-read-as-integer-prices-multiplied-by-10000), please.
