### ISSUE TITLE
Type to search on any page not working, just return no data

### ISSUE THREAD

**Issue by bhojkamal** [akaunting/akaunting#1671]
The issue is submitted on forum and link is below. 
https://akaunting.com/forum/discussion/ideas/type-to-search-on-any-page-is-not-working-and-even-bill-item

### Steps to reproduce the issue
The Type to Search on any page is not working. In the list of items, list of bills, list of payments, list of vendors page, list of revenues page, type to search is not working.

### Expected result
I hope this will be fixed soon and I am planning to buy double-entry as it is very essential for accounting.

### Actual result
It says only 'no data' on typing

### System information (Akaunting, PHP versions)
2.0.25, PHP version: 7.3

### Additional comments
Need to fix to make it more friendly.

**Comment by denisdulici** [comment]
It has been fixed in [2.1](https://github.com/akaunting/akaunting/tree/2.1-dev) version which will be released very soon.
