### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by jcbolor** [akaunting/akaunting#1675]
<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xc4261b5be1d]
Security context: 0x0e2407f1e6c1 <JSObject>
    1: /* anonymous */ [0x146b77b4c319] [/var/www/vhosts/accounting.local/web/node_modules/source-map/lib/source-node.js:~342] [pc=0xc4262df28f3](this=0x382472b0d461 <GlobalObject Object map = 0xec1788c21b1>,chunk=0x3ebc65c9ab31 <String[2]\: ,\n>,original=0x108f27d2aac1 <Object map = 0x1a7db7e21f19>)
    2: SourceNode_walk [0x2ae830c51601] [/var/www/vhosts/ac...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8fb090 node::Abort() [node]
 2: 0x8fb0dc  [node]
 3: 0xb031ce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb03404 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xef7462  [node]
 6: 0xef7568 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xf03642 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xf03f74 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf06be1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
10: 0xed0064 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
11: 0x11701ee v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
12: 0xc4261b5be1d 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! akaunting@2.0.0 development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the akaunting@2.0.0 development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jc/.npm/_logs/2020-12-02T04_40_40_292Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! akaunting@2.0.0 dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the akaunting@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jc/.npm/_logs/2020-12-02T04_40_40_369Z-debug.log
[2020-12-02T04_40_40_369Z-debug.log](https://github.com/akaunting/akaunting/files/5627032/2020-12-02T04_40_40_369Z-debug.log)

**Comment by cuneytsenturk** [comment]
Please remove this line [L77](https://github.com/akaunting/akaunting/blob/master/webpack.mix.js#L77) then test again

**Comment by cuneytsenturk** [comment]
I've remove this line.
