### ISSUE TITLE
Invoices missing Items on Edit route 

### ISSUE THREAD

**Issue by baaks** [akaunting/akaunting#1676]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Go to Sales > Invoices > Open an Invoice > Click Edit Button 

### Expected result
The Items already added to the invoice should show on Items section 

### Actual result
The Items is coming empty and all amount is coming as 0. 

### System information (Akaunting, PHP versions)
Akaunting Version 2.0.26
PHP version 7.4.12

### Additional comments
I have another installation on version 2.0.23 that has the items showing properly.

**Comment by denisdulici** [comment]
Not able to reproduce on a clean installation https://screencast-o-matic.com/watch/cYXU1PLRz3
