### ISSUE TITLE
Search bar returns "No Data"

### ISSUE THREAD

**Issue by baaks** [akaunting/akaunting#1677]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Go to Sales > Invoices 

### Expected result
I believe i could search information related to a specific invoice the way we had on Akaunting version 1. Number, Customer, etc... 

### Actual result
There is field "Type to search".. When we try to find any invoice by number name or whatever other field. the field returns a message: "No Data". 

### System information (Akaunting, PHP versions)
Akaunting Version 2.0.26
PHP 7.4.12

**Comment by cuneytsenturk** [comment]
It has been fixed in [2.1](https://github.com/akaunting/akaunting/tree/2.1-dev) version which will be released very soon.
