### ISSUE TITLE
Display Bank account on invoice

### ISSUE THREAD

**Issue by essteffan** [akaunting/akaunting#1686]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Log in, make an invoice, display/print 

### Expected result
I don't see where i can add bank account. I've added on banks but how do i display it on invoice? 

### Actual result
without bank account

### Additional comments
Noob here, please don't judge 👍

**Comment by essteffan** [comment]
Anyone?

**Comment by denisdulici** [comment]
You can use the footer for that purpose.
