### ISSUE TITLE
Step 2 of install (database connection) still problematic

### ISSUE THREAD

**Issue by FBachofner** [akaunting/akaunting#1687]
I have just come back to Akaunting thanks to the generous Christmas add-on discount offers and find that installation step 2 is still unresolved.

There are multiple questions about this on the forums, generally unanswered with any clear details on requirements -- which seem more stringent than those defined in [requirements](https://akaunting.com/docs/requirements) -- much less a definitive solution.

My post, for example is here: https://akaunting.com/forum/discussion/installation-update/error-could-not-connect-to-the-database-please-make-sure-the-details-are-correct-2    It is 2+ years old and unanswered.

A more recent (similar issue) is here: https://akaunting.com/forum/discussion/installation-update/installation-step-2-loop

Anyways, I noticed that [check printing](https://akaunting.com/forum/discussion/ideas/check-printing) is now available, so I thought I'd give Akaunting another try.

So I installed (using "Akaunting_2.0.26-Stable.zip") on Ubuntu 20.04 running PHP 8.0 with MariaDB 10.5.3 on Nginx 1.19.6. I also made sure I have all the required PHP extensions. Various other PHP applications work fine with this configuration.

I am sorry to report connecting to a database is STILL a problem and, frankly, a worse problem than before.
Previously at least it threw an error. Now, the "next" button at step 2 "database" just shows endlessly cycling dots. The Laravel debug bar (is that what it is called?) gives no indication of what is wrong.

As in my original post from 2 years ago, I have tried with an empty database using nothing extraordinary (ASCII-only password; utf8 charset, not utf8mb4).

I have ALSO tried with NO existing database as "app/Http/Controllers/Install/Database.php" seems to suggest Akaunting can create a DB.

The install documentation is still severely lacking (I never posted to it as I never had a fully functioning installation) and I fear that Akaunting will never truly take off (in the self-hosted arena) without that.

So . . . Could one of the Akaunting Devs *CLEARLY* post what the requirements are for a mySQL/MariaDB underpinning the Akaunting app?

For example:
+ can Akaunting create the DB or must it already exist?
+ are there limits (beyond the limits imposed by mySQL/MaraDB) on DB name?
+ are there limits (beyond the limits imposed by mySQL/MaraDB) on DB password?
+ is utf8mb4 supported now?

Thanks you for any insights!  I'd really like to run Akaunting as we run almost exclusively on PHP apps.

**Comment by pavel-mironchik** [comment]
A browser drops the request by a timeout. In meantime, the Akaunting successfully creates database tables and seeds the permissions. A workaround - after a minute replace the `/install/database` in the browser's address bar with the `/install/settings` and proceed with the installation further.

**Comment by chismitnick** [comment]
Sorry to bother you all, i just wanted to find out if this issue had been resolved. I have tried editing the .env file and creating the database on my local MySQL server but to no avail, any help or workarounds will be highly appreciated.

**Comment by denisdulici** [comment]
Unfortunately, not able to reproduce such an issue. If you still can't manage it, feel free to use either the one-click installation on [DigitalOcean](https://bit.ly/akaunting-do-start) or our [Cloud](https://akaunting.com/cloud) service.
