### ISSUE TITLE
Dependency clarification

### ISSUE THREAD

**Issue by anoma** [akaunting/akaunting#1689]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Compare https://akaunting.com/docs/requirements to https://github.com/akaunting/docker/blob/master/php/Dockerfile

### Expected result
The list of dependencies in the documentation should match those installed by the official container.

### Actual result
There is a mismatch.

### System information (Akaunting, PHP versions)
Documentation as 24-12-2020

### Additional comments
I am attempting to build my own Alpine with nginx docker container and whilst it is working I have hit a couple of areas where documentation does not answer all questions and certain features do not work e.g. pdf download.

Whilst debugging this I started by comparing the official dependencies to those in the official container and noticed they do not match. I expect that akaunting is omitting to document dependencies that are quite common or those that are required purely for building but even then it doesn't seem like a direct match.

Summary of web requirement (excluding dbase server side)

**Documentation says to install**

Packages to install

    PHP 7.2.5 or higher
    Web Server (eg: Apache, Nginx, IIS)

PHP Extensions

    BCMath
    Ctype
    JSON
    Mbstring
    OpenSSL
    PDO
    Tokenizer
    XML
    Zip

**Dockerfile installs**

Packages to install (** signify direct match to documentation )

    **php:7.4-fpm**
    libfreetype6-dev
    libjpeg62-turbo-dev
    libzip-dev
    imagemagick
    libmcrypt-dev
    libpng-dev
    libpq-dev
    libxrender1
    locales
    openssh-client
    patch
    unzip
    zlib1g-dev
    zip

PHP Extensions

    gd
    **bcmath**
    pcntl
    **pdo**
    pdo_pgsql
    pdo_mysql
    **zip**

I am happy to do the leg work here if some general guidance can be given. This may even open the door to a dependency checker steps in the installer which IMHO is net time saver for support.

**Comment by denisdulici** [comment]
The requirements on documentation are for a web server generally used by end-users, not docker.

**Comment by anoma** [comment]
I only mentioned docker as your issue template asked for system information and your best documentation is in your compose yml which happens to be docker as well.

I am simply requesting clarification of the dependencies akaunting needs as https://akaunting.com/docs/requirements is clearly incomplete.

I am happy to put some effort in to fill in the blanks but a `web server generally used by end-users` is far to vague a dependency to me to derive details from.

Please reopen this ticket.

**Comment by anoma** [comment]
SQL related undocumented dependency https://github.com/akaunting/akaunting/issues/1670
