### ISSUE TITLE
Password reset hangs

### ISSUE THREAD

**Issue by xenein** [akaunting/akaunting#1694]
### Steps to reproduce the issue
1. go to /auth/forgot
2. enter account email
3. submit

### Expected result
Browser either acknowledges sent email or displays an error, maybe after a timeout.
Possibly some logs of those events in the (webserver) logs.

### Actual result
The button in the web interface gets disabled and plays a nice animation seemingly forever
No entries in apache error log or php error log.

### System information (Akaunting, PHP versions)

Akaunting 2.0.26, PHP 7.4. This is a fresh installation on an otherwise empty [uberspace](https://Uberspace.de) host. Installation hints via: https://lab.uberspace.de/guide_akaunting.html
### Additional comments

This could be about mail settings, but the behavior is the same for me for PHP-mail, sendmail and smtp. (A button in the settings menu to test mail configuration and send a test mail would have been helpful here.)
If there are any other log files I could have at look at or if you have any other debugging features you need the output, just tell me, so I can attach them to the issue.

**Comment by cuneytsenturk** [comment]
I've tested clean akaunting and everything works. 

You can change mail protocol -> Log mail then test again and look log file.

You can change here;
settings > email > Protocol tab.
