### ISSUE TITLE
Feature Request: Descriptions and Item-Overwriting Option

### ISSUE THREAD

**Issue by wayneoutthere** [akaunting/akaunting#1708]
Hi team.  Great project!

I promise I tried to post this feature request in the forum, however there is no screenshot upload option in the forum it seems.  I was going to blog it on my blog but that will put too much negativity towards the project I think so better in here where it should be.

[Here](https://akaunting.com/forum/discussion/ideas/description-field-for-each-line-invoice) is where I tried to post this

## Current challenge
Right now when you enter a bill or an invoice when you choose the item it auto-fills the name rigidly.  

Here is an invoice and a bill in Quickbooks allowing you to:
* Create an item that is not even in your item list (good) and associate a chart of account (COA) account and
*  Overwrite the description of an item with the wording that you feel is best.

![QuickBooks_Description_over_write_invoice](https://user-images.githubusercontent.com/16578346/103415794-91b8ef00-4b38-11eb-9329-3aa71d0850c5.png)

![Quickbooks_Typing_notes_in_Bill](https://user-images.githubusercontent.com/16578346/103415804-98476680-4b38-11eb-807d-92a1ebeaafe7.png)

## Comments

I believe this functionality is critical / mandatory to have the smooth user experience that QB users expect.  

Thank you!

**Comment by denisdulici** [comment]
Hey Wayne,

This is already available in the code of this repository and will be available to end-users very soon.

Regards

**Comment by wayneoutthere** [comment]
amazing.  thanks for that.
