### ISSUE TITLE
After download invoice, the over line text not correct

### ISSUE THREAD

**Issue by asyrafmuda** [akaunting/akaunting#171]
I create an invoice, after that, i want to download. I see the over line text in invoice are not correct. (as attachment). 
![screen shot 2017-12-28 at 12 11 49 pm](https://user-images.githubusercontent.com/11627478/34400125-3252b0b8-ebc9-11e7-9d1c-36c0f046f6a1.png)

After reviews, when i try to print out, just nice. right now, i just need to click print, and save as pdf. it working. 

thanks. btw, your website discussion, i think they is wrong when i want to open the discussion.

**Comment by denisdulici** [comment]
It seems that DomPDF doesn't read the output correctly 😞

**Comment by angelscabrerag** [comment]
@denisdulici can you guide me which files need to edit to try to solve this? I see akaunting is using the barryvdh DomPdf libary, so i need some points to start.

**Comment by denisdulici** [comment]
The problem is with [DomPDF ](https://github.com/dompdf/dompdf) library as it seems to handle just a few CSS3 properties. There is no exact file to edit.

**Comment by angelscabrerag** [comment]
Im was playing around, made some css fixes but still overflowing the divs with class "col-xs-5" (company info, invoice info & payment info).

**Comment by lalogarcia123** [comment]
For that problem, I print as a PDF in Chrome, and unselect the header and footer
