### ISSUE TITLE
Document type is missing in the histories table

### ISSUE THREAD

**Issue by pavel-mironchik** [akaunting/akaunting#1712]
### Steps to reproduce the issue
Using the Akaunting v2.1.0 mark a bill as received and then check the "Histories" table.

### Expected result
There is a row saying "Bill marked as received!".

### Actual result
There is a row saying " marked as received!":

![2021-01-01 20-01-04 Ubuntu Mate 19 10 (Снимок 164)  Работает  - Oracle VM VirtualBox   2](https://user-images.githubusercontent.com/7408605/103440341-d646a680-4c6e-11eb-82a9-8874ab1cb3a3.png)

### System information (Akaunting, PHP versions)
Akaunting v2.1.0.
PHP v7.4.

### Additional comments
The same is for other statuses like cancelled, sent, and viewed.
I suppose that the easiest way to fix this is to provide the type as the `App\Events\Document\DocumentSent` public field and then just use it in the listener:

![2021-01-01 20-18-45 Ubuntu Mate 19 10 (Снимок 164)  Работает  - Oracle VM VirtualBox   1](https://user-images.githubusercontent.com/7408605/103440336-cdee6b80-4c6e-11eb-9cb0-256befcd2e90.png)

I'm willing to work on a PR for this issue.

**Comment by denisdulici** [comment]
For sure, PR is welcomed 😉

**Comment by denisdulici** [comment]
BTW, the type is already available as `$event->document->type` but its translation is [needed](https://github.com/akaunting/akaunting/blob/master/resources/lang/en-GB/documents.php#L10).

**Comment by pavel-mironchik** [comment]
> BTW, the type is already available as `$event->document->type` but its translation is [needed](https://github.com/akaunting/akaunting/blob/master/resources/lang/en-GB/documents.php#L10).

Yeah, but the problem is that it doesn't contain any information about the module which provides such a document type and its translations.

For example, the `$event->document->type` contains the `debit-note` value and to translate it we have to know that the translation string belongs to the Credit/Debit Notes module. Which is not the case as you see.

Either we keep a document type in the `documents` table with the module's alias like `credit-debit-notes::debit-note` and transform it to a node that contains a translation string (`credit-debit-notes::documents.types.debit_note`), or we provide the type directly when firing an event - `event(new DocumentSent($debit_note, trans_choice('credit-debit-notes::general.debit_notes', 1));`

@burakcakirel what do you think is the preferred way to solve this? We need to bring up some naming convention that will be used by all modules later. I incline to using a module's alias as a prefix. There is a heavy usage of the new "Documents" system, so I think this could help us with other tasks in the future, like it could be used in view components (where we have to explicitly provide the `$type` attribute and different routes now) and elsewhere.

**Comment by denisdulici** [comment]
We can define the `alias` by firing a `LookingForAliasOfType` event as I did for API [permissions](https://github.com/akaunting/akaunting/blob/master/app/Traits/Permissions.php#L412). However, that won't solve the problem itself as knowing the alias doesn't solve the problem in most cases because in my case, I needed the [controller](https://github.com/akaunting/akaunting/blob/master/app/Listeners/Auth/SetPermissionControllerForApi.php#L27).

So after finding the alias, there must some set of rules/constants/files where the system can find routes, controllers, language files, etc of the respective module, right? @burakcakirel @cuneytsenturk

**Comment by pavel-mironchik** [comment]
@denisdulici so we basically have to choose from two approaches.

Either we keep all sufficient data in a database and using it then come up with the appropriate route/controller/language file according to some naming convention. Like the document type translation should be placed in the `documents.types` file in all modules, so we can get a string by adding a module's alias: `credit-debit-notes::documents.types.debit_note`.

Or we fire an event everywhere where needed to get the **exact** data needed - a translated type, or a controller name, or whatever.

In the first approach we have to come up with a relatively sophisticated naming convention that will be able to handle all existing needs and future ones (unknown at the moment). In the second approach we can easily add as much events as needed, but the Sofware could be bloated by such events, though this variant is more flexible.

Another thing that we should keep in mind in case with the document type - authors of other modules know nothing about already existing types. This probably won't happen, but a module's author could add records in the `documents` table with the type `debit-note` and mess with the Credit/Debit Note module's records. Using an alias can prevent such rare issue from happening here and in other places.

**Comment by denisdulici** [comment]
There is no need to fire lots of events, firing the `LookingForAliasOfType` event in the `boot` function of `Document` model and setting the `alias` property based on that is enough. Currently, the `invoice_totals` table of our cloud has 20M+ records with 2.5GB size, and we've 100K+ companies only, so I'm concerned about the performance if we add the alias to `documents` tables.

Then based on the naming convention (set of rules/constants) the system can get determine the appropriate routes, controllers, language files.

**Comment by denisdulici** [comment]
In fact, there is already a [booted](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Model.php#L193) event which can be used by Observers.

**Comment by pavel-mironchik** [comment]
> In fact, there is already a [booted](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Model.php#L193) event which can be used by Observers.

Hmm, interesting... So it seems that in a module we can listen for the `eloquent.booted:App\Models\Document\Document` event and set the `alias` attribute on the model. That's promisingly.

**Comment by cuneytsenturk** [comment]
This issue solved #1732 and  #1742
