### ISSUE TITLE
Menu issue

### ISSUE THREAD

**Issue by Formatado** [akaunting/akaunting#1729]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Go to left menu and click Purchases > Bills, and create new or click Add Bill button. Cancel Bill. It will change to Sales > Invoices menu.
***/purchases/bills -Menu Bills
***/purchases/bills/create - New Bill
***/sales/invoices - Cancel Bill

### Expected result
Stay in Purchase > Bill menu

### Actual result
Change to Sales > Invoices

### System information (Akaunting, PHP versions)
Localhost
Akaunting 2.1.0
PHP 7.4.3

**Comment by denisdulici** [comment]
Confirmed, thanks for reporting.

**Comment by cuneytsenturk** [comment]
I've fixed this [PR](https://github.com/akaunting/akaunting/pull/1742/commits/7b001d039ce0b6f169cec27f251c0852f408d5e4) (#1742)
