### ISSUE TITLE
why bills and vendor is not normalized?

### ISSUE THREAD

**Issue by faststare** [akaunting/akaunting#173]
just asking.

**Comment by denisdulici** [comment]
What is not normalized?

**Comment by faststare** [comment]
bills table have vendor attributes. do you expect to fill up that manually by users everytime they will create a bill?

**Comment by denisdulici** [comment]
Yes, a bill requires a vendor. You can use Payments feature otherwise https://akaunting.com/docs/user-manual/expenses/payments

Feel free to use the forum for further support.
