### ISSUE TITLE
I working on a mobile app for akaunting

### ISSUE THREAD

**Issue by stojankukrika** [akaunting/akaunting#1733]
I working on a mobile app for akaunting but need some updates on akaunting app, (one composer package, one config file, middleware, and update user model) on how to submit updates? The rest I add into an additional application(module).
Maybe someone here tells me how to make it I tried [Akaunting forum](https://akaunting.com/forum/discussion/development/i-working-on-a-mobile-app-for-akaunting) but didn't get any replay :)

**Comment by denisdulici** [comment]
Feel free to send a PR so we could review the changes.

**Comment by stojankukrika** [comment]
OK. Tnx ;)
