### ISSUE TITLE
Import .xslx throws error 500 when paid_at isn't a date format

### ISSUE THREAD

**Issue by balataca** [akaunting/akaunting#1734]
### Steps to reproduce the issue
When trying to import a .xlsx sheet under "payments" and "bills" section if the "payed_at" field is not formatted as a date the server throws a 500 internal server error, without specifying an error message to the user. Also, libreoffice adds a ' character before the date if the user chooses to format a date manually and it also throws the 500 error.

### Expected result
When importing a sheet that the column "payed_at" is not formatted as a date it should automatically format the field as a date and pass a regex to remove other unwanted characters as ' that libreoffice may add. Another way would be to show an error message to the user asking him to change the format of cells and remove any special character.

### Actual result
The server throws a 500 internal server error

### System information (Akaunting, PHP versions)
Akaunting version 2.0.26
Akaunting cloud

### Additional comments
I am using the akaunting in the cloud, but I believe this error may be reproduce on other instances as well.

**Comment by denisdulici** [comment]
That was changed in this PR https://github.com/akaunting/akaunting/pull/1632

Feel free to upload a sample file here so that @burakcakirel could test it.

**Comment by cuneytsenturk** [comment]
this [#1813](https://github.com/akaunting/akaunting/pull/1813) issue solved.
