### ISSUE TITLE
problem with loading GD extension on PHP 8 server .

### ISSUE THREAD

**Issue by dzdeveloper** [akaunting/akaunting#1738]
hello guys I'm having installation issues,
it stuck at the first phase of installation (/requirements)
![Capture](https://user-images.githubusercontent.com/4678731/103923509-7a1fce80-5115-11eb-9e1e-de1df5206ec8.JPG)

### System information (Akaunting, PHP versions)
Akaunting 2.0.26
Fresh install on windows 10

/** WEB SERVER **/
Apache/2.4.46 (Win64) OpenSSL/1.1.1h PHP/8.0.0
Database client version: libmysql - mysqlnd 8.0.0
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 8.0.0

**Comment by denisdulici** [comment]
Feel free to install that extension on your server.
