### ISSUE TITLE
Indian tax system and standard features 

### ISSUE THREAD

**Issue by fuelupeducation** [akaunting/akaunting#1744]
Following features require 

1. Tax structure require 
CGST , SGST and IGST also HSN coloum need to add , challan number and date , po number and date etc.  

2. Gst filling integration 
3. Challan require with gst information and e-way bill generation on platform and auto hsn code filling with transporter information

**Comment by denisdulici** [comment]
Thanks for the feedback. Feel free to use the forum for feature suggestions https://akaunting.com/forum
