### ISSUE TITLE
Incorrect next number for a new document in the module

### ISSUE THREAD

**Issue by pavel-mironchik** [akaunting/akaunting#1753]
### Steps to reproduce the issue
Start creating a new debit note.

### Expected result
Document number should be the next after the last used.

### Actual result
It uses the next number for invoices.
![2021-01-13 19-39-54 Ubuntu Mate 19 10 (Снимок 204)  Работает  - Oracle VM VirtualBox   2](https://user-images.githubusercontent.com/7408605/104461311-65da4680-55d9-11eb-8257-c87069a9b86e.png)

### System information (Akaunting, PHP versions)
Akaunting 2.1
PHP 7.4

### Additional comments
[Documents trait](https://github.com/akaunting/akaunting/blob/master/app/Traits/Documents.php#L12-L19) doesn't expect the module's settings to be prefixed by the alias (which I suppose should), so instead of `credit-debit-notes.debit_note.number_prefix` it queries for the `debit-note.number_prefix`. Also, the unwritten naming convention here requires the setting name (and therefore document type) to be in the snake case.

Core modules use an alias, as well as other modules:

![2021-01-13 19-40-29 Ubuntu Mate 19 10 (Снимок 204)  Работает  - Oracle VM VirtualBox   2](https://user-images.githubusercontent.com/7408605/104460731-a9808080-55d8-11eb-8817-44c050056efe.png)

![2021-01-13 19-42-59 Ubuntu Mate 19 10 (Снимок 204)  Работает  - Oracle VM VirtualBox   2](https://user-images.githubusercontent.com/7408605/104460753-b1402500-55d8-11eb-961e-b0ebcc3de24b.png)

**Comment by cuneytsenturk** [comment]
Hi @pavel-mironchik, 
I've sent commit please check it.

**Comment by pavel-mironchik** [comment]
@cuneytsenturk good work, it's almost done, only you forget this little nuance:

>Also, the unwritten naming convention here requires the setting name (and therefore document type) to be in the snake case.

Maybe so:
```
        if ($alias = config('type.' . $type . '.alias')) {
            $next = $alias . '.' . str_replace('-', '_', $type);
        }
```

**Comment by pavel-mironchik** [comment]
Just have found out that the [IncreaseNextDocumentNumber](https://github.com/akaunting/akaunting/blob/master/app/Listeners/Document/IncreaseNextDocumentNumber.php) saves the next document number in settings without an alias. This will also require changes.

**Comment by pavel-mironchik** [comment]
It now reads `number_next` setting correclty, thanks! Here is an example from my database now:

![2021-01-14 03-03-47 Ubuntu Mate 19 10 (Снимок 204)  Работает  - Oracle VM VirtualBox   1](https://user-images.githubusercontent.com/7408605/104510476-73152680-5615-11eb-8c41-fa150fbb9372.png)

**Comment by cuneytsenturk** [comment]
I've change method
