### ISSUE TITLE
Logo upload, Uncaught DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL

### ISSUE THREAD

**Issue by hen3b182** [akaunting/akaunting#1758]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

1. Fresh install
2. Clone the repository: git clone https://github.com/akaunting/akaunting.git
3. Install dependencies: composer install ; npm install ; npm run dev
4. Install Akaunting: php artisan install --db-name="akaunting" --db-username="root" --db-password="pass" --admin-email="admin@company.com" --admin-password="123456"
5. Open en login: https://akaunting.test/
6. On https://akaunting.test/wizard i noticed the error as the logo upload did not work

### Expected result
1. No console.log errors.
2. Being able to upload logo

### Actual result
After i did a fresh install, console.log error on /wizard and later also on /settings/company page.
![image](https://user-images.githubusercontent.com/22586660/104610460-71cf1280-5684-11eb-8724-86d8cfe2935c.png)

### System information (Akaunting, PHP versions)
![image](https://user-images.githubusercontent.com/22586660/103459091-ea40e580-4d0c-11eb-8447-748c63fa2684.png)

### Additional comments
Fresh install

**Comment by hen3b182** [comment]
Tried using http protocol. Same results. added a line, here is the console.log:

`console.log(this.options.url,files); = http:// [File]`

And then the same issue:
```
1.js:2405 Uncaught DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at Dropzone._uploadData (http://akaunting.test/public/js/1.js:2405:11)
    at http://akaunting.test/public/js/1.js:2359:19
    at http://akaunting.test/public/js/1.js:2518:13
    at Dropzone.transformFile (http://akaunting.test/public/js/1.js:702:20)
    at _loop (http://akaunting.test/public/js/1.js:2514:39)
    at Dropzone._transformFiles (http://akaunting.test/public/js/1.js:2524:9)
    at Dropzone.uploadFiles (http://akaunting.test/public/js/1.js:2266:12)
    at Dropzone.processFiles (http://akaunting.test/public/js/1.js:2173:19)
    at Dropzone.processFile (http://akaunting.test/public/js/1.js:2146:19)
    at Dropzone.processQueue (http://akaunting.test/public/js/1.js:2137:16)
```

**Comment by cuneytsenturk** [comment]
this [PR](https://github.com/akaunting/akaunting/pull/1771) fixed it. so then Thanks @SevanNerse
