### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by williammmussa** [akaunting/akaunting#1759]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
During installation process after running the command
php artisan install --db-name="akaunting" --db-username="root" --db-password="pass" --admin-email="admin@company.com" --admin-password="123456" to setup the database trying to refresh in the browser 

### Expected result
to see the login form 

### Actual result

error screenshot attached

### System information (Akaunting, PHP versions)
PHP 7.3.26 (cli) (built: Jan  8 2021 13:03:03) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.26, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.26, Copyright (c) 1999-2018, by Zend Technologies

am using laravel valet
<img width="1071" alt="Screenshot 2021-01-15 at 10 01 10" src="https://user-images.githubusercontent.com/64524215/104692329-da67cf00-5718-11eb-8eb4-15abfb4e6596.png">
<img width="1277" alt="Screenshot 2021-01-15 at 10 07 40" src="https://user-images.githubusercontent.com/64524215/104692763-90331d80-5719-11eb-846d-494eb24a7d23.png">

**Comment by cuneytsenturk** [comment]
I've tested new release, everything works.

Please test Akaunting 2.1.0
