### ISSUE TITLE
Adjustments to more responsive view

### ISSUE THREAD

**Issue by angelscabrerag** [akaunting/akaunting#176]
Hi, i'm already made some adjustments to get more responsive view of show invoice page and login page,
i wan to make a pull request but i can't because this:

> Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.

capture fail pull request
![imagen](https://user-images.githubusercontent.com/9630621/34824084-47f201c8-f68a-11e7-9a28-d22feb9c73a8.png)

Files into pull request: `public/css/app.css` and `resourses/views/incomes/invoices/show.blade.php`

Solves:

- background image in highers screen resolutions in login page
- logo alignment in dashboard mobile view
- responsive layout view in invoice show page (logo and company info alignment, correctly responsive tables view).

Can you give me access to make the pull request?

**Comment by carvallegro** [comment]
Hi @angelscabrerag,

You don't need any special access to make a Pull Request. You do need to create your PR differently though. Here's what you need to do:

- Fork the repo
- Make the changes in your repo
- Create a PR from your repo to the akaunting's repo

A fair warning, I've had error with creating PR's through git clients. You might want to use GitHub web UI.

Further reading: [Creating a pull request from a fork](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

Hope that helps

**Comment by angelscabrerag** [comment]
Hi @carvallegro, 

Thanks for the advice!. I will follow your instructions.

**Comment by angelscabrerag** [comment]
Yesterday i made a pull request: https://github.com/akaunting/akaunting/pull/178
