### ISSUE TITLE
Invoice View: Sorting invoices by status leads to tripple entries

### ISSUE THREAD

**Issue by sweisgerber-dev** [akaunting/akaunting#177]
Ordering by status leads to tripple entries in the invoice view::
- https://akaunting/incomes/invoices?sort=status.name&order=asc

Ordering by everything else leads to normal invoice count again:
- e.g.: https://akaunting/incomes/invoices?sort=invoice_number&order=asc

**Comment by cchoe1** [comment]
Assuming, you are using v1.1.7, does it only happen when ordered by ascending?  Have you tried setting it to descending and seeing if the same thing happens?

**Comment by sweisgerber-dev** [comment]
Akaunting version of the report: Version 1.1.6

**Comment by sweisgerber-dev** [comment]
It happens when ordering by status ascending & descending

**Comment by denisdulici** [comment]
Thanks Sebastian for reporting this bug.
