### ISSUE TITLE
Customer information get mixed when duplicating invoice from another customer

### ISSUE THREAD

**Issue by arbh89** [akaunting/akaunting#1774]
### Steps to reproduce the issue
Duplicate an invoice from customer that has email and telephone number to another customer that do not have this information, duplicated invoice preserves initial email and telephone and wrong customer get notified.

### Expected result
When duplicating an invoice and changing customer all new customer information should be cleared in the new invoice.

### Actual result
Email and telephone number is preserved from old invoice.

### System information (Akaunting, PHP versions)
Akaunting 2.0.26
PHP 7.3

**Comment by cuneytsenturk** [comment]
Please use master and test again. I installed clean version and test it. Everyting okey.

**Comment by cuneytsenturk** [comment]
@SkullMasher any update?
