### ISSUE TITLE
Overdue invoice notification wrong amount

### ISSUE THREAD

**Issue by arbh89** [akaunting/akaunting#1776]
### Steps to reproduce the issue
Create an invoice, make a partial payment, let it expire and wait for overdue notification.

### Expected result
There should be a subtotal variable in email templates to notify customer about pending amount when there is a partial payment.

### Actual result
There is only a total variable and is not posible to notify customer about pending amount when there is a partial payment.

### System information (Akaunting, PHP versions)
Akaunting 2.026
PHP 7.3

**Comment by denisdulici** [comment]
You can use the `{invoice_amount_due}` tag for such a purpose.
