### ISSUE TITLE
Invoice page : "undefined" word written in between client info

### ISSUE THREAD

**Issue by SkullMasher** [akaunting/akaunting#1779]
### Steps to reproduce the issue

1. Login on app.akaunting.com (or a self-hosted instance)
2. Create a new invoice
3. Add client info
4. back on the preview page (akaunting.com/sales/invoices) the preview contains the word "undefined" on the client info.

### Expected result

Not having the word "undefined" on the client information.

### Actual result

We have the word "undefined" see attached screenshot.
![akaunting-undefined](https://user-images.githubusercontent.com/4488386/104958877-2b095180-59d1-11eb-945b-f5fc22479887.jpg)

### System information (Akaunting, PHP versions)

Whatever version app.akaunting.com is using and on my serveur PHP 7.3 (debian) with the commit 1a562e4707fa05f421f42b1602b97f908cdf42ee (Jan 18 15:00:11)

### Additional comments

Tested on Firefox  with Linux, Windows 10 and android.

Hello there, love the project so far ! My experience as been great. Cheers.

**Comment by cuneytsenturk** [comment]
Please check customer phone and test again.

**Comment by cuneytsenturk** [comment]
@SkullMasher any update?
