### ISSUE TITLE
Corrupted template Invoice PDF

### ISSUE THREAD

**Issue by hen3b182** [akaunting/akaunting#1782]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. fresh install without sample data
2. make sample invoice

### Expected result
invoice like template example
![image](https://user-images.githubusercontent.com/22586660/105105499-77798d80-5ab4-11eb-9412-41cb4ab8f0a7.png)

### Actual result
![image](https://user-images.githubusercontent.com/22586660/105105372-4731ef00-5ab4-11eb-88b3-b70b7216405d.png)

**Comment by ckotso** [comment]
Just a note that this also happens in the DigitalOcean marketplace image. I thought it was my local installation but looks like it's a more general thing. The issue doesn't occur in Akaunting Cloud.

**Comment by ckotso** [comment]
The problem was that dompdf could not find the css files, in my case it was because I was tunneling the connection so instead of dompdf reaching out to localhost:80 it was trying localhost:8080. For me it was enough to bind apache to port 8080 in the VM that is hosting akaunting.

**Comment by denisdulici** [comment]
As @ckotso said, it's related to your installation/connection, not able to reproduce it.
