### ISSUE TITLE
Console::run always fails and returns empty outputs on IIS

### ISSUE THREAD

**Issue by Filiecs** [akaunting/akaunting#1784]
This is what is causing the php version errors for some users even though they have PHP installed.
It also causes addon installation to fail. This is likely to do Akaunting using an older version of Symfony, which [had this issue](https://github.com/symfony/symfony/issues/24924).

### Steps to reproduce the issue
Try to run _any_ command using Symfony's Process.php class on Windows.
An example would be: `Process::fromShellCommandline("ls");`

### Expected result
The process should be executed as expected and not return an error.

### Actual result
The process always returns an error code and no output.

### System information (Akaunting, PHP versions)
Akaunting version 2.0.26 and 2.1.0 rc.
Windows Server 2019
IIS 10

### Additional comments
This is able to be worked around by using php's standard 'exec' instead.

**Comment by denisdulici** [comment]
Unfortunately, I don't have experience with IIS so can't say anything but feel free to submit a PR if there is any solution.
