### ISSUE TITLE
error uploading import in your live site: https://app.akaunting.com/

### ISSUE THREAD

**Issue by engyaserothman** [akaunting/akaunting#1786]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
open sales list,
click on import.
select file: (bug 1: it doesn't show that file is selected)
click on upload (bug 2: it doesn't show that file is uploading, but I can see through network monitoring that there is a data being uploaded)

### Expected result
data to be imported 

### Actual result
Error 524 , Time out exception

### System information (Akaunting, PHP versions)
Version 2.1.0
on your live site: app.akaunting.com
(cache erased)

### Additional comments
we have tried several times with the same error

**Comment by denisdulici** [comment]
Not related to this repository. Feel free to use the forum.
