### ISSUE TITLE
Link to payment/revenue edit not working from the transactions page 

### ISSUE THREAD

**Issue by abooysen** [akaunting/akaunting#1790]
Not passing the transaction id in the URL , passing 0 instead

Example:
https://app.akaunting.com/purchases/payments/0/edit
https://app.akaunting.com/sales/revenues/0/edit  

If I compare it to the Revenues and Payments it seems line 52 in file
https://github.com/akaunting/akaunting/blob/master/resources/views/banking/transactions/index.blade.php
should be
`<a href="{{ route($item->route_name, $item->id) }}">`
and not
`<a href="{{ route($item->route_name, $item->route_id) }}">`

**Comment by cuneytsenturk** [comment]
I've test clean installation and akauntig cloud. Everything works.
I'm closing this issue.

**Comment by abooysen** [comment]
Did you test Imported transactions

**Comment by abooysen** [comment]
And on the "Transactions" page, not on he Revenue and Payments screens (those two work)
