### ISSUE TITLE
php fatal error at php artisan install

### ISSUE THREAD

**Issue by togir2** [akaunting/akaunting#1794]
### Steps to reproduce the issue

- Installed a clean Debian 10, php8.0.1 with all requered extensions, apache2
- Dowloaded zip version 2.0.26.
- Extract it into the webroot.
- changed permissions to www-data:www-data.
- run the command:
`php artisan install --db-host="database.domain" --db-name="akaunting" --db-username="akaunting" --db-password="password" --admin-email="admin@domain" --admin-password="123456" `

### Actual result

Error:

```
Setting locale en-GB
Creating database tables
Connecting to database akaunting@database.domain:3306
PHP Fatal error:  Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in /var/www/akaunting/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 91

In PDOConnection.php line 91:
                                                                                                                                                                 
  Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) 
 
```

### System information (Akaunting, PHP versions)

Akaunting 2.0.26 and 2.1.0RC (tried both versions)
Debian 10
php8.0.1 as apache-mod
apache2.2

**Comment by denisdulici** [comment]
Not related to Akaunting, some packages such as Doctrine are not compatible with PHP 8, yet.

**Comment by josenobile** [comment]
doctrine/dbal is fully compatible with PHP 8 since 2020-11-15 https://github.com/doctrine/dbal/releases
The issue is:
`"doctrine/dbal": "2.11.*",`

Can you please make sure all dependencies are updated and it is compatible with PHP 8 ?

**Comment by mrkalmdn** [comment]
> Can you please make sure all dependencies are updated and it is compatible with PHP 8 ?

+1 on this.
