### ISSUE TITLE
Invalid URL displayed

### ISSUE THREAD

**Issue by mdf092** [akaunting/akaunting#1802]
Hi. 
While displaying the url for share, there are some additional characters **_"amp;"_** 
The URI is:
`/signed/invoices/102?company_id=1&amp;signature=90c6a53485992fe01b1f2f750c0a5bac427c317ecfbd19da08c943dfb2382c00
`
But it is:
`/signed/invoices/102?company_id=1&signature=90c6a53485992fe01b1f2f750c0a5bac427c317ecfbd19da08c943dfb2382c00
`
As I'm new to Laravel, I'm trying to fix it but it may take a while. So any help is appreciated. 

https://github.com/akaunting/akaunting/blob/8ecf4289e860cf607df5f4aab7a61d39c3bfd3d4/resources/views/components/documents/show/timeline.blade.php#L133

**Comment by cuneytsenturk** [comment]
this issue solved new release please check it.
