### ISSUE TITLE
Call to a member function isValid() on array | Accounting 2.1.0

### ISSUE THREAD

**Issue by GaneshKandu** [akaunting/akaunting#1807]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Add New Item with Picture.

### Actual result

![image](https://user-images.githubusercontent.com/12833130/105980595-10169b80-60bb-11eb-82dd-70d5649dd51b.png)

### System information (Akaunting, PHP versions)

Accounting 2.1.0
PHP Version 7.3.11

### Additional comments

No log file created for this error.

Browser console error.

Cookie “sidenav-state” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: vendor/bootstrap/dist/js/bootstrap.bundle.min.js
Source Map URL: bootstrap.bundle.min.js.map

**Comment by cuneytsenturk** [comment]
Akaunting latest package fixed this issue you can check app.akaunting.com

**Comment by GaneshKandu** [comment]
I am downloading from [https://akaunting.com/thank-you](https://akaunting.com/thank-you) i am getting similar package not fixed one

**Comment by GaneshKandu** [comment]
I have downloaded the source package from https://akaunting.com/thank-you and it seems that the new package is not uploaded here as there is no difference between the old and new package.

app.akaunting.com asks for login and password which I don't have.

Please let me know from where I can download the updated package ?

**Comment by cuneytsenturk** [comment]
@SevanNerse and me are working on. please wait us.
