### ISSUE TITLE
Item can't be saved with zero or empty sale or purchase prices

### ISSUE THREAD

**Issue by pavel-mironchik** [akaunting/akaunting#1820]
### Steps to reproduce the issue
Start creating a new item. Don't change sale and purchase prices, leaving them empty, or set them to 0. Click Save button.

### Expected result
An item being saved.

### Actual result
Validation errors appeared:
![2021-02-01 16-35-02 New Item - Pavel Mironchik - Google Chrome](https://user-images.githubusercontent.com/7408605/106447908-3c139180-64ac-11eb-8755-7fe853a61091.png)

![2021-02-01 16-42-08 New Item - Pavel Mironchik - Google Chrome](https://user-images.githubusercontent.com/7408605/106448118-8432b400-64ac-11eb-94c2-a9254b4c3120.png)

### System information (Akaunting, PHP versions)
Akaunting Cloud

### Additional comments
There wasn't such an issue a month ago.
The same for editing an item.

**Comment by cuneytsenturk** [comment]
I've added [`amount`](https://github.com/akaunting/akaunting/issues/1618) validation. But I will remove this `rule`
