### ISSUE TITLE
After upgrade impossible to add payment

### ISSUE THREAD

**Issue by Zagur** [akaunting/akaunting#1824]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

When you add a new payment and configure all the necessary parameters it does not let you send the payment.

![imatge](https://user-images.githubusercontent.com/7691406/106474415-31093300-64a5-11eb-93b7-e5100cfcd458.png)
Note: I have the interface in English but the error seems to appear in Spanish. It says "Invalid amount".

### Expected result

You should get a notification that the payment has been successfully added.

### Actual result

"Invalid amount".

### System information (Akaunting, PHP versions)

Akaunting 2.1.1
PHP 7.4
Debian 10

**Comment by cuneytsenturk** [comment]
I've test clean Akaunting and everything works so then ı am colisng this issue.

**Comment by Zagur** [comment]
The truth is that I am still unable to import payments. And I just saw that I can't make transfers either. I have tried to do a clean install of version 2.1.0 and here I can import without problems. But I upgrade to the latest version 2.1.1 and this is when the import fails. So I suggest not to close the issue and check it a bit more thoroughly.

Regards.
