### ISSUE TITLE
Unable to edit email templates

### ISSUE THREAD

**Issue by arbh89** [akaunting/akaunting#1825]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Go to setings page, email, try to edit a template.

### Expected result
Template field and subject field should be editable.

### Actual result
I am unable to write on it, any key is recognized.

### System information (Akaunting, PHP versions)
Akaunting 2.1.1
PHP 7.3

### Additional comments
I have updated from 2.0.26 to 2.1.0 and now to 2.1.1 and too many things are not working as they did in previous version.

**Comment by cuneytsenturk** [comment]
Thank you your feed back
