### ISSUE TITLE
"Drop files here to uphold" Silently Fails on Multiple Files

### ISSUE THREAD

**Issue by SethFalco** [akaunting/akaunting#1828]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. Attempt to create a payment
2. Drag 2 files to "Drop file**s** here to upload"
3. Save the payment
4. Click the newly created payment observe the attachments

### Expected result
It should attach both files if it's intended for allow for multiple files.

### Actual result
It will fail to attach one of the files silently.

### System information (Akaunting, PHP versions)
Akaunting Version: Version 2.1.1
Running at: https://app.akaunting.com/

**Comment by cuneytsenturk** [comment]
I've send PR and fixed this request, Thank you your feedback.
