### ISSUE TITLE
Fails to import transfer.xlsx files, no errors

### ISSUE THREAD

**Issue by joveice** [akaunting/akaunting#1829]
### Steps to reproduce the issue
Try to import a transfer.xlsx
Try to import the example transfer.xlsx

### Expected result
Upload or error message

### Actual result
Redirect back with no errors.
Debug true (and cache updated)
No nginx error logs
No php error logs
No Laravel error logs

### System information (Akaunting, PHP versions)
PHP 7.4.12
Akaunting 2.1.1

### Additional comments
If the upload fails on Revenue and Payments it also does redirect back with no message. But a correct file works here.

**Comment by joveice** [comment]
Updated from 2.0.26

**Comment by cuneytsenturk** [comment]
Thank you feedback. I am closing this issue :)
We've solved it.
