### ISSUE TITLE
Database connection error During installation

### ISSUE THREAD

**Issue by ruban-s** [akaunting/akaunting#1832]
After Downloading files from Akuanting.com and put server and tried to install the application but it seems db credentials not  are accepting and showing error like below

`
Error: Could not connect to the database! Please, make sure the details are correct.
`
I cross checked my credentials and credentials working fine  but no luck and i tried other credentials as well 

but Akaunting not connecting to database .

is this js error or Composer package related issue?

 

### System information (Akaunting, PHP versions)
Akaunting V2.1.1 
PHP v7.3.24

**Comment by cuneytsenturk** [comment]
Please check your db details. I've tested and everyting works.

**Comment by diogo10** [comment]
I am having the same issue with Xamp on my local machine. Should I change .env or the database.php? I have tried to change both still with same error.

**Comment by ulisses-cruz** [comment]
I'm having the same problem.
```bash
php artisan install --db-name='mydb' --db-username='myuser' --db-password='mypass' --db-host='127.0.0.1' --db-port='3306' --admin-email='my@email.com' --admin-password='otherpass'
```
![image](https://user-images.githubusercontent.com/11726278/164893429-54c3f9a9-29e8-468e-a0ec-91ac5b6fb917.png)

```bash
mysql -D mydb -u myuser --password='mypass' -h 127.0.0.1 -P 3306
```
![image](https://user-images.githubusercontent.com/11726278/164893573-e04efd51-d240-4634-8fce-93fbe292e6df.png)
