### ISSUE TITLE
Error styling

### ISSUE THREAD

**Issue by dev-zm-sl** [akaunting/akaunting#1839]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Sales->Customers->Add New
Leave the email blank and click on **Can Login?** checkbox.

### Expected result
The email field is **required**.

### Actual result
The email field is \<strong>required\</strong>.

**Comment by cuneytsenturk** [comment]
I2ve merge your pull request thank you.
