### ISSUE TITLE
Can´t create new customer

### ISSUE THREAD

**Issue by DavidLiedke** [akaunting/akaunting#184]
Menu:
Incomes --> Customers --> Add new

I entered all data for the customer. After that i click save. The websites with all entered data reloads. But no customer were created.
 
Over the invoice page i can create a new customer. 
Incomes --> Invoices --> Add new --> Select customer (Add new)

**Comment by denisdulici** [comment]
Just tried and it worked fine for me.

**Comment by sebadamus** [comment]
I could also create a customer with no problem...
