### ISSUE TITLE
TypeError: Cannot read property 'company_name' of undefined

### ISSUE THREAD

**Issue by dev-zm-sl** [akaunting/akaunting#1843]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Start visual installation until Settings screen while adding Company name and User account

### Expected result
It must go to Login page

### Actual result
It stucks there and shows 500 error

### System information (Akaunting, PHP versions)
NginX on Ubuntu

### Additional comments
I also have tried installing via artisan install but the visual installation still starts from the initial page.

![image](https://user-images.githubusercontent.com/78361157/107498412-90f28e80-6bb5-11eb-836c-a9a0c11eca6a.png)
![image](https://user-images.githubusercontent.com/78361157/107498494-af588a00-6bb5-11eb-9453-d045a4503f45.png)

**Comment by dev-zm-sl** [comment]
The installation has some issue with Nginx configurations

**Comment by cuneytsenturk** [comment]
please test clean with [download](https://akaunting.com/download) file.

**Comment by dev-zm-sl** [comment]
The whole directory have issues with NginX 

I don't know whether it was tested or not with the NginX
