### ISSUE TITLE
akaunting/akaunting container loops after asking credentials

### ISSUE THREAD

**Issue by NikkyLux** [akaunting/akaunting#1854]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
In the Synology Docker app, look for Akaunting, select the image, download it. Then click on start, the container start. Set the ports 8080:80 and in my case a volume. 
Go to your browser and type the URL.

### Expected result
You should be directed to the install requirement page then the database, first user and first company.

### Actual result

The site is asking for credentials (/auth/login). When you enter a user, the login enter a loop. I have tried to wait some hours...

### System information (Akaunting, PHP versions)
The provided container

### Additional comments
I am trying to install the docker image akaunting/akaunting image on the Docker app of Synology.

With the Docker application of Synology, we do not have access to the command line Docker -Composer.

We have a bash while the container is running. Where can I place the db.env and the run.env in the folder hierarchy of the container to make it run?

Actually, when I run the container, The site ask for credentials then is indefinitely "processing". Anyway, I am not able to access to the installation process asking for the DB and the first user.

**Comment by denisdulici** [comment]
Feel free to use `akaunting/docker` repository for such issues.
