### ISSUE TITLE
How does the deployment process work?

### ISSUE THREAD

**Issue by srini85** [akaunting/akaunting#1862]
Hi Guys,

How does the deployment process work? I have been going through the codebase to see if there are any leads on how the final Akaunting ZIP file is created? I have not been able to track it. I guess its done either locally or on some CI server?

Any leads on this would be really appreciated.

I am trying to see if I can create the final Akaunting Package from my forked repo so that I can get certain changes into my instance without having to wait for the mainline package

**Comment by denisdulici** [comment]
That is done locally but basically, you should run `composer install ; npm install ; npm run prod` commands.
