### ISSUE TITLE
Income & Expense miscalculation on dashboard

### ISSUE THREAD

**Issue by ruban-s** [akaunting/akaunting#1866]
### Steps to reproduce the issue

Dashboard Total Income & expense calculation is Miscalculated 

In income , Total less then 9k but dashboard report showing more 22k.

In expense , Total less then 1k but dashboard report showing more 15k

### For refrence

#Dashboard 
<img src="https://res.cloudinary.com/acceedo/image/upload/v1613469399/freshicons/Dashboard-W3CERT-Technologies_ovqqvs.png"  />

#sales.
<img src="https://res.cloudinary.com/acceedo/image/upload/v1613470475/freshicons/Invoices-W3CERT-Technologies_zpkkzm.png" />

#expense.

<img src="https://res.cloudinary.com/acceedo/image/upload/v1613470528/freshicons/Payments-W3CERT-Technologies_mzcah6.png"/>

### System information (Akaunting, PHP versions)
V2.1.3

**Comment by denisdulici** [comment]
It seems you have a problem with currency rates https://akaunting.com/docs/user-manual/settings/currencies

Feel free to use the forum for further help.
