### ISSUE TITLE
Document Eloquent Model returns NULL 

### ISSUE THREAD

**Issue by stanwarri** [akaunting/akaunting#1871]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

When you try to query the document model  - `App\Models\Document\Document` it returns a NULL.  
`$invoice = App\Models\Document\Document::where('id', 1)->first();` Even when the data exist in the database and `deleted_at` is NULL.

You can try this using Laravel Tinker from the root of the installation.

However there is actual result is returned in some part of the application. So this behaviour is inconsistent. 

### Expected result

<img width="855" alt="Screenshot 2021-02-17 at 05 37 21" src="https://user-images.githubusercontent.com/1219663/108157124-4d7eaf80-70e2-11eb-9880-d7720e8941e7.png">

### Actual result

<img width="733" alt="Screenshot 2021-02-16 at 18 18 44" src="https://user-images.githubusercontent.com/1219663/108157415-ef060100-70e2-11eb-9d18-13cee925534f.png">

### System information (Akaunting, PHP versions)

Akaunting Version 2.1.1
PHP Version 7.4.12

### Additional comments

So I found that eloquent query for document model is returning Plank\Mediable\MediableCollection instead of Illuminate\Database\Eloquent\Collection

Here is a related issue - https://github.com/plank/laravel-mediable/issues/158

**Comment by pavel-mironchik** [comment]
Tinker returns null because of the `company_id` constraint. There is a global `Company` scope for the Document model, which uses the `company_id` from the session. In Tinker, you don't have an active session, so you need to add a constraint yourself: `App\Models\Document\Document::where('company_id', 1)->where('id', 1)->first()`.
