### ISSUE TITLE
Reports / Expense Summary --> Not all categories are displayed

### ISSUE THREAD

**Issue by o---** [akaunting/akaunting#1880]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create and have data for more than 8 Expense categories. (I have > 20 Expense categories). 

### Expected result
All categories are listed

### Actual result
Only top 8 categories are listed

### System information (Akaunting, PHP versions)
2.1.3

### Additional comments
Same issue for Income VS Expense, however working on Profit & Loss

**Comment by cuneytsenturk** [comment]
I've test clean install and test it. Everything works.
![image](https://user-images.githubusercontent.com/10936547/108871931-b72f1a00-760a-11eb-934f-6a7d8dddb6eb.png)
![image](https://user-images.githubusercontent.com/10936547/108872004-ca41ea00-760a-11eb-9de1-34468cdb4871.png)
![image](https://user-images.githubusercontent.com/10936547/108872129-e8a7e580-760a-11eb-8a85-7d795c988fdd.png)

**Comment by o---** [comment]
Yes, @cuneytsenturk  that is working correctly. Perhaps I was not clear enough. 

So when you open the expenses summary report, all categories **having some data** are listed in the table **below** the graph. 
And that is where I am only getting 8 (eight).

**Comment by o---** [comment]
@cuneytsenturk, @denisdulici did you see my comments?

**Comment by cuneytsenturk** [comment]
Yes i saw. I will check again  your answerd
