### ISSUE TITLE
Database migration.

### ISSUE THREAD

**Issue by midsoft2010** [akaunting/akaunting#1885]
![Screenshot (28)](https://user-images.githubusercontent.com/29373167/108817381-e0c75180-75c8-11eb-8fb4-46aa590ea92a.png)
 i cant get past step 2 in local  installation. it keeps loading until forever. what should i do?

**Comment by cuneytsenturk** [comment]
I've tested clean installation and everything okey.
so then;
Not related to this repository. Feel free to use the forum.
