### ISSUE TITLE
API failing

### ISSUE THREAD

**Issue by Malouda** [akaunting/akaunting#1890]
Trying akaunting but failed when calling api end points,the issue is when we are trying to get search string but if we call /api/documents we dont have a search string so it fails,traced to the following line
https://github.com/akaunting/akaunting/blob/eb093c4ef89d1291c5fb8fa4a711cdf88b728fd4/app/Traits/Permissions.php#L414

**Comment by denisdulici** [comment]
You should put `search=type:invoice` variable to URL.
