### ISSUE TITLE
"Add Client" DropZone Loading Wrong client

### ISSUE THREAD

**Issue by tratotech** [akaunting/akaunting#1897]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Register Around 20-30 Contacts. They were generated from CRM Contacts page.
Go To Sales > invoices > Add Client
Choose One one the last Clients from the list

### Expected result
After Choosing Last client for example, It should show his details on page.

### Actual result
Seems to show Client-1 ID. 

### System information (Akaunting, PHP versions)
Akaunting 2.1.5
Php 7.4.15

### Additional comments
GIF IMAGE OF error: https://im6.ezgif.com/tmp/ezgif-6-30b394b33ee1.gif

**Comment by denisdulici** [comment]
Not able to reproduce the error, feel free to use the forum for further help.
