### ISSUE TITLE
Portal Profile Email Edit

### ISSUE THREAD

**Issue by dev-zm-sl** [akaunting/akaunting#1898]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Login as Customer
Edit Profile
Edit Email

### Expected result
User should not be able to change their email

### Actual result
The user is able to edit the email

**Comment by denisdulici** [comment]
Users should be able to edit their email.
