### ISSUE TITLE
adding fideloper/proxy as requirement

### ISSUE THREAD

**Issue by dbrw** [akaunting/akaunting#190]
Hi, I am trying to install your wonderfull app on my server.

My web apps are behind nginx reverse proxy, so I am unable to load all resources though https (which handled by nginx) because `asset()` helper function generate http url.

Maybe you want to add [fideloper/proxy](https://github.com/fideloper/TrustedProxy) package as requirement so the `asset()` helper will works on others setup like mine.

**Comment by denisdulici** [comment]
Added this to the core. Now what you have to do is to publish the config and edit it as per your settings.
