### ISSUE TITLE
500 - Internel Server Error, Dashboard, Banking Accounts

### ISSUE THREAD

**Issue by hanny00** [akaunting/akaunting#1903]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Open https://app.akaunting.com - Login- try to open the dashboard
Open https://app.akaunting.com/banking/accounts

### Expected result
it opens the dashboard
i opens banking accounts 

### Actual result
Oops! Something went wrong 
500- internel server error

### System information (Akaunting, PHP versions)
Cloud Version 2.1.5

### Additional comments

tested with, Microsoft Edge Version 90.0.803.0, Google Chrome Version 88.0.4324.182, Firefox 86.0

![Screenshot_20210303_162756](https://user-images.githubusercontent.com/50232823/109829781-25dd2a80-7c3e-11eb-96b8-4ff0a7d826b9.png)

**Comment by cuneytsenturk** [comment]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum
