### ISSUE TITLE
SMTP Password Creates Blank Page If Using Special Characters

### ISSUE THREAD

**Issue by bitsvital** [akaunting/akaunting#1909]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Main Page of Akaunting --> Settings --> Email --> Protocol Choose SMPT
Enter a SMTP password that has a certain special character, the backslash "\"
If the password contains the backslash --> \ <-- you receive a white page on your web browser when trying to access Akaunting

### Expected result
Normal results when accessing Akaunting from your web browswer

### Actual result
White page on your web browser. You can't access the Akaunting app from any page.

### System information (Akaunting, PHP versions)
PHP7.4

### Additional comments
When I edit the .env in the main directory of Akauinting and remove the backslash from the password and re-save the .env file I can access the Akaunting website.

**Comment by denisdulici** [comment]
You should not use a backslash in password, it breaks in most of the parts.

**Comment by bitsvital** [comment]
Most people use (and if they don't, they should) password managers like SafeInCloud etc. The software auto-generates a password. Just like WordPress and many sites except that. It might be worth noting in the area of the password field when creating a password what special characters are (only) accepted. Like what many banks do. The way you don't get the white screen and have to edit a hidden file. Many users that do not have tech skills will be put off by this annoyance.
