### ISSUE TITLE
TopLeft Company logo wont show from outside LAN addresses

### ISSUE THREAD

**Issue by sebadamus** [akaunting/akaunting#192]
i.e I upload a logo for my test company and it resulted this path:
http://20.0.0.100/akaunting/uploads/1
So outside my LAN logo wont show.

I looked for other images like the default akaunting logo up left and the path shows ok with the url where the site is hosted:
http://mypublicurl/akaunting/public/img/akaunting-logo-white.png

**Comment by denisdulici** [comment]
That is used to protect access to images. The default one is not private.

**Comment by sebadamus** [comment]
Going to test some more! thanks.

**Comment by sebadamus** [comment]
Here, testing some more can explain better.  If you install the project from a LAN IP, ie. 10.0.0.10.  Then it keeps this info in the .env file (APP_URL=http://10.0.0.10/akaunting)

So, the default company logo or the logo I uploaded, works fine while I am inside LAN.   Points to http://10.0.0.10/akaunting//uploads/1

But when I am outside my LAN, I access by NAT tunel to the port 80, but no more with http://10.0.0.10/akaunting... instead with ie http://externalipaddress/akaunting...

I can access the site, but the company logo still points to http://10.0.0.10/akaunting//uploads/1, so, no image is shown on the up-left part of the screen where the logo should be.
![imagen](https://user-images.githubusercontent.com/1787753/36320855-7632aa5c-1326-11e8-8481-733af1a58cb2.png)

It happens **only** with the logo here, it **does not** happen if you try to view the logo from within company edit or with bill attachments.

Hope it helps.

**Comment by sebadamus** [comment]
Testing a little more... using akaunting.com site as test with my account, https://app.akaunting.com/incomes/invoices/709 if you go to this invoice you will see the Company Logo not found and if you click edit on the invoice, and then try to delete an attachment, it wont be deleted.
