### ISSUE TITLE
Currency rates seem to be used in inverse when calculating dashboard values

### ISSUE THREAD

**Issue by gyohng** [akaunting/akaunting#1921]
### Steps to reproduce the issue

Created an additional currency in the same way as the default currencies were created upon installing Akaunting.

I.e., 

- USD 1.0
- EUR 1.25
- JPY 0.0091906519657656

### Expected result

The default rate for EUR is 1.25, hence the assumption is that 1 EUR is more valuable than 1 USD. 1 JPY is less valuable.

If any balance is present in JPY, in dashboard the values should be calculated accordingly.

### Actual result

If the working currency is USD, the values on the dashboard for JPY revenue are shown as if the coefficient is 1/0.0091906519657656 (~108.8), i.e. they are multiplied by 108.8

The default coefficients during installation suggest that the currency rates are supposed to work in reverse.

### System information (Akaunting, PHP versions)

Akaunting 2.1.6
PHP 7.4

**Comment by cuneytsenturk** [comment]
Please check which set default currency

- if you set default USD, it must currency rate 1 and convert other currencies see attached:

![currency_conver-usd-to-yen](https://user-images.githubusercontent.com/10936547/114139535-d7dfd480-9917-11eb-8d2b-7f8eb25ce8af.PNG)

- if you set default JPY, it must currency rate 1 and convert other currencies see attached:

![currency_conver-yen-to-usd](https://user-images.githubusercontent.com/10936547/114139791-25f4d800-9918-11eb-8474-226cd43671ed.PNG)


How to use currency, You can look [docs](https://akaunting.com/docs/user-manual/settings/currencies)
Also if you want to auto update currency rate you can look this app [Live Currency](https://akaunting.com/apps/live-currency)

**Comment by gyohng** [comment]
The defaults provided by akaunting seem to be confusing. USD is set to 1, EUR is set to 1.25 (above one); however, the above calculation suggests that the default rate for EUR should be 0.84 (below 1)
