### ISSUE TITLE
Company limit and invoice creation problems

### ISSUE THREAD

**Issue by jacksonadh** [akaunting/akaunting#1922]
Please send only real questions. Use the forum for support, feature requests, proposals, new versions, help, etc. https://akaunting.com/forum

### Steps to reproduce the problem
#First problem: Switch companies through the side menu and create a new user for a new company.

#Second problem: Create a new invoice.

### Expected outcome
#First problem: it is expected that I can create the company and it will appear normally in the side menu and that I can assign it to new or old users through the user creation / editing screen.

#Second problem: That the invoice is created.

### Current results
#First problem: The system is limited to 10 companies, only 10 appear in the side menu, being necessary to exclude an old company in order for the new company to appear. When the company does not appear in the side menu, it cannot be assigned to any user other than the administrator, it is as if it did not exist.

#Second problem: After clicking the save button, it is verified that the system shows that it has saved, but the invoice is not listed.
### System information (Akaunting, PHP versions)
Akaunting: 2.1.6
PHP: 7.4

### Additional comments
Own hosting

**Comment by denisdulici** [comment]
You can see other companies from the `Manage Companies` page.

I'm not able to replicate the invoice issue. Feel free to use the forum for further help.
