### ISSUE TITLE
Changes to email templates are not being saved

### ISSUE THREAD

**Issue by wslybkkr** [akaunting/akaunting#1928]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. Settings > Emails, change text and or links in template.
2. Click save
3. Button keeps looping as it is transmitting the save

### Expected result
Saving settings and show new changed templates

### Actual result
Old template is being loaded, even after waiting for 15 minutes.

### System information (Akaunting, PHP versions)
Akauting: 2.1.7
PHP: 7.4 (current)

**Comment by denisdulici** [comment]
Not able to reproduce the issue. Feel free to use the forum for further help.
