### ISSUE TITLE
Cronjob not working

### ISSUE THREAD

**Issue by wslybkkr** [akaunting/akaunting#1929]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. setup cronjob as stated under Settings > Recurring

### Expected result
1. Running schedules and doing needed for recurring invoices, reminders, etc.

### Actual result
No schedule is being run. When using the manual commands;

artisan recurring:check
artisan reminder:invoice
artisan reminder:bill

All is working fine.

### System information (Akaunting, PHP versions)
Akaunting: 2.1.7
Php: 7.4 (current)

### Additional comments
See forums for multiple topics;
https://akaunting.com/forum?search=cronjob&sc=forum
https://akaunting.com/forum?search=cron%20job&sc=forum

**Comment by cuneytsenturk** [comment]
Please read [scheduling](https://akaunting.com/docs/user-manual/settings/scheduling) documentation page.

**Comment by wslybkkr** [comment]
Cron job runs, but says there is nothing to do, when doing the manual command it works, so it is an issue in the schedule command. 

the steps in the documentation have been followed, as you can read in my comment.
