### ISSUE TITLE
Page keep loading

### ISSUE THREAD

**Issue by KhairulAzmi21** [akaunting/akaunting#1934]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Invoice > Add new

### Expected result
Display form invoice

### Actual result
Keeps Loading

### System information (Akaunting, PHP versions)
PHP 7.3 , Laravel 8.32.1

### Additional comments
so many page keep loading and I got js error 
![Screenshot 2021-03-15 at 02 32 56](https://user-images.githubusercontent.com/12378983/111079900-0a73f880-8537-11eb-8b6d-43387d73aff6.png)

**Comment by cuneytsenturk** [comment]
Please test clean Akaunting installation. I've test and everything works.
