### ISSUE TITLE
API's returning blank result OR 403 not sufficient rights

### ISSUE THREAD

**Issue by baaks** [akaunting/akaunting#1935]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Open Postman > Enters endpoint of Items(for example) -> link.com/api/items/1 > Execute

### Expected result
Expect Item response from API

### Actual result
HTTP 200 OK, however blank result. 
If i dd the $item variable inside the show method of Api\Common\Items, returns null. 

### System information (Akaunting, PHP versions)
Akaunting 2.1.7
php 7.4.15 

### Additional comments
For other endpoints, such as contacts 
an 403 error returns, while all permissions are rightly granted.

**Comment by denisdulici** [comment]
You should send the `company_id`. Feel free to use the forum for further help.
