### ISSUE TITLE
Multicurrency transfers recreate affected transactions in a sneaky way

### ISSUE THREAD

**Issue by gyohng** [akaunting/akaunting#1937]
### Steps to reproduce the issue

- Create a transfer (e.g., USD -> EUR)
- Edit the EUR transaction to represent the exact amount you have on your bank account (i.e., something different from live exchange rate or any exchange rate you have in Akaunting settings, as banks handle it differently)
- Open transfer, change nothing, press Save

### Expected result

- The transfer dialog should show separate values for outgoing and incoming transactions or at least not overwrite edited values.

### Actual result

- The incoming (receiving) transaction of the transfer is silently overwritten with a different value.

### System information (Akaunting, PHP versions)

Akaunting 2.1.7

PHP 7.4

### Additional comments

Because transfers quite often are not free, and it's impossible to predict the exact transfer value based on an exchange rate (bank fees, different rates, preferential rates), I recommend showing incoming and outgoing values of the child transactions on the transfer dialog. Or having a tickbox 'received amount differs from sent', then a second edit box appears. And when the transaction editing is opened, this tickbox itself takes value from incoming.amount != outgoing.amount condition

**Comment by denisdulici** [comment]
You should not change the transactions of transfers. Feel free to use the forum for future requests.
