### ISSUE TITLE
Overflow in table columns

### ISSUE THREAD

**Issue by doctor-damager** [akaunting/akaunting#1950]
### Steps to reproduce the issue
Add categry with a long name.

### Expected result
Tables show the category name truncated in the columns

### Actual result
the category name overflows other columns

### System information (Akaunting, PHP versions)
v.2

### Additional comments
may also be a problem with other long texts. all table columns schould get a css class with defined overflow handling

**Comment by cuneytsenturk** [comment]
this issue solved re #[2014](https://github.com/akaunting/akaunting/pull/2014)
