### ISSUE TITLE
 Ability to add items to Invoices/Bills on mobile/iPhone doesn't work

### ISSUE THREAD

**Issue by rkemper** [akaunting/akaunting#1951]
I'm Requesting that https://github.com/akaunting/akaunting/issues/1861 be re-opened or addressed as the update that was released did not resolve the issue.

> Still doesn't seem to be working on iPhone after updating? In portrait mode, it doesn't show any results after searching for an item. In landscape mode, it shows the results, but after selecting an item, it doesn't get added to the invoice.
https://github.com/akaunting/akaunting/issues/1861#issuecomment-787527173

> This challenge still exists on the iPhone 12 Max running iOS 14.4.1.
In portrait mode no items are listed when clicking the + button. In landscape mode the items are listed but when selected the item does not appear on the invoice.
https://github.com/akaunting/akaunting/issues/1861#issuecomment-797450894

**Comment by cuneytsenturk** [comment]
https://github.com/akaunting/akaunting/pull/2015
