### ISSUE TITLE
"Tax number" string translation issue

### ISSUE THREAD

**Issue by pavel-mironchik** [akaunting/akaunting#1964]
### Steps to reproduce the issue

1. Set the tax number in your company settings.
2. Create/edit an invoice
3. Expand the "Company" accordion.
4. Look for the tax number.

### Expected result
Label "Tax number" and a tax number.

### Actual result
![2021-04-01 16-09-24 Ubuntu Mate 19 10 (Снимок 92)  Работает  - Oracle VM VirtualBox   2](https://user-images.githubusercontent.com/7408605/113280285-e3bf0b80-9305-11eb-821a-7a1dbacbcfe6.png)

### System information (Akaunting, PHP versions)
Latest Akaunting version, and also happens in the Cloud.

**Comment by cuneytsenturk** [comment]
Already fixed this issue [here](https://github.com/akaunting/akaunting/pull/1955)

**Comment by pavel-mironchik** [comment]
> Already fixed this issue [here](https://github.com/akaunting/akaunting/pull/1955)

And I didn't recompile the assets in my dev environment, that's why the issue existed there.
