### ISSUE TITLE
Client Select Bringing wrong clients

### ISSUE THREAD

**Issue by tratotech** [akaunting/akaunting#1966]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Register Some clients - More than 20 
Go to Sales > Invoices 
Create New Invoice 
Search for a client that don't appear in the first list.
Click on its name

### Expected result
Should bring data of the client clicked.

### Actual result
Bringing data of another client. 

### System information (Akaunting, PHP versions)
Akaunting 2.1.9 
Problem detected on self-hosted installation with php 7.4.15 and reproduced on cloud version(app.akaunting.com). 

### Additional comments
May share credentials if you want to check from inside the instance of the cloud version. 

Video of the issue from the cloud version: https://drive.google.com/file/d/1ccUFV01hy19NXAtYC3x7-eX31iABUrnZ/view?usp=sharing

**Comment by tratotech** [comment]
To complement: 

If i search for the exact full name: OK 

But, if i type like 4 letters or less, than the issue comes up. 

I made a new video with more deep testing. 

https://drive.google.com/file/d/1s5Sqm7-Yi4ctF_MttOlG5TUCboR0DkqO/view?usp=sharing

**Comment by cuneytsenturk** [comment]
thank for feedback @tratotech

**Comment by cuneytsenturk** [comment]
https://github.com/akaunting/akaunting/commit/d483be58ed2ba6b67a3b413b359e217e7007520d
