### ISSUE TITLE
"Ask your hosting provider to use PHP 7.3.0 or higher" error when using PHP 7.4

### ISSUE THREAD

**Issue by toxpal** [akaunting/akaunting#1967]
Downloaded the latest version (2.1.9) and tried to install it on localhost using PHP 7.4.10. Installer displays this error - "Ask your hosting provider to use PHP 7.3.0 or higher for both HTTP and CLI."

Running XAMPP with these modules:

Apache/2.4.46 (Unix) OpenSSL/1.1.1g PHP/7.4.10 mod_perl/2.0.11 Perl/v5.32.0
Database client version: libmysql - mysqlnd 7.4.10

**Comment by cuneytsenturk** [comment]
Please use [forum](https://akaunting.com/forum)

same discussions
[HTTP & CLI Error](https://akaunting.com/forum/discussion/installation-update/http-cli-error)
[Can' install PHP CLI error](https://akaunting.com/forum/discussion/installation-update/can-install-php-cli-error)
[PHP CLI not possible by the provider](https://akaunting.com/tr/forum/discussion/installation-update/php-cli-not-possible-by-the-provider)
etc.

**Comment by toxpal** [comment]
Thanks. It's shame that the only "fix" is to comment out some code in installer when using XAMPP, while all the other scripts detect PHP version properly.

**Comment by laiseng** [comment]
if you're using xampp on windows, set php.exe path to your %PATH%

if you're in linux set $PATH to your environment variable to your php binary
