### ISSUE TITLE
Invoice date problem in creating sales invoice

### ISSUE THREAD

**Issue by sevket-yilmaz** [akaunting/akaunting#1979]
Hi, I am a new user in Akaunting. I created a new account and tried to create a new sales invoice. When I trying to select 12.02.2021 (or another day in February) for the invoice date, I see the date 12.12.2018 in input (when I clicked some empty area).

![image](https://user-images.githubusercontent.com/10208986/114194100-d0d8b680-9957-11eb-8b31-5857ca471534.png)

![image](https://user-images.githubusercontent.com/10208986/114194184-e64de080-9957-11eb-8c13-a4e761feb47c.png)

### System information (Akaunting, PHP versions)
Akaunting cloud..

**Comment by sevket-yilmaz** [comment]
Also I see the same problem in this modal.

![image](https://user-images.githubusercontent.com/10208986/114195737-66c11100-9959-11eb-8b7f-3eaa0da15ff3.png)

**Comment by BhaktaOm** [comment]
Same problem here on Akaunting 2.1.9.

Selecting a date in March or April 2021 works ok, but when selecting a date in February or before, the date gets converted to a date in 2018 when clicking outside the date box.

After selecting a date (date is ok):

![image](https://user-images.githubusercontent.com/57320163/114256654-d4386600-9988-11eb-9da8-86e5bd2d1ac6.png)

After clicking outside the date box (date gets changed to something in 2018):

![image](https://user-images.githubusercontent.com/57320163/114256679-fa5e0600-9988-11eb-8aa0-279134414d94.png)

**Comment by milou12345** [comment]
Had the same problem. Resolved it by changing language under settings > standard values to my language from the drop-down menu. I had set the language in the setup manually to de_De expecting standard localization terminology. You should also check the date settings under localization. Let me know if this helps

**Comment by BhaktaOm** [comment]
Aha, thanks @milou12345!

This helped narrow down what triggers the issue:  when selecting a date format that includes the name of the month in settings/localisation AND using a language other than English.

This should help find the root cause, perhaps there is a "DateTime::createFromFormat()" somewhere that is not configured to convert from a localized version of the month names?

**Comment by milou12345** [comment]
There multiple Datetime conversion errors. Just to be clear i have very little experience with Mysql but i noticed that the format mysql expects ist yy--mm--dd. The conversion is broken on many levels. For example: if you try to add a photo to an item with non English EXIF data (shooting date), the conversion will break too.
