### ISSUE TITLE
Bill Recurring Template missing 

### ISSUE THREAD

**Issue by tratotech** [akaunting/akaunting#1986]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create a Recurring Bill Document
Run command on cli "php artisan recurring:check" 

### Expected result
Creation of the recurring invoice 

### Actual result
An error in throw on Notification Class. 
I Identify that the model is expecting a "bill_recur_customer" that is not seeded on installation. 

### System information (Akaunting, PHP versions)
Akaunting Version 2.1.9 
PHP 7.14.15 

### Additional comments
After i clone the email template "settings.email.templates.bill_recur_customer" to "settings.email.templates.bill_recur_admin" the recurring start to work again.

**Comment by denisdulici** [comment]
Bill vendor should not be notified at all so the problem is not with the missing template but being notified.

**Comment by cuneytsenturk** [comment]
Burak fixed this issue.
