### ISSUE TITLE
Customer able to see revenues, invoices and transactions of all customers

### ISSUE THREAD

**Issue by donaldskip326** [akaunting/akaunting#1987]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Login as a Customer, Sales->Invoices 

### Expected result
The Customer able to see only invoices with himself. 

### Actual result
There are all invoices of that company shows to the Customer

### System information (Akaunting, PHP versions)
Akauting 2.1.9

### Additional comments
Same happens at Revenues, Transactions, Widgets etc

**Comment by denisdulici** [comment]
You're confusing users with customers https://akaunting.com/docs/user-manual/sales/customers

Feel free to use the forum for further help.

**Comment by donaldskip326** [comment]
@denisdulici  That bug reproduced when SSL turned on
