### ISSUE TITLE
refactor accounting Implementation 

### ISSUE THREAD

**Issue by ali3bdalla** [akaunting/akaunting#1998]
this Project architecture looks works fine for small companies , but if we want to scale this project up to work for medium companies we have to change a few accounting implementation, 
for example calculating account balance will require looping through all  transactions for this account, I have built Accounting system witch the single account could have 1Million transaction, 
so this is not good practice , we can use daily account balance snapshots this will help you to calc the balance so fast, you just need for 365 snapshot for each account per year, and this will also help with closing accounting year

**Comment by ali3bdalla** [comment]
I haven't seen the accounting module yet but I deferentially orders and payments side effect so i can imagine that we do need to refactor this module as well

**Comment by denisdulici** [comment]
Feel free to use the forum for such discussions.
