### ISSUE TITLE
Table 'akaunting.ak_settings' doesn't exist - error when running Composer install

### ISSUE THREAD

**Issue by princeton255** [akaunting/akaunting#2]
Hi team,
I tried pulling the repository, and doing a composer install to test it locally. However i am getting below error. I have configured .env file to point to a fresh mysql database on localhost. Trying to do a database migration also gives same error. Can you please advise.
`
generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan ide-helper:generate

                                                                               
  [Illuminate\Database\QueryException]                                         
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akaunting.ak_set  
  tings' doesn't exist (SQL: select * from `ak_settings`)                      
                                                                               

                                                                               
  [PDOException]                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akaunting.ak_set  
  tings' doesn't exist                                                         
                                                                               

Script php artisan ide-helper:generate handling the post-update-cmd event returned with error code 1`

**Comment by denisdulici** [comment]
Hi Tumaini,

You should remove the .env file and proceed with step 1 of normal installation https://akaunting.com/docs/installation

There is no console installation, yet.

Regards

**Comment by princeton255** [comment]
Thanks @denisdulici. Will try that option.
Regards

**Comment by cchoe1** [comment]
Hi, I'm also having issues with my installation.  It seems that I cannot get it to connect to my database.  I've tried to connect to both a local database + a database with my hosting provider and neither would work.

**Comment by denisdulici** [comment]
Hi @cchoe1. Can you please make sure that the port of db connection is 3306?

**Comment by samueldervis** [comment]
Also having trouble installing. Cant even install the stable download from your site

**Comment by denisdulici** [comment]
Guys, opening a discussion on forums with further details such as error message, php version etc would be more helpful https://akaunting.com/forum

**Comment by shern91** [comment]
same problem here, after cloning this repo, i run "composer install" and move this repo to my xampp/htdocs/ path, getting 
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'akaunting.ak_settings' doesn't exist (SQL: select * from `ak_settings`)` error.
