### ISSUE TITLE
Download invoice PDF squashes layout

### ISSUE THREAD

**Issue by knightian** [akaunting/akaunting#2003]
### System information (Akaunting, PHP versions)
Ubuntu 20.04.2 + Akaunting 2.1.10 + PHP 7.4

Invoice template is stretched across the whole screen instead of A4 portrait. This means when you download a PDF of the invoice, it squashes the template to fit A4 portrait and the whole layout of the document gets messed up badly.

This is a very bad bug, it makes downloading invoices unusable.

**Comment by cuneytsenturk** [comment]
Please tell me in more detail.
For ex. Screenshot or Video.

**Comment by knightian** [comment]
> Please tell me in more detail.
> For ex. Screenshot or Video.

When you view the invoice in the web browser, it is stretched the width of the browser.

When you download a PDF, it squashes the content horizontally to fit into the A4 size PDF.

So it is not consistent between the web view and the PDF view.

**Comment by denisdulici** [comment]
Not able to reproduce such an issue, feel free to use the forum for further help.

**Comment by knightian** [comment]
> Not able to reproduce such an issue, feel free to use the forum for further help.

Are you for real? How hard is it to look at an invoice, and then open up the downloaded PDF and see that it has been squashed to be less wide. Are you using screens the size of A4 paper or something? Ridiculous.
