### ISSUE TITLE
Title not being applied to the invoice document

### ISSUE THREAD

**Issue by knightian** [akaunting/akaunting#2004]
### Expected result
When I set a custom title of "Tax Invoice" it is visible on the page but not the document.

When I download the invoice, nowhere on the document does it say "Tax Invoice" which means the document it not legal as a tax invoice in Australia.

Also the sub heading doesn't appear to show anywhere at all.

### Actual result

The document should have the heading ad subheading that we specify. In my case I need the document to have a heading of "Tax Invoice" when it is downloaded as a pdf.

### System information (Akaunting, PHP versions)
akaunting 2.1.10, php 7.4

### Additional comments

See ATO instructions for Tax invoice with the document stating that it is a tax invoice: https://www.ato.gov.au/business/gst/tax-invoices/

**Comment by cuneytsenturk** [comment]
Already you can change Invoice title.

![image](https://user-images.githubusercontent.com/10936547/116775836-ec724100-aa6d-11eb-838b-0fcaf6972d6e.png)

**Comment by knightian** [comment]
@cuneytsenturk It is not applying the title to the document, it only puts it on the page, when you download the PDF the title is nowhere on the document.

**Comment by cuneytsenturk** [comment]
Thank you feedback @knightian
