### ISSUE TITLE
Error on import with quantity

### ISSUE THREAD

**Issue by yecine06** [akaunting/akaunting#2006]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Import invoice_items with quantity as float

Sheet : invoice_items

invoice_number | name | description | quantity | price | total | tax
-- | -- | -- | -- | -- | -- | --
FA1202-0004 | DEV | Dev | 15 | 180 | 2700 |  
FA1202-0004 | DEV | Dev 2 | 6,5 | 180 | 1170 |  

### Expected result
The import should work

### Actual result
Error display :
<span>Error: The quantity must be an <strong>integer</strong>. Column name: quantity. Line number: 3.</span>

### Additional comments
It seems that a rule is blocking is import and forcing the quantity to be an integer instead of a float

As a quick fix for now i have edited the file app/Imports/Sales/Sheets/InvoiceItems.php and unset the rule for quantity

`Line 46 :  unset($rules['invoice_id'], $rules['quantity']);`

**Comment by cuneytsenturk** [comment]
Thanks youe feedback @yecine06
