### ISSUE TITLE
Error on fresh installation

### ISSUE THREAD

**Issue by G4Zz0L1** [akaunting/akaunting#2009]
I'm trying to install the self-hosted version and right after the git clone, composer install yields the result in the screenshot below.
The requirements states PHP 7.3 or higher, but many packages has to be updated to work with PHP 8.0+.
I don't have similar problems in other laravel installation locally, so I thought it may be an issue.

### Steps to reproduce the issue
- git clone https://github.com/akaunting/akaunting.git
- composer install

### System information (Akaunting, PHP versions)
Akaunting master on 567496e564f45b5acd74e7258a5feac3abe458a6
PHP 8.0.5

### Additional comments
![image](https://user-images.githubusercontent.com/13220636/116480438-a22c6c80-a881-11eb-8123-c6f08f0d997d.png)

**Comment by knightian** [comment]
Successfully using PHP 7.4

**Comment by G4Zz0L1** [comment]
Yep, I knew of that, but nothing in the readme nor in the docs suggests that it shouldn't work with PHP 8. The requirements states "PHP 7.3 or higher". If it isn't supported than it should be noted somewhere, I think.

**Comment by denisdulici** [comment]
Those packages need to be compatible with PHP 8.
