### ISSUE TITLE
SQL error when saving a bill with file attachment

### ISSUE THREAD

**Issue by afkiwers** [akaunting/akaunting#2017]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create a bill and attach a file, then save.

### Expected result
save the new bill without SQL error

### Actual result
SQL error: 
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'media_id' at row 1 (SQL: insert into `aka_mediables` (`media_id`, `mediable_id`, `mediable_type`, `order`, `tag`) values (, 10, App\Models\Document\Document, 1, attachment))

### System information (Akaunting, PHP versions)
Version 2.1.11, Using docker image = akaunting/akaunting latest 

### Additional comments
I just updated from previous version to new one from within the app. Before everything was working just fine.

**Comment by cuneytsenturk** [comment]
I've test clean Akaunting and everything work. please check your instance.

**Comment by NajibNour** [comment]
This issue has happened to me as well, Have you found a solution?
Error: `SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'core::ui' for column `akaunting`.`asd_contacts`.`created_from` at row 1 (SQL: insert into `asd_contacts` (`name`, `email`, `tax_number`, `phone`, `website`, `city`, `zip_code`, `state`, `reference`, `enabled`, `type`, `address`, `currency_code`, `country`, `company_id`, `created_by`, `created_from`, `updated_at`, `created_at`) values (Facebook, ?, ?, ?, ?, ?, ?, ?, ?, 1, customer, ?, CAD, ?, 4, 1, core::ui, 2021-10-20 15:49:28, 2021-10-20 15:49:28))`
