### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by shiftrtech** [akaunting/akaunting#2018]
Hey first of all this is a great project, congratulations.

I just installed akaunting on php8 and postgresql 10 (after trying by more than 6 hours), finally i get the first step of wizard,

Just wondering if this project is actively maintained, so I can PR all my progress.

Thanks in advance.

**Comment by denisdulici** [comment]
In such cases, not specific to Akaunting, I'd suggest you check the commit and release history of that repository:

https://github.com/akaunting/akaunting/commits/master
https://github.com/akaunting/akaunting/releases
