### ISSUE TITLE
__invoke Function not found

### ISSUE THREAD

**Issue by imran300** [akaunting/akaunting#2022]
Hello
I have made a new Job class, Controller, FormRequests and rest 
i followed the same pattern of yours but not ajaxDispatch..
I am getting the following error.

![image_2021-05-05_162442](https://user-images.githubusercontent.com/7050400/117133993-6e3fd280-adbe-11eb-8ddd-883d8d7b4ce1.png)
![image_2021-05-05_162514](https://user-images.githubusercontent.com/7050400/117134048-8152a280-adbe-11eb-8886-a0768031af1b.png)

**Comment by cuneytsenturk** [comment]
Akaunting not has this request class.

**Comment by imran300** [comment]
@cuneytsenturk i know. I have created another Files. I dont want to change the default files of akaunting so thats why i create my own files same as akaunting follows
