### ISSUE TITLE
Price value change when editing an invoice

### ISSUE THREAD

**Issue by cyworks** [akaunting/akaunting#2024]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create a new currency XPF rate 1
Change USD rate to 0.01
Change EUR rate to 0.0084
Change the default currency to XPF
Create a new invoice with XPF currency
Add new item with a price value
Save this invoice
Edit this invoice

### Expected result
Price value not change

### Actual result
Three zero added at the end of each price value field

### System information (Akaunting, PHP versions)
Akaunting 2.1.10 / PHP7.3.27

**Comment by denisdulici** [comment]
This has been fixed in master.
