### ISSUE TITLE
Subtitle not showing in export PDF

### ISSUE THREAD

**Issue by cyworks** [akaunting/akaunting#2025]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Export an invoice

### Expected result
Subtitle display at the bottom of the title

### Actual result
Subtitle not appear

### System information (Akaunting, PHP versions)
Akaunting 2.1.10 / PHP7.3.27

**Comment by denisdulici** [comment]
This is fixed in master branch.
