### ISSUE TITLE
Error on new item form (when typing non numeric value in price field)

### ISSUE THREAD

**Issue by Bahaaeddine** [akaunting/akaunting#2026]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Add new item,
Enter a wrong value to purchase/sale price
![price_product_add](https://user-images.githubusercontent.com/7093637/117307637-0605f500-ae81-11eb-88b4-22c58279524f.PNG)

### Expected result
Error message telling that the entered value is not valide

### Actual result
Server error

![errro_stack](https://user-images.githubusercontent.com/7093637/117307663-09997c00-ae81-11eb-841a-44c6c6c24404.PNG)

items.js error: 

![error_2](https://user-images.githubusercontent.com/7093637/117307776-27ff7780-ae81-11eb-9504-1821899f13e3.PNG)

**Comment by denisdulici** [comment]
This has been fixed in master.
