### ISSUE TITLE
issue invoice pdf chinese

### ISSUE THREAD

**Issue by skinrevolutionhk** [akaunting/akaunting#2027]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Select traditional chiense chacters and generate pdf invoice

### Expected result
display chinese fonts

### Actual result
display squares

### System information (Akaunting, PHP versions)
latest
php7.4

### Additional comments
running in lxc nginx proxy forcescheme https

**Comment by cuneytsenturk** [comment]
Fixed this pull request => https://github.com/akaunting/akaunting/pull/2244
