### ISSUE TITLE
laravel 5.5 instead of 5.4

### ISSUE THREAD

**Issue by AGhasemzadeh** [akaunting/akaunting#203]
Hello,
It would be good idea to update 5.4 to 5.5.

**Comment by denisdulici** [comment]
Hello Ali,

Laravel 5.5+ requires PHP 7 version and our stats says that 60% of Akaunting users have PHP 5.6 on their server so we're going to wait for while before implementing it.

Regards

**Comment by AGhasemzadeh** [comment]
Any plan for 5.5 or 5.6 ?

**Comment by denisdulici** [comment]
Yes, as soon as the PHP 7 usage passes 5.6 version.
