### ISSUE TITLE
Inconsistencies between currencies in bank account and transactions are not detected

### ISSUE THREAD

**Issue by Geod24** [akaunting/akaunting#2031]
### Steps to reproduce the issue

I have Akaunting installed on premises with the Double Entry module. I believe this can be reproduced on the cloud version tho.

First, create an new company and leave the default currency as USD.
Install double entry, then go to settings and change currency to EUR. Add some transactions.
Then, dashboards / bank will show USD amounts, despite transactions being recorded in EUR.

### Expected result

Error if a EUR transaction is associated to a non-EUR bank account.

### Actual result

<img width="836" alt="Screen Shot 2021-05-11 at 10 08 51" src="https://user-images.githubusercontent.com/2180215/117743061-061b4180-b241-11eb-84aa-a63864d1e72e.png">
<img width="1273" alt="Screen Shot 2021-05-11 at 10 04 07" src="https://user-images.githubusercontent.com/2180215/117743081-0e737c80-b241-11eb-8b5d-f5bfeedf0dec.png">
<img width="1268" alt="Screen Shot 2021-05-11 at 10 04 18" src="https://user-images.githubusercontent.com/2180215/117743091-10d5d680-b241-11eb-875f-11da46c91217.png">

I fixed this by assigning the few transactions to a newly created EUR account, fixing the USD account, then switching the transactions back.

### System information (Akaunting, PHP versions)

Akaunting: 2.1.11
Double Entry: 2.1.13

**Comment by denisdulici** [comment]
Feel free to use the ticket system for modules.
