### ISSUE TITLE
Profit/Loss Accrual Report

### ISSUE THREAD

**Issue by usvi4me** [akaunting/akaunting#2036]
### Steps to reproduce the issue
Profit/Loss Report Accrual Basis does not separate the categories correct. For some reason it combines the results of multiple categories into one. Not all categories but some.

Profit/Loss Cash basis separates all the categories correct.

System information (Akaunting, PHP versions)
Shared hosting account - php 7.4 — akaunting 2.1.11

**Comment by denisdulici** [comment]
Not able to reproduce such an issue, feel free to use the forum for further help.
