### ISSUE TITLE
Error after 2.1.13 upgrade

### ISSUE THREAD

**Issue by pedromvf** [akaunting/akaunting#2038]
### Steps to reproduce the issue

After the upgrade I can't acess the dashboard or login page.

### Expected result

Login page

### Actual result

404 Error page.

### System information (Akaunting, PHP versions)

2.1.12 to 2.1.13

### Additional comments

![image](https://user-images.githubusercontent.com/57451957/118315719-404c4380-b4cc-11eb-9481-85dc7459f254.png)

**Comment by cyworks** [comment]
Same problem here!

**Comment by denisdulici** [comment]
Not able to reproduce such an error. There is no `auth` link in Akaunting. Feel free to use the forum for further help.
