### ISSUE TITLE
Update to v2.1.13 breaks installation

### ISSUE THREAD

**Issue by ikhoury** [akaunting/akaunting#2040]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Update to v2.1.13 from the UI.

### Expected result
UI refreshes to dashboard.

### Actual result
404 not found page.

### System information (Akaunting, PHP versions)
v2.1.13 DigitalOcean one-click install.

### Additional comments
How can I revert the system to a working state? I still have data in my DB.

**Comment by pedromvf** [comment]
Same here!

**Comment by pedromvf** [comment]
Do you know https://weap.io/?
It is a reliable alternativo to daily backup in Digital Ocean platform.

**Comment by ikhoury** [comment]
Interesting I'll check it out! With DO it's weekly backups...

**Comment by denisdulici** [comment]
Not able to reproduce such an error. Feel free to use the forum for further help.

**Comment by pedromvf** [comment]
Denis, we need your help, please

**Comment by ikhoury** [comment]
You can easily reproduce the error now if you spin up a new Akaunting droplet image on digital ocean. `v2.1.13` is broken.

**Comment by pedromvf** [comment]
Maybe we need upgrade php to 7.4?

**Comment by pedromvf** [comment]
Nope. I've upgraded to 7.4 and same error ocurring

**Comment by cuneytsenturk** [comment]
Please add .env file `APP_URL={YOUR_URL}` then test again.
