### ISSUE TITLE
2.1.13 Install issues.

### ISSUE THREAD

**Issue by Jimmy062006** [akaunting/akaunting#2042]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Extract Zip folder to web host root

### Expected result
Installer presented

### Actual result
404 Error

### System information (Akaunting, PHP versions)
php 8.0 and 7.4 Akaunting 2.1.13

### Additional comments

This looks to me like its caused by a localhost url hardcode by mistake ?

![image](https://user-images.githubusercontent.com/4639349/118376668-57209200-b5c1-11eb-9385-8fba15a09f36.png)

![image](https://user-images.githubusercontent.com/4639349/118376683-74556080-b5c1-11eb-89ac-d29041de174f.png)

**Comment by Jimmy062006** [comment]
OK I have managed to fix the issue by editing config/app.php 

```    'url' => env('APP_URL', 'http://localhost'),
```

This was confusing due to the website suggesting just extract and follow the install wizard.

![image](https://user-images.githubusercontent.com/4639349/118376949-eb3f2900-b5c2-11eb-86c8-778c3e9e53f9.png)

**Comment by cuneytsenturk** [comment]
https://github.com/akaunting/akaunting/issues/2040

**Comment by Jimmy062006** [comment]
I read that other post but that is not what your doc say.

Please update the docs if that is a requirement.
