### ISSUE TITLE
Version 2.1.13 upgrade error page not found 

### ISSUE THREAD

**Issue by usvi4me** [akaunting/akaunting#2045]
After upgrading from 2.1.12 to 2.1.13 the error “page not found (dashboard page) occurs.

when removing APP_ENV=production from .env the page loads.

### Steps to reproduce the issue
Add APP_ENV=production to .env

### Expected result
Load dashboard

### Actual result
Error 403

**Comment by cuneytsenturk** [comment]
https://github.com/akaunting/akaunting/issues/2040
