### ISSUE TITLE
Multiple currency not working in Income summary

### ISSUE THREAD

**Issue by yogs22** [akaunting/akaunting#2047]
### Steps to reproduce the issue
Hi, I'm a new user in Akaunting, i have a problem with multiple currency income summary 

I have two currency, IDR & USD. IDR is my default currency. 

I input revenue with a nominal value of Rp 150,000 and $10. But in income summary, dashboard, profit & loss the revenue not converted to IDR. It only count the nominal

My Revenues

![image](https://user-images.githubusercontent.com/25165999/118603269-e5715f80-b7dd-11eb-854e-74bdda46dd26.png)

Dashboard

![image](https://user-images.githubusercontent.com/25165999/118600893-ca055500-b7db-11eb-9579-4f09b88c09db.png)

Reports

![image](https://user-images.githubusercontent.com/25165999/118602032-544db900-b7dc-11eb-8ccc-d9e20d6368aa.png)

Even though I've already setting the currency

![image](https://user-images.githubusercontent.com/25165999/118603458-1fdafc80-b7de-11eb-857a-4e74fb46f986.png)

### Expected result
The nominal revenue is converted to default currency in total summary

> Rp. 150.000
> $10 = Rp. 140.000
> Total revenue = Rp. 290.000

### Actual result
The currency is not converted to default currency in total summary

> Rp. 150.000
> $10 
> Total revenue = Rp. 150.010

### System information (Akaunting, PHP versions)
Akaunting  = 2.1.13
PHP = 7.3
Nginx = 1.19.8
MySQL = 8.0.23

MacOS Catalina = 10.15.7

### Additional comments

Thank you :)

**Comment by cuneytsenturk** [comment]
I've test clean Akaunting, and everything works.

Yon can look screenshots

![Image Pasted at 2021-5-20 10-22](https://user-images.githubusercontent.com/10936547/118937170-e62d0180-b955-11eb-99a5-17bcbe37ee39.png)
![Image Pasted at 2021-5-20 10-23](https://user-images.githubusercontent.com/10936547/118937173-e75e2e80-b955-11eb-889c-0e3a905132b1.png)
![Image Pasted at 2021-5-20 10-24](https://user-images.githubusercontent.com/10936547/118937211-f3e28700-b955-11eb-9feb-6fbe3d15ac21.png)
![Image Pasted at 2021-5-20 10-25](https://user-images.githubusercontent.com/10936547/118937212-f47b1d80-b955-11eb-8064-4ce03a9c3b88.png)
![Image Pasted at 2021-5-20 10-26](https://user-images.githubusercontent.com/10936547/118937214-f47b1d80-b955-11eb-9c36-55c2716cc6dd.png)
