### ISSUE TITLE
Item selection on invoice bug

### ISSUE THREAD

**Issue by NajibNour** [akaunting/akaunting#2050]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Have an inventory. Create new invoice, Search for an item (M&M) and click on the item.

### Expected result
Chooses the proper item to invoice. (M&M)

### Actual result
Chooses first option in items list

### System information (Akaunting, PHP versions)
Akaunting on docker using image:  2.1.12            a324348afcc8
This was also happening on previous builds. I ave tried updating to 2.1.13 But it does give bigger issue as the web page does not load at all.

### Additional comments
(https://media.giphy.com/media/NxBFnIzcQXnrBH0qTm/giphy.gif)
![Alt Text](https://media.giphy.com/media/NxBFnIzcQXnrBH0qTm/giphy.gif)

**Comment by NajibNour** [comment]
Issue still present in 2.1.14

**Comment by cuneytsenturk** [comment]
Thank you your feedback @NajibNour
