### ISSUE TITLE
Invoice Creation Bug - "Array to string conversion"

### ISSUE THREAD

**Issue by pe3dr0o** [akaunting/akaunting#2054]
### Steps to reproduce the issue
- Create an invoice and click "Save".

### Expected result

The user is redirected to the invoice page (where there is an option to mark the invoice as paid, shipped, etc.)

### Actual result

"Array to string conversion" error message is warned.
Then, the invoice is automatically set to "draft".

![image](https://user-images.githubusercontent.com/84601838/119489665-49da7480-bd32-11eb-9226-87f00d8c925c.png)

### System information (Akaunting, PHP versions)

7.1.13
PHP 7.4

**Comment by SkullMasher** [comment]
Hello everyone hope you're having a good day. I can reproduce your bug exactly. Debug mode does not tell me anything or I lack the experience to provide more info.

Also I cannot access the estimates app at all for a for the same reason. Here's a screenshot whith the debug mode on. 

![2021-05-29_17-43_akaunting-500](https://user-images.githubusercontent.com/4488386/120076379-80531f00-c0a5-11eb-936d-7ce459e7df61.png)

**Comment by denisdulici** [comment]
Not able to reproduce such an issue. Feel free to use the forum/ticket for further help.
