### ISSUE TITLE
Application collapses if fails to update.

### ISSUE THREAD

**Issue by safarovitch** [akaunting/akaunting#2063]
I was trying to update the application which is installed on my shared hostgin account several days ago and encountered 500 server error. No further details was shown and only after few hours of investigation I realised the problem was with the server inode limits reached maximum. Hence the application was not abble to unzip/copy the content of downloaded update.
Since the application is always throwing 500 internl server error.

### Steps to reproduce the issue
Try to update using application update button on user interface while there is not enough space on server.

### Expected result
I don't know what to expect in such a situation becouse 500 server error is the only reasonable expected result. But at least there must be some kind of rollback mechanizm to prevent indefinit errors.

### Actual result
500 Internal server error for rest of its life

### System information (Akaunting, PHP versions)
Akaunting version :
    'major'     =>  '2',

    'minor'     =>  '1',

    'patch'     =>  '9',

PHP version 7.3

**Comment by denisdulici** [comment]
Feel free to use the forum for help related to updates.
