### ISSUE TITLE
New update 2.1.14 broke the site

### ISSUE THREAD

**Issue by ranjithkumar8352** [akaunting/akaunting#2065]
Hello, I'm using Akaunting by self-hosting it. I recently updated it to version 2.1.14 from 2.1.13 and it broke the site. It did show some error that update failed but I couldn't get a chance to look at the error as I clicked on home page after the error.

Now the site keeps showing 500 internal server error. Is there a way to rollback the update?

![image](https://user-images.githubusercontent.com/10174991/120078096-64627400-c0cb-11eb-8f84-d4fe33c31eaf.png)

### Steps to reproduce the issue
Update to version 2.1.14 from version 2.1.13
PHP version 7.4

### Expected result
Either update is successful or failed to update and rolled back to older version

### Actual result
Update failed with error and now site keeps showing 500 internal server error

**Comment by SkullMasher** [comment]
Hello Ranjith. There's a thread on the [akaunting forum here](https://akaunting.com/forum/discussion/installation-update/error-after-upgrade-to-2114?page=2). From page 2 and onwards you can find possible solutions to try specifically the one from Jake day. 

> To get it working after the upgrade, just add the company_id column to both your media and mediables table and you should be good to go.

**Comment by cuneytsenturk** [comment]
Feel free to use the forum for help related to updates.

**Comment by Geod24** [comment]
For reference, I ran the following to solve the issue:
```sql
ALTER TABLE $PREFIX_media ADD COLUMN company_id INT UNSIGNED DEFAULT NULL AFTER id;
```

Replacing $PREFIX with the prefix used for your tables. I'm using Mariadb.

**Comment by denisdulici** [comment]
> For reference, I ran the following to solve the issue:
> 
> ```sql
> ALTER TABLE $PREFIX_media ADD COLUMN company_id INT UNSIGNED DEFAULT NULL AFTER id;
> ```
> 
> Replacing $PREFIX with the prefix used for your tables. I'm using Mariadb.

That is [automatically](https://github.com/akaunting/akaunting/blob/master/database/migrations/2021_05_17_000000_core_v2114.php#L16) done if you update from the interface.

**Comment by Geod24** [comment]
Well I updated from the interface and it broke my install (and that of other people, if you look at the forum).
Not quite sure what went wrong (not a PHP dev), but something is definitely wrong.

**Comment by ranjithkumar8352** [comment]
Thanks @Geod24, That worked!

**Comment by ranjithkumar8352** [comment]
Note: Above command worked and got the UI back working again but there was an error when attaching a document with an invoice. I solved it by adding company_id column to `mediables` table as well
`ALTER TABLE $PREFIX_mediables ADD COLUMN company_id INT UNSIGNED DEFAULT NULL;`
