### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by marcellopato** [akaunting/akaunting#2070]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
I have followed the instructions to install, step by step. Every new page has shown a JSON with the URI, but not did redirect automatically.

### Expected result
A clean install, as expected

### Actual result
At the ```https://akaunting.test/1/wizard``` the page reproduces an error:
```Uncaught SyntaxError: Unexpected token '<' at  line 1 , wizard.js```

I have run:
composer install && npm install

### System information (Akaunting, PHP versions)
PHP 7.3.28 (cli) (built: May 13 2021 05:55:37) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.28, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.28, Copyright (c) 1999-2018, by Zend Technologies

### Additional comments
Hope this could help You to fix the problem!

**Comment by cuneytsenturk** [comment]
Hi,

You should do `npm run dev` or `npm run prod` then test again it works.
