### ISSUE TITLE
Currency table in Settings -> Currencies is not showing when the Dutch language is selected.

### ISSUE THREAD

**Issue by ToBeOnline** [akaunting/akaunting#2076]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. Go to Manage companies and edit the active companie and select Nederlands.
2. Go to Instellingen -> Valuta's

### Expected result
The currencies should be diplayed

### Actual result
The currencies table is only shown for a fraction of a second

### System information (Akaunting, PHP versions)
Akaunting version 2.1.15
PHP versions: 7.4 and 8.0

### Additional comments
This is also the case on the SAAS version.

**Comment by cuneytsenturk** [comment]
https://github.com/akaunting/akaunting/pull/2081
