### ISSUE TITLE
php artisan install is not working properly

### ISSUE THREAD

**Issue by arkniazi** [akaunting/akaunting#2099]
### Steps to reproduce the issue
Take clone of the app.
Install required packages.
then run following command
`php artisan install --db-name="akaunting" --db-username="root" --db-password="pass" --admin-email="admin@company.com" --admin-password="123456"
`

### Expected result
It should create .env file and add required environment variables in it.
And then establish connection with database. 
Complete the migrations etc.

### Actual result
"Error: Could not connect to the database! Please, make sure the details are correct."
The details I have entered are correct. But the database is not created. According to my understanding it should create the new database.

### System information (Akaunting, PHP versions)
Akaunting version: 2.1.16(latest main branch)
PHP version: 7.4

**Comment by denisdulici** [comment]
You should create the database yourself.

**Comment by gausoft** [comment]
Hello. I've created the database before but having the same issue
