### ISSUE TITLE
Mailed and Download invoice PDF squashes layout

### ISSUE THREAD

**Issue by nekocentral** [akaunting/akaunting#2103]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Create invoice
Send invoice per mail

### Expected result

Attached invoice and downloaded invoice look similar to web view

### Actual result

Downloaded result looks squashed and as if there is minimal styling applied

### System information (Akaunting, PHP versions)
4 Core Xeon with 2048MB ram
Nginx 1.14.2
php 7.3.27-1
OS: Debian 10
Akaunting 2.1.16

### Additional comments
The generation of the PDF takes quite a while to the point i had to extend the fgci timeout to 180 seconds.
Example invoice i generated
https://bills.nekoit.nl/1/signed/invoices/8?signature=020e04889cd64b4ec1184d53b66a642e65bb1da36c7d1c0169da95abc392f8bc

**Comment by cuneytsenturk** [comment]
Thank you feed back, Already show same page.

**Comment by nekocentral** [comment]
Still happening
https://bills.nekoit.nl/1/signed/invoices/3?signature=368d375fbbc93fa1bf2215ea62945070d55ec0a1a1502bf9590cd4f7674d0c61
