### ISSUE TITLE
Long Customer/Vendor Address overlaps with Invoice/Bill date.

### ISSUE THREAD

**Issue by rihards-simanovics** [akaunting/akaunting#2105]
If the Vendor/Customer Address is too long, it starts to overlap with the Bill Date. See the example below:
![image](https://user-images.githubusercontent.com/52106095/121820531-33696e00-cc8b-11eb-8ef2-f7292184322c.png)

### Steps to reproduce the issue
Enter some very long Address in for a Customer/Vendor and see how it looks on smaller screens (in case using 4k screen, try scaling to 150%)

### Expected result
![image](https://user-images.githubusercontent.com/52106095/121820702-344ecf80-cc8c-11eb-9dc6-f18251223707.png)

### Actual result
![image](https://user-images.githubusercontent.com/52106095/121820531-33696e00-cc8b-11eb-8ef2-f7292184322c.png)

### How to Fix
![image](https://user-images.githubusercontent.com/52106095/121820868-f69e7680-cc8c-11eb-80d7-469b8434c723.png)

### System information (Akaunting, PHP versions)
Version 2.1.16
PHP 7.4.20 FPM served by Nginx
FastCGI Support enabled

### Additional comments
Generally, I would say that this type of text should be surrounded by a `<p>` tag but if it's not possible, try targeting that class specifically.

**Comment by cuneytsenturk** [comment]
Dear @rihards-simanovics,

If you send this change as a PR, I will accept it.

**Comment by cuneytsenturk** [comment]
This [PR](https://github.com/akaunting/akaunting/pull/2108) solved issue

**Comment by rihards-simanovics** [comment]
Oh great, sorry, I was too busy yesterday. Thanks!
