### ISSUE TITLE
Unable to run Akaunting on domian path.

### ISSUE THREAD

**Issue by 1ubuntuuser** [akaunting/akaunting#2126]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. add path to APP_URL example.com/money
2. redirect requests from /money to Akaunting using nginx 

### Expected result
Akaunting changes it's root domain to example.com/money 

### Actual result
Error 500 on loading of example.com/money 

### Additional comments

I tried using some nginx trickery. Made progress but got stuck with a CSRF issue.
https://laravel.com/docs/8.x/csrf#csrf-introduction

Could this be supported?

https://laravel.com/docs/8.x/csrf#csrf-introduction 

Posted elsewhere:
https://akaunting.com/forum/discussion/general/running-akaunting-behind-path-such-as-examplecommoney

**Comment by denisdulici** [comment]
Duplicate of forum.
