### ISSUE TITLE
After update, change in path structure broke my app integration.

### ISSUE THREAD

**Issue by 1ubuntuuser** [akaunting/akaunting#2127]
### Steps to reproduce the issue
Assume /sales/revenues will redirect to the correct page irreverent of company Id

### Expected result
/sales/revenues will redirect to the correct page irreverent of company Id

### Actual result
/sales/revenues redirects to the dashboard. Company ID is now required in path.
/CompanyID/sales/revenues

### System information (Akaunting, PHP versions)
Docker - latest

### Additional comments
To help users navigate my mashup app, I made use of your path structure and added my own buttons to navigate the Akaunting app. This worked wonderfully until I updated. 

Is there a workaround or fix for this? My app won't necessarily be aware of the company ID of the logged in user.

**Comment by denisdulici** [comment]
You should put the `company_id` into the route or use [macros](https://github.com/akaunting/akaunting/blob/master/app/Providers/Route.php#L75), [example](https://github.com/akaunting/module-paypal-standard/commit/49671f6f3c2c6319c7b319716292d31c2ad7db51).

**Comment by 1ubuntuuser** [comment]
@denisdulici thank you for the information. How exactly can I use a macro? Would I have to modify some code and rebuild the app?

I'm not sure why this is an issue as it used to work just fine without the company_id. Why is it needed now? Is there a way to revert this?

**Comment by 1ubuntuuser** [comment]
I think this should be reopened.
