### ISSUE TITLE
Getting "Error: Could not connect to the database! Please, make sure the details are correct." with correct details

### ISSUE THREAD

**Issue by cyrik-bcn** [akaunting/akaunting#214]
Hi!

I cannot get the installation to connect to the database. All the settings are correct. To make sure it was not a server or configuration problem, I created a new test Joomla website and database and it worked perfectly. Any ideas of what might be happening?

Thank you!

**Comment by cyrik-bcn** [comment]
Thank you Carlos! I am running Plesk and cannot seem to find the way to install the dependency you are talking about... I also tried from SSH (sudo nstall php70-mysql) but I get an error asking for a target directory, and I really don't know where put it or how to write the command.. 
Thanks again!

**Comment by denisdulici** [comment]
Diego, can you plz answer Sebastian [questions](https://akaunting.com/forum/discussion/installation-update/error-could-not-connect-to-the-database-please-make-sure-the-details-are-correct?page=2)?

**Comment by cyrik-bcn** [comment]
Yes Denis, just did, sorry for the delay. :)

Carlos, I think Plesk uses CentOS. I just found out that Tokenizer and OpenSSL PHP Extensions are not installed apparently. I'll try to fix that.

Thanks again!!
