### ISSUE TITLE
Error in creating new Sales Invoice

### ISSUE THREAD

**Issue by Airy301** [akaunting/akaunting#2151]
From version 2.1.16 it throws 500 Internal Server Error when creating new Sales Invoice. I have attached a link to video showing it.

https://drive.google.com/file/d/1KqfbNIVjpHilKa7MKwNoxXuPh1GVZrFg/view?usp=sharing

I just registered for new company on Akaunting Cloud and simply clicked Create New Sales Invoice but it gave 500 error.

Then I downloaded and hosted on my local server and it gave the same error. Later I found that this error is persisting from version 2.1.16 and no such error in 2.1.15.

After reading I believe that some code changing was done for version 2.1.16 in Sales Invoice as it says "Invoice date problem in creating sales invoice" or may be something else.

There are many others complaining the same. Please take a look at this problem.

**Steps to reproduce the issue**
Try registering with new email address on Akaunting Cloud and create a new fresh company. Then just go to sales and create a new sale invoice. It will give 500 Internal Error

**Expected result**
It should simply create a Sale Invoice

**Actual result**
It throws 500 Internal Server Error

**System information (Akaunting, PHP versions)**
Akaunting Cloud Version

**Comment by cuneytsenturk** [comment]
https://github.com/akaunting/akaunting/issues/2152
