### ISSUE TITLE
500 Exception caused by failed migration.

### ISSUE THREAD

**Issue by rihards-simanovics** [akaunting/akaunting#2158]
The new update Breaks Revenues and Payments Page. Perhaps it's a missing DB migration? So the issue occurs in Histories Blade. I can see someone made a change from `$history->creator->name` to `$history->owner-name`, but the problem is the owner object does not exist!

Ok just did an emergency restore and made a pull request from the master directly.
The issue now seems to be resolved but only for those who can pull the most recent changes from git.

### Steps to reproduce the issue
Visit, Revenues or Payments Single Item View.

### Expected result
I should see the detailed Single Items View of the Payment or a Revenue.

### Actual result
500 or Exception Trying to get property 'name' of non-object (View: `/var/www/vhosts/foo.bar/accounts.foo.bar/resources/views/components/transactions/show/histories.blade.php`)

### System information (Akaunting, PHP versions)
`Version 2.1.18`
PHP support (`PHP version 7.4.20`, run PHP as FPM application served by Nginx)
FastCGI support enabled

### Additional comments
I think it might be a good idea to have an emergency patch as people might start complaining about the issue on your support page.

**Comment by cuneytsenturk** [comment]
Already fixed [here](https://github.com/akaunting/akaunting/blob/master/app/Abstracts/Model.php#L78) and [Histories blade](https://github.com/akaunting/akaunting/blob/master/resources/views/components/transactions/show/histories.blade.php#L36)
