### ISSUE TITLE
Export option in payments

### ISSUE THREAD

**Issue by Harsha5205** [akaunting/akaunting#2177]
### Steps to reproduce the issue
1) Go to payments in bills section
2) Make sure you have payments that goes beyond single page
3) Click export option present at the top of the page

### Expected result
It should export all payments data irrespective of number of pages available. 

### Actual result
It is only exporting data that is present in particular page, So I had to manually go to all pages to get all data
Suggestion: Provide customer with an option to select "From date" and "To date". This will provide customer with better user experience and flexibilty.

### System information (Akaunting, PHP versions)
OS: Windows 10
Browser: Chrome

**Comment by denisdulici** [comment]
You can hit export on each page.
