### ISSUE TITLE
Discount amount (in addition to %)

### ISSUE THREAD

**Issue by jaiume** [akaunting/akaunting#2189]
Hi,

We desperately need a discount amount option in addition to the % discount function.

Please address this, as a number of people have asked for it in the forums

Thanks
Jamie

**Comment by bhojkamal** [comment]
Hello, 

we definitely need the discount in fixed too and in percentage. All my users are asking for it. Most of the software has both options to give discount - in discount and in % too.  Please this feature on akaunting. 

Regards,
Bhojkamal

**Comment by cuneytsenturk** [comment]
This feature added this [PR](https://github.com/akaunting/akaunting/pull/2223)
