### ISSUE TITLE
Akaunting sending SMTP mails using the current users email address

### ISSUE THREAD

**Issue by hydazz** [akaunting/akaunting#2192]
When trying to send ANY emails from Akaunting, it uses the currently logged in user email address as the FROM address in the SMTP message, causing the mail to be blocked by the mailserver as it is not coming from the correct email address, below is an example of me trying to send an email to myself (`alexanderhye@icloud.com`), the .env file it is set to use `no-reply@hydesign.com.au` as the from address, but it is using either the admin email or the currently logged in users email, which in this case is `signs@hydesign.com.au `

```bash
NOQUEUE: reject: RCPT from unifi.lan[192.168.1.1]: 553 5.7.1 <signs@hydesign.com.au>: Sender address rejected: not owned by user no-reply@hydesign.com.au; from=<signs@hydesign.com.au> to=<alexanderhyde@icloud.com> proto=ESMTP helo=<_>
```
I believe the guys at [eideasy/nextcloud-electronic-signatures-plugin](https://github.com/eideasy/nextcloud-electronic-signatures-plugin) also had a similar issue here and they fixed it in v1.6.1. see here for the [issue](https://github.com/eideasy/nextcloud-electronic-signatures-plugin/issues/55) I raised there. Hoping this can be fixed in the same way they fixed their issue

**Comment by denisdulici** [comment]
Nop, it uses the `company`'s email address and that's how it's supposed to work.

**Comment by hydazz** [comment]
What is the purpose of supporting SMTP if you are not going to incorporate it properly so it can be used in most scenarios where akaunting mail would originate from its own email address, rather than the companies own email? what is the point of having `MAIL_FROM_ADDRESS` when it is not honoured?
