### ISSUE TITLE
Problemas na hora de salvar configurações de E-mail

### ISSUE THREAD

**Issue by brasileirodacosta** [akaunting/akaunting#2195]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Configuração das informações de SMTP para a empresa cadastrada. Quando vou clicar em salvar essas informações, o botão mostra apenas que está carregando e não salva de forma alguma. Mesmo eu clicando no botão de canelar, ele não salva. Torno a adicionar novamente as informações de SMTP na empresa, mas na hora de salvar ele não salva.

### Expected result
Salvar as informações de SMTP da empresa cadastrada, para então o usuário dessa empresa consiga enviar notificações de faturas para seus clientes.

### Actual result
Não salva as informações, fica apenas carregando e nada acontece.

### System information (Akaunting, PHP versions)
Akaunting versão: 2.1.20
PHP versão: 7.4.21 do Plesk Obsidian 18.0.36.

### Additional comments
Akaunting atrás do proxy da CloudFlare.
Akaunting testado fora do CloudFlare, o problema ainda continua.
ModSecurity do Plesk desativado.
Testado com PHP 7.3 com o mesmo erro.
Todas as extensões do PHP instaladas e ativadas no Plesk.
Print do LOG do Plesk, do momento que clico em salvar as informações de SMTP da empresa: https://prnt.sc/1dh0dy8

Para mais detalhes sobre o problema, segue o link do tópico do fórum que criei e um usuário ainda relatou que já tinha reportado isso, mas que até agora o problema não foi resolvido.

**Comment by denisdulici** [comment]
Not English + forum duplicate.
