### ISSUE TITLE
Unable to install in Ubuntu 20.04

### ISSUE THREAD

**Issue by Acsigen** [akaunting/akaunting#2197]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
composer install

### Actual result
In ProviderRepository.php line 208:

  Class 'BeyondCode\DumpServer\DumpServerServiceProvider' not found

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
Script composer dump-autoload handling the post-update-cmd event returned with error code 1

### System information (Akaunting, PHP versions)
Akaunting version: the latest available on 23.07.2021
PHP version 7.4

### Additional comments
![akaunting-install-error](https://user-images.githubusercontent.com/13287878/126743966-e440f14f-5af2-44b7-b4f8-300cfcb367ae.jpg)

**Comment by denisdulici** [comment]
Not able to reproduce. You can check out the composer and other versions of your server.

**Comment by Acsigen** [comment]
I tried with the composer version available on the Ubuntu repositories and also with the latest version from Composer website. The same result
