### ISSUE TITLE
Akaunting does not save SMTP company information

### ISSUE THREAD

**Issue by brasileirodacosta** [akaunting/akaunting#2198]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Fill in the company's SMTP information, then click on save.

### Expected result
Save SMTP information for invoice notifications.

### Actual result
The company SMTP settings part in Akaunting is not saving. You fill everything in, add SMTP information, but when saving, Akaunting doesn't save. It keeps charging forever and doesn't save. I tested it on Akaunting on your Cloud, even it does the same thing. Does not save SMTP information for the company to send notifications about invoices.

### System information (Akaunting, PHP versions)
PHP Version: 7.4
Akaunting version: 2.1.20

### Additional comments
In your Akaunting in the cloud the same problem happens.

**Comment by cuneytsenturk** [comment]
I've tested clean Akaunting, it works.

Already Akaunting Cloud has mail configuration.
