### ISSUE TITLE
Can this generate TPAR reports? If so where can I find it in the source code?

### ISSUE THREAD

**Issue by Joe23232** [akaunting/akaunting#2217]
Hi, I wanted to ask can this generate [TPAR reports](https://softwaredevelopers.ato.gov.au/TPARspecification) which is an Australian report? If so where can I find it in the source code?

**Comment by denisdulici** [comment]
Submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

**Comment by Joe23232** [comment]
Sure mate
