### ISSUE TITLE
invoice logo in customer account

### ISSUE THREAD

**Issue by mcruk** [akaunting/akaunting#222]
when logged in via customer account invoice logo does not show.  Also after deleting invoice logo in admin area then loging out then in, the invoice logo upload no longer works.   

a temp fix to get logo showing by changing /resources/views/customers/invoices/show.blade.php line 12 - 16

**from this**

`@if (setting('general.invoice_logo'))
      <img src="{{ asset(setting('general.invoice_logo')) }}" class="invoice-logo" />
 @else
        <img src="{{ asset(setting('general.company_logo')) }}" class="invoice-logo" />
@endif`

**to this**

`@if (setting('general.invoice_logo'))
    <img src="{{ !empty($company->company_logo) ? Storage::url($company->company_logo) : asset('public/img/invoice-logo.png') }}" class="invoice-logo" />
@else
           <img src="{{ !empty($company->company_logo) ? Storage::url($company->company_logo) : asset('public/img/invoice-logo.png') }}" class="invoice-logo" />
@endif`

upload invoice-logo.png to the folder  public/img/

**Comment by sebadamus** [comment]
Maybe... its similar to #192 problem I had.  When you say no longer works... can you tell what is the final logo url address when it does not work? (the complete url), and which url when it works?

**Comment by mcruk** [comment]
Hi
The working image url of the logo when logged in as admin is  http://127.0.0.1/mcr/uploads/1
The url of the logo when logged in as customer is http://127.0.0.1/mcr/1
