### ISSUE TITLE
Account Show wrong show transction date

### ISSUE THREAD

**Issue by jay4rrrr** [akaunting/akaunting#2221]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Opening Banking->Accounts-> (select account) / Transaction tab

### Expected result
The date should the same in the content (invoice, revenue, etc.) and arrange decending

### Actual result
Not the same date result and the arrangement is random because of the wrong date 
<img width="837" alt="1" src="https://user-images.githubusercontent.com/18664441/128724188-ef1af217-1b0f-4cda-a010-64ca227f9b55.png">

<img width="994" alt="2" src="https://user-images.githubusercontent.com/18664441/128724225-3c023863-c6dd-43b7-a38f-28cdc375f02d.png">

### System information (Akaunting, PHP versions)
7.4 

### Additional comments
Opening Banking->Accounts-> (select account) / Transaction tab
The date in the tab is not the same in the content (invoice, revenue, etc.)

**Comment by cuneytsenturk** [comment]
@jay4rrrr  Thanks your feedback.
