### ISSUE TITLE
I cannot select Kosova as a country during installation

### ISSUE THREAD

**Issue by agron2017** [akaunting/akaunting#2248]
### Akaunting version

2.1.25

### PHP version

7.4.20

### Operating system

Ubuntu 18.04.4 LTS

### Steps to reproduce

1. unpack Akaunting_2.1.25-Stable.zip to the web server
2. execute `php artisan install --db-host="***.*****.com" --db-name="fakturat" --db-username="kontabilisti" --db-password="*********" --admin-email="********@gmail.com" --admin-password="**********"
`
3. Goto web page and enter your email and password.
4. 

### Expected result

See Kosova on the list of countries

### Actual result

![figurë](https://user-images.githubusercontent.com/6324431/132937744-2403f318-a4fc-4198-9a8c-462a25fc5f49.png)

### Additional comments

I am not sure if this is a bug or feature request but, it would be nice if Kosova was there brother.

**Comment by partinpruthi** [comment]
Yes, the country of Kosovo is missing from the list of countries. The issue is present in 2.1.28 as well.
This means that the company address cannot be set to Kosovo neither can the Vendors or Customers.

**Comment by denisdulici** [comment]
It will be available in the next version.

https://en.wikipedia.org/wiki/Kosovo
https://britannica.com/place/Kosovo
