### ISSUE TITLE
Allow to use sqlite database in install

### ISSUE THREAD

**Issue by martdi** [akaunting/akaunting#225]
In the readme, the requirements state that SQLite is a database that satisfies the requirements:

Requirements
PHP 5.6.4 or higher
Database (eg: MySQL, PostgreSQL, **SQLite**)
Web Server (eg: Apache, Nginx, IIS)
Other libraries

However, if I edit the config/database.php file, the setup won't let me continue, pecause I have not provided a username/password, and if I provide them, it fails to connect to db.

Then, if I try to visit the home page, it won't show the installer, but instead ask for a username/password, which I don't have, since I did not create it.

**Comment by denisdulici** [comment]
You should edit the `.env.example` file.

**Comment by martdi** [comment]
I tried to edit this file, but I can't get it to the point where I have a Sqlite database.

Could you please provide me with a .env file that works properly with sqlite ?

I guess at some point, the install would populate a database with default data, but I can't get make it through the install.

**Comment by denisdulici** [comment]
We use GitHub for bugs and code, feel free to use the forum for support https://akaunting.com/forum

**Comment by mlncn** [comment]
@denisdulici  There is no more `.env.example`, but there is a `.env` file.

Editing it to change `DB_CONNECTION=sqlite` does work.

With prerequisites:
```
sudo apt install sqlite3
sudo apt install php7.2-sqlite3
cd ~/SoftwareApplications/akaunting # (where i installed akaunting)
sqlite akaunting.db
```
I can now get past the install screen, by entering a random username (SQLite doesn't use usernames or passwords, but the form requires a username) and setting the database to 'akaunting.db' (and leaving 'localhost' as is).

The .env file is successfully written to with this information, and a random three-letter prefix is set.

Unfortunately, the installation fails with this error:

> (1/1) SchemaException
> There is no column with name 'attachment' on table 'bill_payments'.

Full output: [Akaunting with SQLite install error gist](https://gist.github.com/mlncn/0cd18395d00b68d8c68737fdfe6a87ae)

Oddly the column in question does seem to be there:

```
.schema w7x_bill_payments 
CREATE TABLE IF NOT EXISTS "w7x_bill_payments" ("id" integer not null primary key autoincrement, "company_id" integer not null, "bill_id" integer not null, "account_id" integer not null, "paid_at" date not null, "amount" float not null, "currency_code" varchar not null, "currency_rate" float not null, "description" text null, "payment_method" varchar not null, "reference" varchar null, "attachment" varchar null, "created_at" datetime null, "updated_at" datetime null, "deleted_at" datetime null);
CREATE INDEX "bill_payments_company_id_index" on "w7x_bill_payments" ("company_id");
```

Any ideas?

I'm not finding this error reported elsewhere, so i'm wondering if it's SQLite-specific.

**Comment by realindiahotel** [comment]
I get the impression that this project is a dud.

There seems to be no answers here or in the forums where people ask the same thing.

I think they are trying to steer you to use their cloud offering so they can steal your data. I would be very careful.
