### ISSUE TITLE
Dashboard Cash Flow cutting off thousands place decimal.

### ISSUE THREAD

**Issue by ScionOfDesign** [akaunting/akaunting#2259]
### Akaunting version

2.1.25

### PHP version

Whatever is in the docker image.

### Operating system

Docker on Linux Mint 20.1

### Steps to reproduce

Have a history of payments totaling over $1,000
Visit the dashboard, and mouse over the cash flow.
See that there is a comma, but the thousandth's place is cut off. This is the same for the other graphs as well.
![image](https://user-images.githubusercontent.com/8867456/134111944-61a0eeba-ad61-4cde-a269-cc687ac6eb76.png)

### Expected result

The thousandth's place should not be cut off.

### Actual result

The thousandth's place is cut off.

**Comment by cuneytsenturk** [comment]
This issue solved this [PR](https://github.com/akaunting/akaunting/pull/2270)
