### ISSUE TITLE
Uncalculated income statistics

### ISSUE THREAD

**Issue by yogs22** [akaunting/akaunting#2261]
### Akaunting version

2.1.25

### PHP version

7.4.21

### Operating system

Ubuntu

### Steps to reproduce

- I've input a lot of income data with the types of income that I've customized all
- But the statistics and income reports are not calculated

![image](https://user-images.githubusercontent.com/25165999/134269787-143532cb-e9fc-4117-8a4e-341f141f389b.png)

![image](https://user-images.githubusercontent.com/25165999/134269783-1403c36f-0eb4-40b7-a081-8f06fa11d6fd.png)

### Expected result

The income reports is calculating

### Actual result

The income report doesn't calculating

**Comment by cuneytsenturk** [comment]
You can use [forum](https://akaunting.com/forum). This is not bug. Your financial date 2020 Mar 2021 Feb.
