### ISSUE TITLE
countries.Canada is displayed when using Canada in creating invoices

### ISSUE THREAD

**Issue by I-Iawk** [akaunting/akaunting#2262]
### Akaunting version

2.1.25

### PHP version

unsure as I am using the webclient

### Operating system

Firefox Browswer

### Steps to reproduce

When creating a new invoice, selecting the Company drop down displays the country incorrectly as countries.Canada 

Unable to change country on the fly, but able to change the company country when directly modifying it. Only the value Canada has this issue.

### Expected result

Canada

### Actual result

countries.Canada

**Comment by cuneytsenturk** [comment]
Thank you, Your feedback.
@CihanSenturk solved this [PR](https://github.com/akaunting/akaunting/pull/2256)
