### ISSUE TITLE
Graph on Dashboard cuts numbers

### ISSUE THREAD

**Issue by HenrikWittemeier** [akaunting/akaunting#2268]
### Akaunting version

2.1.25

### PHP version

7.4.24

### Operating system

Debian 11

### Steps to reproduce

1. Have a running server Instance
2. Add incomes above 1000€
3. Go to Dashboard

### Expected result

See numbers like 1200€

### Actual result

numbers shown 800;900;000;100
![grafik](https://user-images.githubusercontent.com/80068511/135155943-3fa61852-7d07-4a65-8941-a9df473c7362.png)
Here should be an 1044,97€:
![grafik](https://user-images.githubusercontent.com/80068511/135156250-5437f180-90eb-4c73-84fe-be25979f7576.png)

### Additional comments

If you need further information to reproduce, dont hesitate to ask :)

**Comment by cuneytsenturk** [comment]
This issue solved this [PR](https://github.com/akaunting/akaunting/pull/2270)
