### ISSUE TITLE
Profit makes no sense

### ISSUE THREAD

**Issue by HenrikWittemeier** [akaunting/akaunting#2269]
### Akaunting version

2.1.25

### PHP version

7.4.24

### Operating system

Debian 11

### Steps to reproduce

1. Have a running system
2. Add some Earnings and Payments
3. Watch the Dashboard graph

### Expected result

The green line for profit should have another course

### Actual result

The course of the profit makes no sense
![grafik](https://user-images.githubusercontent.com/80068511/135157030-ead2dc9a-470c-4fb2-aade-942a4a30283a.png)

### Additional comments

If you have additional questions, dont hesitate to ask.

**Comment by HenrikWittemeier** [comment]
Oh i understood it wrong

**Comment by cuneytsenturk** [comment]
Thank your feedback, Cashflow line chart show. 3 actions. We'll evaluate
