### ISSUE TITLE
logo upload problem

### ISSUE THREAD

**Issue by AGhasemzadeh** [akaunting/akaunting#227]
Hello,
https://app.akaunting.com/settings/settings
In tab invoice when we want upload image we can not do it.
It submit page.

**Comment by sebadamus** [comment]
You mean, attaching an image as invoice attachment?

**Comment by cuneytsenturk** [comment]
Fixed here https://github.com/akaunting/akaunting/commit/da5eb9b16acf30a344ab17eba2e63b8280a7b5d1
