### ISSUE TITLE
Missing "countries.Switzerland" translation in german

### ISSUE THREAD

**Issue by josias-r** [akaunting/akaunting#2274]
### Akaunting version

2.1.25

### PHP version

7.4.10

### Operating system

Ubuntu 20.4

### Steps to reproduce

View an invoice generated through an Akaunting installation which is set to german.

### Expected result

A translated country name

### Actual result

The invoice displays "countries.Switzerland"

### Additional comments

I find it strange that the term is not translated, since the crowdin project shows that countries actually have been translated correctly and I also found the translated term in the codebase.

**Comment by cuneytsenturk** [comment]
This [PR](https://github.com/akaunting/akaunting/pull/2273/commits/306ec964b239a754cfe0b6d4769fef9669db1f3f) solved issue.

**Comment by josias-r** [comment]
@cuneytsenturk It did not solve it for me, I upgraded to version 2.1.26 and still the same problem

**Comment by josias-r** [comment]
The same goes for recorded customers addresses
