### ISSUE TITLE
Email Template modifications cannot be saved

### ISSUE THREAD

**Issue by desplega** [akaunting/akaunting#2279]
### Akaunting version

2.1.26

### PHP version

7.4.3

### Operating system

Ubuntu 20.04

### Steps to reproduce

Go to Settings > Email
Modify any email template
Press "Save" --> The system blocks
![2021-10-08 123858](https://user-images.githubusercontent.com/7932291/136542664-4ad51141-33c7-4d8a-9e0d-edd08af86e40.png)

### Expected result

The modified email template should be saved and the application should not block.

### Actual result

The application blocks and the modified template is not saved.

**Comment by brasileirodacosta** [comment]
I've also had the same problem from time to time. Even after opening tickets in the forum, the developer insists that there is no problem.
![Screenshot_1](https://user-images.githubusercontent.com/55510222/137638024-ad822fbb-8335-49bd-b4f2-1d6e2cd3a032.png)

**Comment by desplega** [comment]
I tested again without any action and it worked! Not clear to me the reason why (maybe related to browser cache after the update). Anyway, I close the issue.
