### ISSUE TITLE
The uninstalled App (Widget: ) still shows status installed.

### ISSUE THREAD

**Issue by kvacha13** [akaunting/akaunting#2284]
### Akaunting version

2.0.27

### PHP version

7.4

### Operating system

Ubutnu 20.04

### Steps to reproduce

1) Install the free widget "Receivables & Payables" from the app
2) Uninstall the free widget "Receivables & Payables".

### Expected result

The widget should be removed and the widget status in the app store should not say that it is still installed
![widget_akaunting](https://user-images.githubusercontent.com/8162633/136797814-ce784593-b324-4c0d-9dca-51a31c7effd9.png)
.

### Actual result

The widget is actually removed but the widget status in the app store says that it is still installed.

### Additional comments

I've tried to reinstall it again, but despite the successful installation notification, the widget does not show up at all. Repeated installation and uninstallation process multiple times but the widget still not showing and status remains "installed".  
I deceieded to upgrade the akaunting. But on the upgrade page, I got the following message: 

"Your subscription for Aged Receivables/Payables app has expired. Click here to renew it in order to update Akaunting."  

But I have never installed the "Aged Receivables/Payable" paid widget and the status on the app store also says that it is not installed. So, I am not even able to upgrade.

**Comment by cuneytsenturk** [comment]
I've test clean Akaunting. Evertign works, Please clear cache then test again.
