### ISSUE TITLE
Offline Payment Description not being displayed.

### ISSUE THREAD

**Issue by josias-r** [akaunting/akaunting#2285]
### Akaunting version

2.1.26

### PHP version

7.4.10

### Operating system

Ubuntu 20.4

### Steps to reproduce

Create an Offline Payment record and add a description and enable "Show to customer".

### Expected result

The description (bank details ie) is shown to the customer.

### Actual result

Instead only a "Confirm" button is shown with no additional details.

**Comment by cuneytsenturk** [comment]
I've created offline payment [issue](https://github.com/akaunting/module-offline-payments/issues/8)
