### ISSUE TITLE
Intall but server throws error

### ISSUE THREAD

**Issue by atswe** [akaunting/akaunting#229]
Fatal error: Unknown: Failed opening required 'C:\wamp64\www\akaunting/server.php' (include_path='.;C:\php\pear') in Unknown on line 0

plz help i have intalled but cannot run

**Comment by sebadamus** [comment]
You might post this on the https://akaunting.com/forum/category/installation-update forum to get a quicker response.  Do you meet these reqs? https://akaunting.com/docs/requirements?

How did you install? easier if you download package from https://akaunting.com/docs/download than github.

**Comment by denisdulici** [comment]
Plz, use the forum for support: https://akaunting.com/forum
