### ISSUE TITLE
permission issue in installation

### ISSUE THREAD

**Issue by GaneshKandu** [akaunting/akaunting#23]
Hi,

- 1

i am installing akaunting same way you mention here [https://akaunting.com/docs/installation](https://akaunting.com/docs/installation)
but getting blank page
i think it is permission issue. i am installing in non-suphp server
initially i gave 777 recursively for installation but its not safe  so can you mention which file and folder should be writable for web user
runs fine when i am giving 777 permission on
- storage
- bootstrap/cache

but still i cant upload user profile picture
![asdfa](https://user-images.githubusercontent.com/12833130/30805409-e4bef590-a20e-11e7-92c3-92d25321aeaa.png)

- 2

i am getting this error on php 5.6 as mention minimum requirement [here](https://github.com/akaunting/akaunting#requirements) 

production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in akaunting/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php:50

where as ```doctrine\annotations``` required php 7.1

akaunting\vendor\doctrine\annotations\composer.json
```json
    "require": {
        "php": "^7.1",
        "doctrine/lexer": "1.*"
    },
```

**Comment by denisdulici** [comment]
Hi Ganesh,

1) Please, make sure that `storage/app/uploads` folder is writable/readable by the group/public.

2) There is something strange here as all versions are as you say but I have a different one, see the following. Investigating...

![2017-09-26_0132](https://user-images.githubusercontent.com/5254835/30834476-ec49859e-a25b-11e7-83f6-d013a526fbf1.png)

Regards

**Comment by GaneshKandu** [comment]
- storage is recursively writable 
- downloaded from this link of github, its all ready have a vendor folder ( composer installed )  
![retgf](https://user-images.githubusercontent.com/12833130/30841263-3644b5a0-a299-11e7-901c-03dc0c13573e.png)

**Comment by denisdulici** [comment]
1.0.3 version has been released with this issue fixed. Can you please confirm?

**Comment by GaneshKandu** [comment]
Not Working 
```php
{{ asset($item->picture) }}"
```
```$item->picture``` is null in resources\views\auth\users\index.blade.php
getting domain name only in html
```html
<img src="http://mydomain/" class="users-image" alt="Ganesh" title="Ganesh">
```

**Comment by denisdulici** [comment]
That was not for issue 1 but 2, related with PHP 5.6 version. Can you confirm it?

As for the picture, it's not related to file/folder permissions, there is a bug and will fix soon.

**Comment by GaneshKandu** [comment]
i have tested it on php5.6 , php7.0, php7.1 .
got same error on all version .
all images are successfully uploaded but image url is not correct
![3wr4etg](https://user-images.githubusercontent.com/12833130/30952753-b533eb16-a446-11e7-9a11-2df544978204.png)

**Comment by denisdulici** [comment]
1.0.4 version solves your issue.

**Comment by GaneshKandu** [comment]
Thanks ! Working Now 👍

**Comment by GaneshKandu** [comment]
closing
