### ISSUE TITLE
Can't save invoices

### ISSUE THREAD

**Issue by feralhipichik** [akaunting/akaunting#2307]
### Akaunting version

2.1.27

### PHP version

7.4.25

### Operating system

linux

### Steps to reproduce

Create an invoice then try to save it.

### Expected result

Invoice saved

### Actual result

Error message

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'contact_country' in 'field list' (SQL: update `6rl_documents` set `issued_at` = 2021-10-28 10:50:55, `due_at` = 2021-11-25 10:50:55, `contact_country` = ?, `contact_state` = ?, `contact_zip_code` = ?, `contact_city` = ?, `6rl_documents`.`updated_at` = 2021-11-13 10:50:55 where `id` = 39)

### Additional comments

This has just started after updating to the latest version

**Comment by cuneytsenturk** [comment]
This issue solved this [PR](https://github.com/akaunting/akaunting/pull/2313)

**Comment by feralhipichik** [comment]
Hi, I have tried uploading the new files but no joy. I've also tried updating to 2.1.28 bur get an "not able to update core" message. Any ideas?

**Comment by NajibNour** [comment]
@cuneytsenturk Not sure how this is solved. This issue is still present with my instance as well. Ive even tried downgrading my docker container to 2.1.27 and manually updating trough the url to 2.1.28 and the issue is still present.

**Comment by NajibNour** [comment]
@cuneytsenturk Luckly i had a backup,
Solution I had found was to go back to 2.1.21, going into gui and updating to 2.1.28 then changing docker container to 2.1.28. Seems like the fix is within the update only. it does not check this on container boot.
