### ISSUE TITLE
Cannot import Bills

### ISSUE THREAD

**Issue by cver** [akaunting/akaunting#2308]
### Akaunting version

2.1.27

### PHP version

7.4.25

### Operating system

Ubuntu 20.04

### Steps to reproduce

1. Import Items
2. Import Vendors
3. Import Bills

### Expected result

Import success

### Actual result

Import failed with error message "Undefined variable: item"

### Additional comments

I ​think issue came from [this commit](https://github.com/akaunting/akaunting/commit/a40db8195d9844674b08ba3d429e1db561e09f8a)
Looks like the exception has been thrown by the following line
```php
if (Str::contains($item['quantity'], ['.', ','])) {
```
(app/Http/Requests/Document/DocumentItem.php:19)

**Comment by cuneytsenturk** [comment]
This issue solved this [PR](https://github.com/akaunting/akaunting/pull/2313)
