### ISSUE TITLE
After installation wizard issue.

### ISSUE THREAD

**Issue by oxiyazilim** [akaunting/akaunting#2309]
### Akaunting version

2.1.20

### PHP version

7.3

### Operating system

macos

### Steps to reproduce

Wizard form not opening after installation

### Expected result

wizard must be open

### Actual result

wizard form not open without wizard.js

**Comment by cuneytsenturk** [comment]
You should run npm

`npm install ; npm run prod`

Wizard page use vue SPA so then if you can not run npm it can not see.
