### ISSUE TITLE
Getting error after Update to 2.1.27

### ISSUE THREAD

**Issue by kvacha13** [akaunting/akaunting#2310]
### Akaunting version

2.1.27

### PHP version

7.4

### Operating system

Ubutnu 20.04

### Steps to reproduce

Upgrade from 2.1.26 to 2.1.27

### Expected result

During the installation got some errors and when the upgrade had finished could not add any invoices.

### Actual result

Getting follwoing error
![akaunting_err](https://user-images.githubusercontent.com/8162633/141767156-c8a67a47-4f9d-425d-a5ee-097439bfc348.png)

### Additional comments

Do you change database structure with every upgrade?  The error shows that there have been added multiple fields in the table "documents" that were missing in the previous version (2.1.26) database. The same happened in the past when upgrading from the old version to the newer one (cannot recall the exact versions) and I had to add fields to tables to match the databases.

Am I missing something? Maybe there is some procedure to upgrade from old databases to new ones? Or some instruction on how to match databases (old structure to new);

**Comment by rihards-simanovics** [comment]
Same issue here.

**Comment by rihards-simanovics** [comment]
Will have to roll back as I got some invoices that need to be generated tomorrow.

**Comment by cuneytsenturk** [comment]
this [migration](https://github.com/akaunting/akaunting/blob/master/database/migrations/2021_09_10_000000_core_v2127.php) added document columns so then if you use auto-update this migration run.
