### ISSUE TITLE
Impossible to update to latest Akaunting version

### ISSUE THREAD

**Issue by josias-r** [akaunting/akaunting#2332]
### Akaunting version

2.1.27

### PHP version

7.4.3

### Operating system

Ubuntu 20.4

### Steps to reproduce

Update from version 2.1.27 to 2.1.28 through the Web Interface OR php artisan.

### Expected result

The update should run.

### Actual result

Getting an error.
CLI Error:
`php artisan update core 1 --verbose`:
```
Not able to get the latest version of core!
```
or
`php artisan updat:all 1 --verbose`:
```
Starting update...
Updating core...
The command php artisan update core 1 failed.<br /><br />Exit Code: 1(General error)<br /><br />Working directory: /var/www/html<br /><br />Output:<br />================<br />Not able to get the latest version of core!<br /><br /><br />Error Output:<br />================<br />
Not able to update core!
```

Web Interface error (in german, translates to smth like "Unable to download core")
<img width="1301" alt="Screenshot 2021-12-06 at 13 28 43" src="https://user-images.githubusercontent.com/11424820/144846200-1fe40c42-e611-4972-a5be-54d0dfbed66a.png">

### Additional comments

I traced the `php artisan update core 1 --verbose` CLI command to where the error is thrown in the application.

https://github.com/akaunting/akaunting/blob/afeef58f80ca48b7881d9f6453a3483541a6802a/app/Console/Commands/Update.php#L59

`getNewVersion()` returns `false`, because the Versions utility checks for a `data` key on the versions object.
see: https://github.com/akaunting/akaunting/blob/afeef58f80ca48b7881d9f6453a3483541a6802a/app/Utilities/Versions.php#L58

The actual array is:

```
Array
(
    [core] => 2.1.28
    [bc21] => 2.0.0
    [my-private-module] => 1.0.0
    [offline-payments] => 2.0.1
    [paypal-standard] => 2.0.0
)
```
And as you can see there is no `data` property for `core`.
But the [file](https://github.com/akaunting/akaunting/blob/afeef58f80ca48b7881d9f6453a3483541a6802a/app/Utilities/Versions.php#L58) checks for `empty($versions['core']->data)`

### Relevant log output

I checked PHP, Apache and laravel logs, without success.

**Comment by pavel-mironchik** [comment]
I see the same error message in a browser on 2 Digital Ocean servers and in my local testing environment. Was thinking that this is a connectivity (latency) problem, though.

**Comment by josias-r** [comment]
I'm also using a DigitalOcean droplet, but I'm pretty sure after investigating that there is more to it then connectivity (latency) 😄

**Comment by CFusionMM** [comment]
getting same error trying to upgrade from v1.3.17 -> 2.0.6

**Comment by feralhipichik** [comment]
I'm getting the same error trying to update from version 2.1.27 to 2.1.28

**Comment by kvacha13** [comment]
Same problem here. Running version 2.1.27 on Ubuntu 20.04.3 and trying to update to 2.1.28. Getting error: Not able to download core. 
![image](https://user-images.githubusercontent.com/8162633/145585358-eb66d35a-8a2e-4095-9c20-b870eee41270.png)

**Comment by cuneytsenturk** [comment]
Please test again. This update issue solved.

**Comment by josias-r** [comment]
Awesome, worked!
Had a 500 error, because of permission errors on a cached file, so the app didnt load anymore. dunno where that came from. So I ran `php artisan cache:clear` inside `/var/www/html` and after that I could run the update

**Comment by kvacha13** [comment]
Confirming here. Updated Successfully. Thanks.

**Comment by josias-r** [comment]
@cuneytsenturk Seems like the latest version has the same problem again. Should I open a new issue?

**Comment by barthmania** [comment]
> @cuneytsenturk Seems like the latest version has the same problem again. Should I open a new issue?

Same issue for me to update core from 2.1.31 to 2.1.33.

App updates doesn't work either.

**Comment by nickian** [comment]
Updates are not working for me as well.

```
root@localhost:.../www# php artisan cache:clear
Application cache cleared!
root@localhost:.../www# sudo -u www-data php artisan update:all
Starting update...
Updating core...
The command php artisan update core 1 failed.<br /><br />Exit Code: 1(General error)<br /><br />Working directory: /my/dir/www<br /><br />Output:<br />================<br />Not able to get the latest version of core!<br /><br /><br />Error Output:<br />================<br />
Not able to update core!
```

**Comment by josias-r** [comment]
Yup its the same problem from the original issue I had a few versions back.
> The actual array is: ...

> But the [file](https://github.com/akaunting/akaunting/blob/afeef58f80ca48b7881d9f6453a3483541a6802a/app/Utilities/Versions.php#L58) checks for empty($versions['core']->data)
