### ISSUE TITLE
Cannot search by invoice amount

### ISSUE THREAD

**Issue by wayneoutthere** [akaunting/akaunting#2343]
### Akaunting version

2.1.25

### PHP version

7.4.10

### Operating system

ubuntu 20.04

### Steps to reproduce

1. go to 'sales'
2. go to 'invoices'
3. search for a dollar amount of an invoice that you have entered 
4. observe that absolutely no results come up!

### Expected result

One of the most important and useful features of an accounting software suite is the ability to look at your bank statement, see an amount, go to your software, and search that amount show up.  I expected to see immediately any invoice (or bill) for that amount to show up in the search result.  You can search for: status, due date, invoice date, and many other useful things but you cannot search the most useful thing: invoice amount

### Actual result

blank search results

### Additional comments

To me this is the only remaining item that prevents me from very positively promoting Akaunting to everyone i know.  With this bug, it is very difficult to recommend because it is very very painful to search for an invoice by amount . The current workaround is this:  

1. sort list of all invoices by 'amount' column
2. go to bottom and make 100 items per page appear
3. use the navigation arrows to scroll through the pages until you find the amount you are looking for

Otherwise, best every opensource accounting software I've ever seen! Great great work

**Comment by denisdulici** [comment]
Use the forum for support, feature requests, proposals, new versions, help etc.
