### ISSUE TITLE
allow assigning categories to bills and invoices

### ISSUE THREAD

**Issue by edgimar** [akaunting/akaunting#235]
In order to properly track expenses and income, it should be possible to assign the same categories to a bill that we can assign to a payment.  Then the reports can accurately reflect the income and expenses per category.  I'm using categories like budget line-items (e.g. "equipment", "travel", "office rent", etc.).

**Comment by denisdulici** [comment]
Thanks @edgimar . Feel free to use our forum for feature requests. https://akaunting.com/forum/category/ideas

**Comment by edgimar** [comment]
Sure- no problem -- I wasn't aware of the forum.  Interestingly the most recent thread is about this very topic!
