### ISSUE TITLE
[UI Ambiguity] Trying to upload a new Logo; apparently, mine has the wrong dimensions, but what are the correct dimensions???

### ISSUE THREAD

**Issue by rihards-simanovics** [akaunting/akaunting#2350]
### Akaunting version

2.1.28

### PHP version

Plesk PHP support (PHP version 7.4.27, run PHP as CGI application served by Apache)

### Operating system

Ubuntu 20.04

### Steps to reproduce

Change a logo of a company through the settings page.
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/52106095/147374051-1aac92e9-68f2-4678-9a1c-64ecb21ba583.png">

### Expected result

Suppose I do not have time to read the documentation about the feature that should be explained above the input field. In such a case, I should get an error message with the exact dimensions the image must be to get successfully uploaded.

I.e. "the image you are trying to upload is too large, please make sure that the dimensions of the image do not exceed `XX.XX px` and `YY.YY px`."

### Actual result

Go and read the source code! Have fun!

### Additional comments

Guys, I know that this is a large project and an open-source one, so you expect us as users to bring feedback, but these UI issues should be addressed during UI Testing (or, as we call it, UIT).

Here is what I do with my team when creating a new release. We have an excel spreadsheet with every single feature that the software has a UI interface for and break it into groups (depending on how many people are available). The new features added with the release are appended to the spreadsheet with a special note (NEW RELEASE). Once backend testing is complete by the developer (meaning DB Migrations and language tests), it gets released to the Front-end team. They go through each feature one by one making notes as they go along if anything is not working right or is ambiguous. I will now go through the source code, check the requirements, and create a PR with a label fix. Though that is, if I have time, If not, I will update this issue with the fix.

**Comment by rihards-simanovics** [comment]
Here is the fix, though someone may want to change the wording and get it translated.
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/52106095/147374227-5256612b-2bbb-4429-988e-977edb5cceac.png">

**Comment by rihards-simanovics** [comment]
Since to fully resolve this, a translation to other languages will be required; I will leave it here. but if anyone is free to fix the issue, here is the link and exact params to use:
``` php
'dimensions' => 'The :attribute you are trying to upload is too large. Please make sure that the dimensions do not exceed :max_width px width and :max_height px height.',
```
https://github.com/akaunting/akaunting/blob/6fa079d8b40806d801c4b1501cafb8f55f8cb6ad/resources/lang/en-GB/validation.php#L41

**Comment by denisdulici** [comment]
Feel free to send a PR.
