### ISSUE TITLE
Cannot import payments in bulk

### ISSUE THREAD

**Issue by Ulferno** [akaunting/akaunting#2351]
### Akaunting version

2.1.28

### PHP version

7.4.3

### Operating system

Ubuntu 20.04.3 LTS

### Steps to reproduce

1. Go to Purchases -> Payments -> Import
2. Download the sample
3. Fill in some data & save the file
4. Upload the file and click "Import"

### Expected result

The payments should be imported and added into the system.

### Actual result

It responds with "Expected response code 220 but got an empty response" and the data is not imported.

![image](https://user-images.githubusercontent.com/36534987/147513461-c1beb28d-81c2-4340-a488-2158432077e2.png)

### Additional comments

Tried adding my own data in, tried just uploading the sample itself unmodified. Same results.

**Comment by cuneytsenturk** [comment]
You should check the fill data. I've tested it, but ı can not see the same issue.
