### ISSUE TITLE
[bug] On Dashboard selecting 'Previous Year' only selects up to December 30th, not the 31st.

### ISSUE THREAD

**Issue by ScionOfDesign** [akaunting/akaunting#2355]
### Akaunting version

2.1.28

### PHP version

Whatever is in the docker image.

### Operating system

Docker on Linux Mint 20.2

### Steps to reproduce

Go to the Dashboard and select 'Previous Year'. It selects a date range from January 1st to December 30th. This leaves an extra day at the end.
![image](https://user-images.githubusercontent.com/8867456/149078278-ed498cb8-2b19-4bc8-94e0-e1cc7e541a80.png)

### Expected result

Selecting the range of "Previous Year" should encompass the _entire_ year, up to December 31st.

### Actual result

A range only up to December 30th is selected.

**Comment by cuneytsenturk** [comment]
I've tested clean akaunting. Everything okey. So then ı am closing this issue.

**Comment by ScionOfDesign** [comment]
> I've tested clean akaunting. Everything okey. So then ı am closing this issue.

I also tested on a clean Akaunting install via docker. I only set the location to United States. I can record a video of the process if you want.

**Comment by ScionOfDesign** [comment]
This video shows how to replicate the bug on a fresh instance, as well as the bug https://github.com/akaunting/akaunting/issues/2260.
https://user-images.githubusercontent.com/8867456/149323438-7a649646-df22-4e43-927f-644f22f1f47d.mp4

Please re-open this issue or have me make a new one.

**Comment by ScionOfDesign** [comment]
@cuneytsenturk Please check out the video I posted to see exactly how to replicate this issue as well as https://github.com/akaunting/akaunting/issues/2260.
