### ISSUE TITLE
Support Icon is hidden on mobile versions 

### ISSUE THREAD

**Issue by leonardofilhogm** [akaunting/akaunting#2363]
### Akaunting version

2.1.30

### PHP version

7.4.10

### Operating system

Ubuntu 20.04

### Steps to reproduce

Open Akaunting com a mobile device. 
Look on the topbar. 

### Expected result

The same icon of support should appear on mobile. 

### Actual result

The icon is hidden. 

### Additional comments

Checked on both self-hosted installation and cloud. 
![image](https://user-images.githubusercontent.com/16747637/151068082-c67c4ee6-186b-4793-a9cc-be38badf4e76.png)
![image](https://user-images.githubusercontent.com/16747637/151068165-31a4ea61-b132-42c5-bec4-57017412e9cf.png)

**Comment by cuneytsenturk** [comment]
Thank your feed back
