### ISSUE TITLE
How can I change data format on insert

### ISSUE THREAD

**Issue by sarwarahmed07** [akaunting/akaunting#2376]
### Akaunting version

2.1.20

### PHP version

7.4

### Operating system

Windows 10

### Steps to reproduce

After creating a new module, when I use issued_at as a "Delivery Challan" I am getting  `The issued at does not match the format Y-m-d H:i:s.`

Are there any settings or some configuration setup for the date-time format when we store? 

### Expected result

After submitting the form data should be stored

### Actual result

Please check the screenshot: https://prnt.sc/IhcJPc27v9yA

**Comment by cuneytsenturk** [comment]
You can read documentation for Akaunring core. How to change date format => https://akaunting.com/docs/user-manual/settings/localisation

**Comment by sarwarahmed07** [comment]
whatever date format I choose I am getting `The issued at does not match the format Y-m-d H:i:s` .  I have purchased the sales-purchase module. With the same settings, insert is working fine but not with the my custom module. Do I need to pass any datetime settings on insert?
