### ISSUE TITLE
Erro instalação

### ISSUE THREAD

**Issue by demasnet** [akaunting/akaunting#2392]
### Akaunting version

2.1.35

### PHP version

7.4.28

### Operating system

xampp/localhost

### Steps to reproduce

não consigo instalar, após a seleção de idioma, e clicar em next, recebo sempre a seguinte mensagem:

{"redirect":"http:\/\/localhost\/akaunting\/install\/database"}

### Expected result

s

### Actual result

s

### Additional comments

s

### Relevant log output

```shell
s
```

**Comment by dadeke** [comment]
Hello!

I can speak Portuguese. 🙂

#

Olá @demasnet 

Então deve existir algum log ou alguma mensagem de erro com mais informações.

Foi criado algum arquivo em `[diretório da sua instalação Akaunting]/storage/logs/*`? Qual é o conteúdo do log?

Caso não esteja criando nenhum arquivo de log, talvez esteja exibindo alguma mensagem de erro no inspector do seu navegador. É preciso procurar.

Sem postar aqui algum log ou alguma mensagem com mais detalhes fica muito difícil para alguém da comunidade ajudar a solucionar seu problema.

Cumprimentos

**Comment by felipelm3g** [comment]
Estou com erro na instalação, não passa do Admin, fica carregando eternamente

**Comment by leonardofilhogm** [comment]
Olá, esse erro é porque o o build do npm não rodou, e aí o Wizard não consegue redirecionar. 
Você pode logar no ssh do seu servidor na raiz do projeto e rodar o comando "npm run dev". 
Isso vai buildar os arquivos js do webpack e provavelmente o erro vai desaparecer.

**Comment by dadeke** [comment]
> Estou com erro na instalação, não passa do Admin, fica carregando eternamente

Conforme o @leonardofilhogm explicou utilize a _Release_ https://github.com/akaunting/akaunting/releases/tag/2.1.35 que já foi realizada a _build_ dos js do webpack e está pronto para instalação.

Agora caso queira instalar a partir do clone deste repositório vai precisar utilizar o **npm**

**Comment by felipelm3g** [comment]
> > Estou com erro na instalação, não passa do Admin, fica carregando eternamente
> 
> Conforme o @leonardofilhogm explicou utilize a _Release_ https://github.com/akaunting/akaunting/releases/tag/2.1.35 que já foi realizada a _build_ dos js do webpack e está pronto para instalação.
> 
> Agora caso queira instalar a partir do clone deste repositório vai precisar utilizar o **npm**

Acabei de tentar, mesmo erro ainda.

**Comment by dadeke** [comment]
> 
> Acabei de tentar, mesmo erro ainda.

Acho que não posso ajudá-lo com a pequena quantidade de detalhes que você forneceu.

Algumas dicas (talvez óbvias): Tente instalar em uma VPS com um Linux. Por exemplo, instale no Ubuntu ou em qualquer outro tipo de servidor. 🙂

**Comment by leonardofilhogm** [comment]
@felipelm3g Você seguiu a recomendação do @dadeke ou a minha? 
Se pegou os arquivos buildados e você continua com o problema, limpa o cache e tenta novamente. 
abre o inspector do browser e da uma olhada no console pra ver quais erros ele tá acusando?

**Comment by denisdulici** [comment]
Feel free to use the forum for non-English support https://akaunting.com/forum/category/brazilian
