### ISSUE TITLE
Can't update to the latest version

### ISSUE THREAD

**Issue by ikhoury** [akaunting/akaunting#2393]
### Akaunting version

2.1.31

### PHP version

7.4.3

### Operating system

Ubuntu 20.04.4 LTS

### Steps to reproduce

Attempt to update Akaunting to the latest version through the UI.

### Expected result

Progress bar completes and latest version is installed.

### Actual result

Progress bar is stuck at 0%. The following XHR request is failing:
`POST https://<my-host>/1/install/updates/steps` with body:

```json
{"name":"Akaunting 2.1.35","version":{}}
```

_Response Status_: 422
_Response Body_: `{"message":"The given data was invalid.","errors":{"version":["The version format is invalid."]}}`

**Comment by sebadamus** [comment]
Hi friend, you should post this in the community forum. Here is more for posting about bugs, this looks more like a server problem (permission folders, .env)  I would recommend you post it in the forum, enable the debug mode in .env and also php to show all errors.  Also you can update coping the new version over the old, without loosing the .env config.
