### ISSUE TITLE
Paid Bills should not be allowed to edit...

### ISSUE THREAD

**Issue by sebadamus** [akaunting/akaunting#240]
If you add a Bill and then you add its Payments to complete the Bill... then its status change to Paid, thats good :-)

But then if you edit the Bill and change items/values/taxes (in my test I change Bill to a minor value than what I paid), and saved again... it will let you save and Bill status will remain as "Paid"

Maybe the right way would be that if status is "Paid", you cant edit the Bill unless you first delete the payments, so status go back to Draft?

**Comment by denisdulici** [comment]
What happens if you're going to change just the customer address or anything else not related to the amount?
