### ISSUE TITLE
SQLSTATE[HY000]: General error: 1364 Field 'password' doesn't have a default value

### ISSUE THREAD

**Issue by dadeke** [akaunting/akaunting#2407]
### Akaunting version

3.0.0

### PHP version

8.1.6

### Operating system

Rocky Linux 8

### Steps to reproduce

Edit a customer > Check **Invite to Client Portal** > **Save**

### Expected result

Edited customer

### Actual result

![akaunting-edit-customer](https://user-images.githubusercontent.com/6050573/171486219-bb96ce13-d941-4ead-ac5f-5f4d063f0423.png)

### Additional comments

`php artisan migrate:status`

![screenshot-migrate-status](https://user-images.githubusercontent.com/6050573/171485931-5c875665-304d-4ad4-b663-25e6015668f8.png)

Can I set a default value here?

https://github.com/akaunting/akaunting/blob/506e3ec381ef6fffcd3396c0efbfb153220c90df/database/migrations/2017_09_14_000000_core_v1.php#L505

### Relevant log output

```shell
`SQLSTATE[HY000]: General error: 1364 Field 'password' doesn't have a default value`
```

**Comment by cuneytsenturk** [comment]
Thanks for feed back. @sevannerse  solved this issue.

**Comment by ratanclinics** [comment]
SQLSTATE[HY000]: General error: 1364 Field 'user_type' doesn't have a default value (Connection: mysql, SQL: insert into `vpn_user_roles` (`role_id`, `user_id`) values (2, 3))
