### ISSUE TITLE
Some translations in PDF downloads are not encoded

### ISSUE THREAD

**Issue by Markoftw** [akaunting/akaunting#2411]
### Akaunting version

3.0.0

### PHP version

8.0.19

### Operating system

Ubuntu 20.04

### Steps to reproduce

1. Switch language to one that uses Č Š Ž, for example, Croatian and Slovenian
2. Create a dummy invoice
3. Download the PDF of the invoice
4. Open the downloaded file

### Expected result

To show correctly encoded characters.

e.g. č š ž

### Actual result

![image](https://user-images.githubusercontent.com/1616694/171605331-29cce338-31e3-456e-a43c-d3e07b39ae48.png)

### Additional comments

It works fine in the preview of the web page in the invoice.

![image](https://user-images.githubusercontent.com/1616694/171605045-c1ec2aba-9863-4d10-b786-71106fc5b907.png)

**Comment by brkcvn** [comment]
I hope, this issue fix after this development. You ca test again. https://github.com/akaunting/akaunting/commit/c5e91273657a354591119f6faf05a107c80f6b44
