### ISSUE TITLE
Updating to 3.0 Internal Server Error

### ISSUE THREAD

**Issue by nickian** [akaunting/akaunting#2417]
### Akaunting version

2.1.35

### PHP version

8.1

### Operating system

Ubuntu 20.04

### Steps to reproduce

Disabled the unsupported apps, then tried to update in the browser. Then I tried running `php artisan update:all` and `php artisan update:terminal`

### Expected result

That it would update to 3.0.

### Actual result

Login screen shows up, but after logging in I get the internal server error page.

### Relevant log output

Nothing is showing in the nginx log. On the CLI, I get this error when trying to update:

```
php artisan update:all
Starting update...
Updating core...
The command php artisan update core 1 failed.<br /><br />Exit Code: 1(General error)<br /><br />Working directory: /path/to/akaunting<br /><br />Output:<br />================<br />Not able to get the latest version of core!<br /><br /><br />Error Output:<br />================<br />
Not able to update core!
```

**Comment by rihards-simanovics** [comment]
Same here, had to do a clean install. Also, some DB Migrations were missing when I tried to do artisan migrate:refresh, had to roll back the update and restore the backup.

**Comment by denisdulici** [comment]
Not able to reproduce such an issue. Feel free to use the forum for further help.

**Comment by nickian** [comment]
It may have been related to having PHP 8.1 set for nginx and my command line PHP was set to 7.4. I restored my backup, then did this:

```
sudo update-alternatives --set php /usr/bin/php8.1
```

I also updated composer. Then everything worked!
