### ISSUE TITLE
Update to v 3 throws SQL Error

### ISSUE THREAD

**Issue by safarovitch** [akaunting/akaunting#2418]
### Akaunting version

3.0

### PHP version

8

### Operating system

Ubuntu 20.4

### Steps to reproduce

Updating through UI broke the system throwing SQL error:

**SQLSTATE[42S22]:` Column not found: 1054 Unknown column 'parent_id' in 'where clause' (SQL: select `id` from `aer_categories` where `aer_categories`.`type` = other and `aer_categories`.`deleted_at` is null and `aer_categories`.`company_id` = 1 and `parent_id` is null) (View: /home/bumeraft/domains/bumeraft.com/public_html/subdomains/acc/resources/views/common/dashboards/show.blade.php**

### Expected result

System update

### Actual result

**SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'where clause' (SQL: select `id` from `aer_categories` where `aer_categories`.`type` = other and `aer_categories`.`deleted_at` is null and `aer_categories`.`company_id` = 1 and `parent_id` is null) (View: /home/bumeraft/domains/bumeraft.com/public_html/subdomains/acc/resources/views/common/dashboards/show.blade.php)**

**Comment by sebadamus** [comment]
Same here! also post it in Community Forum https://akaunting.com/forum/discussion/installation-update/updating-from-2136-to-30-parent-id-error

What I noticed is that there is no 2.1.36 version to download from github, but if you go to update in akaunting selfhosted config menu it tells to update from 2.1.35 to 2.1.36 (which is the only pre 3.0 version) that update in my case broke it and after that I get the 'parent_id' error opening v3.

**Comment by denisdulici** [comment]
Not able to reproduce such an issue. Feel free to use the forum for further help.

**Comment by seth586** [comment]
Same error when creating a new user (email set to log, I cant seem to get SMTP working either), see below

FreeBSD 13.1
PHP 8.1
MariaDB 10.6

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_by' in 'field list' (Connection: mysql, SQL: insert into `kgx_user_invitations` (`user_id`, `token`, `created_by`, `created_from`, `updated_at`, `created_at`) values (4, f6617bf1-f6b9-4a02-bab0-68682b916201, 1, core::ui, 2023-08-11 18:10:01, 2023-08-11 18:10:01))
```
