### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by sheesetfs** [akaunting/akaunting#2500]
### Akaunting version

3.0.3

### PHP version

8.0.20

### Operating system

Ubuntu 20.04

### Steps to reproduce

Run the install commands as per readme; commands run:
```
git clone https://github.com/akaunting/akaunting.git
cd akaunting
composer install
```

### Expected result

Application dependencies are installed

### Actual result

Getting a bunch of database related errors that start from
```
php artisan ide-helper:models --nowrite
Exception: SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost'
```

### Additional comments

got  another error while trying to run `php artisan install --db-name="akaunting" --db-username="root" --db-password="pass" --admin-email="admin@company.com" --admin-password="123456" `

error output
```
user@server:/home/user/akaunting$ php artisan install --db-name="sql_akaunting" --db-username="sql_akaunting" --db-password="password" --admin-email="admin@email.com" --admin-password="password"
Setting locale en-GB
Creating database tables
Connecting to database sql_akaunting_tf@localhost:3306

   Illuminate\Database\QueryException

  SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '#sql-83c_1b4e6' (SQL: alter table `oxq_media` add constraint `original_media_id` foreign key (`original_media_id`) references `oxq_media` (`id`) on delete set null)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:759
    755▕         // If an exception occurs when attempting to run a query, we'll format the error
    756▕         // message to include the bindings with SQL, which will make this exception a
    757▕         // lot more helpful to the developer instead of just the database's errors.
    758▕         catch (Exception $e) {
  ➜ 759▕             throw new QueryException(
    760▕                 $query, $this->prepareBindings($bindings), $e
    761▕             );
    762▕         }
    763▕     }

      +34 vendor frames
  35  app/Utilities/Installer.php:161
      Illuminate\Support\Facades\Facade::__callStatic()

  36  app/Console/Commands/Install.php:193
      App\Utilities\Installer::createDbTables()
```

### Relevant log output

```shell
Log posted on Pastebin: https://pastebin.com/dx2dcBuG
as the body is too long (maximum is 65536 characters).
```

**Comment by patimio66** [comment]
Same issue.
`Setting locale en-GB
Creating database tables
Connecting to database dbexample@localhost:3306

   Illuminate\Database\QueryException 

  SQLSTATE[HY000]: General error: 1826 Duplicate foreign key constraint name 'original_media_id' (SQL: alter table `h2u_media` add constraint `original_media_id` foreign key (`original_media_id`) references `h2u_media` (`id`) on delete set null)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:759
    755▕         // If an exception occurs when attempting to run a query, we'll format the error
    756▕         // message to include the bindings with SQL, which will make this exception a
    757▕         // lot more helpful to the developer instead of just the database's errors.
    758▕         catch (Exception $e) {
  ➜ 759▕             throw new QueryException(
    760▕                 $query, $this->prepareBindings($bindings), $e
    761▕             );
    762▕         }
    763▕     }

      +34 vendor frames 
  35  app/Utilities/Installer.php:161
      Illuminate\Support\Facades\Facade::__callStatic()

  36  app/Console/Commands/Install.php:193
      App\Utilities\Installer::createDbTables()
`

**Comment by patimio66** [comment]
Same issue:

```
Setting locale en-GB
Creating database tables
Connecting to database dbexample@localhost:3306

   Illuminate\Database\QueryException 

  SQLSTATE[HY000]: General error: 1826 Duplicate foreign key constraint name 'original_media_id' (SQL: alter table `h2u_media` add constraint `original_media_id` foreign key (`original_media_id`) references `h2u_media` (`id`) on delete set null)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:759
    755▕         // If an exception occurs when attempting to run a query, we'll format the error
    756▕         // message to include the bindings with SQL, which will make this exception a
    757▕         // lot more helpful to the developer instead of just the database's errors.
    758▕         catch (Exception $e) {
  ➜ 759▕             throw new QueryException(
    760▕                 $query, $this->prepareBindings($bindings), $e
    761▕             );
    762▕         }
    763▕     }

      +34 vendor frames 
  35  app/Utilities/Installer.php:161
      Illuminate\Support\Facades\Facade::__callStatic()

  36  app/Console/Commands/Install.php:193
      App\Utilities\Installer::createDbTables()

```

**Comment by chongkan** [comment]
I managed to advance till I get a UI broken screen but no PHP errors: 

$ php artisan db:wipe
$ php artisan install --db-name="akaunting" --db-username="root" --db-password="pass" --admin-email="admin@company.com" --admin-password="123456" 

It seems to be lacking the UI files but getting a node error now.

**Comment by cuneytsenturk** [comment]
Please read how to install akaunting. 


## Installation

* Install [Composer](https://getcomposer.org/download) and [Npm](https://nodejs.org/en/download)
* Clone the repository: `git clone https://github.com/akaunting/akaunting.git`
* Install dependencies: `composer install ; npm install ; npm run dev`
* Install Akaunting:

```bash
php artisan install --db-name="akaunting" --db-username="root" --db-password="pass" --admin-email="admin@company.com" --admin-password="123456"
```

**Comment by yasinelabe** [comment]
> Please read how to install akaunting.
> 
> ## Installation
> * Install [Composer](https://getcomposer.org/download) and [Npm](https://nodejs.org/en/download)
> * Clone the repository: `git clone https://github.com/akaunting/akaunting.git`
> * Install dependencies: `composer install ; npm install ; npm run dev`
> * Install Akaunting:
> 
> ```shell
> php artisan install --db-name="akaunting" --db-username="root" --db-password="pass" --admin-email="admin@company.com" --admin-password="123456"
> ```

I did all of these steps and passed some challenges but its giving me a broken UI and also the public/index.php is missing
I had to copy one from the Laravel repo.

**Comment by yasinelabe** [comment]
> I managed to advance till I get a UI broken screen but no PHP errors:
> 
> $ php artisan db:wipe $ php artisan install --db-name="akaunting" --db-username="root" --db-password="pass" --admin-email="[admin@company.com](mailto:admin@company.com)" --admin-password="123456" --db-host="localhost"
> 
> It seems to be lacking the UI files, troubleshooting the npm UI atm.

have you still figured out why it's given us the broke UI?

**Comment by sebadamus** [comment]
There might be a 'forge'@'localhost' somewhere the config when creating the project, but no clue in the documentation about it... you might have to research some before getit working... it has been this way since the begining, dont expect good install documentation, its for medium/expert composer/laravel guys.  Will try to find a solution and post back.
