### ISSUE TITLE
Configurable invoice, email and subject

### ISSUE THREAD

**Issue by ChipwizBen** [akaunting/akaunting#251]
As per: https://akaunting.com/forum/discussion/general/invoice-email-to-customer

The subject is just 'Invoice' which is a great way to get the email caught in a spam filter. Is this / can this be configurable? Possibly even 'Invoice from <Company>'?

Secondly, the line of text in the email doesn't make sense:
"You are receiving this email because you have an upcoming $57.50 invoice to <customer name> customer."

Why would a customer receive an email that says they owe money to themselves?
 

Thirdly, the PDF is out of shape. All the tables are messed up and out of line or overlapping each other. The invoice is also 2 pages long while the text and boxes only span for half of the first page. Interestingly, the format when printing the PDF is perfectly OK.
 

And finally, when you click the "Pay Now" button in the email, it takes you to the login page for Akaunting. This customer doesn't have an account on the system that they're able to login to, and there doesn't appear to be a way to:    

- Change the email format to make it clearer
- Add payment instructions to the invoice

**Comment by denisdulici** [comment]
As said in forum, the invoice email is going to be replaced by the Email Templates feature in the next version.

**Comment by Marcel40625** [comment]
any updates?

**Comment by quangbahoa** [comment]
+1
