### ISSUE TITLE
Customer Statement 500 error

### ISSUE THREAD

**Issue by jaiume** [akaunting/akaunting#2517]
### Akaunting version

3.0.3

### PHP version

8.1

### Operating system

Debian 10

### Steps to reproduce

Click on Sales | Customers
Select a customer
Click on Customer Statement

### Expected result

Customer statement is produced

### Actual result

500 Server Error

**Comment by cuneytsenturk** [comment]
@jaiume You can use [ticket system](https://akaunting.com/tickets).
