### ISSUE TITLE
UX for wrong permission on new installation is lacking

### ISSUE THREAD

**Issue by Geod24** [akaunting/akaunting#2524]
### Akaunting version

v3.0.3

### PHP version

Irrelevant but v8.1.0

### Operating system

Irrelevant but v3.0.3

### Steps to reproduce

Configure a server to run as `www-data` or any non-root user, download the `zip` and extract it as `root`.
Files will be owned by `root` and things will error out in non-obvious ways. In addition to that permission problem, running `php artisan install` as `root` can lead to similar problems.

### Expected result

As this is likely to be a common error, a nicer error message would be good.

### Actual result

Currently one has to dig in the log and understand why there is a permission error.

**Comment by denisdulici** [comment]
It's related to your server setup, out of the scope of the app.
