### ISSUE TITLE
Unable to individually name invoices

### ISSUE THREAD

**Issue by Geod24** [akaunting/akaunting#2525]
### Akaunting version

v3.0.3

### PHP version

v8.1.0

### Operating system

Ubuntu 22.04.0 

### Steps to reproduce

Go to Sales -> Invoice, then create two separate invoices.
Then go back to the first one and change the title, e.g.:
![image](https://user-images.githubusercontent.com/2180215/177961353-1c66ceeb-04be-4c9d-928a-443d75545391.png)

It will change the title on all invoices.

### Expected result

I should be able to name invoices individually. Some invoices are for a given month, some are for expenses, etc... Controlling the individual name is pretty important.

### Actual result

The "Title" being under company means that changing one title affects all titles.

**Comment by mwa85** [comment]
@novag have been looking at this and made a pull-request #2877 but there was something needed from the core developers so believe that it has been backlog - I hope so as I also would be using this feature.

**Comment by cuneytsenturk** [comment]
This PR [#2877](https://github.com/akaunting/akaunting/pull/2877) merge it and published new version please waiting 3.0.17 version then update it.
