### ISSUE TITLE
History section in invoices does not reflect all changes

### ISSUE THREAD

**Issue by ChipwizBen** [akaunting/akaunting#253]
As per: https://akaunting.com/forum/discussion/general/invoice-email-to-customer
 
I was able to edit an invoice after a payment was made and it didn't warn me about it. Not a massive deal, except that the edit doesn't show up at all in the "Histories" section at the bottom. I believe Histories should contain all invoice actions, including:

-  Creation date and time (partially done)
-  Partial payments (done)
-  Edits, and ideally what was edited
-  Time and date it was sent to customer using the 'send email' button
-  Custom history note (e.g. "Customer called and asked for payment to be delayed until Tuesday. Accepted.")

**Comment by denisdulici** [comment]
Thanks Ben. It makes sense to me. Can you please create a new topic to the Ideas category on the forum? Sorry for these routings.
