### ISSUE TITLE
Automated emails sent with localhost in link

### ISSUE THREAD

**Issue by jaiume** [akaunting/akaunting#2532]
### Akaunting version

3.0.3

### PHP version

8.1

### Operating system

Debian 10

### Steps to reproduce

Setup scheduled emails

### Expected result

Links have external website address as URL

### Actual result

Links have localhost as URL

### Additional comments

There is no place in settings to set the URL for system (At least none that I could find)

**Comment by denisdulici** [comment]
You should set the `APP_URL` variable within your `.env` file.
