### ISSUE TITLE
Can't create a hyperlink in email template editor

### ISSUE THREAD

**Issue by jaiume** [akaunting/akaunting#2533]
### Akaunting version

3.0.3

### PHP version

8.1

### Operating system

Debian 10

### Steps to reproduce

Edit an email template
Try to create a new hyperlink (Not edit an existing one)

### Expected result

There is a button to add a hyperlink

### Actual result

There is no way to add a new hyperlink

**Comment by denisdulici** [comment]
Added https://github.com/akaunting/akaunting/pull/2556
