### ISSUE TITLE
 Cannot read properties of undefined

### ISSUE THREAD

**Issue by rodrigoserracoelho** [akaunting/akaunting#2535]
### Akaunting version

3.0.3

### PHP version

8.0

### Operating system

Cloud linux (3.10.0-962.3.2.lve1.5.70.el7.x86_64)

### Steps to reproduce

Install Akaunting using the softaculous provided by CPanel (which will install version 3.0.3) on HTTPS.
Then navigate to ~/auth/login and put your email and password and submit.
I can see a post to: /auth/login with the correct payload:
`_token: hLVdUxJqX8CRrYocoA9Q48BzQVC27hNvw4eY98Cp
_method: POST
email: <my mail>
password: <mypassword>
remember: 
`
This call returns a 500.
In the browser console i can see the following error:
`common.min.js?v=3.0.3:7 TypeError: Cannot read properties of undefined (reading 'email')
    at e.value (common.min.js?v=3.0.3:7:95022)
    at Ln.eval (eval at ds (common.min.js?v=3.0.3:7:92570), <anonymous>:4:39)
    at e._render (common.min.js?v=3.0.3:7:35452)
    at Ln.r (common.min.js?v=3.0.3:7:68584)
    at _n.get (common.min.js?v=3.0.3:7:26843)
    at _n.run (common.min.js?v=3.0.3:7:27727)
    at yn (common.min.js?v=3.0.3:7:25835)
    at Array.<anonymous> (common.min.js?v=3.0.3:7:12434)
    at et (common.min.js?v=3.0.3:7:11833)
Ke @ common.min.js?v=3.0.3:7
Xe @ common.min.js?v=3.0.3:7
qe @ common.min.js?v=3.0.3:7
e._render @ common.min.js?v=3.0.3:7
r @ common.min.js?v=3.0.3:7
_n.get @ common.min.js?v=3.0.3:7
_n.run @ common.min.js?v=3.0.3:7
yn @ common.min.js?v=3.0.3:7
(anonymous) @ common.min.js?v=3.0.3:7
et @ common.min.js?v=3.0.3:7
Promise.then (async)
Ye @ common.min.js?v=3.0.3:7
ot @ common.min.js?v=3.0.3:7
(anonymous) @ common.min.js?v=3.0.3:7
_n.update @ common.min.js?v=3.0.3:7
pe.notify @ common.min.js?v=3.0.3:7
set @ common.min.js?v=3.0.3:7
value @ common.min.js?v=3.0.3:7
value @ common.min.js?v=3.0.3:7
Promise.catch (async)
value @ common.min.js?v=3.0.3:7
onSubmit @ common.min.js?v=3.0.3:7
submit @ VM12:3
Ve @ common.min.js?v=3.0.3:7
n @ common.min.js?v=3.0.3:7
o._wrapper @ common.min.js?v=3.0.3:7
3common.min.js?v=3.0.3:7 TypeError: Cannot convert undefined or null to object
    at e.value (common.min.js?v=3.0.3:7:95163)
    at keydown (eval at ds (common.min.js?v=3.0.3:7:92570), <anonymous>:3:1238)
    at Ve (common.min.js?v=3.0.3:7:11348)
    at HTMLFormElement.n (common.min.js?v=3.0.3:7:13139)
    at o._wrapper (common.min.js?v=3.0.3:7:48814)
    `
Let me know if you need more info.

### Expected result

Login success.

### Actual result

500 HTTP CODE

**Comment by rodrigoserracoelho** [comment]
Thanks a lot for making Akaunting available for everyone.

**Comment by tpishz** [comment]
I have a similar issue 

`TypeError: this.errors is undefined
    value https://***/public/js/auth/common.min.js?v=3.0.6:7
    anonymous https://***/public/js/auth/common.min.js?v=3.0.6 line 7 > Function:4`
`TypeError: this.errors is undefined
    value https://***/public/js/auth/common.min.js?v=3.0.6:7
    keydown https://***/js/auth/common.min.js?v=3.0.6 line 7 > Function:3`

Looking forward to the solution. The file itself shows countless amount of errors. 

Key information: I installed it from Softaculous so all regular checks were already made and every requirements are installed. The software used to work until this new update. Everything akaunting needs from the server is provided so this problem is definitely in the auth section.

Thank you for keeping the open source world open, free and secure. A lot of companies can learn from you.

**Comment by tpishz** [comment]
I am not sure what went wrong exactly, however I simply switched PHP-FPM on and it started working.

**Comment by cuneytsenturk** [comment]
Akaunting 3.0.8 release fixed this issues: 
https://github.com/akaunting/akaunting/commit/7f4f376252a15a85a65a7473efee78e29b05c9cf https://github.com/akaunting/akaunting/commit/6e8588e06bf518b7f0d548dd1b8fef1e9e729c5a

**Comment by gempain** [comment]
I'm using 3.0.9 with Docker and still getting this error when trying to log in.
