### ISSUE TITLE
not redirecting to /install/requirements

### ISSUE THREAD

**Issue by htmujahid** [akaunting/akaunting#2538]
### Akaunting version

3.0.4

### PHP version

8.1.6

### Operating system

Ubuntu 22.04

### Steps to reproduce

1. Change the `APP_INSTALLED=false` in .env
2. Produce an error in server requirements manually
- In App/Utilities/Installer.php replace the line 25 `$requirements = [trans('install.requirements.disabled', ['feature' => 'Safe Mode'])]`;
3. check any route like /install/requirements: this will work fine by displaying error of server requirements
4. check all routes of routes/install.php except /install/requirements 

### Expected result

it should be redirected to /installer/requirements 

### Actual result

it is not displaying server requirement error message in this case
it has bypassed the error

**Comment by cuneytsenturk** [comment]
@yasirmturk solved this issue; please use the same method.
