### ISSUE TITLE
'Mark Paid' for invoices doesn't work if partial payments have already been applied

### ISSUE THREAD

**Issue by ChipwizBen** [akaunting/akaunting#254]
As per: https://akaunting.com/forum/discussion/general/invoice-email-to-customer
 
'Mark Paid' option in the menu doesn't seem to do anything at all if partial payments exist. I've only managed to get it to work with an invoice that had no previous payments on it.

**Comment by denisdulici** [comment]
Ben, I just tried and it worked fine for me. Anyone else having such an issue?
