### ISSUE TITLE
Piwik plugin 'URL' is not really a URL

### ISSUE THREAD

**Issue by ChipwizBen** [akaunting/akaunting#255]
When entering the URL and site number to my piwik server into the fields in Akaunting like this:
URL: https://analytics.example.com
SiteID: 10

The URL that Akaunting actually tries is (found while debugging in the browser):
https://https//analytics.example.com/piwik.js

Setting the URL in Akaunting's Piwik settings to just analytics.example.com solves the problem. I don't know PHP that well, but here's some regex that might solve the problem of mixed inputs:
`s/https*:\/\///g`

**Comment by denisdulici** [comment]
Ben, please, use the Apps category in forums as it's not related to the core.
