### ISSUE TITLE
Countries prefix flaw

### ISSUE THREAD

**Issue by IbrahimS2** [akaunting/akaunting#2561]
### Akaunting version

Latest

### PHP version

8.1

### Operating system

Debian 11

### Steps to reproduce

Fill business info, including business addressin 

### Expected result

It displays the address normally

### Actual result

The address is displayed, but the country is prefixed with "countries."

### Additional comments

After debugging this further, I found this:
https://github.com/akaunting/akaunting/blob/96b12323a9bfe2919f46135f678c5fdc50d399b9/app/Exports/Sales/Sheets/Invoices.php#L22

So it appears it is by design, any explanation why there is a prefix?

**Comment by IbrahimS2** [comment]
@cuneytsenturk Please check from this.

**Comment by cuneytsenturk** [comment]
@IbrahimS2 Thanks for feedback
