### ISSUE TITLE
Send receipt send button not working

### ISSUE THREAD

**Issue by jaiume** [akaunting/akaunting#2566]
### Akaunting version

3.0.5

### PHP version

8.1

### Operating system

Debian 10

### Steps to reproduce

Go to invoices
View an invoice
Click **Send Receipt**
From the preview window, click **send**

### Expected result

Email will be sent and preview window will be closed

### Actual result

Emails isn't sent, and preview window stays open

### Additional comments

A 403 error seems to be generated when the button is clicked

### Relevant log output

```shell
POST /1/modals/transactions/188/emails HTTP/1.0" 403 1380 "https://acc.wifiventures.co.tt/1/sales/invoices/102" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
```

**Comment by denisdulici** [comment]
Not able to reproduce it. Make sure your email settings are correct. Feel free to use the forum for further help.

**Comment by jaiume** [comment]
ok, well just so you know. Was working fine on 3.0.3

Did a bit of digging and getting a CSRF token mismatch

**Comment by jaiume** [comment]
Turning firewall off solves the problem
