### ISSUE TITLE
Call to undefined method App\Builders\Category::disableModelCaching()

### ISSUE THREAD

**Issue by jamescumming** [akaunting/akaunting#2567]
### Akaunting version

3.0.5

### PHP version

8.1.6

### Operating system

Ubuntu

### Steps to reproduce

1. open a "New Income" page
2. fill in details
3. click "save"

### Expected result

Save the income

### Actual result

get an error message:

Call to undefined method App\Builders\Category::disableModelCaching()

This also occurs with trying to save a bill payment, and saving a expense.

### Additional comments

The above worked fine with v3.0.4, it only gave these problems after updrading to v3.0.5

**Comment by denisdulici** [comment]
Not able to reproduce it. Feel free to use the forum for further help.
