### ISSUE TITLE
Class "Termwind\Laravel\TermwindServiceProvider" not found  

### ISSUE THREAD

**Issue by IoanSolovastru** [akaunting/akaunting#2576]
### Akaunting version

3.0.5

### PHP version

8.1.0

### Operating system

Ubuntu 20.04

### Steps to reproduce

I was updating my Akauting software from `3.0.4` to `3.0.5` via GUI. Some errors occurred and now I got error HTTP 500.

When I try to run `php artisan update core 3.0.5` using SSH in my current akauting directory I got:
```bash
Class "Termwind\Laravel\TermwindServiceProvider" not found  
```

### Expected result

I was expected either to work from updating the GUI or with the manual update using ssh.

### Actual result

The app is stucked along with my data.

**Comment by cuneytsenturk** [comment]
This issue reason Akaunting update step broken.

Please read this [documentation](https://akaunting.com/docs/update). Auto update and manual update
