### ISSUE TITLE
Redirect prints out json

### ISSUE THREAD

**Issue by yasirmturk** [akaunting/akaunting#2581]
### Akaunting version

3.0.0 lastest master

### PHP version

8.1.9

### Operating system

Ubuntu heroku-20

### Steps to reproduce

start installation;
- select locale

### Expected result

redirect to install/database

### Actual result

prints out json with install/database link
<img width="595" alt="Screenshot 2022-08-05 at 4 23 25 PM" src="https://user-images.githubusercontent.com/306691/183100141-bf934a67-c9c5-4847-8f80-c0d706b9c79c.png">
 
<img width="708" alt="Screenshot 2022-08-05 at 4 24 56 PM" src="https://user-images.githubusercontent.com/306691/183100150-3f279715-bc74-4de4-ae11-d8bb5662b584.png">

**Comment by cuneytsenturk** [comment]
This json output issue reason. You should run npm. You can look installation [docs](https://github.com/akaunting/akaunting#installation)/
