### ISSUE TITLE
Dashboard Icons not showing after Installation

### ISSUE THREAD

**Issue by pthoelken** [akaunting/akaunting#2593]
### Akaunting version

latest 

### PHP version

8.1

### Operating system

Debian 11

### Steps to reproduce

Install Akaunting by installation web procedure

### Expected result

Dashboard is showing correct after installation

### Actual result

![image](https://user-images.githubusercontent.com/12643853/184006474-d0a758eb-9d29-443f-97e2-664d6fad936c.png)

**Comment by pthoelken** [comment]
bump

**Comment by atiabjobayer** [comment]
Same issue

**Comment by ThanhNha** [comment]
I install app on xampp. i can't login dashboard error 500 Internal Server Error. Help me !!!

**Comment by raflymln** [comment]
Try my solution here: https://github.com/akaunting/akaunting/issues/2648#issuecomment-1307197126

**Comment by cuneytsenturk** [comment]
This issue fixed #2648 so then  ı am closing this issue. thank @raflymln
