### ISSUE TITLE
Currency rates

### ISSUE THREAD

**Issue by joveice** [akaunting/akaunting#26]
Hello, I guess the rates are by 1 USD? if so I tried to add mine 7.95 NOK and, then if set the account to 300 (whatever currency this is?) it turns out to 30.000,00kr which is 3.764,00 USD. So nothing makes sense here to me.

What do you do here? could we get some info on this because there is no documentation on how to use this what so ever?

**Comment by denisdulici** [comment]
@joveice You can change the rates as you want. As mentioned in the documentation, the **Default** currency rate must be set to 1:
https://akaunting.com/docs/user-manual/settings/currencies

Feel free to use the support forum for further support on usage: https://akaunting.com/forum

**Comment by joveice** [comment]
@denisdulici 
In banking > accounts I added a new account, selected my default currency (is now 1). gave it a start of 300. saved, shows up as 30.000,00kr, that's 100 times bigger than what I put in.

Now I went and added -73,93 in payments and it's displaying 226,07. if I add 73,93 in sales it's displaying 300kr. Bug?
