### ISSUE TITLE
Adding a payment to a bill creates a double history entry

### ISSUE THREAD

**Issue by ChipwizBen** [akaunting/akaunting#261]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create a bill
Add a payment
Double history entry appears (can be 'Paid', 'Partial', 'Received')

### Expected result
Single history entry

### Actual result
Double history entry

### System information (Akaunting, PHP versions)
Akaunting 1.1.15
[root@web dev]# rpm -qa | grep php
php56u-devel-5.6.34-1.ius.centos7.x86_64
php56u-gd-5.6.34-1.ius.centos7.x86_64
php56u-common-5.6.34-1.ius.centos7.x86_64
php56u-pdo-5.6.34-1.ius.centos7.x86_64
php56u-5.6.34-1.ius.centos7.x86_64
php56u-mbstring-5.6.34-1.ius.centos7.x86_64
php56u-process-5.6.34-1.ius.centos7.x86_64
php56u-pear-1.10.5-1.ius.centos7.noarch
php56u-pecl-jsonc-devel-1.3.10-2.ius.centos7.x86_64
php56u-pecl-memcache-3.0.8-6.ius.centos7.x86_64
php56u-cli-5.6.34-1.ius.centos7.x86_64
php56u-mysqlnd-5.6.34-1.ius.centos7.x86_64
php56u-xml-5.6.34-1.ius.centos7.x86_64
php56u-pecl-jsonc-1.3.10-2.ius.centos7.x86_64

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue Ben

![2018-03-31_1032](https://user-images.githubusercontent.com/5254835/38160955-c7822cc4-34ce-11e8-89ce-68249b0ea2a9.png)
