### ISSUE TITLE
transaction.number_next

### ISSUE THREAD

**Issue by InteliClic** [akaunting/akaunting#2610]
### Akaunting version

3.0.6

### PHP version

8.1

### Operating system

Ubuntu 14.04

### Steps to reproduce

Import data which changes the auto-increment of the transactions table creates an annoying error on the add payments popup and in add income/expense transaction.

In the following images you can see the issue:
![Screenshot 2022-08-27 094938](https://user-images.githubusercontent.com/1582354/187040316-7267c5a9-ff75-4664-aeac-5fff9c39c248.png)
![Screenshot 2022-08-27 094953](https://user-images.githubusercontent.com/1582354/187040317-397fb97b-a286-48a1-bae8-ec90a02ddccf.png)
tings table.

### Expected result

Add a payment without issue.

### Actual result

Add a payment prompts an error.

### Additional comments

I managed to fix this issue very easily by going into the database and changing the settings.transaction.number_next but it seems to me that Akaunting should check the auto-increment on the database and update the row in the set.

This ended up happening because I had to manually import the old Akaunting system. Quite frustrating that the export / import didn't work either. On the old system kept getting an error but since that's not supported seems pointless to explore that.

**Comment by barthmania** [comment]
I have the exact same issue since the V3 update, I have to manually input a transaction number for every single invoice or expense I add... Which is very annoying.

**Comment by cuneytsenturk** [comment]
You can update on database this number, `settings` table key  =  `transaction.number_next`
