### ISSUE TITLE
Invoice Edit Payment

### ISSUE THREAD

**Issue by InteliClic** [akaunting/akaunting#2613]
### Akaunting version

3.0.6

### PHP version

8.1

### Operating system

Ubuntu 14.04

### Steps to reproduce

To replicate. Create an invoice for $10. Add a payment for $7.

![image](https://user-images.githubusercontent.com/1582354/187493305-553ac6fc-1f1f-4b2c-9633-ecdc44ee1695.png)
![image](https://user-images.githubusercontent.com/1582354/187493357-edb0c3f5-70b2-476f-b784-e8a426ea1fc9.png)
![image](https://user-images.githubusercontent.com/1582354/187493412-8ecc497c-dbba-4af8-9d04-ef9248baaa3d.png)

So everything goes well up until this point.

The problem starts here when we realize we've made a mistake and need to edit the payment because it was supposed to be for $10. Unfortunately an error is not allowing the amount to be updated.

![image](https://user-images.githubusercontent.com/1582354/187493681-6961f799-47ec-42cb-ae59-e972f9b51995.png)

### Expected result

Payment should be changed to $10

### Actual result

Error: Payment not added! The amount you entered exceeds the total: $3.00

### Additional comments

I could simply add another payment for $3. However that won't match in the reconciliation. I'll have 2 payments when we only received 1 payment.

### Relevant log output

```shell
None
```

**Comment by cuneytsenturk** [comment]
Thanks for feedback @InteliClic
