### ISSUE TITLE
Trying to set reverse proxy results in "Could not open input file: artisan"

### ISSUE THREAD

**Issue by zkvvoob** [akaunting/akaunting#2615]
### Akaunting version

3

### PHP version

7.4.10 (or whatever ships with Akaunting's Docker image)

### Operating system

Ubuntu 20.04

### Steps to reproduce

Run inside the container
`php artisan vendor:publish --provider="Fideloper\Proxy\TrustedProxyServiceProvider"`

### Expected result

No idea, but not an error message

### Actual result

Could not open input file: artisan

### Additional comments

I'm trying to set up Akaunting behind an Nginx reverse proxy (actually using Nginx Proxy Manager). `APP_URL=http://10.0.0.11:1200`, which is the internal IP of my server and the port I've mapped to the container's 80 in the docker-compose.yml file. The goal is for Akaunting to be accessible at `https://akaunting.mydomain.com`.

### Relevant log output

```shell
root@555ee24ee078:/var/www/akaunting# ls -al
total 12
drwxr-xr-x 2 root root 4096 Sep  2 10:07 .
drwxr-xr-x 1 root root 4096 Sep  2 10:07 ..
root@555ee24ee078:/var/www/akaunting# php artisan vendor:publish --provider="Fideloper\Proxy\TrustedProxyServiceProvider"
Could not open input file: artisan
```

**Comment by cuneytsenturk** [comment]
You have 2 option.
1. Wrong console location
2. Improper permissions of artisan

Please read this [details](https://bobcares.com/blog/laravel-could-not-open-input-file-artisan/)
