### ISSUE TITLE
Dashboard does not calculate partial payments

### ISSUE THREAD

**Issue by ChipwizBen** [akaunting/akaunting#264]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
I have two bills that have not been marked as paid due to issues #262 and #263, despite one having been paid in full and the other having been paid in full less 1 cent. But this has also highlighted a bug in the dashboard. What I'd expect to see in the dashboard is 1c outstanding, but instead I see the full total for both bills without any consideration for any payments.

### Expected result
Dashboard reads $0.01 for expenses.

### Actual result
Dashboard reads $59.86 for expenses (full total of two unpaid bills).

### System information (Akaunting, PHP versions)
Akaunting 1.1.15
[root@web dev]# rpm -qa | grep php
php56u-devel-5.6.34-1.ius.centos7.x86_64
php56u-gd-5.6.34-1.ius.centos7.x86_64
php56u-common-5.6.34-1.ius.centos7.x86_64
php56u-pdo-5.6.34-1.ius.centos7.x86_64
php56u-5.6.34-1.ius.centos7.x86_64
php56u-mbstring-5.6.34-1.ius.centos7.x86_64
php56u-process-5.6.34-1.ius.centos7.x86_64
php56u-pear-1.10.5-1.ius.centos7.noarch
php56u-pecl-jsonc-devel-1.3.10-2.ius.centos7.x86_64
php56u-pecl-memcache-3.0.8-6.ius.centos7.x86_64
php56u-cli-5.6.34-1.ius.centos7.x86_64
php56u-mysqlnd-5.6.34-1.ius.centos7.x86_64
php56u-xml-5.6.34-1.ius.centos7.x86_64
php56u-pecl-jsonc-1.3.10-2.ius.centos7.x86_64

### Additional comments
This issue also affects the totals in the profit dashboard counter.

**Comment by denisdulici** [comment]
That's because dashboard reports show the accrued incomes and expenses, except Cash Flow chart. https://akaunting.com/docs/user-manual/dashboard
