### ISSUE TITLE
Connet Invoice (Error in Total when selecting an invoice)

### ISSUE THREAD

**Issue by xsuleymandogan** [akaunting/akaunting#2646]
### Akaunting version

3.0.6

### PHP version

8.0.23

### Operating system

Ubuntu 22.04

### Steps to reproduce

> Create New Currecny (Lira)
> Create Invoices and Enter a Income
> Select Connect 

### Expected result

When selecting and invoice the fidure n total shuld be the amounth of the invoice.

### Actual result

When select an invoice that was creates using TRY the numbers dow not come correcly.

![image](https://user-images.githubusercontent.com/28389812/193382873-0bfdaf72-974c-4170-9369-d9b9614fff8d.png)

### Additional comments

I presume the bug is in the Decimal Mark and Thousands Separator of the TRY setting.

**Comment by mrtn3000** [comment]
The problem still exists in 3.0.11 and with EUR

**Comment by cuneytsenturk** [comment]
This issue solved 3.0.12 and [commit](https://github.com/akaunting/akaunting/commit/297ee6eba023c811c95ecb414d6416c85c837c55) here
