### ISSUE TITLE
IntlException Constructor failed

### ISSUE THREAD

**Issue by ibjorn** [akaunting/akaunting#2658]
### Akaunting version

3.0.6

### PHP version

8.1.11

### Operating system

CentOS Linux 7.9.2009 /  Plesk Obsidian Version 18.0.47

### Steps to reproduce

Follow installation instructions from GitHub repository and install application.

OR

Installation guide from Akaunting docs and install application.

### Expected result

Application works as expected.

### Actual result

Accessing Dashboard results in 500 server error. 

With debug enabled, the following exceptions are thrown:

```
Constructor failed (View: /resources/views/common/dashboards/show.blade.php)
/vendor/akaunting/laravel-money/src/Money.php#594
Illuminate\View\ViewException

Constructor failed
/vendor/akaunting/laravel-money/src/Money.php#594
```

### Additional comments

Tried different installation methods, as described above. 

Multiple install attempts with the following PHP Handlers:
- FastCGI served by Apache
- FPM served by Apache
- FPM served by Nginx
- Dedicated FPM served by Apache
- Dedicated FPM served by Nginx

Node:
- 16.17.1
- 17.9.1

Ensured PHP path set correctly using ENV variables.

Same server runs Laravel applications without any hitch. From Laravel 6 through to 9.

Have tried intermittently past week or two, running composer and npm updates but continue to get the same result.

### Relevant log output

```shell
WARNING str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in /vendor/laravel/framework/src/Illuminate/Support/Str.php on line 242
WARNING str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in /vendor/laravel/framework/src/Illuminate/Support/Str.php on line 242
WARNING str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in /vendor/laravel/framework/src/Illuminate/Support/Str.php on line 242
WARNING str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in /vendor/laravel/framework/src/Illuminate/Support/Str.php on line 242
WARNING Return type of Akaunting\Menu\Menu::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/akaunting/laravel-menu/src/Menu.php on line 163
WARNING Return type of Akaunting\Menu\MenuBuilder::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/akaunting/laravel-menu/src/MenuBuilder.php on line 562
WARNING str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in /vendor/laravel/framework/src/Illuminate/Support/Str.php on line 242
WARNING str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in /vendor/laravel/framework/src/Illuminate/Support/Str.php on line 242
WARNING str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in /vendor/laravel/framework/src/Illuminate/Support/Str.php on line 242
WARNING str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in /vendor/laravel/framework/src/Illuminate/Support/Str.php on line 242
WARNING explode(): Passing null to parameter #2 ($string) of type string is deprecated in /app/Traits/SearchString.php on line 25
WARNING explode(): Passing null to parameter #2 ($string) of type string is deprecated in /app/Traits/SearchString.php on line 25
WARNING explode(): Passing null to parameter #2 ($string) of type string is deprecated in /app/Traits/SearchString.php on line 25
WARNING Return type of Balping\JsonRaw\Raw::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute
```

**Comment by cuneytsenturk** [comment]
Akaunting requirement list [here](https://akaunting.com/docs/requirements) . Please check this all `Environment` and `Extensions`

**Comment by ibjorn** [comment]
I have checked that page before. The server meets all those requirements.

**Comment by pratikjajal** [comment]
Hi Cüneyt,

Please open this topic. I am also getting the same error. It is only with the Dashboard. For other pages, Akaunting is working fine. 

Constructor failed (View: /httpdocs/resources/views/common/dashboards/show.blade.php)
/httpdocs/vendor/akaunting/laravel-money/src/Money.php#594
Illuminate\View\ViewException
Constructor failed
/httpdocs/vendor/akaunting/laravel-money/src/Money.php#594

These errors are occurring on Dashboard. Need your help to quickly fix it share workaround for the same.

Regards,
Pratik
