### ISSUE TITLE
CSS fault with dashboard date picker (Firefox)

### ISSUE THREAD

**Issue by ChipwizBen** [akaunting/akaunting#266]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Select a custom date range

### Expected result
Date range popup appears correctly

### Actual result
Date range popup appears but slips underneath date range picker. It seems that the class 'calendar-table' is only wide enough for 6 days for both the start and the end dates. The consequence of this is that Sunday is cut off the start calendar (as it slips underneath the end calendar) and the Sunday on the end calendar is unselectable as it slips underneath the date dropdown.

### System information (Akaunting, PHP versions)
Akaunting 1.1.15
Firefox 58.0.2

### Additional comments
Edit: Have since tested the same on Chrome 64.0.3282.140, which renders the popup correctly. The issue appears to be with Firefox (haven't tested other browsers though, don't have a Windows machine).

**Comment by cuneytsenturk** [comment]
This issue secreenshot
![mozill-dashboad-cash-flow-custom-date-datenge-issue](https://user-images.githubusercontent.com/10936547/42935679-eb2d8440-8b52-11e8-9f37-ae2869832308.png)

**Comment by cuneytsenturk** [comment]
![mozill-dashboad-cash-flow-custom-date-datenge-issue-solved](https://user-images.githubusercontent.com/10936547/42936121-fc9a6b48-8b53-11e8-9c19-bdaedd7f218c.png)
