### ISSUE TITLE
Settings -> Company - Missing Save/Cancel buttons

### ISSUE THREAD

**Issue by jamescumming** [akaunting/akaunting#2668]
### Akaunting version

3.0.7

### PHP version

8.1.9

### Operating system

Ubuntu

### Steps to reproduce

Go to Settings --> Select Company

No save or cancel buttons are displayed

### Expected result

Expect to see canvel and save buttons

### Actual result

No save or cancel buttons are displayed

**Comment by cuneytsenturk** [comment]
Please check user permission for save and cancel buttons.

**Comment by Amon-X** [comment]
I am having this same issue on 3.0.10. I am using an admin account none of the settings pages have a save button.
