### ISSUE TITLE
Dashboard - Latest Incomes box - Not showing invoice payments 

### ISSUE THREAD

**Issue by johnnyq** [akaunting/akaunting#267]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create an Invoice - Add Payment make it for the full amount of the invoice. 
Go to Dashboard check the latest incomes box it doesn't show up there.

### Expected result
Paid invoices should show up under dashboard - latest incomes

### Actual result
Does not show payed invoices

### System information (Akaunting, PHP versions)
1.1.15
PHP 7.0

**Comment by denisdulici** [comment]
Expected result is not correct as it is designed to show only invoice records, not their payments.
