### ISSUE TITLE
Incomes - Revenues: Not displaying invoice payments

### ISSUE THREAD

**Issue by johnnyq** [akaunting/akaunting#271]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Create an invoice and add a payment to that invoice then click on Incomes - Revenues on the side menu

### Expected result

Invoice Payments should show here

### Actual result

No Invoice Payments are being displayed

### System information (Akaunting, PHP versions)

Akaunting 1.1.15
PHP7

**Comment by denisdulici** [comment]
Expected result is not correct as they are different income records https://akaunting.com/docs/faq/invoices-vs-revenues
