### ISSUE TITLE
Cannot import invoices if invoice_number is numeric

### ISSUE THREAD

**Issue by uddevil** [akaunting/akaunting#2710]
### Akaunting version

3.0.8

### PHP version

8.0.4

### Operating system

Debian 10

### Steps to reproduce

1. Download sample file from ```common/import/sales/invoices```
2. Fill in the sample file, but use all number on ```invoice_number``` column
3. Upload / Import file

### Expected result

All data imported.

### Actual result

Error because the invoice_number is not a string.

### Additional comments

Temporary work around, in ```app/Imports/Sales/Sheets/*``` 
I force ```$row['invoice_number']``` to be a string, like this :

```$row['invoice_number'] = $row['invoice_number'] . "";```

**Comment by JensGryspeert** [comment]
I would like to assign myself to this issue.

**Comment by EnesSacid-Buker** [comment]
Hi @uddevil

I didn't get the error you got in the last version.
Can you try it in the latest version of Akaunting?
