### ISSUE TITLE
No save button so can't edit payment transactions

### ISSUE THREAD

**Issue by meaz** [akaunting/akaunting#2719]
### Akaunting version

3.0.8

### PHP version

8.1

### Operating system

Debian bullseye

### Steps to reproduce

- Go to Banking -> Transactions
- Scroll over a payment transaction to open the Edit interface.
- Change any input value.
- It is not possible to save those changes. It looks like the 'Save' button is missing on that page.

### Expected result

Be able to save the changes by clicking on a "Save" button.

### Actual result

No "Save" button, so changes can not be changed.

**Comment by cuneytsenturk** [comment]
I've tested clean Akaunting installation and everything works.
