### ISSUE TITLE
Banking - Transfer and Transactions - Latest dates should be first then descend for consistency

### ISSUE THREAD

**Issue by johnnyq** [akaunting/akaunting#273]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Create a bunch of expenses and transfers for different dates then click on transfers and transactions

### Expected result

Newest to oldest should be displayed by default for both transactions and transfers for consistency 

### Actual result

It shows oldest to newest

### System information (Akaunting, PHP versions)

Akaunting 1.1.15
PHP 7

**Comment by cuneytsenturk** [comment]
Thanks your feed back  @johnnyq

**Comment by johnnyq** [comment]
I couldn't do it without you, thanks for fixing!
