### ISSUE TITLE
username login instead of email 

### ISSUE THREAD

**Issue by vignesh007vicky** [akaunting/akaunting#274]
I want a simple feature or idea to refer username in users table instead of email.

### Steps to reproduce the issue
 
changed username instead of email
// Attempt to login
        if (!auth()->attempt(request(['username', 'password']))) {
            flash(trans('auth.failed'))->error();

            return back();
        }

### Expected result
to login with username

### Actual result
Invalid credentials

### System information (Akaunting, PHP versions)
Laravel Framework 5.4.36
php version 7.0
Akaunting Version 1.1.11

**Comment by denisdulici** [comment]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum
