### ISSUE TITLE
Jessenger/date Error on composer update

### ISSUE THREAD

**Issue by kwhohasamullet** [akaunting/akaunting#275]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. Run composer update on akaunting installation

### Expected result
Composer update the complete as normal

### Actual result
Console error
----------------------------
In Date.php line 10:

  Declaration of Jenssegers\Date\Date::diffForHumans(?Carbon\Carbon $since =
  NULL, $absolute = false, $short = false) should be compatible with Carbon\C
  arbon::diffForHumans(?Carbon\Carbon $other = NULL, $absolute = false, $shor
  t = false, $parts = 1)

### Additional comments
I was able to resolve this updating jessenger/date in composer.json to 3.3.*
I am not currently able to submit a pull request but hopefully it is easy enough for someone else to do
Further info on this error can be found here https://github.com/jenssegers/date/issues/280

**Comment by denisdulici** [comment]
Thanks Kieran.
