### ISSUE TITLE
Invoice Logo removed on save

### ISSUE THREAD

**Issue by DaGuus** [akaunting/akaunting#2752]
### Akaunting version

3.0.9

### PHP version

8.1.8

### Operating system

Ubuntu 20.04.5 (Docker)

### Steps to reproduce

In the recent version whenever I save my invoice my logo is removed and I have to reupload.
I checked in the settings my logo is still there (I also removed it and reuploaded it).

Whenever I create a invoice the logo is there, but when I save it is gone.

### Expected result

The logo stays

### Actual result

The logo is removed. When I go to edit invoice and check, it also tells me there is no logo and I have to upload one.

**Comment by dk52** [comment]
Unfortunately I have the same problem on the same version...

**Comment by cuneytsenturk** [comment]
This issue solved [here](https://github.com/akaunting/akaunting/commit/4123515da9b9fbe7d69a531593cb32d6328e2348)
