### ISSUE TITLE
Some words not available for translation

### ISSUE THREAD

**Issue by dadeke** [akaunting/akaunting#2753]
### Akaunting version

3.0.9

### PHP version

8.1.6

### Operating system

Rocky Linux 8

### Steps to reproduce

Go to **Sales** > **Invoices** > **Recurring Templates** > **New Recurring Invoice** > **Schedule**
using any other language no English

![Screenshot1 2022-11-19](https://user-images.githubusercontent.com/6050573/202872666-07c024e6-4467-4bd9-8a05-f8788e24b417.png)

### Expected result

The expected result is the words avaliable for translation:
https://crowdin.com/translate/akaunting/30/engb-ptbr

### Actual result

These words are not translated:

![Screenshot2 2022-11-19](https://user-images.githubusercontent.com/6050573/202872700-b6ea0b30-0cce-4914-852c-f24e69d17a40.png)

**Comment by cuneytsenturk** [comment]
This schedule section already tranlated. Please waiting update Akaunting latest version..
![image](https://user-images.githubusercontent.com/10936547/210501032-e44f546d-00ce-4373-a9c2-03825185ad1a.png)

**Comment by dadeke** [comment]
Thank you!

https://github.com/akaunting/akaunting/blob/94a0f9f7a1a7a98fcd0e51ca744ecbf0902bf179/resources/views/components/form/group/recurring.blade.php#L1-L8

But `type` is not translatable? 🤔
