### ISSUE TITLE
Payment Method selection not listing offline payments

### ISSUE THREAD

**Issue by raflymln** [akaunting/akaunting#2758]
### Akaunting version

3.0.9

### PHP version

8.0.25

### Operating system

Ubuntu 18.04

### Steps to reproduce

Create new Expense

### Expected result

The Payment Method selections should list "Cash" and "Bank Transfer"

### Actual result

![image](https://user-images.githubusercontent.com/19299378/203029200-37346dfd-e47f-463d-a31c-ef24249fda00.png)

Here's when i try to edit the other transaction which is using Bank Transfer
![image](https://user-images.githubusercontent.com/19299378/203029884-ec6fd4a3-903d-49b5-9f14-83843ad74c82.png)

### Additional comments

Previously it's working fine, idk why this happens suddenly

My offline payments settings:
![image](https://user-images.githubusercontent.com/19299378/203030036-0fc4d23f-5081-4f63-9e95-2dac640f41ee.png)

### Relevant log output

```shell
[2022-11-21 17:25:59] production.ERROR: Attempted to lazy load [currency] on model [App\Models\Banking\Account]. {"userId":2,"exception":"[object] (Exception(code: 0): Attempted to lazy load [currency] on model [App\\Models\\Banking\\Account]. at /var/www/acct.runes.asia/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:677)
[stacktrace]
```

**Comment by cuneytsenturk** [comment]
Please update Akaunting latest package and clear all cache
