### ISSUE TITLE
Commas in prices causes Whoops screen

### ISSUE THREAD

**Issue by pztrn** [akaunting/akaunting#277]
Right now when saving something where price contains commas (e.g. copied from excel) - I'm receiving "Whoops" screen. When comma replaced with dot - everything is fine. This isn't applicable to calculations in web interface - they're calculated ok with comma and dot.

I'm on Debian 9 with php 7.2 from deb.sury.org and revision f3587963884089474959d587d9d9c7fd589d2c4c

**Comment by denisdulici** [comment]
Stanislav, this is a known issue and we're working on it https://github.com/akaunting/akaunting/pull/189
