### ISSUE TITLE
Can't move invoice items

### ISSUE THREAD

**Issue by jaiume** [akaunting/akaunting#2779]
### Akaunting version

3.0.9

### PHP version

8.1

### Operating system

Debian 10

### Steps to reproduce

Create a new invoice
Add 2 items to invoice
Click the 3 lines on the left of the items and try to drag bottom item above top item

### Expected result

Items on invoice can be reordered by dragging up or down

### Actual result

Unable to drag items up or down

**Comment by cuneytsenturk** [comment]
This issue solved this [PR](https://github.com/akaunting/akaunting/pull/2849)
