### ISSUE TITLE
Disable autocomplete on select item create invoice

### ISSUE THREAD

**Issue by chomnit** [akaunting/akaunting#279]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
- Create new invoice
- Add item in the item list

### Expected result
- I should get the drop down instead of auto suggest
<img width="381" alt="screen shot 2018-03-30 at 15 17 47" src="https://user-images.githubusercontent.com/6535394/38130496-8d8872ae-342d-11e8-9dfe-1edc7834feb1.png">

### Actual result

<img width="605" alt="screen shot 2018-03-30 at 15 15 20" src="https://user-images.githubusercontent.com/6535394/38130470-707104b0-342d-11e8-8351-8e4044279a7d.png">

**Comment by denisdulici** [comment]
Thanks for the detailed report :wink:

**Comment by chomnit** [comment]
@denisdulici  the same issue also happen in bill module.

**Comment by ahmed1886** [comment]
It's fixed there too.
