### ISSUE TITLE
No save in any settings thus unable to make changes to Company, Invoice, etc

### ISSUE THREAD

**Issue by Amon-X** [akaunting/akaunting#2790]
### Akaunting version

3.0.10

### PHP version

8.1.2

### Operating system

Ubuntu 22.04.1 LTS x86_64 

### Steps to reproduce

Go to Settings -> Select Company
No save or cancel buttons are displayed

Go to Settings -> Select Localisation
No save or cancel buttons are displayed

Go to Settings -> Select Invoice
No save or cancel buttons are displayed

Go to Settings -> Select Email Service
No save or cancel buttons are displayed

Go to Settings -> Select Scheduling
No save or cancel buttons are displayed

Go to Settings -> Select Categories
No save or cancel buttons are displayed

Go to Settings -> Select Currencies
No save or cancel buttons are displayed

Go to Settings -> Select % Taxes
No save or cancel buttons are displayed

### Expected result

Expecting a save button to be able to save any changes

### Actual result

Unable to save any changes to company, invoices or any settings. 

### Additional comments

Running the self hosted version. Upgraded from version 2 to 3 and no longer had save buttons show up after the upgrade. I am using an admin account and there are no options for user permissions for save and cancel buttons on the self hosted version.

**Comment by cuneytsenturk** [comment]
Hi Amon,

Please make sure the upgrade is done correctly. Because this issue reason your permissions.

Have a good day.

**Comment by Amon-X** [comment]
How do I check that the upgrade is done correctly? How do I change the permissions?

**Comment by NajibNour** [comment]
@cuneytsenturk  Good day, can we get some more guidance on this? What permissions is needed. Who do the files need to be owned by? are we taking about the DB files or the akaunting files?

 I am running my instance trough a docker container. 

Any help would ge greatly appreciated

**Comment by NajibNour** [comment]
All db files are owned by 911  (MariaDB user) and all akaunting files are owned by (www-data)

**Comment by NajibNour** [comment]
Looking at the cloud version of akaunting and the self hosted one, When I inspect element on the self hosted one there is no code about the save button...

**Comment by NajibNour** [comment]
@Amon-X  So looking at other tickets its related to the user permissions. But im not able to access that page as I get a 500 error. Investigating that now.

**Comment by Amon-X** [comment]
> Looking at the cloud version of akaunting and the self hosted one, When I inspect element on the self hosted one there is no code about the save button...

The save button only appears if the user has permissions. If you inspect the files themselves they have a code block for displaying a save button.

**Comment by NajibNour** [comment]
enabled APP_DEBUG=true getting some errors now

seems like there is missing content in the database

**Comment by NajibNour** [comment]
Here is where im at. Seems like there's an issue in the database. 

```
SQLSTATE[42S02]: Base table or view not found: 1932 Table 'akaunting.asd_user_invitations' doesn't exist in engine (SQL: select * from `asd_user_invitations` where `user_id` = 1 and `asd_user_invitations`.`deleted_at` is null limit 1) (View: /var/www/html/resources/views/auth/users/edit.blade.php)
```

**Comment by Amon-X** [comment]
Yes I am able to get to my user page and my account is admin but there is no way to edit permissions without the roles page which you have to buy and last I checked does not work with the self hosted version.

**Comment by NajibNour** [comment]
Would you be willing to share the contents of your ``akaunting.asd_user_invitations`` table? Im trying to rebuild mine so I cab get to the users page and investigate further

**Comment by Amon-X** [comment]
I can. How would I go about doing that though?

**Comment by NajibNour** [comment]
How are you running your instance? Docker containers or standard services?

**Comment by Amon-X** [comment]
Self hosted on a web server. I am not good with database stuff and just followed a tutorial to get it running. It was manually set up. Something along the lines of this https://computingforgeeks.com/install-akaunting-accounting-software-on-ubuntu/

**Comment by NajibNour** [comment]
Try the following 

`sudo mysql -u root -p PASSWORD
use akaunting;
show * from akaunting.asd_user_invitations;`

**Comment by Amon-X** [comment]
It took me a while because the names were different 
mysql> select * from akauntnew.sah_user_invitations;
+----+---------+--------------------------------------+---------------------+---------------------+---------------------+
| id | user_id | token                                | created_at          | updated_at          | deleted_at          |
+----+---------+--------------------------------------+---------------------+---------------------+---------------------+
|  1 |       4 | (I deleted the token here) | 2023-01-05 18:16:06 | 2023-01-06 02:18:55 | 2023-01-06 02:18:55 |
+----+---------+--------------------------------------+---------------------+---------------------+---------------------+
1 row in set (0.00 sec)

**Comment by Amon-X** [comment]
in the database migration php files Akaunting_3.0.11-Stable/database/migrations/2022_05_10_000000_core_v300.php
        Schema::create('user_invitations', function (Blueprint $table) {
            $table->id();
            $table->integer('user_id')->unsigned();
            $table->integer('company_id')->unsigned();
            $table->string('token');
            $table->timestamps();
            $table->softDeletes();
        });
