### ISSUE TITLE
It should be nice to see tax % on the create invoice page

### ISSUE THREAD

**Issue by chomnit** [akaunting/akaunting#281]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Expected result

<img width="1144" alt="screen shot 2018-03-30 at 15 23 23" src="https://user-images.githubusercontent.com/6535394/38130732-654ac426-342e-11e8-86ba-55eec5cd9c0e.png">

### Actual result
<img width="1151" alt="screen shot 2018-03-30 at 15 23 10" src="https://user-images.githubusercontent.com/6535394/38130746-728ef206-342e-11e8-8ab1-b548abf5b5cf.png">

**Comment by chomnit** [comment]
@denisdulici  the same issue should also fix in bill module.

**Comment by denisdulici** [comment]
I've added to show/print page too and there is a setting to select the sign position.
