### ISSUE TITLE
The price in the list did not get update when change currency at the top

### ISSUE THREAD

**Issue by chomnit** [akaunting/akaunting#282]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
- Create invoice
- Keep adding item
- Then change the currency at the top
- The price  and total column in the list should get update, but it doesn't 

### Expected result
- It should update the price and total column

### Actual result

<img width="1178" alt="screen shot 2018-03-30 at 15 35 50" src="https://user-images.githubusercontent.com/6535394/38131149-2c0d6036-3430-11e8-9aea-9eb87c8220b6.png">

**Comment by chomnit** [comment]
@denisdulici  the same issue also happen in bill module.

**Comment by denisdulici** [comment]
When you create an item, you don't select a currency (i.e. USD) but enter a raw price so the system doesn't convert it if you select another currency (i.e. EUR).
