### ISSUE TITLE
Mapping field when import xls or csv

### ISSUE THREAD

**Issue by chomnit** [akaunting/akaunting#283]
As a user, I want to be able to map the field from excel file or excel file when I importing data so that I can pick whatever field I want to import (I don't need to follow the file format).

- List the field of the database on the left hand side
- Then excel field put in the dropdown list so user can chose which field from excel match the field in database.

**Comment by denisdulici** [comment]
Please, use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

**Comment by chomnit** [comment]
I will create the request. Thanks.
