### ISSUE TITLE
Issue with  Reconciliations 

### ISSUE THREAD

**Issue by killmasta93** [akaunting/akaunting#2850]
### Akaunting version

3.0.7

### PHP version

8.1.11

### Operating system

ubuntu 20.04

### Steps to reproduce

Hi
Currently have configured in docker, when we create the first Reconciliations then save to draft. and then want to edit im getting the 500 internal error

### Expected result

able to let me do reconciliations 

### Actual result

```
Uncaught TypeError: mainContent is null
    Layout https://domain.com/2/banking/reconciliations/3/edit:154
    <anonymous> https://domain.com/2/banking/reconciliations/3/edit:425

```

**Comment by EnesSacid-Buker** [comment]
Hello @killmasta93

I tried to get the error you mentioned but couldn't get it.
I created and saved an reconciliation, then added a transaction.
When I went to the edit page, I did not encounter a problem.
I even deleted the transaction and got no error when I went to the edit page again.
Can you share the error you got with me in more detail?
video, screenshot etc.

**Comment by killmasta93** [comment]
Thank you so much for the reply, it seems that i updated to the recent version and seem to fix the issue
