### ISSUE TITLE
Vendor/almasaeed2010 assets loading failed on Heroku deployment

### ISSUE THREAD

**Issue by iceberg53** [akaunting/akaunting#286]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Take the latest release source code
Uncompress it 
Composer install
Create a new Heroku app 
Move fzaninotto/faker dependency from require-dev to require to avoid  its suppression during the deployment on Heroku
Composer require jensengers/date:3.3.1 to solve an issue with nesbot/carbon library
Composer update to generate a new lock file
Point it to the root folder
Launch the installer

### Expected result
The installation process should be fine 

### Actual result
The layout styling is broken
The browser console reveals that (in french)

`Échec du chargement pour l’élément <script> dont la source est « http://akaunting.herokuapp.com/vendor/almasaeed2010/adminlte/plugins/jQuery/jquery-2.2.3.min.js ».
database:36
Échec du chargement pour l’élément <script> dont la source est « http://akaunting.herokuapp.com/vendor/almasaeed2010/adminlte/bootstrap/js/bootstrap.min.js ».
database:38
Échec du chargement pour l’élément <script> dont la source est « http://akaunting.herokuapp.com/vendor/almasaeed2010/adminlte/plugins/slimScroll/jquery.slimscroll.min.js ».
database:40
Échec du chargement pour l’élément <script> dont la source est « http://akaunting.herokuapp.com/vendor/almasaeed2010/adminlte/dist/js/app.min.js ».
database:42
`

### System information (Akaunting, PHP versions)
Heroku platform php 5.6
Akaunting latest release source code

### Additional comments

I thought about publishing the assets with vendor:publish after googling but it seems that it's useless because I didn't had to do such a thing in Homestead.
Excuse me if I missed something trivial.
Thank you for the great work you're doing.

**Comment by denisdulici** [comment]
Can you plz try the [stable version](https://akaunting.com/download) and/or the current latest version again? Sorry for the late reply.
