### ISSUE TITLE
Settings > Invoice

### ISSUE THREAD

**Issue by HolFl465** [akaunting/akaunting#2860]
### Akaunting version

3.0.11

### PHP version

8.1.13

### Operating system

Debian 10

### Steps to reproduce

Go to settings, then select Invoice.

### Expected result

There should be two buttons (Save/Cancel) at the bottom of the page.

### Actual result

The buttons are missing from the page.

**Comment by cuneytsenturk** [comment]
I've tested clean and updated Akaunting version everything works
![image](https://user-images.githubusercontent.com/10936547/210942417-3f344836-e898-4095-8d0b-988a57622545.png)


Please check your user permissions

**Comment by HolFl465** [comment]
Hello,
My user has admin permissions. I would like to re-install the software but
how can I backup the data and settings? Is there an app?
