### ISSUE TITLE
Upgrade from 3.0.10 to 3.0.11 doesn't finalize

### ISSUE THREAD

**Issue by HolFl465** [akaunting/akaunting#2861]
### Akaunting version

3.0.11

### PHP version

8.1.13

### Operating system

Debian 10

### Steps to reproduce

Visit update page (https://sub.domain.tld/1/install/updates/run/core/3.0.11) and wait for the update to happen.

### Expected result

Update finishes successfully with 100%

### Actual result

At 80% the update stops and gives an error message:

![image](https://user-images.githubusercontent.com/7515612/210791731-430026e9-fa72-499f-a64a-f0e098fc5789.png)

The system seems to run on 3.0.11 now, but there must be something missing since it didn't finalize.

### Relevant log output

```shell
The command php artisan update:finish core 1 3.0.11 3.0.11 failed.

Exit Code: 1(General error)

Working directory: /var/www/flo.lu/akaunting

Output:
================
Finishing update...
INFO Application cache cleared successfully.


In Connection.php line 760:

could not find driver (SQL: select * from `v9s_companies` where `v9s_compan
ies`.`id` = 1 and `v9s_companies`.`deleted_at` is null limit 1)


In Connector.php line 70:

could not find driver




Error Output:
================
```

**Comment by EnesSacid-Buker** [comment]
Hi @HolFl465 

I found this [resource](https://akaunting.com/forum/discussion/installation-update/app-installation-failed-error-occurred) on Akaunting's forum page, you can check if others are getting the same error from the forum page.
This looks more like a server problem.
You should check the php extensions in php.ini.
Are extension such as Mysql and PDO active, if they are active, are they installed?
