### ISSUE TITLE
Install Fails on Database

### ISSUE THREAD

**Issue by nmbgeek** [akaunting/akaunting#2862]
### Akaunting version

3.0.11

### PHP version

8.1.12

### Operating system

Ubuntu 18.04

### Steps to reproduce

Clean install of Akounting.

### Expected result

Successful installation

### Actual result

On clean installation progress hangs on myhostname.com/install/database page.  MySQL is running on local host and entered as so in the Hostname field with correct information.  If credentials are changed intentionally to something incorrect an error is displayed.  When correct credentials are used the progress shows the pulsing dots as if it is working however the Javascript console logs the error below.  The .env file is updated with credentials but the database remains empty.  If invalid database credentials are used then the expected error "Error: Could not connect to the database! Please make sure the details are correct." does display.  When correct credentials are used the process hangs with dots pulsing as if it is making progress when actually an error is logged to JS console.

`install.min.js?v=3.0.11:1 
POST https://xxx.xxx.xxx/install/database 500
TypeError: Cannot read properties of undefined (reading 'hostname')
    at e.value (install.min.js?v=3.0.11:36:305644)
    at a.<anonymous> (install.min.js?v=3.0.11:36:326020)
    at e._render (install.min.js?v=3.0.11:36:44743)
    at a.i (install.min.js?v=3.0.11:36:78695)
    at e.get (install.min.js?v=3.0.11:36:27256)
    at e.run (install.min.js?v=3.0.11:36:27989)
    at wn (install.min.js?v=3.0.11:36:19855)
    at Array.<anonymous> (install.min.js?v=3.0.11:36:24666)
    at Xn (install.min.js?v=3.0.11:36:24065)`
![image](https://user-images.githubusercontent.com/50661551/211409260-fac9b400-5577-485d-9eea-a2ad4f5a9968.png)

### Relevant log output

```shell
install.min.js?v=3.0.11:1 
POST https://books.MYDOMAINNAME.org/install/database 500
(anonymous) @ install.min.js?v=3.0.11:1
e.exports @ install.min.js?v=3.0.11:1
e.exports @ install.min.js?v=3.0.11:1
c.request @ install.min.js?v=3.0.11:1
(anonymous) @ install.min.js?v=3.0.11:1
value @ install.min.js?v=3.0.11:36
onSubmit @ install.min.js?v=3.0.11:36
click @ install.min.js?v=3.0.11:36
Hn @ install.min.js?v=3.0.11:36
n @ install.min.js?v=3.0.11:36
Lo.o._wrapper @ install.min.js?v=3.0.11:36
install.min.js?v=3.0.11:36 
        
TypeError: Cannot read properties of undefined (reading 'hostname')
    at e.value (install.min.js?v=3.0.11:36:305644)
    at a.<anonymous> (install.min.js?v=3.0.11:36:326020)
    at e._render (install.min.js?v=3.0.11:36:44743)
    at a.i (install.min.js?v=3.0.11:36:78695)
    at e.get (install.min.js?v=3.0.11:36:27256)
    at e.run (install.min.js?v=3.0.11:36:27989)
    at wn (install.min.js?v=3.0.11:36:19855)
    at Array.<anonymous> (install.min.js?v=3.0.11:36:24666)
    at Xn (install.min.js?v=3.0.11:36:24065)
Wn @ install.min.js?v=3.0.11:36
qn @ install.min.js?v=3.0.11:36
Rn @ install.min.js?v=3.0.11:36
e._render @ install.min.js?v=3.0.11:36
i @ install.min.js?v=3.0.11:36
e.get @ install.min.js?v=3.0.11:36
e.run @ install.min.js?v=3.0.11:36
wn @ install.min.js?v=3.0.11:36
(anonymous) @ install.min.js?v=3.0.11:36
Xn @ install.min.js?v=3.0.11:36
Promise.then (async)
Un @ install.min.js?v=3.0.11:36
ti @ install.min.js?v=3.0.11:36
xn @ install.min.js?v=3.0.11:36
e.update @ install.min.js?v=3.0.11:36
e.notify @ install.min.js?v=3.0.11:36
set @ install.min.js?v=3.0.11:36
value @ install.min.js?v=3.0.11:36
value @ install.min.js?v=3.0.11:36
Promise.catch (async)
value @ install.min.js?v=3.0.11:36
onSubmit @ install.min.js?v=3.0.11:36
click @ install.min.js?v=3.0.11:36
Hn @ install.min.js?v=3.0.11:36
n @ install.min.js?v=3.0.11:36
Lo.o._wrapper @ install.min.js?v=3.0.11:36
```

**Comment by seth586** [comment]
Similar problem on FreeBSD 13.1 & Akaunting 3.0.11 & PHP 8.1.13 & MariaDB-server 10.6.11

```
root@akaunting:~/akaunting-3.0.11 # php artisan install --db-name="akaunting" --db-username="akaunting" --db-password="abc123" --admin-email="admin@company.com" --admin-password="123456"
Setting locale en-GB
Creating database tables
Connecting to database akaunting@localhost:3306
Error: Could not connect to the database! Please, make sure the details are correct.
root@akaunting:~/akaunting-3.0.11 # sockstat
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
root     login      49167 3  dgram  -> /var/run/logpriv
root     cron       49045 5  dgram  -> /var/run/logpriv
www      php-fpm    49038 7  stream /var/run/php-fpm.sock
www      php-fpm    49037 7  stream /var/run/php-fpm.sock
root     php-fpm    49036 6  stream -> ??
root     php-fpm    49036 8  stream -> ??
root     php-fpm    49036 9  stream /var/run/php-fpm.sock
www      nginx      49030 7  tcp4   *:80                  *:*
www      nginx      49030 8  stream -> ??
root     nginx      49029 3  stream -> ??
root     nginx      49029 7  tcp4   *:80                  *:*
root     nginx      49029 8  stream -> ??
mysql    mariadbd   49025 20 tcp4   *:3306                *:*
mysql    mariadbd   49025 21 stream /var/run/mysql/mysql.sock
root     syslogd    48698 5  dgram  /var/run/log
root     syslogd    48698 6  dgram  /var/run/logpriv
root@akaunting:~/akaunting-3.0.11 #

```

Claims it can not connect to database, even though mysql database is valid& running & listening at :3306

**Comment by nmbgeek** [comment]
I finally got around to troubleshooting this today.  I use RunCloud for my hosting management which has a large set of default disabled php functions.  These include:
`getmyuid
passthru
leak
listen
diskfreespace
tmpfile
link
ignore_user_abort
shell_exec
dl
set_time_limit
exec
system
highlight_file
source
show_source
fpassthru
virtual
posix_ctermid
posix_getcwd
posix_getegid
posix_geteuid
posix_getgid
posix_getgrgid
posix_getgrnam
posix_getgroups
posix_getlogin
posix_getpgid
posix_getpgrp
posix_getpid
posix_getppid
posix_getpwuid
posix_getrlimit
posix_getsid
posix_getuid
posix_isatty
posix_kill
posix_mkfifo
posix_setegid
posix_seteuid
posix_setgid
posix_setpgid
posix_setsid
posix_setuid
posix_times
posix_ttyname
posix_uname
proc_nice
proc_terminate
escapeshellcmd
ini_alter
popen
pcntl_exec
socket_accept
socket_bind
socket_clear_error
socket_close
socket_connect
symlink
posix_geteuid
ini_alter
socket_listen
socket_create_listen
socket_read
socket_create_pair
stream_socket_server`

I was unable to find any documentation that lists any non-standard required functions however removing the disabled functions did allow me to install.  After installation I re-added the list and reloaded PHP and it does seem to be functioning so possibly the function is only required for the initial database connection.  While my issue is resolved I think the ultimate resolution would be to list any required functions.

**Comment by cuneytsenturk** [comment]
@nmbgeek Thanks for shared how to it has solved this issue.

**Comment by nmbgeek** [comment]
I would consider adding required php functions to Requirements in readme.md
