### ISSUE TITLE
Firefox font warning on each page

### ISSUE THREAD

**Issue by mrtnmueller** [akaunting/akaunting#2863]
### Akaunting version

3.0.11

### PHP version

8.1.0

### Operating system

Ubuntu 20.04

### Steps to reproduce

Visit any page

### Expected result

Page opens and I can work

### Actual result

On each page there is a warning, which i have to dismiss first

![Screenshot_20230110_083900](https://user-images.githubusercontent.com/2004318/211490550-ec0ac04e-4e99-4b4d-a4ee-c3925dd38194.png)

**Comment by novag** [comment]
I think this is a duplicate of #2856 and was already fixed in 7ab2774. Can you reproduce it in Akaunting v3.0.11?

**Comment by mrtnmueller** [comment]
After upgrading to 3.0.11 AND cleaning cookies, the warning disappeared.
