### ISSUE TITLE
Unable to find PHP command / correct version using Laravel Valet

### ISSUE THREAD

**Issue by benjibee** [akaunting/akaunting#2879]
### Akaunting version

3.0.11

### PHP version

8.1.11

### Operating system

macOS 13.1 

### Steps to reproduce

1. Download Akaunting from [installation page](https://akaunting.com/docs/installation)
2. Unzip and move folder to preferred directory
3. Link and secure directory using `valet link` and `valet secure`
4. Visit site in browser to see error about server requirements

### Expected result

The installation wizard should be shown, all requirements should be satisfied.

### Actual result

The following error is shown: `Error: Ask your hosting provider to use PHP 8.0.2 or higher for both HTTP and CLI.`

### Additional comments

I'm running four other Laravel installations on this machine without any issue. Valet has installed PHP using Homebrew and it is located in the following path: `/opt/homebrew/bin/php` and `php -v` outputs `8.1.11` and adding a PHP file to the document root with `phpinfo()` outputs the same version.

### Relevant log output

```shell
[2023-01-31 11:55:32] local.DEBUG: Console command:: 'php' 'artisan' help  
[2023-01-31 11:55:32] local.DEBUG: Console output:: The command "'php' 'artisan' help" failed.

Exit Code: 127(Command not found)

Working directory: /Users/[REMOVED]/accounting

Output:
================


Error Output:
================
sh: php: command not found
  
[2023-01-31 11:55:32] local.DEBUG: Console command:: 'php' 'artisan' help  
[2023-01-31 11:55:32] local.DEBUG: Console output:: The command "'php' 'artisan' help" failed.

Exit Code: 127(Command not found)

Working directory: /Users/[REMOVED]/accounting

Output:
================


Error Output:
================
sh: php: command not found
```

**Comment by EnesSacid-Buker** [comment]
Hi @benjibee

You can check this [link](https://akaunting.com/hc/docs/faq/i-cant-install-apps/) to solve the php version problem
or you can use this command line:
`php artisan install --db-name="akaunting" --db-username="root" --db-password="pass" --admin-email="admin@company.com" --admin-password="123456"`

**Comment by benjibee** [comment]
@EnesSacid-Buker thanks for the info. I tried that and eventually was able to get around this issue. I ran into so many other issues along the way I've had to find another solution for our accounting needs, however.
