### ISSUE TITLE
Cancelled invoice: Restore button without function

### ISSUE THREAD

**Issue by novag** [akaunting/akaunting#2889]
### Akaunting version

3.0.11

### PHP version

8

### Operating system

Debian

### Steps to reproduce

1. Create an invoice.
2. Cancel the invoice.
3. Open the cancelled invoice.
4. Open the "Restore" accordion.
5. Click "Restore".

### Expected result

The invoice is restored.

### Actual result

Nothing happens.

### Additional comments

https://github.com/akaunting/akaunting/blob/master/resources/views/components/documents/show/restore.blade.php#L10

**Comment by cuneytsenturk** [comment]
We've added [3.1.0](https://github.com/akaunting/akaunting/releases/tag/3.1.0) release
