### ISSUE TITLE
Invoice: Tax label with more than 4 characters is truncated

### ISSUE THREAD

**Issue by novag** [akaunting/akaunting#2890]
### Akaunting version

3.0.11

### PHP version

8

### Operating system

Debian

### Steps to reproduce

1. Change the language to one in which the word for "tax" has more than 4 characters (e.g. German).
2. Create an invoice.
3. Create a line item.
4. Click "Add Tax" ("Artikel neu hinzufügen" in German)

### Expected result

The full word "Steuer" should be visible.

### Actual result

![image](https://user-images.githubusercontent.com/7754358/218801879-40658cc9-26c9-47ba-ab0a-5c3a2209550d.png)

The word "Steuer" is truncated and hidden behind the text box.

**Comment by cuneytsenturk** [comment]
This issue solved this [PR](https://github.com/akaunting/akaunting/pull/2926) @mervekaraman fixed it.
