### ISSUE TITLE
After the fresh installation, the app is blank on wizard step

### ISSUE THREAD

**Issue by techniasoft** [akaunting/akaunting#2895]
### Akaunting version

3.0.11

### PHP version

8.1

### Operating system

Mac

### Steps to reproduce

do a fresh installation of akaunting app, and then wait until you reach the wizard steps, and you see the app is left blank

### Expected result

the app should show the wizard steps

### Actual result

the app is showing blank screen

**Comment by YeeJiaWei** [comment]
Is that the assets file are loaded?

**Comment by aloul84** [comment]
> Hi, first did you do the `npm install` and `npm run dev`?

this is work , but if you use cpanel you can do this localy then upload project by FTP
