### ISSUE TITLE
Unable to edit compary address from inline form on create invoice page

### ISSUE THREAD

**Issue by codisfy** [akaunting/akaunting#2937]
### Akaunting version

3.0.12

### PHP version

8.0.28

### Operating system

Ubuntu 22.04

### Steps to reproduce

1. Create an invoice. 
2. Try to edit the company address using the icon 
![image](https://user-images.githubusercontent.com/19868700/224578904-b1f4ed2d-6b94-4105-b050-3fc3c9078086.png)
3. The settings never get saved and the button keeps showing loading.

### Expected result

The settings should get updated

### Actual result

The settings don't get updated and the UI gets stuck. 

### Additional comments

Network panel shows that there was a 403. 
So it seems like permissions are not correctly loaded when editing a company from the popup

**Comment by cuneytsenturk** [comment]
You should check this permissions for user role `permission:read-settings-company` and `permission:update-settings-company`.
because this edit company information feature works. Your issue reason permissions.
