### ISSUE TITLE
Overlap on Characters of Accounts view under banking tab

### ISSUE THREAD

**Issue by JackPala** [akaunting/akaunting#2938]
### Akaunting version

3.0.12

### PHP version

7.4.10

### Operating system

Docker Version in Ubuntu Host

### Steps to reproduce

Use a 3 digit currency identifier code and characters overlap. Attached photo for reference in Additional comments. Running on Mac OS using Brave browser at full desktop width

### Expected result

CSS spacing

### Actual result

overlap

### Additional comments

<img width="600" alt="Screenshot 2023-03-14 at 9 45 20 PM" src="https://user-images.githubusercontent.com/2214871/225192054-289d3bc8-d944-44c3-9d86-ad2781a93233.png">

**Comment by cuneytsenturk** [comment]
Already **akaunting** latest version use overlap

![image](https://github.com/akaunting/akaunting/assets/10936547/eccce6fa-28e8-4c26-a425-f453750551ae)

Please check this secrenshot
