### ISSUE TITLE
could not add payment to invoice and bill. got error

### ISSUE THREAD

**Issue by bhojkamal** [akaunting/akaunting#2948]
### Akaunting version

3.0.12

### PHP version

8.1

### Operating system

windows and Ubuntu

### Steps to reproduce

Create any bill or invoice and add payment for any of them.
The payment could not be saved. 

### Expected result

We expect the payment take and save and redirect list of invoices. 

### Actual result

{"success":false,"error":true,"data":null,"message":"Call to undefined method App\\Builders\\Category::disableModelCaching()","redirect":null}
got this response.
could not save payment

### Additional comments

I have double-entry, Inventory and credit-debit notes app as well,

### Relevant log output

```shell
I have following data on payload. 
`_method: POST
(empty)
null: 
amount: 5300
number: TRA-00001
reference: 
document_id: 2
category_id: 12
currency_code: NPR
currency_rate: 1
type: expense
description: 
payment_method: offline-payments.cash.1
account_id: 1
de_account_id: 6
paid_at: 2023-03-22
currency: NP Rupees`
This is on network tab of web dev tools.
there is nothing on console tab.
```

**Comment by cuneytsenturk** [comment]
Please re-run `composer:update` then test again.
