### ISSUE TITLE
Unknown or bad timezone on recurring check

### ISSUE THREAD

**Issue by nemerald-voip** [akaunting/akaunting#2961]
### Akaunting version

3.0.14

### PHP version

8.1.12

### Operating system

Debian 11

### Steps to reproduce

When I run the command manually 
`php artisan recurring:check`

It gives me the following error:

`  at app/Traits/Recurring.php:145
    141▕     }
    142▕ 
    143▕     public function getRecurringRuleDate($date)
    144▕     {
   145▕         return new \DateTime($date, new \DateTimeZone($this->getRecurringRuleTimeZone()));
    146▕     }
    147▕ 
    148▕     public function getRecurringRuleTimeZone()
    149▕     {

  1   app/Traits/Recurring.php:145
      DateTimeZone::__construct()

  2   app/Traits/Recurring.php:125
      App\Models\Common\Recurring::getRecurringRuleDate()`

### Expected result

I'm not sure If this command is meant to be run manually, but I noticed that recurring invoices aren't generating either on the schedule. 

### Actual result

It doesn't look like this value 
`setting('localisation.timezone');`
is initiated at the time the script runs.

**Comment by nemerald-voip** [comment]
I tested and scheduled invoices generated. It's just I can't manually force the command by running 
`php artisan recurring:check`

**Comment by cuneytsenturk** [comment]
Thank your feedback @nemerald-voip 

You can set the timezone on [Locatization](https://akaunting.com/hc/docs/settings/localization/) setting page, after that You can not forget, You have to set [cron](https://akaunting.com/hc/docs/settings/scheduling/) settings.
