### ISSUE TITLE
Error SQL State

### ISSUE THREAD

**Issue by bhonsle-chand** [akaunting/akaunting#2965]
### Akaunting version

2.1.20

### PHP version

8.2

### Operating system

Self Hosting

### Steps to reproduce

Account Creation Modification 

### Expected result

Send email or do the necessary 

### Actual result

SQLSTATE[HY000]: General error: 1364 Field 'user_type' doesn't have a default value (Connection: mysql, SQL: insert into `cy4_user_roles` (`role_id`, `user_id`) values (1, 8))

### Additional comments

SQLSTATE[HY000]: General error: 1364 Field 'user_type' doesn't have a default value (Connection: mysql, SQL: insert into `cy4_user_roles` (`role_id`, `user_id`) values (1, 8))

### Relevant log output

```shell
SQLSTATE[HY000]: General error: 1364 Field 'user_type' doesn't have a default value (Connection: mysql, SQL: insert into `cy4_user_roles` (`role_id`, `user_id`) values (1, 8))
```

**Comment by ratanclinics** [comment]
SQLSTATE[HY000]: General error: 1364 Field 'user_type' doesn't have a default value (Connection: mysql, SQL: insert into `vpn_user_roles` (`role_id`, `user_id`) values (2, 3))

**Comment by ratanclinics** [comment]
SQLSTATE[HY000]: General error: 1364 Field 'user_type' doesn't have a default value (Connection: mysql, SQL: insert into `vpn_user_roles` (`role_id`, `user_id`) values (2, 10))

**Comment by cuneytsenturk** [comment]
@bhonsle-chand I think, [2022_07_21_000000_core_v305.php](https://github.com/akaunting/akaunting/blob/master/database/migrations/2022_07_21_000000_core_v305.php) not working for you. Please check the migrations table. If you can run this migration file, it solve all issues.

Thank you for feedback
