### ISSUE TITLE
Recurring Invoice Custom Interval

### ISSUE THREAD

**Issue by jaiume** [akaunting/akaunting#2975]
### Akaunting version

3.0.14

### PHP version

8.1

### Operating system

Debian 10

### Steps to reproduce

Create Recurring Invoice Template
Set Interval to be Custom
Set to every 3 months
Save recurring invoice template
Edit invoice template
Interval goes back to monthly

### Expected result

Interval will stay configured as custom

### Actual result

Interval reverts to monthly

**Comment by cuneytsenturk** [comment]
@jaiume Thank your feedback
