### ISSUE TITLE
Recurring invoice incorrect next invoice

### ISSUE THREAD

**Issue by jaiume** [akaunting/akaunting#2976]
### Akaunting version

3.0.14

### PHP version

8.1

### Operating system

Debian 10

### Steps to reproduce

Create recurring invoice template
Set interval to custom 3 months
Set Create First Invoice in the future
Save recurring invoice template
Blue notification box shows next invoice when second invoice should be
Schedule shows 'since' even though first invoice is in the future

### Expected result

Blue notification box should show first invoice
Schedule should show that first invoice will be on future date

### Actual result

Blue Notification box shows when second invoice will be
Schedule shows future date of first invoice as be 'since'

**Comment by cuneytsenturk** [comment]
Hi @jaiume,

I've checked this case, but it's work.
Please look at the screenshots.

![create-recurring-invoice-template](https://github.com/akaunting/akaunting/assets/10936547/52221648-e169-4705-9e46-6d28bad1a115)

![show-recurring-invoice-template](https://github.com/akaunting/akaunting/assets/10936547/5199b1c0-2934-4492-857e-1894cfd5f042)

**Comment by cuneytsenturk** [comment]
@jaiume Please check your **scheduling** > cron configuration https://akaunting.com/hc/docs/settings/scheduling/
