### ISSUE TITLE
Customer information on Invoices formatted incorrectly

### ISSUE THREAD

**Issue by deleonbe** [akaunting/akaunting#2985]
### Akaunting version

3.0.15

### PHP version

8.1.2

### Operating system

Ubuntu 22.04.2

### Steps to reproduce

Create an invoice and print to PDF

### Expected result

Expect Customer address to be formatted correctly for mailing.
The line that includes the city, state zipcode is not displaying correctly.

### Actual result

It displays city, zip, sate

**Comment by cuneytsenturk** [comment]
@deleonbe Thank your your feedback.
