### ISSUE TITLE
Change the filename of the Norwegian flag from nb.png to no.png

### ISSUE THREAD

**Issue by kanenas** [akaunting/akaunting#301]
**Akaunting**: v.1.1.15-Stable

In "Header Navbar" > "Change Language" the flag for **Norway** (Norsk Bokmål) is not displayed.
You should change the filename from `/vendor/akaunting/language/src/Resources/assets/img/flags/nb.png` to `/vendor/akaunting/language/src/Resources/assets/img/flags/no.png`

**Comment by denisdulici** [comment]
Thanks Nikolas, just fixed https://github.com/akaunting/language/releases/tag/1.0.5
