### ISSUE TITLE
Can not delete invoice payment

### ISSUE THREAD

**Issue by meaz** [akaunting/akaunting#3013]
### Akaunting version

3.0.16

### PHP version

8.1.18

### Operating system

Debian bullseye

### Steps to reproduce

- Create an invoice
- Add a payment
- Go back to this invoice
- Click on "Delete payment" then "Delete" to confim

### Expected result

Payment is removed

### Actual result

The Delete button spins endlessly.

### Additional comments

Nothing in the logs...

**Comment by cuneytsenturk** [comment]
Hello,

I've tested this case but, I works please watch this video =>
[invoice-payment-issue-fixed.webm](https://github.com/akaunting/akaunting/assets/10936547/55c14fd7-f55f-4b10-8107-c6b33508d40d) or link
 https://sharing.clickup.com/clip/p/t4755221/9393c225-5d85-4bf2-b5c0-febe6f62e4d2/screen-recording-2023-08-10-10%3A20.webm
