### ISSUE TITLE
[Bug] Error when update from 2.1.33 to 3.0.13

### ISSUE THREAD

**Issue by sshcli** [akaunting/akaunting#3044]
### Akaunting version

2.133

### PHP version

 8.1

### Operating system

CentOS v7.9.2009 STANDARD kvm

### Steps to reproduce

Just try to update from 2.1.33 to 3.0.13 by using the update button in the backend

### Expected result

It should run a check first, to see if all minimum requirements are ok before start the major update process

### Actual result

Once you press the update button, the website will crash, and you will need to make a new installation or restore a backup

**Comment by cuneytsenturk** [comment]
Already, Akaunting has this package. Firstly, You should update 2.1.36 then checking all control then update Akaunting 3.x version.

Akaunting old version customer used this method.
