### ISSUE TITLE
getting error when run composer install

### ISSUE THREAD

**Issue by tauseedzaman** [akaunting/akaunting#3047]
### Akaunting version

latest

### PHP version

8.2

### Operating system

22.04

### Steps to reproduce

when i run compose install or update i am getting this error

![image](https://github.com/akaunting/akaunting/assets/64689921/8bc44f26-9b16-4f0f-9e09-2de1c3537411)

### Expected result

![image](https://github.com/akaunting/akaunting/assets/64689921/b0a005f5-0649-4d68-be5e-47bd0219f9a5)

### Actual result

it should install the dependencies as mentioned in the docs

### Additional comments

any help is appricated

**Comment by tatlicak** [comment]
I got this error too.

**Comment by cuneytsenturk** [comment]
This is not an error, and it only shows information. Because your akaunting can not connection database.
