### ISSUE TITLE
Payment issues in both invoicing and bills

### ISSUE THREAD

**Issue by Simon-Doc** [akaunting/akaunting#3063]
### Akaunting version

3.1.1

### PHP version

8.2.10

### Operating system

Ubuntu 20.04

### Steps to reproduce

Bug 1:
When adding payment of invoice. The system is only accepting the amount before the decimal point.
EG Make adding payment of invoice for £125.23. Only £125.00 is entered with the £0.23 left outstanding. Trying to make payment of the £0.23 results in an error.

Bug 2:
When adding payment in bills The system is not accepting the full amount.
EG: Add payment of £8.62 on a bill of £8.62 comes up with the error: Error: Payment not added! The amount you entered passes the total: £8.62.
Error is not there if you add a partial payment below this amount EG: £8.61 but then there is an amount outstanding obviously.

### Expected result

Payments to be added.

### Actual result

See above.

**Comment by markoftw** [comment]
Can confirm, happens on my end as well.
