### ISSUE TITLE
Icon pwa not found

### ISSUE THREAD

**Issue by dadeke** [akaunting/akaunting#3068]
### Akaunting version

3.1.2

### PHP version

8.1.17

### Operating system

Rocky Linux 9.1

### Steps to reproduce

Icon pwa 404 not found

https://app.akaunting.com/public/img/pwa/akaunting-512x512.png

### Expected result

Found

https://app.akaunting.com/public/img/pwa/icon-512x512.png

### Actual result

Lines 10 and 16:

https://github.com/akaunting/akaunting/blob/39aba3a14fbeb92db46315acff8d974cc576d263/resources/views/components/layouts/pwa/head.blade.php#L10-L16

It needs change `akaunting-512x512.png` to `icon-512x512.png` or rename file. 👨‍💻

### Additional comments

Can I submit a pull request? 🙂

**Comment by cuneytsenturk** [comment]
Thank your feedback @dadeke
