### ISSUE TITLE
Offline Payment Methods not available in settings menu

### ISSUE THREAD

**Issue by kawish** [akaunting/akaunting#3096]
### Akaunting version

3.1.4

### PHP version

8.1

### Operating system

Ubuntu 22

### Steps to reproduce

Open settings menu

### Expected result

Offline Payment Methods should be visible and allow adding custom payment method

### Actual result

Offline Payment Methods option is inaccessible

**Comment by kawish** [comment]
![Screenshot 2023-11-23 183459](https://github.com/akaunting/akaunting/assets/12142095/3e2196fd-8e5b-4158-8029-a9debedecb42)

**Comment by cuneytsenturk** [comment]
Hello,

As you know, Offline payments and PayPal standard modules come with core Akaunting software.

Please ensure that the Offline payment module files are on your server and check that offline payment is active in the modules table in the database.

**Comment by HolFl465** [comment]
I opened an issue regarding this.

The files are present and permissions are correct. Module is enabled in DB.

When trying to access the module with the URL I get a 403 Forbidden splash screen.

**Comment by jaiume** [comment]
I also opened an issue, and it got deleted. Looking for some help
