### ISSUE TITLE
Recurring with adviced crontab not doing anything

### ISSUE THREAD

**Issue by meredrica** [akaunting/akaunting#3106]
### Akaunting version

3.1.4

### PHP version

8.2.12

### Operating system

don't know

### Steps to reproduce

1. Create a recurring invoice/.
2. Set up the crontab as told on the settings page. I run it every minute
3. set the delivery time
4. wait for the crontab to fire (of execute it yourself)

### Expected result

Email is sent, new invoice is created

### Actual result

nothing happens (no new invoice, no email)

### Additional comments

If i run the artisan `recurring:check` manually it works. 

Here's the output of running `php artisan schedule:run`:
```bash
artisan schedule:run
  2023-11-30 20:30:17 Running ['artisan' firewall:unblockip]  249ms DONE
  ⇂ '/usr/local/bin/php' 'artisan' firewall:unblockip > '/dev/null' 2>&1
```
running `artisan recurring:check` creates all the invoices and sends the emails.
it doesn't however attach the invoices as pdf

**Comment by cuneytsenturk** [comment]
I've tested clean Akaunting and already used this feature cloud, and it is works. Please check your schedule command.
