### ISSUE TITLE
Error while installing: Uncaught Error: Failed opening required '/home/ubuntu/akaunting/bootstrap/.

### ISSUE THREAD

**Issue by timonson** [akaunting/akaunting#3133]
### Akaunting version

3.0.13 dev

### PHP version

PHP 8.1.2-1ubuntu2.14

### Operating system

Ubuntu 22.04 LTS

### Steps to reproduce

The installation steps inside the README.

### Expected result

It works.

### Actual result

PHP Fatal error:  Uncaught Error: Failed opening required '/home/ubuntu/akaunting/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/ubuntu/akaunting/bootstrap/autoload.php:20

**Comment by cuneytsenturk** [comment]
## Installation

* Install [Composer](https://getcomposer.org/download) and [Npm](https://nodejs.org/en/download)
* Clone the repository: `git clone https://github.com/akaunting/akaunting.git`
* Install dependencies: `composer install ; npm install ; npm run dev`
* Install Akaunting:

```bash
php artisan install --db-name="akaunting" --db-username="root" --db-password="pass" --admin-email="admin@company.com" --admin-password="123456"
```

* Create sample data (optional): `php artisan sample-data:seed`

**Comment by timonson** [comment]
php artisan install --db-name="akaunting" --db-username="root" --db-password="pass" --admin-email="admin@company.com" --admin-password="123456"
> PHP Warning:  require(/home/ubuntu/akaunting/bootstrap/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/ubuntu/akaunting/bootstrap/autoload.php on line 20
PHP Fatal error:  Uncaught Error: Failed opening required '/home/ubuntu/akaunting/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/ubuntu/akaunting/bootstrap/autoload.php:20
Stack trace:
#0 /home/ubuntu/akaunting/artisan(14): require()
#1 {main}
  thrown in /home/ubuntu/akaunting/bootstrap/autoload.php on line 20

**Comment by Frebbers** [comment]
@timonson did you manage to solve the issue? I'm having the same and wondering if it is related to dependencies being incorrectly installed.
