### ISSUE TITLE
 Deprecated: Optional parameter

### ISSUE THREAD

**Issue by Yousha** [akaunting/akaunting#3148]
### Akaunting version

3.1.6-Stable

### PHP version

8.3.4 64bit TS

### Operating system

Windows 10 Pro 64bit

### Steps to reproduce

- Download the stable version of app
- Extract it into the web root directory
- Open it via web browser: http://localhost/akaunting

### Expected result

Work without any error.

### Actual result

Deprecated: Optional parameter $request declared before required parameter $company_id is implicitly treated as a required parameter in C:\WWW\root\akaunting\app\Utilities\helpers.php on line 362

Deprecated: Optional parameter $request declared before required parameter $company_id is implicitly treated as a required parameter in C:\WWW\root\akaunting\app\Utilities\helpers.php on line 371

### Additional comments

HTTP server: Apache HTTPD 2.4.58 64bit
Database server: MariaDB 10.11.7 64bit
Web root directory: C:\WWW\root\

**Comment by cuneytsenturk** [comment]
When I tried the latest version on a clean Windows installation, I encountered no problems.

I am sending you the [documentation](https://akaunting.com/hc/docs/on-premise/installation/) of the Akaunting installation steps. Please follow it and try to install it again.

_Note:_ Make sure that your server meets all [requirements](https://akaunting.com/hc/docs/on-premise/requirements/) requirements.

**Comment by sh4msi** [comment]
hi,
I have the same problem

![image](https://github.com/akaunting/akaunting/assets/6229984/869778ad-9130-463f-b2fa-b15ece2c9fe8)

**Comment by sh4msi** [comment]
> When I tried the latest version on a clean Windows installation, I encountered no problems.
> 
> I am sending you the [documentation](https://akaunting.com/hc/docs/on-premise/installation/) of the Akaunting installation steps. Please follow it and try to install it again.
> 
> _Note:_ Make sure that your server meets all [requirements](https://akaunting.com/hc/docs/on-premise/requirements/) requirements.


hi,
I have the same problem

![image](https://github.com/akaunting/akaunting/assets/6229984/869778ad-9130-463f-b2fa-b15ece2c9fe8)

**Comment by DGEllis** [comment]
My environment is Almalinux 9.5, PHP 8.3 and Nginx 1.24. I have this error also.

I followed the instructions carefully, choosing to let the installer build the .env file for me. I get a blank screen. Enabling errors in PHP gave the following:

Deprecated: Optional parameter $request declared before required parameter $company_id is implicitly treated as a required parameter in /usr/share/nginx/akaunting/app/Utilities/helpers.php on line 408

Deprecated: Optional parameter $request declared before required parameter $company_id is implicitly treated as a required parameter in /usr/share/nginx/akaunting/app/Utilities/helpers.php on line 417

Please advise. Thank you.
