### ISSUE TITLE
Bug in new release 3.1.7

### ISSUE THREAD

**Issue by stojankukrika** [akaunting/akaunting#3160]
### Akaunting version

3.1.7

### PHP version

8.2

### Operating system

Ubuntu 20.04

### Steps to reproduce

Can't click on any page, in console shows only this error:
<img width="1703" alt="Screenshot 2024-05-03 at 08 42 19" src="https://github.com/akaunting/akaunting/assets/10199584/b790075a-b4eb-4a7f-b75f-5d45606cb482">

### Expected result

Can't click on any page, in console shows only this error:
<img width="1703" alt="Screenshot 2024-05-03 at 08 42 19" src="https://github.com/akaunting/akaunting/assets/10199584/b790075a-b4eb-4a7f-b75f-5d45606cb482">

### Actual result

Can't click on any page, in console shows only this error:
<img width="1703" alt="Screenshot 2024-05-03 at 08 42 19" src="https://github.com/akaunting/akaunting/assets/10199584/b790075a-b4eb-4a7f-b75f-5d45606cb482">

### Additional comments

This happened after update on last version 3.1.7

**Comment by cuneytsenturk** [comment]
We have identified the cause of the error and we have 2 solutions for you

1- delete `public/vendor/livewire` and `public/vendor/alpinejs` folders

2- We will release version **3.1.8**, if you switch to it, the problem will be solved.

**{YOUR_DOMAIN}/{YOUR_COMPANY_ID}/install/updates**
Example: app.akaunting.com/1/install/updates

or you can run a manual update.

  If you have SSH access to your server, you can update Akaunting manually.
  
  You should run the following command from the console:
  
`  php /your/akaunting/directory/artisan update:all`
