### ISSUE TITLE
Attachments in bills/invoices not downloadable anymore after update

### ISSUE THREAD

**Issue by alexbela** [akaunting/akaunting#3161]
### Akaunting version

3.1.7

### PHP version

8.1

### Operating system

Ubuntu 20.04.6 LTS

### Steps to reproduce

- Use any Akaunting version lower than the recent one
- Add attachments (e.g. PDF files) to your bills/invoices
- Update Akaunting to a more recent version
- Reopen the bill/invoice and try to open the attachment -> a blank screen appears

### Expected result

Attachments can be downloaded again after update of Akaunting version

### Actual result

Blank screen

**Comment by cuneytsenturk** [comment]
I tested the issue you mentioned in a clean install Akaunting, but I did not encounter any problems. The cause of this problem may be related to the file permissions on your server. During the update, no action is taken including the files you have uploaded during the update.
