### ISSUE TITLE
Menu vanished after update

### ISSUE THREAD

**Issue by thesamug** [akaunting/akaunting#3162]
### Akaunting version

3.1.8

### PHP version

8.2.4

### Operating system

Windows 10

### Steps to reproduce

I am using Akaunting on my personal computer (local host) for creating local invoices. With the recent update installed, I am facing the following issues.

1. My whole menu has vanished and is not loading properly.
2. Software is stuck only on the dashboard other pages are also inaccessible.
3. As I decide to load the pages via typing the URL in the address bar, the page loads and the loader keeps loading till infinity
I have attached a video for you to look over so you can better diagnose the issue.

https://github.com/akaunting/akaunting/assets/169035881/cf092b1e-41e9-4840-bae3-7c436a2c93ca

### Expected result

I was expecting a smoother and better performance.

### Actual result

I have already explained.

**Comment by cuneytsenturk** [comment]
We have identified the cause of the error and we have 2 solutions for you

1- delete `public/vendor/livewire` and `public/vendor/alpinejs` folders

2- We will release version **3.1.8**, if you switch to it, the problem will be solved.

**{YOUR_DOMAIN}/{YOUR_COMPANY_ID}/install/updates**
Example: app.akaunting.com/1/install/updates

or you can run a manual update.

  If you have SSH access to your server, you can update Akaunting manually.
  
  You should run the following command from the console:
  
`  php /your/akaunting/directory/artisan update:all`

**Comment by mvdgun** [comment]
Sorry to revive this old issue but it seems I am having the same issue on a fresh Akaunting install via de Docker method. When navigating to a different page (the "New dashboard" for instance) and going back sometimes the menu actually displays again. I am running the 3.1.14 as displayed in the footer of the app.
