### ISSUE TITLE
Error in seeder file, "arguement company" missing

### ISSUE THREAD

**Issue by meghakundu** [akaunting/akaunting#3170]
### Akaunting version

3.1.8

### PHP version

8.2.0

### Operating system

windows10

### Steps to reproduce

error comes when we seed data in db.

### Expected result

php artisan db:seed --class=AccountSeeder

![image](https://github.com/akaunting/akaunting/assets/54468245/abbb3616-79fe-45ec-a40e-e7016b5f3954)

### Actual result

![image](https://github.com/akaunting/akaunting/assets/54468245/f6820dc6-d17e-4905-84ac-b4425bb5ac7d)

### Additional comments

The naming of seeder files should be proper.

**Comment by cuneytsenturk** [comment]
You don't need to run a piecemeal seeder to install Akaunting. 

`php artisan install --db-name=‘akaunting’ --db-username=‘root’ --db-password=‘pass’ --admin-email=‘admin@company.com’ --admin-password=‘123456’`

You can install it in one line using the command here.

If you want to run Account seeder alone. You must also specify the company_id you want this seeder to run.
