### ISSUE TITLE
Frontpage/site not working

### ISSUE THREAD

**Issue by meghakundu** [akaunting/akaunting#3171]
### Akaunting version

3.1.8

### PHP version

8.2.0

### Operating system

windows10

### Steps to reproduce

after running command "php artisan serve" , homepage shows error.
![image](https://github.com/akaunting/akaunting/assets/54468245/8eda7878-c5f3-4312-b9c4-22dce1a2ebea)

### Expected result

any login screen!

### Actual result

![image](https://github.com/akaunting/akaunting/assets/54468245/575170fe-63dc-478a-ba1e-0d2395935f9c)

**Comment by cuneytsenturk** [comment]
Akaunting doesn't ship with serve command, it works fine on your xampp server.

Or 

simply you can run with `php -S localhost:8000`
