### ISSUE TITLE
BUG: Recurring Invoices: Sort by "Start Date" crashes with 500

### ISSUE THREAD

**Issue by DarkSil3ncer** [akaunting/akaunting#3172]
### Akaunting version

3.1.18

### PHP version

8.1

### Operating system

Linux

### Steps to reproduce

**Pre-requisites**
Have a few recurring templates (recurring invoices) created.
**Steps to reproduce**

1. Navigate to Sales > Invoices
2. Click on the Recurring Templates tab
3. Click on the Start Date (Last Issued) column heading to sort by Start Date.

### Expected result

The table will be sorted by Start Date (Last Issued).

### Actual result

The site crashes with 500 Internal Server Error.

### Additional comments

Here is the URL it tries to navigate to with xxxx as domain placeholders: https://www.xxxxx.com/1/sales/recurring-invoices?sort=recurring.started_at&direction=asc

**Comment by cuneytsenturk** [comment]
This issue fixed this PF https://github.com/akaunting/laravel-sortable/pull/1

**Comment by cuneytsenturk** [comment]
Thanks for all helps @CihanSenturk
