### ISSUE TITLE
Public Index.php file is missing .....Error thrown when i setup this app on local ubuntu os

### ISSUE THREAD

**Issue by rashidtufail84** [akaunting/akaunting#3184]
### Akaunting version

3.1.8

### PHP version

8.3

### Operating system

ubuntu 22.04.4 LTS

### Steps to reproduce

i simply unzip the download folder from the akaunting website and run php artisan serve command then i try to access it using 127.0.0.1:8000 it say 500 error on browser and give this on terminal

PHP Warning: require_once(public/index.php): Failed to open stream: No such file or directory in vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php on line 16.

PHP Fatal error: Uncaught Error: Failed opening required 'public/index.php' (include_path='.:/usr/share/php') in vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php:16.

thrown in vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php on line 16.

### Expected result

it should display me setup page as described in the documentation

### Actual result

it gives you this page is not working error 500

**Comment by rashidtufail84** [comment]
![Screenshot from 2024-07-22 10-59-49](https://github.com/user-attachments/assets/8dfce0ce-4e13-48ae-8777-47f782f735db)

**Comment by ankushzest** [comment]
same issue

**Comment by rashidtufail84** [comment]
thanks @cuneytsenturk
