### ISSUE TITLE
Bug on installation 

### ISSUE THREAD

**Issue by rashidtufail84** [akaunting/akaunting#3185]
### Akaunting version

3.1.8

### PHP version

8.3

### Operating system

ubuntu 22.04.4 LTS

### Steps to reproduce

I simply unzip the project and then run php artisan serve command ....after this i simply access it through my browser

![image](https://github.com/user-attachments/assets/6371b291-efc4-40b9-98d3-883bd9cef6a1)

### Expected result

should display installation window

### Actual result

give error 500

**Comment by cuneytsenturk** [comment]
Akaunting doesn't ship with serve command, it works fine on your xampp server.

or 

simply you can run with `php -S localhost:8000`
