### ISSUE TITLE
Users and profile aren't working when using Gravatar

### ISSUE THREAD

**Issue by EgyptianM** [akaunting/akaunting#319]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Go to Settings->General->Appearance
Set Use Gravatar to Yes

### Expected result
Users and profile are working 

### Actual result
In Users case:
Whoops, looks like something went wrong.
```
(2/2) ErrorException
Trying to get property of non-object (View: /home/galebplc/markets.ta3leemi.net/resources/views/auth/users/index.blade.php)
```
In Profile case:
```
(2/2) ErrorException
Trying to get property of non-object (View: /home/galebplc/markets.ta3leemi.net/resources/views/auth/users/edit.blade.php)
```

### System information (Akaunting, PHP versions)
Issue is in all releases including the stable version and 1.2.0 RC
PHP 7.0

**Comment by cuneytsenturk** [comment]
Thanks for reporting.
