### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by rashidtufail84** [akaunting/akaunting#3190]
### Akaunting version

3.1.8

### PHP version

8.3

### Operating system

ubuntu 22.04.4 LTS

### Steps to reproduce

unzip the downloaded project from akaunting.com
make .env file
then run php artisan serve
then try to access the project using browser

### Expected result

it should display the installation screen

### Actual result

it gives error  500 see the below pictures
![image](https://github.com/user-attachments/assets/91b5dec4-dbb7-46be-91cc-dbe22bc624ed)
![image](https://github.com/user-attachments/assets/07aba82b-0647-46cc-be9c-7902109a7029)

**Comment by cuneytsenturk** [comment]
Your method of uploading is incorrect.

if you downloaded the zip from akaunting.com.

There is no need to create .env by hand and do artisan serve.

When you go directly to the directory, you will encounter the installation page.

Please start the installation again and try again.
