### ISSUE TITLE
"Access denied" after trying to send invoice email

### ISSUE THREAD

**Issue by HolFl465** [akaunting/akaunting#3193]
### Akaunting version

3.1.9

### PHP version

8.1.29

### Operating system

Debian 12

### Steps to reproduce

Send invoice email, then reload page

### Expected result

Sends email. Page reloads normally.

### Actual result

After clicking on "Send" nothing happens and when we try to reload the page we get "Access denied"
![image](https://github.com/user-attachments/assets/38a3af34-c781-4594-b963-6e608d133057)

**Comment by HolFl465** [comment]
UPDATE: If I manually remove the Akaunting footer text it works.

**Comment by o850cHQk** [comment]
Have had the same issue here. Email is not sending and then the ip address has been added to the xyz_firewall_ips database.

**Comment by HolFl465** [comment]
I deactivated the firewall in .env but the ip is still blocked.

i‘ll try to remove the ip from the db

**Comment by HolFl465** [comment]
Workaround: disable firewall + remove entries in xxx_firewall_ips AND xxx_firewall_logs
