### ISSUE TITLE
Weird Comment appended to invoices when printed / download pdf

### ISSUE THREAD

**Issue by o850cHQk** [akaunting/akaunting#3194]
### Akaunting version

3.1.9

### PHP version

8.1

### Operating system

Ubuntu 24.04

### Steps to reproduce

Go to an invoice and select print or download pdf.

### Expected result

Invoice to display.

### Actual result

Invoice is displayed with an appended comment.
```//should queue control added for bulk action download``` 

### Additional comments

I have tested this with and without a footer since there is currently an issue with this that I am also being affected with.
However this does not seem to change anything.

**Comment by HolFl465** [comment]
I can confirm this bug on my install.

**Comment by cuneytsenturk** [comment]
This issue solved this [PR](https://github.com/akaunting/akaunting/pull/3189) and next release solved it v 3.1.10
