### ISSUE TITLE
Documentation doesn't open

### ISSUE THREAD

**Issue by Messhias** [akaunting/akaunting#3198]
### Akaunting version

it's the website

### PHP version

it's the website

### Operating system

it's the website

### Steps to reproduce

Just open https://akaunting.com/hc/docs/

### Expected result

See the doc

### Actual result

<img width="1474" alt="image" src="https://github.com/user-attachments/assets/c62ccb76-6b89-4f23-8760-99f6a22814ab">

**Comment by jryio** [comment]
Also experiencing this. Will look for the offending line and make a PR if possible.

**Comment by CloudMyn** [comment]
Any updates?

**Comment by cuneytsenturk** [comment]
The white page error of the help centre and documentation has been solved, you can go and use it now.

**Comment by jryio** [comment]
@cuneytsenturk you deserve a medal thank you!
