### ISSUE TITLE
Invoice payments to partially paid invoice

### ISSUE THREAD

**Issue by vitis586** [akaunting/akaunting#3212]
### Akaunting version

3.1.11

### PHP version

Cloud Trial

### Operating system

Cloud Trial

### Steps to reproduce

1. Start a company with two currencies - I chose CZK as default and USD as secondary
2. Change the currency rate between them to something sensible - I chose 0.03 USD for 1 CZK
3. Create an invoice for 350 USD
4. Pay it partially with 2000 CZK and 1000 CZK

### Expected result

1. I would expect that the payment should reflect the currency of the selected target account
2. I would expect that the tickbox actually work a bit different
- When Pay in Full is selected the Currency rate and Amount is disabled (greyed out) and in the amount is the remaining amount to pay in the correct currency (In this case 8666,67 CZK)
- When Pay in Full is not selected I should be able to type in the amount that was paid

### Actual result

1. If you want to add another payment the currency does not reflect the selected account - the account Hotovost is in CZK (the amount is correct, just in different currency)
2. Pay in full tick box just enables and disables the currency rate - which is not 1 but 0,03

![obrazek](https://github.com/user-attachments/assets/b11cf425-2153-49a7-bb5a-3b3dc3e1a864)

**Comment by cuneytsenturk** [comment]
This issue solved this commit https://github.com/akaunting/akaunting/commit/90b30b98a0f50c7fade593593df6fc2ff96f82f0 Thank for your feedback
