### ISSUE TITLE
Is the Public folder missing index.php and other necessary files?

### ISSUE THREAD

**Issue by Samimi-Information-Technology** [akaunting/akaunting#3228]
### Akaunting version

Akaunting_3.1.12-Stable

### PHP version

PHP 8.2.12

### Operating system

Windows XAMPP

### Steps to reproduce

The error shown missing `index.php`

Screen shot below:

![image](https://github.com/user-attachments/assets/ef57696c-ad77-42df-b828-23522ddd0a35)

I also checked the repo `public` folder and the file `index.php` is not there as of opening this issue. 

Screen shot below:

![image](https://github.com/user-attachments/assets/c05f9fc0-ab42-46e9-b254-b09aebedafde)

No problems with `composer install` and `npm install` and `npm run dev`
No problems with `migrations `nor `database`

What am I missing?

### Expected result

to show the login page?

### Actual result

Error missing `index.php`

**Comment by cuneytsenturk** [comment]
index.php of Akaunting is in the root of it.

Also you can read this documentation => https://akaunting.com/hc/docs/on-premise/installation/ 

and you can read github readme how to install Akaunting.

**Comment by Samimi-Information-Technology** [comment]
Thank you for replying.

I have it installed already through the installer wizard and config.

I was wondering if i can go about as a normal laravel repo deploy process with git clone, composer, npm, artisan which is failing.

Why no `public/index.php` as the standard approach?

**Comment by rizaldywirawan** [comment]
The same question as @Samimi-Information-Technology
