### ISSUE TITLE
BUG: Dashboard - Calendar Control

### ISSUE THREAD

**Issue by DarkSil3ncer** [akaunting/akaunting#3230]
### Akaunting version

3.1.12

### PHP version

8.1

### Operating system

Linux

### Steps to reproduce

1. Open the Dashboard
2. Click on calendar icon
3. Click "Previous Year"
4. Click "This Year"

### Expected result

Should be taken back to the current financial year.

### Actual result

Stays on the current year. Giving the "Steps to reproduce" the value in the calendar control will be the "Previous Year" values.

**Comment by cuneytsenturk** [comment]
This issue solved [here](https://github.com/akaunting/akaunting/pull/3231)
