### ISSUE TITLE
Invoice Reminders not working

### ISSUE THREAD

**Issue by jaiume** [akaunting/akaunting#3235]
### Akaunting version

3.1.12

### PHP version

8.2

### Operating system

Debian 11

### Steps to reproduce

Invoice reminders working on 3.1.11
Update to 3.1.12
Invoice reminders not working on 3.1.12

### Expected result

Invoice reminders working

### Actual result

Invoice reminders not working
Other emails being sent out as normal

### Additional comments

One click update got stuck during the update process (seems to be a regular occurrence with recent updates)
Did artisan update
Did artisan migrate

**Comment by cuneytsenturk** [comment]
If you had a problem during the update, you can review the update in the documentation for this.

https://akaunting.com/hc/docs/on-premise/update/
