### ISSUE TITLE
'New :type' , 'Edit :type' translation error in Arabic (RTL language)

### ISSUE THREAD

**Issue by EgyptianM** [akaunting/akaunting#324]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1- Open Add new bill/invoice/revenue ... etc form
2- Open Edit bill/invoice/revenue ... etc form

### Expected result
1- Expect to see the translation of 'New Bill', "New Invoice'... etc
2- Expect to see the translation of 'Edit Bill', "Edit Invoice'... etc

### Actual result
1- It shows the literally translation of 'New :type' 
2- It shows the literally translation of 'Edit :type' 
This means it shows New : type instead of New Bill but in Arabic

### System information (Akaunting, PHP versions)
Akaunting all releases , php 7

**Comment by denisdulici** [comment]
Fixed in Crowdin, you can join and contribute here https://crowdin.com/project/akaunting
