### ISSUE TITLE
Please Re-Open Bug 3148 as it is Not Fixed.

### ISSUE THREAD

**Issue by DGEllis** [akaunting/akaunting#3242]
### Akaunting version

Latest as of 20241130

### PHP version

8.3.14

### Operating system

Almalinux 9.5

### Steps to reproduce

Follow the installation instructions and browse to the URL

### Expected result

The installation script

### Actual result

I get a blank screen. I enable PHP errors and get the same error as in #3148 

### Additional comments

I have verified that all PHP modules are installed. 
I have followed the installation instructions carefully. 

This isn't a missing PHP module. It is a problem with the Akaunting code not keeping up with PHP development.

### Relevant log output

```shell
Deprecated: Optional parameter $request declared before required parameter $company_id is implicitly treated as a required parameter in /usr/share/nginx/akaunting/app/Utilities/helpers.php on line 408

Deprecated: Optional parameter $request declared before required parameter $company_id is implicitly treated as a required parameter in /usr/share/nginx/akaunting/app/Utilities/helpers.php on line 417
```

**Comment by cuneytsenturk** [comment]
The issue fixed this [commit](https://github.com/akaunting/akaunting/commit/a407c35ac2e4a599616fe81310b8178204d76bec)
