### ISSUE TITLE
After update to 1.2.1 the transfers page stop working 

### ISSUE THREAD

**Issue by Acvarium** [akaunting/akaunting#329]
Just updated Akaunting to 1.2.1 and page Banking -> Transfers stop working

![scr2018-05-05-15 09 54](https://user-images.githubusercontent.com/463177/39663154-b5b3075c-5076-11e8-8a4f-3d842e6d91b4.png)

### System information (Akaunting, PHP versions)
Akaunting 1.2.1
PHP 7.1.16

**Comment by denisdulici** [comment]
Just fixed here https://github.com/akaunting/akaunting/issues/327
