### ISSUE TITLE
Error on setup with table names

### ISSUE THREAD

**Issue by m-xn** [akaunting/akaunting#333]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Install 1.2.1

### Expected result
The installer to succed

### Actual result
It seems the installer created a random 3 chars prefix for the tables (like bzy_companies) but then when entering the company data in the last step the installer tries to install to ak_* tables, hence the error:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wherever.ak_companies'

Is there a configuration for the prefix of tables I could check?

Thanks,
Juan Martin.

**Comment by denisdulici** [comment]
That happens when your host doesn't allow Akaunting to rename .env.example file and/or write new data into .env file. Feel free to use the forum for further support.
