### ISSUE TITLE
Not allowing decimal tax rate

### ISSUE THREAD

**Issue by denisdulici** [akaunting/akaunting#334]
### Steps to reproduce the issue

Settings > Tax Rates > Add New

### Expected result

Decimal tax rate (7.7)

### Actual result

Converts to numeric (7)

### System information (Akaunting, PHP versions)

Akaunting 1.2

### Additional comments

https://akaunting.com/forum/discussion/development/swiss-tax

**Comment by kingemir** [comment]
Please reopen this issue. I'm using version 1.3.14 (on app.akaunting.com) and it's still rounding floats up to integer.

**Comment by DinoSane** [comment]
I second! The version 1.3.15 still have this behavior. A workaround is edit directly to your database the table nuw_taxes.

**Comment by kingemir** [comment]
@denisdulici Hello Denis, can you please reopen the issue? Thanks.

**Comment by Shirkit** [comment]
Hello, it seems that this issue is still present on @denisdulici on the cloud version of Akaunting.
