### ISSUE TITLE
Relation Invoice x Revenue and Bill x Payment

### ISSUE THREAD

**Issue by mrcssilvasouza** [akaunting/akaunting#335]
Dear,

The system is excellent and fulfills the functions well, but I found something that is bothering and disrupting the control. Invoices posted within Revenue should be paid in revenue, or when clicked pahgo, should open the revenue module to enter the date of payment and proof of payment. One module should be related to another. In the reference field, you should list the posted invoices and we associate the received revenue. The same should occur between Invoices x Payments

**Comment by denisdulici** [comment]
@mrcssilvasouza They're different income/expense items. Feel free to check the following articles:

https://akaunting.com/docs/faq/invoices-vs-revenues
https://akaunting.com/docs/faq/bills-vs-payments

**Comment by mrcssilvasouza** [comment]
Denis,

I know the difference. What I am saying is that the invoice is a process, the payment of that invoice is another, and the payment could be made in revenue, being that in the reference field, we would select the invoice. Or at least the system should accept more than one attachment on the invoice.
