### ISSUE TITLE
At least add an option to delete a bank transfers.

### ISSUE THREAD

**Issue by Acvarium** [akaunting/akaunting#338]
For now there is no option to edit bank transfers. But sometimes it is necessary. Give us at least option to delete transfer and create new. As I can understand, it will be just removing lines from 3 database tables 581_transfers, 581_payments, 581_revenues. It look like simple to do.

**Comment by denisdulici** [comment]
Please, use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum
