### ISSUE TITLE
Akaunting errors after adding a Composer package

### ISSUE THREAD

**Issue by m-xn** [akaunting/akaunting#341]
I am trying to add FPDF to create a document associated to the invoice data.

After doing:

`composer require setasign/fpdf`

Akaunting stopped working with the following error:

`Uncaught ReflectionException: Class App\Console\Kernel does not exist in /www/vendor/laravel/framework/src/Illuminate/Container/Container.php:729`

Happened when added other Composer components as well

Is there any special step involved on adding Composer packages to work alongside Akaunting?

### System information (Akaunting, PHP versions)
1.2.3

**Comment by denisdulici** [comment]
There is no any special step for Akaunting there but you may try to add it to `composer.json` file.
