### ISSUE TITLE
Importing Vendors/Customers seems not to work

### ISSUE THREAD

**Issue by sebadamus** [akaunting/akaunting#344]
### Steps to reproduce the issue
Download the Vendor/Customer template proposed by Akaunting, Vendors template contents equals to:
```
"user_id","name","email","tax_number","phone","address","website","currency_code","enabled","created_at","updated_at","deleted_at"
"","Test Vendor","test@vendor.com","","","","","USD","1","2017-11-30 00:00:00","2017-11-30 00:00:00",NULL
```
Based on this I create:
```
"user_id","name","email","tax_number","phone","address","website","currency_code","enabled","created_at","updated_at","deleted_at"
"","Proveedor prueba1","myemail@gmail.com","Nro CUIT Proveedor prueba1 Pesos","","Direccion Proveedor prueba1 Pesos","","USD",1,"2017-11-30 00:00:00","2017-11-30 00:00:00",NULL
```
### Expected result
The Vendors/Clients populate with my CSV, as I did long time ago first time with 1.1x (or 1.0x, cant remember)

### Actual result
After the import process message says "Vendors imported", but no vendors appears.  The same happens trying Customers import.

### System information (Akaunting, PHP versions)
Akaunting 1.2.2, 1.2.3, 1.2.4
PHP 7.0

### Additional comments
The database also appears empty at xx_customers and xx_vendors tables.
Also tried without first line header and without ""
Have debug enabled but no error seems to appear.
Test it on my server and online www.akaunting.com self hosted.

Attached CSV files in a zip.
[CSV_files.zip](https://github.com/akaunting/akaunting/files/2007872/CSV_files.zip)

**Comment by denisdulici** [comment]
Just fixed here https://github.com/akaunting/akaunting/issues/347
