### ISSUE TITLE
Bill item prices must use point as decimal separator,

### ISSUE THREAD

**Issue by sebadamus** [akaunting/akaunting#358]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Enter a new bill, enter an item, quantity and price i.e. 1000,50 press enter or tab to continue and you will see Total 1000,00 instead of 1000,50

### Expected result
Total should be 1000,50
I have Currency Pesos and its setup has comma , as decimal separator and point as thousand separator.

### Actual result
Total 1000,00

### System information (Akaunting, PHP versions)
1.2.5 php7.2

### Additional comments
Here two images
![captura](https://user-images.githubusercontent.com/1787753/40571047-7828922e-6068-11e8-8ad0-73bde3f3259f.PNG)
![captura2](https://user-images.githubusercontent.com/1787753/40571048-7b3bd2d2-6068-11e8-8c25-7db571dce751.PNG)

**Comment by denisdulici** [comment]
This is a known issue Sebastian https://github.com/akaunting/akaunting/pull/189

Will also consider this library http://plentz.github.io/jquery-maskmoney

**Comment by sebadamus** [comment]
Whoops didnt see it... closing.
