### ISSUE TITLE
Clicking on Header Logo gives error

### ISSUE THREAD

**Issue by sm2x** [akaunting/akaunting#359]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1.  Login as Customer -> Portal
2.  Click on Header Logo to reset-refresh page

### Expected result
Display initial page (Dashboard)

### Actual result
Red Whoops error page

### System information (Akaunting, PHP versions)
1.2.5, PHP  7.0.27

**Comment by denisdulici** [comment]
Thanks for reporting
