### ISSUE TITLE
Editing Banking Account the first time

### ISSUE THREAD

**Issue by sm2x** [akaunting/akaunting#360]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1.  Create new default currency
2.  Go to Banking, change the default Cash account's currency to new default currency
3.  Save

### Expected result
Save the edited record, and land to browse form

### Actual result
Display red whoops error instead.

### System information (Akaunting, PHP versions)
1.2.5, PHP  7.0.27

**Comment by denisdulici** [comment]
I just tried but was not able to reproduce such a problem.
