### ISSUE TITLE
Attachment won't delete

### ISSUE THREAD

**Issue by dima-ser** [akaunting/akaunting#362]
Attachment still showing up after deleting it from a payment transaction.

### Steps to reproduce the issue
Go to Expenses > Payments. Find a payment with an attachment and click on it to bring up details. In the attachment section on the bottom, click red "X" next to attached file name. Popup appears "Confirm delete [filename] attachment?", click "Delete".

### Expected result
The attachment is deleted and you are either taken back to transaction detail screen or to transaction list. When looking at the same transaction again, the attachment should not be there,

### Actual result
You are taken back to the dashboard. When going back to the transaction and viewing it, the attached file is still there

### System information (Akaunting, PHP versions)
Hosted solution at https://app.akaunting.com

### Additional comments
Not sure if this is the code issue or the hosted environment issue at app.akaunting.com

**Comment by denisdulici** [comment]
Dima, I'm not able to reproduce this in Akaunting itself but in the hosted/cloud one so can you please open a new support topic on our forum https://akaunting.com/forum

Thanks for your understanding.
