### ISSUE TITLE
Rounding Totals and Payments

### ISSUE THREAD

**Issue by asonet** [akaunting/akaunting#367]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
So if the price of a product is specific to fractions of a cent (eg $43.9565) then the total as rounded seems to not really round in the database, but only appear rounded on on the invoice. The totals look right (ie are rounded to the nearest whole cent) but when you try to add a payment for that amount, it will warn you that *you can't pay more than the total* or else will show *partial* status and not *paid* like you would expect. 

### Expected result
A payment for the total shown on the invoice changes the invoice to paid.

### Actual result
The rounded numbers aren't really rounded as they appear.

### System information (Akaunting, PHP versions)
Akaunting 1.2.5
PHP 7.1.12

### Additional comments
The fractional prices come up in my instance because we are selling flooring by the square foot ($1.39/Sq Ft for example) but there is not an even number of square feet in a box (18.73 SqFt/box for example), and I want to sell by the box to make inventory easier, so my price per box comes to $26.0347, but then maybe the customer wants to by 95 boxes, then total is 2473.2965 or 2473.30 when rounded. But when the payment is made for 2473.30, it says *cannot pay over* because my guess is it's really not 2473.30 in the db.

**Comment by denisdulici** [comment]
Can you plz try to increase the number of Precision for that currency? https://akaunting.com/docs/user-manual/settings/currencies

**Comment by asonet** [comment]
Ok, yes, I think it is working correctly actually. I still want the total price to be rounded though, but that is more of a suggestion. Thank you!
