### ISSUE TITLE
System not working properly when session is saved to database

### ISSUE THREAD

**Issue by carlos-mora** [akaunting/akaunting#370]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Install Akaunting downloading the zip from the web

### Expected result
Update Taxes

### Actual result
Throws a Whoops!

### System information (Akaunting, PHP versions)
Akaunting 1.2 stable on Ubuntu 18.4 LTS, Apache, PHP 7.2

### Additional comments
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'company_id' cannot be null (SQL: update `yhk_taxes` set `company_id` = , `updated_at` = 2018-06-02 19:51:50 where `id` = 1) in /var/www/erp.fourtech.es/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647

**Comment by carlos-mora** [comment]
The problem seems to be global: any CRUD operation falls into the same problem : 
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'company_id' cannot be null (SQL: insert into `yhk_items` (`name`, `sku`, `description`, `sale_price`, `purchase_price`, `quantity`, `tax_id`, `category_id`, `enabled`, `company_id`, `updated_at`, `created_at`) values (Test, 01, , 100, 20, 100, 1, , 1, , 2018-06-02 20:45:54, 2018-06-02 20:45:54))

**Comment by carlos-mora** [comment]
I've found the problem. You can change the session manager in settings from 'file' to 'database' easily, but you don't get warned about there is no table for sessions or whatever. I'll try to findout how to enable database session storage, meanwhile, it would be nice not allow the user to change that setting if the system is not ready for the change. KR.

**Comment by denisdulici** [comment]
Carlos, the sessions table is already there https://github.com/akaunting/akaunting/blob/master/database/migrations/2017_09_01_000000_create_sessions_table.php
