### ISSUE TITLE
currency conversion issue (make transaction between accounts)

### ISSUE THREAD

**Issue by locvfx** [akaunting/akaunting#372]
### Steps to reproduce the issue
- The default currency is in PHP
- Add  new transaction from USD account to USD account, the system automatically convert to PHP without checking whether the target account is in same currency or not
* An example: 
- The current balance of account B (USD): $1 , current balance of account A : $100
- Transfer $100 from account A to account B (under menu Banking > Transfer)
- Rate: 1USD = 52 PHP
- Results by the system: account A: $0 , account B: $5201
This is wrong

### Expected result
Without currency conversion, if source and target have the same currency.
$101

### Actual result
$5201

### System information (Akaunting, PHP versions)
Version 1.2.6

### Additional comments
Still can make transaction even though account balance = 0. Should popup notice or reject the transaction

**Comment by ertomedia** [comment]
Hi, thanks for the post. I've also faced the same issue for weeks. As a workaround, I decided to stop using currency conversion and use a single currency instead.

**Comment by locvfx** [comment]
Hi, any update on this issue?
