### ISSUE TITLE
ERROR: Service 'web' failed to build: Unknown flag: from

### ISSUE THREAD

**Issue by rodolfovillaruz** [akaunting/akaunting#373]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

```
$ docker-compose build -t akaunting .
```

### Expected result

The docker-compose should build successfully.

### Actual result

```
Step 3/10 : COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
ERROR: Service 'web' failed to build: Unknown flag: from
```

### System information (Akaunting, PHP versions)

```
$ docker --version
Docker version 1.13.1, build 092cba3
$ docker-compose --version
docker-compose version 1.21.2, build a133471
```

### Additional comments

We could put it in the instruction to build first the docker image before giving a `docker-compose up -d` command.

**Comment by denisdulici** [comment]
Closing based on this comment https://github.com/akaunting/akaunting/pull/353#commitcomment-29284022
