### ISSUE TITLE
All money is float?!

### ISSUE THREAD

**Issue by mvrhov** [akaunting/akaunting#375]
All the money should be represented as a numeric value but as php doesn't have the numeric type something like moneyphp/money should be used and in database this should be stored as numeric or as int64. A lot can go wrong when using floating point as a money.

Also all calculations that deal with the money should be made using moneyphp/money.

**Comment by denisdulici** [comment]
Miha, thanks for your suggestion. Feel free to report a real issue according to our issue template.

**Comment by mvrhov** [comment]
I find this a real issue. The database fields containing monetary values are of type double.. the code that deals with the monetary values explicitly casts the passed in value as double. 
So IMO there is no need for me to hunt every occurrence of this and explicitly report it. Those who have written the code know it in and out and know of all such cases.
