### ISSUE TITLE
Update 1.2.5 to 1.2.6 giving strange App versions

### ISSUE THREAD

**Issue by sm2x** [akaunting/akaunting#379]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Update the core from 1.2.5 to 1.2.6 by clicking on Update through user's UI

### Expected result
I have originally 2 update notifications, one being the Core, and the other Double Entry 1.00 to 1.0.1,
as I have updated the core, the notification should be down to 1.

### Actual result
From 2 notifications it became 4!
- Core version 0.0.0
- Double Entry, current version 1.0.0, update 0.0.0
- Offline Payment, current version 1.0.0, update 0.0.0
- Paypal, current version 1.0.0, update 0.0.0

### System information (Akaunting, PHP versions)
akaunting 1.2.5
php 7.0.27

**Comment by denisdulici** [comment]
I'm not able to reproduce such an error, feel free to use the forum for further support.
