### ISSUE TITLE
Item Image in the invoice page

### ISSUE THREAD

**Issue by abel-masila** [akaunting/akaunting#381]
### Steps to reproduce the issue
I have just setup the application in my machine and i was testing the invoicing part. I wanted to show the image of the item in the invoice preview and also in the print view
### Expected result
To have the item image in the invoice previews.
### Actual result
Just the item  Item | Quantity | Price | Total are shown.
![image](https://user-images.githubusercontent.com/7681686/41355547-75619646-6f2a-11e8-8ad9-ea5a8de52cdc.png)

### System information (Akaunting, PHP versions)
Version 1.2.7

**Comment by denisdulici** [comment]
Abel, please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum
