### ISSUE TITLE
Docker installataion - no connection to database

### ISSUE THREAD

**Issue by Engwer** [akaunting/akaunting#382]
Hi, I want to use akaunting and install it on my homeserver. However, I cannot finish the installation, because in step 2 I cannot connect to the database with the error message:

> Error: Could not connect to the database! Please, make sure the details are correct. 

As I am already running a few applications on my server, including a mysql container listening to port 3306, I used a slightly modified `docker-compose.yml` file that looks as follows:

> version: '3'
> services:
>     web:
>    image: akaunting
>    build: ./
>    volumes:
>      - ./:/var/www/html
>    ports:
>      - 5002:80
>    environment:
>      APP_DEBUG: "true"
>    external_links:
>      - mysql

When I continue with the installation in the browser, I cannot continue past step 2 as I cannot connect to the database.

Help is much appreciated.

**Comment by rjrodriguezalvarez97** [comment]
Make sure your mysql user has grant permission, that was an error that I faced and that was the solution.

**Comment by Engwer** [comment]
I checked the permissions of the akaunting database inside the mysql docker container and everything seemed fine. In the meantime I also tested the composer installation and encountered the same issues. After manually adding the database and granting permissions, it at least worked for the composer installation - I'll further check what's the problem with the docker installation.

**Comment by curtisdelicata** [comment]
I've not tested this application but found this on a search. Are you entering mysql as the db_host? It is mapped to mysql under default Docker and not 127.0.0.1 or localhost?

**Comment by birkof** [comment]
@Engwer provide more info about your stack. You should enter the mysql service details when setuping the whole thing (host: your_mysql_service_name)
