### ISSUE TITLE
Mail settings correct - no password reset possible, no login of second user

### ISSUE THREAD

**Issue by Engwer** [akaunting/akaunting#383]
Hi (and sorry for the second issue in a few days) - I managed to install akaunting with composer and I'm still playing with all possible settings. I encountered two specific problems/bugs:

1. No reset mail is sent after requesting a password reset on the login page despite correct mail settings
2. No login of a secong user account, i.e. manager or second admin is possible

I entered the mail-server settings under settings>general>email as follows:

> protocol: smtp
> smtp host: smtp.1und1.de
> smtp port: 465
> smtp username: username
> smtp password: password
> smtp security: ssl

When I create a customer and assign an invoice to that customer and hit "send mail" afterwards, the mail arrives at the customer. However, when I am at the login-page no password reset link is sent after resetting the same. 
Additionally, it is not possible to login in with a second user account such as a manager or another admin while in fact it is possible for customers to login. Strangely, if I enter the correct credentials for the second user, nothing happens and I stay on the login page. Whereas, if I enter incorrect credentials, I get an error `These credentials do not match our records.`. 
When I check the users table in the database, I get the following result:
````
+----+---------+--------------------+
| id | name    | last_logged_in_at   |
+----+---------+---------------------+
|  1 | Admin | 2018-06-19 06:07:52 |
|  2 | Customer  | 2018-06-19 06:06:54 |
|  3 | Manager | NULL                |
+----+---------+---------------------+
````
As you can see, both admin and customer are able to login, whereas the manager account cannot login despite correct credentials.

Thanks for help

**Comment by denisdulici** [comment]
Please, use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum
