### ISSUE TITLE
Unable to upload file in Vendor App

### ISSUE THREAD

**Issue by xzhenghao** [akaunting/akaunting#385]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

1. Upload zip file in Vendor Dashboard

### Expected result

New file uploaded

### Actual result

500 error
![image](https://user-images.githubusercontent.com/4718721/41634949-ad941d60-7478-11e8-9c34-59fff5804c11.png)

**Comment by denisdulici** [comment]
Please, don't create issues for problems not related to the software.
