### ISSUE TITLE
Reports show only 4 years back, where it should take a look at first expenses/incomes?

### ISSUE THREAD

**Issue by ramonleenders** [akaunting/akaunting#395]
### Steps to reproduce the issue

Go to _/reports/income-summary_ (or any other report). It shows 10 years in total, 5 years after the current year (addYears(5) on app/Http/ViewComposers/Index.php:25). But I'm sure there are many others, like me, having data going back to 2013 and older. Now it only goes until 2014 and next year (2019) it will be 2015. Sure you want to take a look at older reports and be able to print them whenever needed (without changing the URL, which is 100% possible).

### Expected result

Start the year with the first expenses/incomes item? You can even take the first item from the bank transfer too and according to all these (3, could be more) take the lowest one and show that? If there are no entries, take only the current year?

### Actual result

Default of 10 years, not looking at any data in the database at all (so 2014-2023 right now, 2015-2024 next year).

**Comment by denisdulici** [comment]
Ramon, can you please post this feature request in the Ideas category of our forum https://akaunting.com/forum
