### ISSUE TITLE
Can't run on servers with SymLinksIfOwnerMatch Apache restrictions.

### ISSUE THREAD

**Issue by Skelv** [akaunting/akaunting#396]
### Steps to reproduce the issue
Run the software in an environment where `FollowSymLinks` is not supported, such as Virtualmin and load any Akaunting page.

### Expected result
Akaunting should load successfully.

### Actual result
An error 500 appears, and the log shows " Option FollowSymLinks not allowed here"

### System information (Akaunting, PHP versions)
Akaunting 1.2.8 stable.
PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )
Ubuntu Server 16.04
Virtualmin 6.03

### Additional comments
This can be fixed by changing in the .htaccess file(s) the option `FollowSymLinks` with `SymLinksIfOwnerMatch`, as it is a more secure option [according to apache docs](https://httpd.apache.org/docs/2.4/mod/core.html#options).

If the .htaccess is edited directly in the installation folder, the application works but when trying to perform an upgrade it will get overwritten and the upgrade will crash. so editing it again results in the older version and upgrades need to be done manually.

**Comment by trinkaljuneja** [comment]
remove this line from .htaccess and try again 

Options +FollowSymlinks

**Comment by denisdulici** [comment]
What is exactly the difference between `FollowSymLinks` and `SymLinksIfOwnerMatch`? Why all other CMSs such as Joomla, WordPress etc use `FollowSymLinks`?

**Comment by denisdulici** [comment]
Removed `FollowSymLinks` line.

**Comment by Skelv** [comment]
According to [this explanation](https://webmasters.stackexchange.com/a/98828) based on the Apache documentation, with `SymLinksIfOwnerMatch `the server will only follow symbolic links for which the target file or directory is owned by the same user id as the link, so it is a more restrictive option than `FollowSynLinks` prevents symbolic links being followed that might point to some critical parts of the system.
