### ISSUE TITLE
Adding new vendors POST error

### ISSUE THREAD

**Issue by redzrex** [akaunting/akaunting#397]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Add new vendor.

### Expected result
Add successfully.

### Actual result
500 POST error. "Whoops, looks like something went wrong." page.

### System information (Akaunting, PHP versions)
Akaunting: 1.2.8
PHP: 7.1.2

**Comment by ramonleenders** [comment]
The error message is the default one, so you haven't enabled APP_DEBUG in your .env file. Do it like so:

`APP_DEBUG=true`

Then let us know if you can grab the best errors (mostly on top), or perhaps get to fix it yourself?

**Comment by denisdulici** [comment]
I'm not able to reproduce such an error. Feel free to use the forum for further support.

**Comment by redzrex** [comment]
Have you tried adding a new vendor and leave the email empty?
