### ISSUE TITLE
Unable to login after updating to 1.2.10

### ISSUE THREAD

**Issue by ertomedia** [akaunting/akaunting#405]
### Steps to reproduce the issue
Update from 1.2.9 to 1.2.10
Login

### Expected result
Can login into dashboard.

### Actual result
At the login page click on the login button resulting the page only to reload.

### System information (Akaunting, PHP versions)
Akaunting ver: 1.2.10
PHP ver: 7.0.27

**Comment by denisdulici** [comment]
I'm not able to reproduce such a problem, feel free to use the forum for further support.
