### ISSUE TITLE
how do i access the site after installation using docker

### ISSUE THREAD

**Issue by heromiyo** [akaunting/akaunting#406]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
# Access the container
docker-compose exec web /bin/sh

### Expected result

what i should do next to access the site

### Actual result
interactive shell with the source files
![image](https://user-images.githubusercontent.com/39757927/42395835-dbaaef82-8191-11e8-8548-553857a1229d.png)

### System information (Akaunting, PHP versions)

installation using docker 

### Additional comments

new to php :)

**Comment by denisdulici** [comment]
Francis, all you have to do is to access the URL you've installed Akaunting via your browser.
