### ISSUE TITLE
i can't log in with new users

### ISSUE THREAD

**Issue by xMohammedx** [akaunting/akaunting#407]
hi,
first of all , thank you for the great app.

### Steps to reproduce the issue
i just create user from users > add new user.
then give the user Roles also i created then try to login with the new user i got:
Whoops, looks like something went wrong.

### Expected result
i expect to login with the new users

### Actual result
i got this log in laravel logs:

[2018-07-08 11:35:44] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function url() on null in www/modules/OfflinePayment/Events/Handlers/OfflinePaymentAdminMenu.php:20
Stack trace:
0 [internal function]: Modules\OfflinePayment\Events\Handlers\OfflinePaymentAdminMenu->handle(Object(App\Events\AdminMenuCreated))

### System information (Akaunting, PHP versions)
Akaunting  Version 1.2.10 
PHP 7.2
mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper

**Comment by cuneytsenturk** [comment]
@xMohammedx if you do not assign company. Your created new user  can not login on Akaunting. Please check it

**Comment by xMohammedx** [comment]
Dear @cuneytsenturk , Thank you for your replay,
the user is assigned already to the company.
also i just created another user same problem?!

**Comment by cuneytsenturk** [comment]
Dear @xMohammedx . Please you use the [forum](https://akaunting.com/forum) for more support
