### ISSUE TITLE
 Incomes and Expenses Problem in Turkish Lira

### ISSUE THREAD

**Issue by batuhawk** [akaunting/akaunting#408]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

It's about create incomes and expenses in Turkish Lira
If i create new price for incomes or expenses

### Expected result

price : 1,000.000 ₺ result is total : 1,000.000 ₺

### Actual result

price : 1,000.000 ₺  result is total : 1,00 ₺ or
price : 1000,000 ₺   result is total : 1,000,000 ₺

### System information (Akaunting, PHP versions)
Akaunting Version 1.2.10
PHP 7.1

**Comment by denisdulici** [comment]
This is a known issue https://github.com/akaunting/akaunting/pull/189
