### ISSUE TITLE
Visual Bug - Invoice status color mismatch between invoices and show invoice

### ISSUE THREAD

**Issue by johnnyq** [akaunting/akaunting#409]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Create a couple invoices, keep one as a draft, one as sent and one as payed. Click Incomes - Invoices and you will see 3 different colors with their status in the status field blue for draft orange for sent and green for paid. Now click action then show invoice for each invoice you created you will notice on the top left corner the status color are all blue.

### Expected result

The invoices grid view status field should match the color of the status in show invoice.

### Actual result

color for status is always blue under show invoice

### System information (Akaunting, PHP versions)

Akaunting 1.2.10 - PHP 7.2

**Comment by cuneytsenturk** [comment]
![2018-07-10_1148](https://user-images.githubusercontent.com/10936547/42500320-a25313cc-8439-11e8-9406-bb868a29609c.png)

**Comment by johnnyq** [comment]
thats super nice way to go!! I like this look!! @cuneytsenturk
