### ISSUE TITLE
Add Payment currency error

### ISSUE THREAD

**Issue by xMohammedx** [akaunting/akaunting#410]
Hi,

### Steps to reproduce the issue
i choose one currency to be my default currency *not US Dollar*,
and create invoice with my default currency.
when i try to add payment to that invoice i see only US Dollar it's cannot be changed to another currency. 
and i got an error if i pay with dollar more than British Pound.

### Expected result
![image](https://user-images.githubusercontent.com/12001629/42475840-950f1982-83d4-11e8-86e5-6abdb5d703be.png)

### Actual result

it's only US Dollar and it's can not be changed.
i need to transfer from British Pound to us dollar manually then pay with us dollar to make invoice paid.
 
![image](https://user-images.githubusercontent.com/12001629/42475712-1badeb5e-83d4-11e8-9de1-b63ea18b3ef4.png)

### System information (Akaunting, PHP versions)
 Version 1.2.10 
php 7.2

**Comment by cuneytsenturk** [comment]
Hi @xMohammedx This not issue.

Your banking account use USD currency so then just pay USD.
 if you change account currency or add new banking account and set British Pound then use it.

**Comment by xMohammedx** [comment]
Thank you for your support.
