### ISSUE TITLE
Revenues currency 

### ISSUE THREAD

**Issue by xMohammedx** [akaunting/akaunting#411]
hello
when i add new Revenue it's give me US Dollar currency only 
it's not give me the default currency or i can choose another currency ?

when i see my dashboard it's transfer these row 1000$ and 1000$ to my default currency 
![image](https://user-images.githubusercontent.com/12001629/42476350-5b6e0100-83d6-11e8-8508-d4789dbdf343.png)

![image](https://user-images.githubusercontent.com/12001629/42476295-2758da8e-83d6-11e8-9dc5-e84fb1bfb75b.png)

### System information (Akaunting, PHP versions)

Version 1.2.10
PHP 7.2

**Comment by cuneytsenturk** [comment]
You selected account 'CASH' and it use USD.
You should change it.
You can read documentasion [here](https://akaunting.com/docs)

**Comment by xMohammedx** [comment]
Thank you.
