### ISSUE TITLE
Problem saving invoices

### ISSUE THREAD

**Issue by antil0pa** [akaunting/akaunting#414]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Go to Income -> Invoices
Create new invoice with new or existing customer
Save invoice

### Expected result

Invoice is saved successfully

### Actual result

Nothing happens and invoice is not saved 

### System information (Akaunting, PHP versions)

Akaunting 1.2.11
PHP 7.2

### Additional comments

When duplicating an invoice first, and trying to edit it to change customer - the invoice will not get saved. When changing other field in a duplicated invoice without changing the customer, saving works as expected.

**Comment by denisdulici** [comment]
I just tried this and it works fine for me. Feel free to use the forum for further help.
