### ISSUE TITLE
Got error 500 while registering on akaunting.com

### ISSUE THREAD

**Issue by agilov** [akaunting/akaunting#419]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Go to https://akaunting.com/register
and register new account

### Expected result
Account created

### Actual result
Account not created - error message shown

**Comment by denisdulici** [comment]
Try now again plz.

**Comment by agilov** [comment]
Works! thank you
