### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by exomarty** [akaunting/akaunting#422]
https://github.com/akaunting/akaunting/blob/7cf3b5d90972d6211a8f815e444552b62d4fbaf1/resources/views/vendor/notifications/email.blade.php#L7
https://github.com/akaunting/akaunting/blob/7cf3b5d90972d6211a8f815e444552b62d4fbaf1/resources/views/vendor/notifications/email.blade.php#L9
https://github.com/akaunting/akaunting/blob/7cf3b5d90972d6211a8f815e444552b62d4fbaf1/resources/views/vendor/notifications/email.blade.php#L48
https://github.com/akaunting/akaunting/blob/7cf3b5d90972d6211a8f815e444552b62d4fbaf1/resources/views/vendor/notifications/email.blade.php#L54
https://github.com/akaunting/akaunting/blob/7cf3b5d90972d6211a8f815e444552b62d4fbaf1/resources/views/vendor/notifications/email.blade.php#L55

this ones are important because your clients will read email in other language
thank you

**Comment by cuneytsenturk** [comment]
thank your feed back @exomarty
