### ISSUE TITLE
Pdf currency icon and Turkish character problem

### ISSUE THREAD

**Issue by batuhawk** [akaunting/akaunting#424]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

İf i downloaded my invoices with pdf format, currency icons and Turkish letters doesn't work

### Expected result
Proper operation of icons and turkish letters

### Actual result
![adsiz](https://user-images.githubusercontent.com/18425070/42760893-947bb238-8914-11e8-8bc3-9732c74671b1.png)

### System information (Akaunting, PHP versions)
Akaunting Version 1.2.11
PHP 7.1

**Comment by cuneytsenturk** [comment]
same issue solved here #413 => this commit (https://github.com/akaunting/akaunting/commit/14b925fbacecf49e59e2acf5857ac0ac8363da39)
