### ISSUE TITLE
unable to run php artisan

### ISSUE THREAD

**Issue by angelagilhotra** [akaunting/akaunting#425]
i keep getting the following error whenever I run the php artisan command: 

I'm not sure why this keeps coming, even though there is a `clp_settings` table existing in the database

```
akaunting> sudo php artisan

In Connection.php line 647:

  SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from
   `clp_settings`)


In PDOConnection.php line 47:

  SQLSTATE[HY000] [2002] No such file or directory


In PDOConnection.php line 43:

  SQLSTATE[HY000] [2002] No such file or directory

```

**Comment by denisdulici** [comment]
There is no `php artisan` command, you must add something after. Feel free to use the forum for further support.
