### ISSUE TITLE
Dashboard total profits are higher than bank account value (by 1.25x)

### ISSUE THREAD

**Issue by tpulatha** [akaunting/akaunting#427]
### Steps to reproduce the issue

1. Setup a fresh install
2. Create a bank account
3. Set default currency to EUR
4. Add revenue and expenses in EUR to Bank Account

### Expected result

1. Dashboard shows total Profits equal Bank account value

### Actual result

1. Dashboard shows total Profits which are higher than Bank account value
_The Total Profits show a value that is 1.25x the Bank account Value_

### System information (Akaunting, PHP versions)

Akaunting 1.2.11
PHP 7.0
MySQL (MariaDB)

### Additional comments

PS: The "Banking" Page shows all numbers correctly, the "Reports" Page has everything multiplied by 1.25.

**Comment by cuneytsenturk** [comment]
Hi Timur,

You can support on [forum](https://akaunting.com/forum) and read [documentation](https://akaunting.com/docs) for currency rate feature.

**Comment by tpulatha** [comment]
After manually editing the `currency_rate` field in the `tpu_revenues` and `tpu_payments` tables from 1.25 to 1.00 both values are aligned. 
I still stand by my original bug report, even if you hardcode the currency rate into the payments/revenues (which leaves room for improvement), the bank account value and profits should never be different.
