### ISSUE TITLE
can not login with one permission

### ISSUE THREAD

**Issue by xMohammedx** [akaunting/akaunting#429]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
hello
i just create new user + create new role with "Read Incomes Invoices permissions"
and i can't log in with the new user
when i see laravel logs:

```
production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function url() on null' in /var/www/example.com/public_html/test/modules/OfflinePayment/Events/Handlers/OfflinePaymentAdminMenu.php:but 20
Stack trace:
#0 {main}
```

### System information (Akaunting, PHP versions)
php 5.6 , akaunting  Version 1.2.11 

### Additional comments
https://akaunting.com/forum/discussion/installation-update/i-cant-log-in-with-new-users

**Comment by cuneytsenturk** [comment]
Dear @xMohammedx . Please you use the [forum](https://akaunting.com/forum) for more support
