### ISSUE TITLE
How to load cURL and ZIP extensions?  (Better error messages and/or better composer requirements catching)

### ISSUE THREAD

**Issue by mlncn** [akaunting/akaunting#431]
### Steps to reproduce the issue

On Ubuntu 18.04:
```
# Note that the xml, gd, mbstring packages are necessary for extensions the composer install will require
sudo apt install php7.2 php7.2-xml php7.2-gd php7.2-mbstring
# [install composer; my newly installed one is composer version 1.6.5]
wget https://github.com/akaunting/akaunting/archive/master.zip
unzip master.zip
rm master.zip
mv akaunting-master akaunting
cd akaunting
composer install
php -S localhost:8000 &
xdg-open http://localhost:8000
```
### Expected result

Given that i've followed all instructions and composer completed successfully, i would expect the installation to proceed successfully or at least provide / link to clear instructions for completing it.

### Actual result

Web site loads successfully but says:

> Please, meet the following requirements!  
> cURL extension needs to be loaded!  
> ZIP extension needs to be loaded! 

### System information (Akaunting, PHP versions)

Latest Akaunting.
PHP 7.2.7-0ubuntu0.18.04.2

### Additional comments

* I tried enabling curl in php.ini but no change.  There wasn't even an option for anything zip in any of the /etc/php/7.2/cli configuration files.
* There's a similar query in the forum, https://akaunting.com/forum/discussion/installation-update/curl-error

**Comment by mlncn** [comment]
OK PHP started reporting a curl issue and that error message led me to the solution.  (Ironically, that error was because of my enabling curl in php.ini— after the correct fix, per below, i had to edit my php.ini to comment that out again (allowing the proper separate extension config file to handle it.)

The fix (for me, on Ubuntu 8.04 with PHP 7.2 installed per above) is obvious once done:

```
sudo apt install php7.2-curl
sudo apt install php7.2-zip
```
I guess after composer completed successfully, i didn't expect more of this sort of dependency-providing to be needed.

My problem is resolved but i suggest this is still an issue for Akaunting:

* The installation documentation should flag the PHP extensions required (if not provide a nice apt install list for Debian/Ubuntu users).
* Composer should be able to catch these missing dependencies if Akaunting adds them directly?  Composer did catch the need for dom, gd, and mbstring, with errors ("dompdf/dompdf v0.8.2 requires ext-dom * -> the requested PHP extension dom is missing from your system") that were at least easy to search.  This was because dependencies of Akaunting did properly note their requirements at the PHP level.
* The final error message on the site should link to a page that at least indicates that extensions may have to be installed not just enabled, and link to the improved installation documentation mentioned in bullet point number 1.  ;-)

Thanks!

**Comment by mlncn** [comment]
That enhanced in-one-shot apt installation line for PHP:
```
sudo apt install php7.2 php7.2-curl php7.2-gd php7.2-mbstring php7.2-xml php7.2-zip
```
This would have saved me more than an hour of installation time!

**Comment by denisdulici** [comment]
Thanks Benjamin for your feedback.

Akaunting requirements are already listed on our documentation but if you feel they aren't then you can freely contribute to the documentation https://github.com/akaunting/docs

We can't add all the requirements of other packages to our `composer.json` file so I guess composer should be smart enough to read the requirements of packages.
