### ISSUE TITLE
Errors when opening Payments Transactions and Apps pages

### ISSUE THREAD

**Issue by shaharyarahmad** [akaunting/akaunting#433]
The get the following error when opening the token create page:

```
(1/1) FatalErrorExceptionCannot use App\Traits\Modules as Modules because the name is already in use
--
in Suggestions.php line 6
```

And I am also unable to open the payments and transactions page

I get the following errors when viewing the payments page

```
(2/2) ErrorExceptionTrying to get property of non-object (View: /resources/views/expenses/payments/index.blade.php)
--
(1/2) ErrorException
Trying to get property of non-object
```

On the transaction page I get the error

```
(1/1) ErrorException
Trying to get property of non-object
```

Version 1.2.12

**Comment by cuneytsenturk** [comment]
Hi Shaharyar Ahmad,

Thank you your feedback,

I've test clean package but I can not take this issue. Please use more support our [forum](https://akaunting.com/forum)

**Comment by shaharyarahmad** [comment]
Hi Cüneyt,

I was able to fix the issue. There was some problem with an incorrectly submitted payment record.

Best Regards,

Shaharyar Ahmad
On 30 Jul 2018, 1:35 PM +0500, Cüneyt Şentürk <notifications@github.com>, wrote:

Hi Shaharyar Ahmad,

Thank you your feedback,

I've test clean package but I can not take this issue. Please use more support our forum<https://akaunting.com/forum>
