### ISSUE TITLE
Cannot Import Data

### ISSUE THREAD

**Issue by thanhluu** [akaunting/akaunting#434]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. Click Payment
2. Click Import
3. Select file & upload

### Expected result
Import all data into system from excel file

### Actual result
Displayed message: Something went wrong

### Additional comments
I think because phpexcel has been outdated:
`Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.`

**Comment by cuneytsenturk** [comment]
Hi Thanh Luu,

Thank you your feedback,

Akaunting use [laravel excel](https://github.com/akaunting/akaunting/blob/master/composer.json#L31) package so then it use this `phpoffice/phpexcel` package.

Akaunting support PHP 5.6.4 or newer so then it can not use laravel excel v3.

it is a good feedback. We will evaluate it all together.

You ca use more support our [forum](https://akaunting.com/forum)

**Comment by denisdulici** [comment]
Guys, it's not caused by the `phpexcel` itself but the change in the date fields.

**Comment by cuneytsenturk** [comment]
[refs](https://github.com/akaunting/akaunting/commit/56a046b866f71bf4154e5e98de3fa020270f072c)
