### ISSUE TITLE
Total income bigger than it supposed

### ISSUE THREAD

**Issue by Trle94** [akaunting/akaunting#435]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. create an invoice
2. Mark it as paid
3. go to overview

### Expected result
I should have total income of 1140 but it actually shows: 1425 eur

### Actual result
http://prntscr.com/kct5kq

**Comment by tpulatha** [comment]
Seems to be related to #427

**Comment by cuneytsenturk** [comment]
You can look #427 and 

You can support on [forum](https://akaunting.com/forum) and read [documentation](https://akaunting.com/docs) for currency rate feature.
