### ISSUE TITLE
popover issue

### ISSUE THREAD

**Issue by shreyansh9226** [akaunting/akaunting#439]
> resources/views/incomes/invoices/create.blade.php#L275
`  $('a[rel=popover]').popover({
               html: 'true',`

`true` flag is surrounded by quotes which sometimes raise an error with popover. The quotes surrounding true should be removed. As html argument only expects boolean [https://getbootstrap.com/docs/4.0/components/popovers/#options](url)

**Comment by denisdulici** [comment]
Shreyansh, can you please send a pull request about this fix?

**Comment by shreyansh9226** [comment]
@denisdulici I think i don't have permission to do that.
