### ISSUE TITLE
Apps : Piwik has been renamed to Matomo

### ISSUE THREAD

**Issue by MagicFab** [akaunting/akaunting#440]
When going to the apps, "Piwik" is listed as a free analytics app.

It should be "Matomo" as the project has been renamed since:

See https://matomo.org/blog/2018/01/piwik-is-now-matomo/

**Comment by denisdulici** [comment]
Fabian, please, use the forum for non-core Akaunting issues.

**Comment by MagicFab** [comment]
Thanks for clarifying this, I've posted this [here](https://akaunting.com/forum/discussion/apps/piwik-has-been-renamed-to-matomo).
