### ISSUE TITLE
RFE : Add support for multiple taxes in Canada

### ISSUE THREAD

**Issue by MagicFab** [akaunting/akaunting#441]
In Canada 2 taxes can be charged in some provinces: provincial (PST) and federal (GST).

As a business you register for tax numbers which need to appear on each invoice. When specifying "Canada" and the appropriate province this could be preconfigured.

Several provinces use only 1 tax (HST), others use both.

Furthermore sometimes taxes don't apply to some items / services, and are not required to be charged by businesses making less than a fixed amount of annual revenue. This means when implemented each item on an invoice should have the ability to specify taxes (or not) - issue #54 seems to be about this.

For details, see:
https://en.wikipedia.org/wiki/Taxation_in_Canada#Current_sales_tax_rates

**Comment by MagicFab** [comment]
#54 is related to this.

**Comment by denisdulici** [comment]
Fabian, please, kindly use the forum for feature requests.
