### ISSUE TITLE
phpunit will delete the db

### ISSUE THREAD

**Issue by MohiuddinSumon** [akaunting/akaunting#452]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
just try to run the unit test from vscode in win10

### Expected result
feature test, and unit test result

### Actual result
db tables got deleted and had to re import db to work

### System information (Akaunting, PHP versions)

downloaded from website and installed using installer

### Additional comments

I tried to use sqlite for testing , that also fails

**Comment by denisdulici** [comment]
@berkaygure any comment on this?
