### ISSUE TITLE
İçeri aktarmada sorun : Undefined index: currency_code

### ISSUE THREAD

**Issue by Savashascelik** [akaunting/akaunting#454]
Merhabalar gelir ve giderlerde excel'den içeri aktarma yapıldığında "Undefined index: currency_code" hatası veriyor. Para biriminde herhangi bir değişiklikte yapmadım.  Sorun yeni temiz kurulum yaptığımda da çıkıyor nedeni nedir acaba ?

**Comment by cuneytsenturk** [comment]
This issue solved here https://github.com/akaunting/akaunting/issues/434

Please you use the [forum](https://akaunting.com/forum) for more support
