### ISSUE TITLE
 Error for Bills table in status column

### ISSUE THREAD

**Issue by mrcssilvasouza** [akaunting/akaunting#455]
Dear,

Please note the error in the Biils table, because after doing the payment, the bank changes the status to partial, when it should be paid. It does not see
![erro akaunting](https://user-images.githubusercontent.com/30185683/44351706-e16f5200-a478-11e8-9e69-7a23f949da9c.png)
![erro akaunting](https://user-images.githubusercontent.com/30185683/44351759-019f1100-a479-11e8-84d0-63554f0a3187.png)

m to recognize the cents.

**Comment by denisdulici** [comment]
I'm not able to see any difference between the two screenshots. Feel free to use the forum for further support.
