### ISSUE TITLE
Installer not working (/auth/login - 404 Not found)

### ISSUE THREAD

**Issue by jbakuwel** [akaunting/akaunting#457]
Hi there,
Just came across Akaunting and am wondering why I hadn't found this - it looks absolutely great!
Looking forward to trialling it!
However... the installer is not working.

### Steps to reproduce the issue
Download latest 1.2.12 zipfile
Extract on Debian 9 system

### Expected result
See the installer.

### Actual result
Browser is redirected to http://<domain>/auth/login
which does not exist (ie. 404 Not found)

### System information (Akaunting, PHP versions)
Debian 9
PHP7.0
All required dependencies installed

**Comment by denisdulici** [comment]
It works fine for me @jbakuwel. Feel free to use the forum for further support.

**Comment by undrwater** [comment]
> It works fine for me @jbakuwel. Feel free to use the forum for further support.

I'm getting similar results regardless of the zip download version or the git version with composer. It might be helpful @denisdulici if you could describe your environment.
