### ISSUE TITLE
"docker-compose exec web composer install" failed

### ISSUE THREAD

**Issue by jvkranenburg** [akaunting/akaunting#458]
Running the docker commands from the readme fails at step: "docker-compose exec web composer install"

Please see attached screenshot.
Docker version: Docker version 18.06.0-ce, build 0ffa825
Akauning version: commit 398c8d38a6b75e68f7651ecb5ffb896a63e49e8a

<img width="571" alt="screen shot 2018-08-25 at 10 37 59" src="https://user-images.githubusercontent.com/7745377/44616622-68467500-a853-11e8-8923-d2dc1148c83c.png">

**Comment by denisdulici** [comment]
@birkof can you plz check this?

**Comment by birkof** [comment]
@jvkranenburg i've checked the installation with master branch and didn't find any errors here.

```
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan ide-helper:generate
Exception: Class debugbar does not exist
Skipping \Barryvdh\Debugbar\Facade.
A new helper file was written to _ide_helper.php
> php artisan ide-helper:meta
A new meta file was written to .phpstorm.meta.php
> php artisan clear-compiled
The compiled services file has been removed.
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
> composer dump-autoload
Generating autoload files
```

Check if your containers are running properly. 
I suspect there is an issue with MySQL container.
If everything seems ok to you, try to destroy all container & images and restart the installation.

``docker-compose down -v`` should to the trick

PS: @denisdulici Thanks for pinging me
