### ISSUE TITLE
Cannot add new users if Gravatars are enabled in company Settings

### ISSUE THREAD

**Issue by tmanick01** [akaunting/akaunting#462]
Cannot add new users if Gravatars are enabled in company Settings :

First of all great work !  Love how simple and intuitive it is. While the issue itself is not at all critical, the confusion this bug causes is quite non-intuitive. This issue is more of a FYI to first time users like me , who are having trouble adding new users to the installation / company under Akaunting.

### Steps to reproduce the issue
In a company's general settings -> appearance -> use gravatar -> Yes

### Expected result

Gravatar should be used if it exists, else should use a place holder

### Actual result

1 . under list of users, missing gravatars appear broken
2.  Adding a new user with out a gravatar (eg: corporate or selfhosted email )  does not save / persist the user. (No Exception in laravel.logs)
3. Switching to general settings -> appearance -> use gravatar -> No  :  able to add new users without trouble.

### System information (Akaunting, PHP versions)
Akaunting : Version 1.2.12
PHP : PHP (7.1.21)
          Laravel (5.6.33)
SQL:  MySQL (5.7.23) 
Operating System :  Debian (9)
Server:  Apache (2.4.34)

**Comment by cuneytsenturk** [comment]
thanks you your feed back @tmanick01 :) I've fixed it.
