### ISSUE TITLE
Possible false alert of a new update

### ISSUE THREAD

**Issue by tmanick01** [akaunting/akaunting#463]
Possible false alert of a new update : 

### Steps to reproduce the issue
On a fresh install of v 1.2.12,  there are 3 update notifications (one each for the app itself, OfflinePayment, and PaypalStandard ). However the latest version is tagged 0.0.0.0. 
Change logs are empty. 

### Expected result
New version alerts for an actual version roll out.

### Actual result
Unable to dismiss the alerts or update. clicking on update, returns a failed to update message.

### System information (Akaunting, PHP versions)
Akaunting : Version 1.2.12
PHP : PHP (7.1.21)
Laravel (5.6.33)
SQL: MySQL (5.7.23)
Operating System : Debian (9)
Server: Apache (2.4.34)

### Screenshot : 
![capture](https://user-images.githubusercontent.com/16397597/44839157-b3012c00-ac5b-11e8-8faf-f2de84248a2d.PNG)

**Comment by tmanick01** [comment]
@cuneytsenturk , Nothing changes. It is still displayed as 3 versions are available and each of it points to version 0 as the latest. I have tried on a fresh install (on the same setup as mentioned in the issue description) too.

**Comment by cuneytsenturk** [comment]
I think your issue reason version check response timeout so then  return result 0.0.0 [look here](https://github.com/akaunting/akaunting/blob/master/app/Utilities/Versions.php#L92)

Where do you use Akaunting. Your localhost or your hosting?

**Comment by tmanick01** [comment]
@cuneytsenturk  thanks for the pointer, it does seem like a timeout issue - i'll investigate for gotchas on my setup and  configurations.  I'm running this on a Bitnami LAMP stack on a Google compute engine vm. 
I've been running a similar setup for a couple of months and recently upgraded that from v 1.2.11 -> 1.2.12 a few days back.

**Comment by cuneytsenturk** [comment]
Ok, I am close this issue, You can use [forum](https://akaunting.com/forum) for more support.
