### ISSUE TITLE
Error 404 /auth/login not found

### ISSUE THREAD

**Issue by mbh-dev** [akaunting/akaunting#470]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Installation of Akaunting and visiting https://domain/akauntingdir

### Expected result

Installation wizard should appear

### Actual result

Error 404

### System information (Akaunting, PHP versions)

Ubuntu 16.04 PHP 7.2 Akaunting latest stable release

**Comment by lightcowboy** [comment]
I seem to be getting the same issue. I have mod_rewrite working so it shouldn't be that.
When I type http://localhost:8044/index/php it take my to the login screen (I have it setup with XAMPP as a virtual host)

Going to the localhost:8044 just re-directs to : http://localhost:8044/auth/login

**Comment by denisdulici** [comment]
I'm not able to reproduce such an error guys. Make sure you've pointed the address in browser correctly, to the Akaunting directory. Feel free to use the forum for further help.

**Comment by Enaah** [comment]
I had the same issue and find a solution.

In my case it was the **.htaccess** missing (because it's hidden in most OS').

If you copying the dowloaded Version make sure you copy the **.htaccess** ind the **root-Folder** aswell.


Hope this helps someone.

**Comment by tjcomserv** [comment]
Same issue with CentOS 8. 
.htaccess has been copied
mod_rewrite seems to be working
Did anyone manage to solve this?

**Comment by ghaseminya** [comment]
I had the same issue with Almalinux-8 too.
