### ISSUE TITLE
can not delete invoice and bills

### ISSUE THREAD

**Issue by xMohammedx** [akaunting/akaunting#473]
**Hi**
thank you for your support

i think there is problem with deleting invoices.
and i don't know if the problem from my side or not.

### Steps to reproduce the issue
go to incomes/invoices or expenses/bills then try to delete bills or invoices but i can't delete it.

### Expected result
incomes/invoices should be deleted.
expenses/bills should be deleted.

### Actual result
Whoops, looks like something went wrong.

production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function all() on null' in /var/www/mysite.com/public_html/gate/app/Http/Controllers/Controller.php:97

### System information (Akaunting, PHP versions)
 Version 1.2.14 
PHP 5.6.36

Thank you.

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue with the GitHub version of Akaunting.
