### ISSUE TITLE
Increase the timeout in getLatestVersion($url)

### ISSUE THREAD

**Issue by tmanick01** [akaunting/akaunting#477]
Currently the timeout for version check in app/Utilities/Versions.php is 1, which is way too low for a production setup. Please change the timeout to something more reasonable (10, 20, 30 ?)
### Steps to reproduce the issue
On a infrastructure with firewalls/ port forwards / redirects, the update check time out is way too low.
Latest version check fails mostly due to timeouts. 

### Expected result
Checks fail after a reasonable timeout.

### Actual result
Checks/updates mostly fail due to a veryshort timeout , on a production setup, causing a bit of a confusion ( #463, for reference ).

### System information (Akaunting, PHP versions)

Akaunting : Version 1.2.14
PHP : PHP (7.1.21)
Laravel (5.6.33)
SQL: MySQL (5.7.23)
Operating System : Debian (9)
Server: Apache (2.4.34)

**Comment by tpulatha** [comment]
It probably also makes sense to increase the timeout in https://github.com/akaunting/akaunting/blob/master/app/Utilities/Updater.php#L110 from 30 to something like 300. This timeout always made my update fail.

**Comment by denisdulici** [comment]
Thanks guys for your feedback.
