### ISSUE TITLE
How can i create app ?

### ISSUE THREAD

**Issue by navneetccna** [akaunting/akaunting#479]
Is there any document or tutorial to create an app or custom module for akaunting ? Is App and module are similar and this is the documentation to create an app https://akaunting.com/docs/developer-manual/modules?

**Comment by denisdulici** [comment]
Navneet, app and module are the same thing. As said in that article:

> While technical we call it Module, we name it App for the end-user as that's what they are familiar to.

So yes, that's the documentation to create an app.

**Comment by navneetccna** [comment]
Ok thanks
