### ISSUE TITLE
After changing timezone the app crashes and won't work even if change is reverted.

### ISSUE THREAD

**Issue by joveice** [akaunting/akaunting#481]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Login, logout, change config/app.php 'timezone' => 'Europe/Oslo',
Config cache
login

### Expected result
Correct timezone to be used

### Actual result
Undefined variable: date_format (View: project/root/resources/views/common/dashboard/index.blade.php)

### System information (Akaunting, PHP versions)
PHP 7.2.*, Akaounting 1.2.12

**Comment by denisdulici** [comment]
You should not change the core files, there is a timezone option in the Settings > General page in Akaunting admin panel.

**Comment by joveice** [comment]
It's not a core file, it's a configuration file.

Even after reverting I'm still having the issue, what can I do?

**Comment by woppywush** [comment]
I have the same problem, i change the language for general from the setting and this is what happen:

https://cl.ly/007b7de57b38
