### ISSUE TITLE
after import - no acces to revenues

### ISSUE THREAD

**Issue by hell-e** [akaunting/akaunting#482]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
After import of revenues, the revenues page ist not accessable - Errormessage:
"Whoops, looks like something went wrong."

### Expected result
See the importet Data

### Actual result
"Whoops, looks like something went wrong."
I can see somethin at the Dashbord, but can not edit the importet data.

### System information (Akaunting, PHP versions)
Cloud-Version
ID 
1363 | ASKOe BBC McDonald's Iron Scorps Steyr | www.bbc-steyr.at
-- | -- | --

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue, try to enable debug and see the error details https://akaunting.com/docs/developer-manual/debug

Feel free to use the forum for further support.

**Comment by hell-e** [comment]
How can I enable this in my cloud-version?

Helmut

Denis Duliçi <notifications@github.com> schrieb am Mi., 12. Sep. 2018,
14:09:

**Comment by hell-e** [comment]
Hi Denis,

 

now I installed a instance of akaunting on my webserver an activated the debug-mode. When I import the file attached revenues will not anymore ☹

 

Greetings

Helmut

 

Von: Denis Duliçi <notifications@github.com> 
Gesendet: Mittwoch, 12. September 2018 14:09
An: akaunting/akaunting <akaunting@noreply.github.com>
Cc: hell-e <helmut.kaiser82@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [akaunting/akaunting] after import - no acces to revenues (#482)

 

I'm not able to reproduce such an issue, try to enable debug and see the error details https://akaunting.com/docs/developer-manual/debug

Feel free to use the forum for further support.
