### ISSUE TITLE
Can't not save Currency Symbol Position "After Amount"

### ISSUE THREAD

**Issue by dichvuhuuich** [akaunting/akaunting#487]
### Steps to reproduce the issue
Go to /settings/currencies/1/edit
In Symbol Position, choose: "After Amount", click Save

### Expected result
Go to /settings/currencies/1/edit again, In Symbol Position, option is "After Amount" and Symbol Position in all website in "After Amount"

### Actual result
Go to /settings/currencies/1/edit again, In Symbol Position, still option is "Before Amount" and Symbol Position in all website still in "Before Amount"

### System information (Akaunting, PHP versions)
Akaunting version: 1.2.15
PHP version: 7.1.21

### Additional comments
Please check and fix.

**Comment by cruisemaniac** [comment]
The currency is being updated in the database. Changing position from before amount to after amount changes the database value from 1 to 0 for the `symbol_first` field.

This is however not showing properly in the view on page load.

**Comment by m431342** [comment]
A very dirty quick fix to force the symbol position to 'after amount' for a currency:
In file 
`vendor/akaunting/money/src/Currency.php`
in the constructor approx. line 90 change:
`$this->symbolFirst = (bool) $attributes['symbol_first'];`
to:
`$this->symbolFirst = $this->currency === 'EUR' ? (bool) 0 : (bool) $attributes['symbol_first'];`

**Comment by denisdulici** [comment]
Can you please try to change the following line:
https://github.com/akaunting/akaunting/blob/1.3-dev/app/Utilities/Overrider.php#L73

`config(['money.' . $currency->code . '.symbol_first' => (bool) $currency->symbol_first]);`

**Comment by m431342** [comment]
I think I found the bug.

In Function `getSymbolFirstAttribute` in `app/Models/Setting/Currency.php` 
change `empty($value)` to `is_null($value)`
