### ISSUE TITLE
 Cron does not work

### ISSUE THREAD

**Issue by mrcssilvasouza** [akaunting/akaunting#490]
Gentlemen

Can anyone help me with cron doing Akaunting? Already create the file located in the path as recommended and it does not work. I already noticed that the various users have the same problem. I use CentOS 7 and have already put 03 times different and does not rotate. I also looked for the log file to identify the error but not find it. Where is?
![erro akauting cron](https://user-images.githubusercontent.com/30185683/45550963-d652dc00-b802-11e8-9c85-3d01762bb246.jpg)

**Comment by tmanick01** [comment]
you do not see cron errors because you are redirecting stderr to null. redirect it to a file to see what's going wrong with the cron .job .
eg : 
/some/path/tologfile.log 2>&1 instead of /dev/null 2>&1
PS: Also  check the path to artisian.. remove the extra '/ 'in front of var.

**Comment by riorinald** [comment]
let me put my error here, 
i got this error while log the cron task.

> In ArgvInput.php line 280:                                           
>   Invalid argument supplied for foreach() 

and this the line 280 in /akaunting/vendor/symfony/console/Input/ArgvInput.php
```
        foreach ($this->tokens as $token) {
            if ($onlyParams && '--' === $token) {
                return false;
            }
            foreach ($values as $value) {
                // Options with values:
                //   For long options, test for '--option=' at beginning
                //   For short options, test for '-o' at beginning
                $leading = 0 === strpos($value, '--') ? $value.'=' : $value;
                if ($token === $value || '' !== $leading && 0 === strpos($token, $leading)) {
                    return true;
                }
            }
        }
```

**Comment by mrcssilvasouza** [comment]
tmanick01

I did what you recommended, now I have a record, but there is nothing that is done, this is more than a month.

![log_akaunting](https://user-images.githubusercontent.com/30185683/46492490-12ff6b00-c7e4-11e8-8fca-039b7f27d024.png)

**Comment by denisdulici** [comment]
Akaunting uses the Laravel's Scheduling feature and it works fine for me guys:

https://laravel.com/docs/5.4/scheduling

Feel free to use the forum for further support.
