### ISSUE TITLE
Suggestion / request: use Dependabot to update dependencies

### ISSUE THREAD

**Issue by greysteil** [akaunting/akaunting#498]
First of all, thanks for Akaunting!

(I checked the forum, but since this is a GitHub specific request figured it made more sense to post this here than there. Sorry if that's wrong!)

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs for this repo? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/akaunting/pulls). I'll port the `fzaninotto/faker` one across to this repo now.

I built Dependabot and give it away for free to open source projects (partly for the exposure, but mainly because it feels good to give back and because the feedback is incredibly useful). I'm honestly only suggesting it because I hope it can save you some time doing work that is otherwise monotonous.

If you do decide to give Dependabot a go the easiest URL to add it from is https://github.com/apps/dependabot (alternatively you can go through the GitHub Marketplace, but the flow there can be a little confusing for open-source repos on an organisation account.

:octocat:

**Comment by denisdulici** [comment]
Thanks Grey, just installed ;)

**Comment by greysteil** [comment]
Awesome! I'll watch on my side and make sure everything goes smoothly. Thanks for giving it a try.
