### ISSUE TITLE
Issue in Invoicing

### ISSUE THREAD

**Issue by makvital** [akaunting/akaunting#500]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
While Editing or Duplicating the Invoice

### Expected result
Date Picker and other JS are not working

### Actual result
Uncaught RangeError: Invalid array length
Failed to load resource: the server responded with a status of 404 (Not Found) bootstrap-datepicker.en.js:1 

### System information (Akaunting, PHP versions)
Akaunting 1.2.16
PHP 7.0.1

**Comment by pnyet** [comment]
Hi,

I have same problem and fix this issue by creating file 
With the following code:

`/**
 * British English translation for bootstrap-datepicker
 * Xavier Dutreilh <xavier@dutreilh.com>
 */
;(function($){
$.fn.datepicker.dates['en'] = {
days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
daysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
daysMin: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
today: "Today",
monthsTitle: "Months",
clear: "Clear",
weekStart: 1,
format: "dd/mm/yyyy"
};
}(jQuery));`

But I still have problem to create an invoice or add an item on the invoice without any error.
