### ISSUE TITLE
Can´t add a payment to a bill

### ISSUE THREAD

**Issue by lalogarcia123** [akaunting/akaunting#504]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
We use Spanish translation:

(English)
1.- Select an invoice
2.- Select "more actions" button
3.- Select "add payment" button
4.- Fill all the fields
--> The date field don't respond
-->When pressing "save" button, theres no action

(Español)
1.- Seleccionar una factura
2.- Seleccionar el boton "mas acciones"
3.- Seleccionar el boton "añadir pago"
4.- Llenar todos los campos
--> El campo fecha no responde
--> Cuando se presiona el boton guardar no hay respuesta

### Expected result

It's expected to save the payment info of the bill

### Actual result

No action from the "Save" button is shown

### System information (Akaunting, PHP versions)

Akauting 1.2.15
PHP 7.1

### Additional comments

In a past version there was no problem with payment add

**Comment by aamanlamba** [comment]
I have this problem also in 1.2.16 - unable to save payments to bills

**Comment by cuneytsenturk** [comment]
We've fixed this issue here => (#581, #582) so then I've closed this issue.

Thanks your feedback.
