### ISSUE TITLE
EURO symbol rendering problem  during PDF invoice generation, 

### ISSUE THREAD

**Issue by maty535** [akaunting/akaunting#506]
When generate pdf invoice euro symbol is shown as empty square:

![image](https://user-images.githubusercontent.com/17314690/46206186-7c363880-c323-11e8-9d62-22d03ee21631.png)

Version 1.2.16 Powered By Akaunting: Free Accounting Software

**Comment by maty535** [comment]
I found problem in barryvdh/laravel-dompdf, 

i changed there definition of euro entity, we would need to use last version of this module.

**Comment by denisdulici** [comment]
Which changes are you exactly talking about?

**Comment by dseegers** [comment]
We still have this problem
