### ISSUE TITLE
Units definition (string) in Invoice

### ISSUE THREAD

**Issue by maty535** [akaunting/akaunting#507]
It would bee good to add new field when creating new Invoice items:

 - Unit  (days, hours, pcs, kg )

and change label of field Price, to  Unit price.

Actual Status:
![image](https://user-images.githubusercontent.com/17314690/46214242-fd4cfa00-c33a-11e8-87e6-d258fe59db1d.png)

Future look:

![image](https://user-images.githubusercontent.com/17314690/46214525-a72c8680-c33b-11e8-88de-2b3a86897c3e.png)

**Comment by denisdulici** [comment]
Matus, please, use the forum for requests/support.

**Comment by maty535** [comment]
Ok.
