### ISSUE TITLE
Expenses - Payments - Can no longer use " - " in a new payment amount (Needed for refunds)

### ISSUE THREAD

**Issue by johnnyq** [akaunting/akaunting#516]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Click Expenses > Payments then add new. Under Amount try to put " - " fex -100.00

### Expected result

It should allow you to use a - in front of the amount

### Actual result

It doesnt allow it

### System information (Akaunting, PHP versions)

Akaunting 1.2.16 - PHP7.2

**Comment by denisdulici** [comment]
Johnny, you should create a Revenue in such a case.

**Comment by johnnyq** [comment]
I was able to do it in the previous version and have been using that way for awhile. If I log it as revenue then that would show as income which is taxable.
