### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' 

### ISSUE THREAD

**Issue by abkrim** [akaunting/akaunting#521]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Install on develop localhost with MySQL 8.0.11

### Expected result
Install

### Actual result
Error after create database step.
SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' (SQL: select * from information_schema.tables where table_schema = akaunting and table_name = joy_migrations)

### System information (Akaunting, PHP versions)
1.3-dev
PHP 7.2.10
MySQL 8.0.11

### Additional comments
Work if comment conf/database.php
```
            'modes' => [
		//'ONLY_FULL_GROUP_BY', // conflicts with eloquence
                'STRICT_TRANS_TABLES',
                'NO_ZERO_IN_DATE',
                'NO_ZERO_DATE',
                'ERROR_FOR_DIVISION_BY_ZERO',
                //'NO_AUTO_CREATE_USER',
....

```

**Comment by developerbmw** [comment]
NO_AUTO_CREATE_USER was made the default in MySQL 5.7 (https://dev.mysql.com/worklog/task/?id=8326)

And it was removed in MySQL 8 (https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-11.html)

Can this just be removed from the config? Surely the app isn't using GRANT anyway?

**Comment by elderjames314** [comment]
Disable strict mode works for me like this below:

'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3308'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
           // 'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
