### ISSUE TITLE
transactions error after deleting invoice

### ISSUE THREAD

**Issue by alistairquinn** [akaunting/akaunting#522]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue 

1. Import invoices with tax line and null amount
2. Expect an error telling you your amount invalid
3. Delete invoice
4. Repeat several times

### Expected result

Invoice would be deleted
Totals in Cash account will be corrected
Access to transactions

### Actual result

Cash account contains values of imported invoices
Transactions page errors

### System information (Akaunting, PHP versions)

Cloud version

**Comment by batuhawk** [comment]
Why do you enter the amount as null? You shouldn't do that.
