### ISSUE TITLE
Cant setup the database connection details when setting up via docker

### ISSUE THREAD

**Issue by naneri** [akaunting/akaunting#525]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, 

 pull access denied for akaunting, repository does not exist or may require 'docker login'
### Steps to reproduce the issue
I am on Ubuntu 18.04 spinning up the image with docker. After I get to 'install/databases' and input the creds from `docker-compose.yml` it says that those are incorrect

### Expected result
it should successfully pass to next step 

### Actual result
After I get to 'install/databases' and input the creds from `docker-compose.yml` it says that those are incorrect

### System information (Akaunting, PHP versions)
Ubuntu 18.04, docker

**Comment by cruisemaniac** [comment]
This works if you change the host of the database from `localhost` to `mysql` as defined in the `docker-compose.yml`.

**Comment by naneri** [comment]
ok, thanks
