### ISSUE TITLE
cannot open the file.

### ISSUE THREAD

**Issue by hotmash24** [akaunting/akaunting#539]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Unknown: Failed opening required 'D:\PERSONAL FILE\akaunting/server.php' (include_path='D:\xampp\php\PEAR') in Unknown on line 0

**Comment by denisdulici** [comment]
Use `index.php` instead.
