### ISSUE TITLE
Roles does not show when Read Customer Panel is checked - bug

### ISSUE THREAD

**Issue by mlibre** [akaunting/akaunting#545]
If you check "Read Customer Panel" Permission in any role. The role will now show up for users to add.
### Steps to reproduce the issue
- Check "Read Customer Panel" Permission in any role.
- Try to add the role to a user

### Expected result
- Can add the role to a user

### Actual result
- The role will now show up for users to add.

### System information (Akaunting, PHP versions)
- Akaunting: Version 1.2.16
- PHP 7.2 FPM
- Ngnix

**Comment by denisdulici** [comment]
That's how the system is designed to work. A User can't access the Customer panel.
