### ISSUE TITLE
Enhancement Request - Full System Seed required

### ISSUE THREAD

**Issue by cruisemaniac** [akaunting/akaunting#551]
Can we have a seeder that injects data for all the models in the app?

**Comment by denisdulici** [comment]
Ashwin, please, use the forum for feature requests and proposals.

**Comment by cruisemaniac** [comment]
@denisdulici I contemplated posting on the forum but posted here since the seeding aspect is code only.
I will put in a feature request on the forum in a bit. Thanks.
