### ISSUE TITLE
Dev Version 1.3.0 asks to update to 1.2.6

### ISSUE THREAD

**Issue by cruisemaniac** [akaunting/akaunting#552]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Upon logging into the dashboard, the update  icon lights up with a "1 update available".

Dev Version is 1.3.0 but it asks to update to version 1.2.6.

### Expected result
No new updates should be available

### Actual result
Dev Version is 1.3.0 but it asks to update to version 1.2.6.

**Comment by denisdulici** [comment]
Thanks Ashwin, it's a temporary error.
