### ISSUE TITLE
Tax Summary Report "paid" incorrect if multiple payments per invoice

### ISSUE THREAD

**Issue by ghost** [akaunting/akaunting#553]
### Steps to reproduce the issue
1. create an invoice with invoice date in January, total amount 100 including 20% tax (net amount 80, tax amount 20)
2. assign a payment of 60 to the invoice
3. assign another payment of 40 to the invoice
4. open the tax summary report, click on button "paid"

### Expected result
The tax amount shown in row "Incomes", column "Jan", should be 20.

### Actual result
The tax amount shown in row "Incomes", column "Jan" is 40.

### System information (Akaunting, PHP versions)
Akaunting 1.2.16
PHP 7.1.19-1+ubuntu16.04

### Additional comments
The program "loops" over invoice_payments and for each one the amount from invoice_totals gets added up.
So if there are two payments for a single invoice, it will add the invoice totals twice.

Possible solution:
The payments table could be grouped by invoice_id, thus essentially creating a 1-1 relationship rather than the n-1 between invoice_payments and invoice_totals. This would prevent the problem of the invoice totals getting added up multiple times. There might still be a problem if the payments are in different months, though.

**Comment by m431342** [comment]
Quick fix as mentioned above:
In TaxSummary.php change line 69 from
`$invoices = InvoicePayment::with(['invoice', 'invoice.totals'])->monthsOfYear('paid_at')->get();`
to
`$invoices = InvoicePayment::with(['invoice', 'invoice.totals'])->groupBy('invoice_id')->monthsOfYear('paid_at')->get();`

That will fix the problem as long as the multiple payments are all within the same month.
