### ISSUE TITLE
Invoices not sending via email

### ISSUE THREAD

**Issue by dmurphy779** [akaunting/akaunting#558]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1) Set up email settings in either PHP SMTP or Sendmail (I tried using smtp.gmail.com for gmail)
2) Try sending an invoice via email

### Expected result
Receive success message to confirm email being sent. 

### Actual result
Received error: Whoops, looks like something went wrong. 

### System information (Akaunting, PHP versions)
Akaunting | 1.2.16
Apache Version | 2.4.33
PHP Version | 7.0.30
MySQL Version | 10.2.17-MariaDB
Operating System | linux
Path to Sendmail | /usr/sbin/sendmail

### Additional comments

The error should also be more descriptive other than a general error message. Additionally, the admin should be able to toggle/choose to show server errors for troubleshooting.

**Comment by m431342** [comment]
Open the file .env and change DEBUG=false to DEBUG=true.
That will give you a more detailed error message.

**Comment by denisdulici** [comment]
We're not able to reproduce such an error Daniel. Try to enable debug to see more details. Feel free to use the forum for further support.

**Comment by kbhagchandani** [comment]
I have tried same for sending mails using smtp to mailtrap.io and this error can be easily reproduced. I have turned on debug and found the following log:

Swift_TransportException: Expected response code 250 but got code "502", with message "502 5.5.2 Error: command not recognized"

I am trying to use mailtrap.io for email testing.
