### ISSUE TITLE
Wizard is not very easy to use

### ISSUE THREAD

**Issue by kostasdizas** [akaunting/akaunting#575]
While the first step in the wizard (setting up companies) provides a Save button that suggests the user will proceed to the next step, the currencies and taxes parts have only a Skip button instead. There are no instructions in the wizard pages, so it is not clear what that you are meant to proceed by clicking the Skip button.

From a ux point of view it should be quite clear for first time users what they are meant to do at each step, both by using a short description of what they are actually doing at each step, and a clear UI that demonstrates their options. Here the user would either set up some configuration and proceed, or skip the current step (some information should be provided about how and where to complete the setup after exiting the wizard).

https://github.com/akaunting/akaunting/blob/40041ee40258559de4d5dcfebddbcf4e8918dcc5/resources/views/wizard/taxes/index.blade.php#L101

https://github.com/akaunting/akaunting/blob/40041ee40258559de4d5dcfebddbcf4e8918dcc5/resources/views/wizard/currencies/index.blade.php#L103

**Comment by denisdulici** [comment]
Thanks Kostas for your suggestions. Any PR about this is welcomed.
