### ISSUE TITLE
Reconciliations don't work on non-windows environments

### ISSUE THREAD

**Issue by kostasdizas** [akaunting/akaunting#578]
The new reconciliations module uses the name of the expected model classes to, at the controller level, decide where to find the contact name, and at the reconciliation views, to show the amount as a withdrawal or deposit. The code seems to be using the `basename` method to get the class name out of the qualified class string. `basename` can only be used in this way on windows environments as it is meant for paths and windows contain backslashes (same as the qualified class names). It should instead use `is_a`. Additionally, it would be better if the transaction could decode the class name to something the views can use to draw accordingly, without having to know about the underlying class name.

### Steps to reproduce the issue

1. Install akaunting on linux
2. Create one revenue and one payment transaction
3. Create a reconciliation for the account used above

### Expected result

The amount from the revenue transaction shows as a deposit and the amount from the payment shows as a withdrawal.

### Actual result

Both transactions show as withdrawals

### System information (Akaunting, PHP versions)

Akaunting 1.3-dev, PHP 7.0

**Comment by denisdulici** [comment]
Kostas, I just tested on Windows 8.1 and it works fine for me.

**Comment by kostasdizas** [comment]
Yes, that’s the problem, it only works on windows where the implementation of `basename` is different and splits on \ as well as /. On Linux it only splits on /.
