### ISSUE TITLE
Cannot scroll menu on Android Firefox Browser

### ISSUE THREAD

**Issue by Junker** [akaunting/akaunting#588]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. Install Firefox Browser on Android phone
2. Login to Akaunting
3. Open menu and some submenus
4. Try to scroll menu to bottom 

### Expected result
Should be able to scroll menu

### Actual result
Cannot see part of menu, cannot scroll menu.

### System information (Akaunting, PHP versions)
Akaunting 1.2.16
PHP 7.2

**Comment by denisdulici** [comment]
That's a known issue of AdminLTE theme and none has found a real solution yet:
https://github.com/almasaeed2010/AdminLTE/issues/1143
https://github.com/almasaeed2010/AdminLTE/issues/1720
