### ISSUE TITLE
Logo Upload: Does not show up

### ISSUE THREAD

**Issue by zgjonbalaj** [akaunting/akaunting#593]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Upload logo as png (have not tried other formats)

### Expected result

Logo shows up resized or cropped or at all

### Actual result

No logo shows up, a 404 not found is on the image.

### System information (Akaunting, PHP versions)

Windows 10 Enterprise
Chrome Version 70.0.3538.77 (Official Build) (64-bit)
PHP 7.2
Akaunting Version 1.2.16
Installed on cPanel Account

**Comment by denisdulici** [comment]
Zgjim, I'm not able to reproduce such an issue. Make sure the file/folder permissions of storage directory are correct. You can use our forum for further help https://akaunting.com/forum

**Comment by zgjonbalaj** [comment]
@denisdulici I did check permissions, same result. Permissions were carried over from archive as it was uploaded then extracted on server.
