### ISSUE TITLE
Email Configuration: Cant change from "hello@example.com"

### ISSUE THREAD

**Issue by zgjonbalaj** [akaunting/akaunting#594]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Have a reset password email sent to you.

### Expected result

Email should be coming from the email configured in the system or at least have a configurable email address tab.

### Actual result

Email comes from hello@example.com

### System information (Akaunting, PHP versions)

Windows 10 Enterprise
Chrome Version 70.0.3538.77 (Official Build) (64-bit)
PHP 7.2
Akaunting Version 1.2.16
Installed on cPanel Account

**Comment by denisdulici** [comment]
I can confirm this issue Zgjim, thanks for reporting.
