### ISSUE TITLE
Invoicing: Generating invoice causes "Whoop's something went wrong"

### ISSUE THREAD

**Issue by zgjonbalaj** [akaunting/akaunting#595]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Create invoice normally, click save.

### Expected result

Invoice saved, email sent?

### Actual result

Getting a whoops something went wrong error

### System information (Akaunting, PHP versions)

Windows 10 Enterprise
Chrome Version 70.0.3538.77 (Official Build) (64-bit)
PHP 7.2
Akaunting Version 1.2.16
Installed on cPanel Account

### Additional comments

Looked at Laravel logs, getting a few issues there:

[laravel.log](https://github.com/akaunting/akaunting/files/2546371/laravel.log)

**Comment by denisdulici** [comment]
Zgjim, I'm not able to reproduce such an issue. Feel free to enable debug and post in our forum for further help https://akaunting.com/docs/developer-manual/debug
