### ISSUE TITLE
Erratic behavior of payment amount

### ISSUE THREAD

**Issue by Sanqui** [akaunting/akaunting#600]
### Steps to reproduce the issue

1. Create a currency with the following parameters
    * Name: Czech Koruna
    * Code: CZK
    * Rate: 25
    * Precision: 2
    * Symbol: Kč
    * Symbol position: After Amount
    * Decimal mark: .
    * Thousands separator: ,
2. Create Account using the Czech Koruna currency
3. Add New Payment and select the CZK account
4. Put 2600 in the Amount field
5. Focus out of and into the Amount field

### Expected result
The Amount value stays the same

### Actual result
The Amount value changes every time the focus changes.  It goes 2,600.00Kč → 26.00Kč → 0.26Kč → 2.00Kč → 20.00Kč → 0.20Kč → 2.00Kč and loops.

This behavior renders this software essentially unusable for accounting.

### System information (Akaunting, PHP versions)
Firefox 62, version on app.akaunting.com

**Comment by denisdulici** [comment]
This is related to your default currency, here you can find more information https://akaunting.com/docs/user-manual/settings/currencies

Feel free to use the forum for further help.

**Comment by Sanqui** [comment]
Excuse me.  Are you saying this is correct and intended behavior?  I cannot find anything about it on the page about currencies you have linked.

![peek 2018-11-07 11-51](https://user-images.githubusercontent.com/289437/48127250-897c0680-e283-11e8-81af-d002eb4c16f1.gif)

**Comment by thunoldolsen** [comment]
Same problem for NOK, Norwegian kroner. 1.3.4. 
I have to reenter the amount everytime before I save
My currency settings:
    Name: Norske kroner
    Code: NOK
    Rate: 1 (Standard currency)
    Precision: 2
    Symbol: Kr
    Symbol position: After Amount
    Decimal mark: ,
    Thousands separator: .

**Comment by denisdulici** [comment]
Confirmed this issue when the `Symbol Position` is `After Amount`.

**Comment by slal2003** [comment]
Hi, any news about when this issue wî’ Be solved? Thanks for the great work.
