### ISSUE TITLE
Call to undefined method DOMDocument::hasAttribute()

### ISSUE THREAD

**Issue by GaneshKandu** [akaunting/akaunting#61]
#### Call to undefined method DOMDocument::hasAttribute()

Hi

i am Getting Fetal Error in Akaunting 1.0.6 on pdf downloads
[https://akaunting.com/forum/discussion/general/error-when-creating-pdf](https://akaunting.com/forum/discussion/general/error-when-creating-pdf)
```
Call to undefined method DOMDocument::hasAttribute() in 
vendor/dompdf/dompdf/src/Css/Stylesheet.php on line 970
```
[error_log.txt](https://github.com/akaunting/akaunting/files/1424012/error_log.txt)
[laravel.log](https://github.com/akaunting/akaunting/files/1424016/laravel.log)

#### system
- Apache/2.2.31
- PHP 
  - 5.6
  - 7.0
  - 7.1

#### php extenstion enabled
- bcmath
- bz2
- calendar
- Core
- ctype
- curl
- date
- dba
- dom
- exif
- fileinfo
- filter
- ftp
- gd
- gettext
- gmp
- hash
- iconv
- imap
- intl
- json
- ldap
- libxml
- mbstring
- mcrypt
- mysqli
- openssl
- pcntl
- pcre
- PDO
- pdo_mysql
- pdo_sqlite
- Phar
- posix
- Reflection
- session
- shmop
- SimpleXML
- soap
- sockets
- SPL
- sqlite3
- standard
- sysvsem
- sysvshm
- tidy
- tokenizer
- wddx
- xml
- xmlreader
- xmlrpc
- xmlwriter
- xsl
- Zend OPcache
- zip
- zlib

**Comment by denisdulici** [comment]
Thanks Ganesh for the details. It seems to be a generic problem of DomPDF. Looking for a solution and/or another pdf library.

**Comment by denisdulici** [comment]
Here I have suggested the fix to Dompdf https://github.com/dompdf/dompdf/pull/1584
