### ISSUE TITLE
Negative Numbers in Expenses Not Working

### ISSUE THREAD

**Issue by johnnyq** [akaunting/akaunting#617]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create a new expense f ex dishsoap 5.00 from Big Grocery Store. Now lets say you returned the item back to the grocery store. Create a new expense try to enter -5.00 in the amount.

### Expected result

The amount field should allow a negative number for returns on your expenses. 

### Actual result

Does Not allow you to enter negative number under expenses. 

### System information (Akaunting, PHP versions)

Akaunt 1.3.1 / PHP 7.2

### Additional comments

Expense refunds should not go under revenues as this is not a revenue and it would count towards income, and throw numbers off balance.

**Comment by rishirajpurohit** [comment]
Maybe create a new module named refunds handling this specific functionality ?

**Comment by johnnyq** [comment]
@rishirajpurohit That could work. Something like this when you goto expenses click payments, find your orignal expense payment click on the ... action button then there have an option for refund. This way it can reference the original expense as well

**Comment by johnnyq** [comment]
Heres what i'm doing in the mean time while waiting on a fix. I clone an expense, change the date for the refund, then manually go into the database using phpmyadmin and add - in the amount field. It's a temp solution but it does work.

**Comment by denisdulici** [comment]
@johnnyq How is this handled by other vendors such as Xero, Zoho, FreshBooks etc?

**Comment by rishirajpurohit** [comment]
https://www.freshbooks.com/support/how-do-i-refund-in-freshbooks
They say you can edit a payment and set the amount to zero, go to invoice and add the line item with negative value, or delete a record of payment. 

For full refund, delete invoice and payment or set amount to zero(for record keeping)
For partial refund, edit the payment, add a negative line item to invoice(named refund)

**Comment by johnnyq** [comment]
@rishirajpurohit Thanks for looking that up, I believe thats instructions for issuing a refund to a customer to existing invoice. @denisdulici I'll take a look as well and report back.

**Comment by denisdulici** [comment]
Ok, will be waiting for your feedback @johnnyq

**Comment by johnnyq** [comment]
@denisdulici click on the link below and see the bottom portion the faqs, to do a refund on their app you have to pull up the existing expense and just 0.00 it out for the refund. so it balances your books. I guess I could do it that way. I like to use negative expense as well as keep my original expense, that way it matches up with my bank statements. Im really not sure what is the best way to record the expense refunds. Maybe a community poll could help, but really its up to you to make that decision im happy either way. Akaunting is such a  great and excellent open source product!

https://www.freshbooks.com/support/managing-your-expenses-in-freshbooks

**Comment by denisdulici** [comment]
@johnnyq ATM the way other systems issues the refund doesn't match the bank statements but solves it:

https://support.freshbooks.com/hc/en-us/articles/216631488-How-do-I-create-an-Expense-#faqs

I'm closing this but you can create add this to the Ideas category in the forum so we could consider it again for the next versions.

**Comment by enieber** [comment]
@johnnyq if you need use negative items in invoice/bill you can use negative quantity like is "bug" #2102
