### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by pedmindset** [akaunting/akaunting#618]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Do a new installation, follow the install steps and try to log in

### Expected result
Login into dashboard

### Actual result
This page isn’t working accounting.jumeni.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

### System information (Akaunting, PHP versions)
Akaunt 1.3.1 / PHP 7.2

**Comment by denisdulici** [comment]
I'm not able to reproduce such an error, Emmanuel. Feel free to use the forum for further help https://akaunting.com/forum
