### ISSUE TITLE
Cannot install into postgresql

### ISSUE THREAD

**Issue by pongraczi** [akaunting/akaunting#625]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Install process, database setup step, set valid database credentials.

### Expected result
Installation process continues and connect to PGSQL and move on.

### Actual result
No way to select PGSQL as DB type, and error message on step 2:  
Error: Could not connect to the database! Please, make sure the details are correct.  

It seems, it is not possible to install Akaunting with PGSQL at this moment.

### System information (Akaunting, PHP versions)
PHP 7.2  
Akaunting: 1.3.1-stable  
PGSQL 9.6

### Additional comments

Please note, boolean in PGSQL is valid boolean, but laravel used to use integer (0/1) as boolean, which somehow valid in mysql, but in PGSQL it is not valid.

**Comment by pongraczi** [comment]
![kijeloles_862](https://user-images.githubusercontent.com/5891983/48489183-b9e31800-e822-11e8-895a-71d050251d3e.png)

**Comment by denisdulici** [comment]
Have you changed the `DB_CONNECTION` setting from the `.env` file?
