### ISSUE TITLE
Is this project open to contributions and where can i find a more detailed guideline.

### ISSUE THREAD

**Issue by pirupius** [akaunting/akaunting#63]
I've already forked and cloned the repo and; 
- i noticed the `.env.example` file was excluded from the git.  So i created a new `.env` using the basic laravel example. 
- created a new database and made the necesary changes to the db credentials but stil can't get it to run. 
- also run `composer install`

Is there there a step i missed that wasn't mentioned in the `readme.md`

**Comment by denisdulici** [comment]
You don't need to create .env file. Please, follow the Installation steps here, all of them:

https://github.com/akaunting/akaunting#installation

**Comment by pirupius** [comment]
please elaborate on :point_right: `Finally, launch the installer`. i am using vagrant + homestead for development and i've pointed the project to `akaunting.dev`. 

The website link says
Open the link: http://your-domain/akaunting-directory in your browser. It will start the installation wizard.

**Comment by denisdulici** [comment]
Just open `akaunting.dev` in your browser.

**Comment by pirupius** [comment]
i did and it gives a nginx error so i needed to clear it with you if there's any extra configuration needed or it the issue on my end so i can fix it?

**Comment by pirupius** [comment]
@denisdulici i think am just going to close this cause I haven't received any feedback from you. I've checked every configuration on my end and everything is fine so definitely my house is clean. Thanks for whatever help you offered.
