### ISSUE TITLE
Dashboard - Cash flow date range wrong quarter

### ISSUE THREAD

**Issue by spacariz** [akaunting/akaunting#630]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

When selected date range in cash flow as "This quarter" also wring when select "Previous quarter"

### Expected result

01.10.2018 - 31.12.2018

### Actual result

01.09.2018 - 30.11.2018

### System information (Akaunting, PHP versions)

verstion 1.31, php 7.0

**Comment by denisdulici** [comment]
Thanks for reporting.
