### ISSUE TITLE
Error 500 on adding new item to invoice after Update 1.3.2

### ISSUE THREAD

**Issue by fellek** [akaunting/akaunting#631]
Its not possible to add items to invoice or bill.
Error appears after Update to Akaunting 1.3.2.

### Steps to reproduce the issue
1. Create new Invoice or Expenses Bill
2. Fill first Item Row
3. Add new Item

### Expected result
New Item Row should appear

### Actual result
No Item Row appears. 
Request: /incomes/invoices/addItem?item_row=1
Response: Statuscode 500 Internal Server Error

### System information (Akaunting, PHP versions)
Akaunting 1.3.2
PHP 7.2.11
Ubuntu 16.04
Nginx

### Additional comments
Thanks for your codes!

**Comment by JvanEst** [comment]
I have this exact same problem. Found the problem as an variable is tried to be initialised at a stage that the dropdown for the currency code is not yet present. I proposed a fix in my pull-request.

**Comment by cuneytsenturk** [comment]
Solved here #635

**Comment by cuneytsenturk** [comment]
Thank you feedback @fellek
