### ISSUE TITLE
Sending mail throws Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by dseegers** [akaunting/akaunting#641]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Click invoice > More action > Send mail

### Expected result

A send invoice

### Actual result

`/incomes/invoices/1/email`

![image](https://user-images.githubusercontent.com/6848396/49007538-022bff80-f16c-11e8-8de5-931ca67dcda4.png)

### System information (Akaunting, PHP versions)
PHP 7.0

**Comment by denisdulici** [comment]
Daan, I just tried and it worked fine for me. Make sure that your mail settings are correct. Feel free to use the forum for further support.
