### ISSUE TITLE
Invoices do not have a euro sign (PDF)

### ISSUE THREAD

**Issue by dseegers** [akaunting/akaunting#642]
We still have this issue (https://github.com/akaunting/akaunting/issues/506) 

The euro sign is not shown by a new install

![knipsel](https://user-images.githubusercontent.com/6848396/49007828-b594f400-f16c-11e8-82ad-671205b24682.PNG)

**Comment by dseegers** [comment]
I have tested it. The both (the one from the site and the one from gitub) have the same issue.

**Comment by Jhamende** [comment]
Hi ,

I've update to the latest version. When I generate de PDF I don't have any issue, but when sending the invoices to customers, the € symbol in still missing in the pdf-documents. 

Kind regards,
Jonathan Hamende

**Comment by boumanb** [comment]
I can confirm, still experiencing this issue.

![screenshot_2019-02-05_08-36-35](https://user-images.githubusercontent.com/29407220/52258998-63690f80-2921-11e9-86aa-1baec5ed7467.png)

**Comment by boumanb** [comment]
This seems to be fixed by replacing the '€' symbol for '&euro;'.
