### ISSUE TITLE
Add Discount not working

### ISSUE THREAD

**Issue by denisdulici** [akaunting/akaunting#643]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Go to Invoices/Bills > Add New and click on Add Discount link

### Expected result

Show the popup to enter a discount

### Actual result

Nothing

### System information (Akaunting, PHP versions)

Akaunting 1.3.3

### Additional comments

https://akaunting.com/forum/discussion/general/add-discount-not-functioning

**Comment by cuneytsenturk** [comment]
fixed here => https://github.com/akaunting/akaunting/pull/638
