### ISSUE TITLE
Freah Heroku Install - Class 'Faker\Factory' not found

### ISSUE THREAD

**Issue by warisali2** [akaunting/akaunting#644]
Can't Deploy on Heroku

### Steps to reproduce the issue
Push the latest source code (version 1.3.3) to heroku

### Expected result
It should install correctly

### Actual result
remote: In DatabaseServiceProvider.php line 78:
remote:                                      
remote:          Class 'Faker\Factory' not found  
remote:                                           
remote:        
remote:        Script php artisan ide-helper:generate handling the post-install-cmd event returned with error code 1

### System information (Akaunting, PHP versions)
Heroku

**Comment by denisdulici** [comment]
Have you checked the following instructions:
https://devcenter.heroku.com/articles/getting-started-with-laravel
https://medium.com/@sdkcodes/how-to-deploy-a-laravel-app-to-heroku-24b5cb33fbe

**Comment by Jhhames** [comment]
This happens when you're trying to seed in production
In your composer.json file, move "fzaninotto/faker": "~1.4" from "require-dev" to "require", then push to heroku again.

**Comment by ilhamsj** [comment]
still doesn't work for me

**Comment by hamidrezaghanbari** [comment]
> 
> 
> This happens when you're trying to seed in production
> In your composer.json file, move "fzaninotto/faker": "~1.4" from "require-dev" to "require", then push to heroku again.

and this is important to run composer update to update composer.lock file and after that its work now

**Comment by hamidrezaghanbari** [comment]
> 
> 
> still doesn't work for me

please run composer update and after that push on heroku this is the key to solve this problem

**Comment by elvis-onobo** [comment]
**```
> Clear cache
> composer install 
> composer update
> git add
> git commit 
> git push heroku
> 
```**

this worked for me

**Comment by amoungui** [comment]
thanks elvis-onobo,  for your help.

**Comment by rafael019** [comment]
Thanks elvis-onobo :)

**Comment by viveksinh007** [comment]
Thanks elvis 👍

**Comment by nguyenhaidangyq** [comment]
thanks for your help elvis-onobo !! Amazing good job

**Comment by lazaaq** [comment]
Thanks elvis-onobo and hamidrezaghanbari. it works

**Comment by josefernandoperezgarcia1998** [comment]
**```
After moving "fzaninotto/faker": "~1.4" from "require-dev" to "require" in composer.json and composer.lock

Clear cache
composer install
composer update
git add
git commit
git push heroku

THIS WORKS FOR MY PROJECT!!!!! THXX <3
--------------------------
MY NOTES....

**You can translate this to english...**

1. Salir de heroku run bash con "ctrl + c" y decir que "NO" a lo de lotes
2. Abrir vscode, abrir el archivo composer.json
3. Cambiar de "requide-dev" a "require" la línea de "faker", esta linea <"fakerphp/faker": "^1.9.1",>
4. Después en la terminal hacemos un "composer install"
5. Después hacemos un "composer update"
6. Despues hacemos un git status
7. Después hacemos un git add . 
8. Después hacemos un git commit -m "mensaje"
9. Después hacemos un git push heroku master
10. Después hacemos un "heroku run bash"
11. Después hacemos un "php artisan migrate:refresh --seed" 
12. Después vemos la web y listo, iniciamos sesión/registramos, etc...

**Comment by rohit-sagar256** [comment]
Thanks @elvis-onobo i was stuck.

**Comment by Fatkhur123** [comment]
thanks @elvis-onobo this is very good

**Comment by vanotis720** [comment]
> This happens when you're trying to seed in production In your composer.json file, move "fzaninotto/faker": "~1.4" from "require-dev" to "require", then push to heroku again.

> please run composer update and after that push on heroku this is the key to solve this problem

This worked for me
