### ISSUE TITLE
GST Compatability SGST, CGST, IGST, HSN Code, GSTIN information in masters and views ?

### ISSUE THREAD

**Issue by Paumil** [akaunting/akaunting#645]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Install Custom Fields App

Add custom field HSN Code to ITEMS
select where it will appear
Now it will show in the Item blade
store some value
save

### Expected result

Now This custom fields needed to be called from create invoice blade that is not working

### Actual result

no option to call these field in Invoice. It shall be Items table under create invoice blade

### System information (Akaunting, PHP versions)

Akaunting 1.3.3 PHP 7.2.1

**Comment by denisdulici** [comment]
Please, submit issues related to the Akaunting core only.
