### ISSUE TITLE
Problem after editing payed invoice item quantity.

### ISSUE THREAD

**Issue by metecwb** [akaunting/akaunting#647]
items stock quantity is calculated wrong after editing a payed invoice item quantity.

### Steps to reproduce the issue
check an items stock quantity. open a payed invoice and edit quantity of one item you checked .
say you have 100 more items in stock. and you changed item quantity of invoice from 1 to 2.  

### Expected result
after invoice is saved, items is expected to be 99

### Actual result
but actually its 98.

### System information (Akaunting, PHP versions)

Akaunting 1.3.3 and php 7.2.7

**Comment by cuneytsenturk** [comment]
thanks for reporting. @metecwb
