### ISSUE TITLE
 Problem with value display with wrong decimals

### ISSUE THREAD

**Issue by mrcssilvasouza** [akaunting/akaunting#648]
Dear,

In all modules, in the values ​​column, they are being displayed with 4 thousands and 2 decimals.
![error_akaunting](https://user-images.githubusercontent.com/30185683/49157244-19025b80-f2fe-11e8-8833-f44919317a4b.png)

**Comment by denisdulici** [comment]
Please, use the forum for such support requests.

**Comment by qhoirulanwar** [comment]
see https://akaunting.com/forum/discussion/general/currency-issue?page=2
