### ISSUE TITLE
Invoice TOTAL Calculation Mistake between create and showing/paying times

### ISSUE THREAD

**Issue by BRVK** [akaunting/akaunting#650]
![paying invoice](https://user-images.githubusercontent.com/23258135/49174392-3b32c280-f36c-11e8-8c9f-9f84508e5073.PNG)
![creating invoice](https://user-images.githubusercontent.com/23258135/49174393-3bcb5900-f36c-11e8-9217-4d32255eb127.PNG)

Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Go to New Invoice Add Invoice with item. ex:- cost-200 qty:- 1 sub total: 200 now 
add Discount:-10%=20 then Add Tax:-(subtotal-discount)*tax = 18% now 
Total:- (subtotal-discount) + Tax

### Expected result
Total:- (subtotal-discount) + Tax
Total:-  200-20 + 32.4
Total:- 212.4
Here it is showing correct. Ok!, but

### Actual result
While Showing and Paying time
Tax is calculating only for for discounted amount!. ex:- total: 200,  10%discount: 20 
now 18%tax should calculate for 200-20 = 180 is 32.4, but it is showing on disc
i.e discount: 20 tax= 20*18%tax = 3.6.
now the **Total** is become **wrong** from starting creating invoice time...

### System information (Akaunting, PHP versions)
        "php": "=7.2",
        "akaunting/language": "1.0.*",
        "akaunting/money": "1.0.*",
        "akaunting/setting": "1.0.*",
        "akaunting/signed-url": "1.0.*",
        "akaunting/version": "1.0.*",

### Additional comments
Thanks for the software..great one.

**Comment by cuneytsenturk** [comment]
Thanks for reporting. @BRVK [Raghuvamshikrishna Boine]

**Comment by BRVK** [comment]
Thank you...I Appreciate that.
