### ISSUE TITLE
Can't add new bank account

### ISSUE THREAD

**Issue by winfredkqin** [akaunting/akaunting#657]
Can't add a new bank account.

### Steps to reproduce the issue

1. Banking -> Accounts -> Add New
2. "Whoops, looks like something went wrong."

### Expected result

Display Add New Bank Account form

### Actual result

"Whoops, looks like something went wrong."

### System information (Akaunting, PHP versions)

* Akaunting 1.3.4
* PHP 7.0.30
* Debian 9
* Apache 2.4.25

### Additional comments

After turn Debug = true in .env file:

`
Whoops, looks like something went wrong.

(2/2) ErrorException
Trying to get property of non-object (View: AKAUNTING_PATH/public/resources/vie
ws/banking/accounts/create.blade.php) in c85eb88b207b7c00019ee17d41b57deced3f4a96.php line 57

at CompilerEngine -> handleViewException( object(ErrorException), 1) in PhpEngine.php line 44

at PhpEngine -> evaluatePath( 'AKAUNTING_PATH/public/storage/framework
/views/c85eb88b207b7c00019ee17d41b57deced3f4a96.php', array('__env' => object(Factory),
'app' => object(Application), 'errors' => object(ViewErrorBag), 'currencies' => object(Collection),
'currency' => null, 'auth_user' => object(User), 'date_format' => 'd M Y')) in CompilerEngine.php line 59

at CompilerEngine -> get( 'AKAUNTING_PATH/public/resources/views/banking
/accounts/create.blade.php', array('__env' => object(Factory), 'app' => object(Application),
'errors' => object(ViewErrorBag), 'currencies' => object(Collection), 'currency' => null,
'auth_user' => object(User), 'date_format' => 'd M Y')) in View.php line 137

at View -> getContents( ) in View.php line 120

at View -> renderContents( )
in View.php line 85

at View -> render( )
in Response.php line 38

at Response -> setContent( object(View))
in Response.php line 206

at Response -> __construct( object(View))
in Router.php line 615

at Router -> prepareResponse( object(Request), object(View))
in Router.php line 572

at Router -> Illuminate\Routing\{closure}( object(Request))

...
`

**Comment by denisdulici** [comment]
@winfredkqin I'm not able to reproduce such an issue but it seems you've problems with currencies. Please, use the forum for further help.

**Comment by winfredkqin** [comment]
Thank you @denisdulici.  Problem solved by:

`apt install build-essential`

Thanks for your tips.
