### ISSUE TITLE
Error with the constumers module.

### ISSUE THREAD

**Issue by mrcssilvasouza** [akaunting/akaunting#659]
Dear,

When you try to load the clients module, you get an error on line 32 ('emails')

[customers_error.pdf](https://github.com/akaunting/akaunting/files/2637638/customers_error.pdf)

As a palliative solution, I've removed the field [emails]

**Comment by denisdulici** [comment]
There is no customer module in Akaunting. Not sure where do you get it so please, use the forum for further support.

**Comment by mrcssilvasouza** [comment]
Did you load the attached file? Within the Income menu, then Customers
