### ISSUE TITLE
Inclusive tax calculation seems incorrect

### ISSUE THREAD

**Issue by sausin** [akaunting/akaunting#660]
### Steps to reproduce the issue
1. Create an inclusive tax type (eg. 15%)
2. Create a bill with item (eg $115) having the inclusive tax
3. See tax calculated

### Expected result

The tax is calculated on the price of any item and when back calculating tax, the final amount is divided by tax factor. 

In above example, 115 should be divided by 1.15 to obtain non-tax price and subtracted from total price to get 15. 

### Actual result
If an item is added with total $115 price and 15% inclusive tax, the tax calculated is $17.25

### System information (Akaunting, PHP versions)
Akaunting - 1.3.3
PHP - 7.2.10

### Additional comments
![image](https://user-images.githubusercontent.com/11542923/49352573-a2d76d80-f6de-11e8-896c-25208f0a5184.png)

This can also be verified at below links:
http://vatcalconline.com/
https://www.simetric.co.uk/si_deduct_tax.htm

**Comment by cuneytsenturk** [comment]
Thank report @sausin,

**Comment by sausin** [comment]
@cuneytsenturk thanks for the prompt fix!! Awesome stuff :+1:

**Comment by dzid26** [comment]
This is done incorrectly again. 
<img width="743" alt="image" src="https://user-images.githubusercontent.com/841061/232341537-aadd5b90-ff75-4eed-bd0b-6b46a37228b8.png">
