### ISSUE TITLE
SMTP Mail protocol. Have to reenter password to account everytime I change something in general settings, or it is not possible to send emails

### ISSUE THREAD

**Issue by thunoldolsen** [akaunting/akaunting#661]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Change anytning and save on general settings after SMTP password is stored. 

### Expected result
Doesnt have to reenter password on SMTP-account every time I change something in general settings.

### Actual result
It is not possible to send emails befor I reenter the password in SMTP-account and saves again.

### System information (Akaunting, PHP versions)
Akaunting 1.3.4. PHP 7.2

**Comment by denisdulici** [comment]
Confirmed, thanks for reporting.
