### ISSUE TITLE
Apache 2 virtualhost example

### ISSUE THREAD

**Issue by minusplusminus** [akaunting/akaunting#67]
Hi,

could you add this virtualhost example to the docs?

     <VirtualHost *:80>
 
        ServerName example.url.com
        ServerAdmin email@project.com
        DocumentRoot /opt/akaunting
 
        <Directory "/opt/akaunting">
             Options Indexes FollowSymLinks Includes ExecCGI
             Require all granted
              AllowOverride all
        </Directory>
 
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
 
     </VirtualHost>

Solved my problem

**Comment by denisdulici** [comment]
Thanks Martijn. I'm not able to see anything special for Akaunting in your code. I mean that is a general virtual host example. Mine works with the following but again, it's not related with Akaunting:

```
<VirtualHost *:80>
    ServerAdmin webmaster@akaunting.dev
    DocumentRoot "C:/xampp71/htdocs/akaunting-dev"
    ServerName akaunting.dev
    ErrorLog "logs/akaunting-dev-error.log"
    CustomLog "logs/akaunting-dev-access.log" common
</VirtualHost>
```
