### ISSUE TITLE
[Feature Request]: Customisation of financial year

### ISSUE THREAD

**Issue by sausin** [akaunting/akaunting#670]
### Steps to reproduce the issue
1. Go to dashboard
2. See default financial year (currently same as calendar year)

### Expected result
Possibility of setting up a custom financial year. For eg, in India the financial year runs from 1st of April to 31st of March.

### Actual result
Currently not possible.

**Comment by denisdulici** [comment]
Please, use the forum for feature requests.

**Comment by kbhagchandani** [comment]
there is a option to set different financial month start in settings. By default there is 01-01 is there which means 1st Jan. But when we set it to 01-04 which is 1st April. It makes jumping into the future and shows future dates on Dashboard.
![image](https://user-images.githubusercontent.com/2826206/54085363-5649a100-4363-11e9-993c-a460070ecd74.png)
Which should be treated as a bug.
