### ISSUE TITLE
New Paymet Date picker missing

### ISSUE THREAD

**Issue by gucluoz** [akaunting/akaunting#672]
### Steps to reproduce the issue
From a given bill -> add payment 
Click Date text area

### Expected result
Date picker should be visible

### Actual result
Nothing pops up

**Comment by denisdulici** [comment]
It works fine for me:

![screenshot_1544534180](https://user-images.githubusercontent.com/5254835/49803275-605a0480-fd60-11e8-9a7c-418ab6a25475.jpg)

Feel free to use the forum for further help.

**Comment by gucluoz** [comment]
Hello,

Double checked again. Still not working in my case. 
Safari Version 12.0.1 (14606.2.104.1.1) on MacOs Mojave 10.14.1

<img width="1736" alt="screen shot 2018-12-11 at 16 41 47" src="https://user-images.githubusercontent.com/7089196/49804960-014abe80-fd65-11e8-9996-b02c4b992d42.png">
