### ISSUE TITLE
Expense bill numbers should not be unique

### ISSUE THREAD

**Issue by gucluoz** [akaunting/akaunting#673]
### Steps to reproduce the issue
Any given vendor might be accumulating its own numbering scheme thus expense bill numbers are only individually unique.

### Expected result
Cannot insert duplicate expense bill number (eg.65)

### Actual result
Should be able to insert duplicate bill number

**Comment by sausin** [comment]
I think the vendor order number goes in "Order Number" and the bill number is your own unique identifier. I couldn't see any limitation in the code on a quick glance.

**Comment by gucluoz** [comment]
I suppose vendor bill# and order# are different entities in reality. I ain't numbering vendor bills on my side. At least bill number should be accepting null values. Otherwise one should be generating random unique numbers on each vendor bill.

**Comment by denisdulici** [comment]
You may add a prefix to bill number like first 3 letters of the vendor as a unique identifier is required.
