### ISSUE TITLE
Ledger does not include tax amounts

### ISSUE THREAD

**Issue by jholweg** [akaunting/akaunting#678]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. Setup a tax amount (e.g. 21% normal tax)
2. Create a bill with 1 item, amount Eur. 100, use the previously setup tax rate
3. The total bill amount will be Eur. 121 (100 + 21% tax)
4. The ledger table now has the Eur. 100 on the account that was selected when entering the bill item (e.g. 628 General expenses) and Eur. 121 on Accounts Payable (OK)
5. The tax is not recorded in the ledger.
6. The (trial) balance sheet is therefore not in balance (Eur. 100 Debit, Eur. 121 Credit)

### Expected result
The tax should also be recorded in the ledger table. That way, the tax will show up (Eur. 21 in the above example) in the (trial) balance sheet (seperate line "Tax"), and the report is ok again.

### Actual result
See above (steps to reproduce)

### System information (Akaunting, PHP versions)
PHP 7.1, Akaunting 1.3.4

### Additional comments
I would expect that is tax is being used, the profit & loss report should report excluding tax, since tax is not considered to be part of profit & loss (but it is needed to record for payment and withholding, so it needs to be registered and put on the balance sheet as liability (or asset). This will all be much easier to handle (I guess) if the amounts are stored consistenly through the ledger table.

**Comment by kiambal** [comment]
Actually, Total profit include tax as well, total income should exclude tax because debit of Cash should be counterbalanced by the credit of "Sales" and "Sales tax". Error reporting in Double-Entry. If let unchanged, the tax system is let in an unusable state.

**Comment by denisdulici** [comment]
Use this repo only for issues related to the core.
