### ISSUE TITLE
Cannot create new user

### ISSUE THREAD

**Issue by stevkky** [akaunting/akaunting#679]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Click on Add New at auth/users/create
The roles field is required but nothing is showing there

### Expected result
The Roles drop-down is expected to show so that you can select the role the new user belongs to

### Actual result
Missing Role Drop-down but the Red asterix on the Role label still shows

### System information (Akaunting, PHP versions)

Version 1.3.4 
PHP version: 7.1
![error1](https://user-images.githubusercontent.com/4806616/49899373-73013600-fe53-11e8-865b-f8a4ee0313c8.PNG)

**Comment by denisdulici** [comment]
Works fine for me, Stephen, so feel free to use the forum for further support.

![screenshot_1544774116](https://user-images.githubusercontent.com/5254835/49990579-2e7ab500-ff8f-11e8-966f-1e7a3626f5f6.jpg)
