### ISSUE TITLE
Website link is broken

### ISSUE THREAD

**Issue by jeanniton-mnr** [akaunting/akaunting#680]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Go to the project website : https://akaunting.com/

### Expected result

The website content / page

### Actual result

Can't reach site.
akaunting.com’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by denisdulici** [comment]
Works fine for me atm.

**Comment by jeanniton-mnr** [comment]
> Works fine for me atm.

Work for me now too.
Thanks
