### ISSUE TITLE
Related to tax rates during installation.

### ISSUE THREAD

**Issue by aliyilmaz** [akaunting/akaunting#685]
There is a problem in the tax rates section of the setup screen; I couldn't add a tax rate on this screen and couldn't regulate the current tax rates.

### Steps to reproduce the issue

Access the tax rates tab on the Setup screen.

### Expected result

I want it to work.

### Actual result

Not working.

### System information (Akaunting, PHP versions)

PHP 7.1.23
Akaunting 1.3.4

**Comment by batuhawk** [comment]
thanks @aliyilmaz
