### ISSUE TITLE
Add new Item to Paid Invoice should mark Invoice Status as Partial

### ISSUE THREAD

**Issue by jonagoldman** [akaunting/akaunting#690]
### Steps to reproduce the issue
- Create Invoice
- Add Item to Invoice
- Add Full Payment to Invoice
- Add new Item to Invoice

### Expected result
Invoice Status is Partial

### Actual result
Invoice Status is Paid

### System information (Akaunting, PHP versions)
Akaunting 1.3.4
PHP 7.2

### Additional comments
Invoice Status should be Partial because a new Item was added and Invoice Total is not 0

![screenshot from 2018-12-20 17-18-35](https://user-images.githubusercontent.com/1297559/50314021-53819300-047b-11e9-9ca9-22e9c3594dd5.png)

![screenshot from 2018-12-20 17-18-48](https://user-images.githubusercontent.com/1297559/50314026-55e3ed00-047b-11e9-85c0-ea1c9c39d34a.png)

**Comment by denisdulici** [comment]
Instead of that, the system should not allow you to add/remove items if the invoice is paid.

**Comment by jonagoldman** [comment]
i think it can be useful, for example in an hotel, each customer have an invoice with the room already paid, but maybe later they want to add another night, or a shuttle service to the airport. you don't want to make an new invoice every time, you want to use the same one.

**Comment by ferenczAndras** [comment]
That's Right! You need to have the availability to edit paid invoices too.
