### ISSUE TITLE
Facade typo in vendor\akaunting\language\src\Facade.php

### ISSUE THREAD

**Issue by dsparks999** [akaunting/akaunting#691]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

**Just download the latest version off github and unzip in a test folder.  Run composer to install all packages. This was tested on 20 Dec 2018.

Edit the file: C:\xampp\htdocs\test\vendor\akaunting\language\src\Facade.php

File contents are:

```
<?php
namespace Akaunting\Language;
use Illuminate\Support\Facades\Facade as BaceFacade;

class Facade extends BaceFacade
{
    /**
     * Get the registered name of the component.
     */
    public static function getFacadeAccessor()
    {
        return 'language';
    }
}
```

### Expected result

Should probably read "BaseFacade" not "BaceFacade".

### Actual result

Unknown

### System information (Akaunting, PHP versions)

Akaunting 1.3.4

```
<?php
return [
    'name'      =>  'Akaunting',
    'code'      =>  'Reconciliation',
    'major'     =>  '1',
    'minor'     =>  '3',
    'patch'     =>  '4',
    'build'     =>  '',
    'status'    =>  'Stable',
    'date'      =>  '30-November-2018',
    'time'      =>  '18:30',
    'zone'      =>  'GMT +3',
];
```

Language 1.0.7 `( - Installing akaunting/language (1.0.7): Downloading (100%))`

### Additional comments

Seems to not cause any issues but seems like a typo.

A search of the name "BaceFacade" shows zero results except for the file noted above.

**Comment by denisdulici** [comment]
Feel free to report it to the Language repository https://github.com/akaunting/language
