### ISSUE TITLE
Hard coded default language codes in vendor source file Language.php.

### ISSUE THREAD

**Issue by dsparks999** [akaunting/akaunting#692]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

**Just download the latest version off github and unzip in a test folder. Run composer to install all packages. This was tested on 20 Dec 2018.

### Expected result

Unknown

### Actual result

Unknown

### System information (Akaunting, PHP versions)

Akaunting 1.3.4

```
<?php
return [
    'name'      =>  'Akaunting',
    'code'      =>  'Reconciliation',
    'major'     =>  '1',
    'minor'     =>  '3',
    'patch'     =>  '4',
    'build'     =>  '',
    'status'    =>  'Stable',
    'date'      =>  '30-November-2018',
    'time'      =>  '18:30',
    'zone'      =>  'GMT +3',
];
```

Language 1.0.7` ( - Installing akaunting/language (1.0.7): Downloading (100%))`

### Additional comments

There are 2 methods in the file below that seem to have the default language codes hard coded in them.

`File: C:\xampp\htdocs\test\vendor\akaunting\language\src\Language.php`

```
/**
     * Returns the language long code.
     *
     * @param string $short
     *
     * @return string
     **/
    public static function getLongCode($short = 'default')
    {
        if ($short == 'default') {
            $short = app()->getLocale();
        }

        $long = 'en-GB';

        // Get languages from config
        $languages = config('language.all');

        foreach ($languages as $language) {
            if ($language['short'] != $short) {
                continue;
            }

            $long = $language['long'];
        }

        return $long;
    }
```

```
    /**
     * Returns the language short code.
     *
     * @param string $long
     *
     * @return string
     **/
    public static function getShortCode($long = 'default')
    {
        if ($long == 'default') {
            $long = app()->getLocale();
        }

        $short = 'en';

        // Get languages from config
        $languages = config('language.all');

        foreach ($languages as $language) {
            if ($language['long'] != $long) {
                continue;
            }

            $short = $language['short'];
        }

        return $short;
    }
```

The lines in question are: 

```
Line 233: $long = 'en-GB';

Line 262: $short = 'en';

```
I am not sure if these are supposed to be there or left over from testing. I would assume these values would be pulled from the configuration files and not hard coded in the methods shown above.

**Comment by denisdulici** [comment]
Yes, those are supposed to be there.
