### ISSUE TITLE
Getting error when viewing projects or sending from invoice

### ISSUE THREAD

**Issue by os-rsingleton** [akaunting/akaunting#694]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
**Projects Error:**
1. Login
2. Click Projects
3. Select Project (or choose show from tasks menu)

-or-

1. Login
2. Enter `http://<domain>/projects/projects/1 into address bar

**Invoices Error:**
1. Login
2. Click Incomes
3. Click Invoices
4. Select Invoice
5. Click More Actions button
6. Click Send Email

### Expected result
Projects:
Expect the selected project to appear

Invoices:
Expect invoice to be sent to customer

### Actual result
In both cases I get a white screen with the message `Whoops, looks like something went wrong.`

### System information (Akaunting, PHP versions)
php 5.6.3
akaunting 1.2.16

**Comment by os-rsingleton** [comment]
Attached is the error_log from the webserver
[error_log.txt](https://github.com/akaunting/akaunting/files/2703841/error_log.txt)

**Comment by denisdulici** [comment]
Use this repo only for issues related to the core.
