### ISSUE TITLE
cannot send email in 1.0.8

### ISSUE THREAD

**Issue by minusplusminus** [akaunting/akaunting#70]
Hi, I would like to send an email. But sadly enough it doesn't happen. 

<img width="626" alt="schermafbeelding 2017-11-07 om 18 02 57" src="https://user-images.githubusercontent.com/1842262/32506852-f5e9c7ca-c3e5-11e7-867a-e12d58e4d4de.png">

sendmail was missing, but still didn't fix the problem. It can be installed in ubuntu by running:

` sudo apt-get install sendmail`

**Comment by AGhasemzadeh** [comment]
yes, I have this problem too.

**Comment by denisdulici** [comment]
Working on this at https://github.com/akaunting/akaunting/issues/40
