### ISSUE TITLE
Creating invoice fails if fields aren't filled in.

### ISSUE THREAD

**Issue by MatricomHQ** [akaunting/akaunting#708]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create an invoice
Don't fill in required field(s)

### Expected result
System notifies you that a field is required

### Actual result
System instead fails with error:
![image](https://user-images.githubusercontent.com/11204032/50569864-b5b58000-0d26-11e9-9d29-47f591e1c37b.png)

**Comment by denisdulici** [comment]
This must be related to custom fields. Please, use the contact form at the bottom of our site for app support.
