### ISSUE TITLE
Custom fields not showing on Invoice and not searchable

### ISSUE THREAD

**Issue by MatricomHQ** [akaunting/akaunting#709]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create invoice with custom field
OR
Search the system for the custom field data

### Expected result
Invoice shows custom field
AND
Invoice can be located via field's data

### Actual result
Invoice does not show custom field
Invoice cannot be searched with custom field data

![image](https://user-images.githubusercontent.com/11204032/50570002-134ccb00-0d2d-11e9-8081-d5381a42d487.png)

The custom field shows in the EDIT view, however:
![image](https://user-images.githubusercontent.com/11204032/50570010-6aeb3680-0d2d-11e9-8f65-2abd4cf78012.png)

### Additional comments

Without the ability to view or search the custom fields on invoices, they are virtually useless. We need to be able to search for data in this field in our example we need to do a VIN lookup, which is not possible with the way it is currently handled.

**Comment by denisdulici** [comment]
Please, use this repo only for issues related to the core. Use the contact form at the bottom of our site for apps.
