### ISSUE TITLE
no image of company in invoice pdf in 1.0.8

### ISSUE THREAD

**Issue by minusplusminus** [akaunting/akaunting#71]
Hi, when I generate my PDF, I don't see an company logo i just added. I tried to add the logo to /settings/settings/invoice, but that isn't possible neither
<img width="411" alt="schermafbeelding 2017-11-07 om 18 07 18" src="https://user-images.githubusercontent.com/1842262/32507031-98b9c496-c3e6-11e7-987d-7468e8c516fd.png">

But when the print option is selected, the company logo is visible.

**Comment by denisdulici** [comment]
I can confirm this problem, looking for a solution...

**Comment by Marc-oO** [comment]
:+1: +1
According to `routes/web.php +10` :
`http://localhost/uploads/settings/logo.png` is not accessible without a logged in session
PDF lib try to download the "remote" png and fall in a 302 redirect to `http://localhost/auth/login`

**Comment by denisdulici** [comment]
It seems we'll need to embed the logo into the PDF file, otherwise won't work.
