### ISSUE TITLE
Export crashes system

### ISSUE THREAD

**Issue by MatricomHQ** [akaunting/akaunting#710]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Export anything (invoice, bill, etc)

### Expected result
Data will be exported and downloadable

### Actual result
System crashes:
![image](https://user-images.githubusercontent.com/11204032/50570038-fe713700-0d2e-11e9-8c7e-559448452cb7.png)

### Additional comments

I should note that this is being tested after installing custom fields.

**Comment by denisdulici** [comment]
Please, enable debug to see more details https://akaunting.com/docs/developer-manual/debug

**Comment by MatricomHQ** [comment]
I've enabled debug, which works up until I try to export:

![image](https://user-images.githubusercontent.com/11204032/50571515-8112ea00-0d61-11e9-9075-b94cadc23e60.png)


As soon as I click "export", there is no debug, the only thing we have is this:

![image](https://user-images.githubusercontent.com/11204032/50571524-ac95d480-0d61-11e9-988a-0daf08999d2a.png)


Hope this can help. BTW, I have disabled all Apps hoping I could gather a debug.

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue @MatricomHQ. Feel free to use the forum for further support.
