### ISSUE TITLE
Positions are not shown on Report

### ISSUE THREAD

**Issue by diethmar** [akaunting/akaunting#716]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Creating an Income Position dated on 31/12/2018 in a new category "Interests".

### Expected result
Should be shown on income summary with the related category.

### Actual result
The category is shown, but with the amount of 0.00.

### System information (Akaunting, PHP versions)
latest Version of Akaunting

### Additional comments

![grafik](https://user-images.githubusercontent.com/46340491/50627661-d5ba8e80-0f34-11e9-822c-b850281b7afe.png)

**Comment by jleu84** [comment]
I was about to report the same issue.

**Comment by denisdulici** [comment]
Guys, what is your screen resolution?

**Comment by diethmar** [comment]
Resolution is 3840 x 2160, but as already mentioned, it doesn't seem to 
be a problem with the resolution. The categroy is shown, as well "an" 
amount, but alway 0.00 instaed of the amounts given.


Am 07.01.2019 um 18:29 schrieb jleu84:

**Comment by cuneytsenturk** [comment]
Thanks for report. @diethmar
