### ISSUE TITLE
Reporting page shows error

### ISSUE THREAD

**Issue by ahnurbd65** [akaunting/akaunting#719]
### Steps to reproduce the issue

After logging in > open Reports>Income Summary/Expense Summary/Income-Expense Summary

### Expected result

Income Summary/Expense Summary/Income-Expense Summary is shown

### Actual result

Whoops, something went wrong, Error message

### System information (Akaunting, PHP versions)

Version: 1.3.8 Stable, PHP 7.2.3

### Additional comments
Attached debug log as pdf files
You guys are just awesome. Such a great software. Really helpful for small struggling companies like ourselves. ^_^ <3
[expense-summary.pdf](https://github.com/akaunting/akaunting/files/2730375/expense-summary.pdf)
[income-summary.pdf](https://github.com/akaunting/akaunting/files/2730376/income-summary.pdf)
[income-expense-summary.pdf](https://github.com/akaunting/akaunting/files/2730377/income-expense-summary.pdf)

**Comment by ahnurbd65** [comment]
Problem solved when using PHP 5.6

**Comment by EntrepreneurAJ** [comment]
@ahnurbd65 PHP 5 is no longer supported http://php.net/supported-versions.php

All software should now be compatible with PHP 7.2+
