### ISSUE TITLE
getting exception on 3rd step of installation  

### ISSUE THREAD

**Issue by prajay2018** [akaunting/akaunting#723]
getting exception on 3rd step of installation  

 

(3/3) QueryException
SQLSTATE[HY000] [1045] Access denied for user 'forge'@'127.0.0.1' (using password: NO) (SQL: insert into `ak_companies` (`domain`, `updated_at`, `created_at`) values (, 2019-01-10 11:31:36, 2019-01-10 11:31:36))

why user is forge

**Comment by denisdulici** [comment]
I was not able to reproduce such an issue so please, feel free to use the forum for further support.
