### ISSUE TITLE
Unable to install site created with cPanel

### ISSUE THREAD

**Issue by oplarshad** [akaunting/akaunting#724]
Unable to install site created with cPanel.

### Steps to reproduce the issue

1. Created web site using CPanel
2. Unpacked the Akaunting Package into its public_htm folder
3.  Opened the site via browser
### Expected result

Installation window should appear

### Actual result

Currently the site cannot handle this request
HTTP 500 error

### System information (Akaunting, PHP versions)

Akaunting 1.3.9, also tried earlier versions
PHP : tried version 5.6, 7.0, 7.1, 7.2

### Additional comments
Using the 15 days trial version of CPanel

**Comment by mix5003** [comment]
try 
```
chmod -R 0777 storage
chmod -R 0777 bootstrap/cache
```

**Comment by denisdulici** [comment]
Please, use the forum for such issues.
