### ISSUE TITLE
Wrong currency round up

### ISSUE THREAD

**Issue by marcospaegle** [akaunting/akaunting#73]
When I input a invoice/bill item with float value (ex: 62.5) theitems/items/autocomplete?query=hor&type=invoice&currency_code=BRL return round up the value to 63. I search the problem in ClickNow\Money\Money class method "parseAmount" line 239 and "convert" method line 535. If I change that lines to return (float) round($this->convertAmount($amount, $convert), 2); and return new self(round($this->amount * $ratio, 2, $roundingMode), $currency); the price coming right.

**Comment by marcospaegle** [comment]
How I solve this problem: Create a Utils class Money extends ClickNow\Money\Money class and overide the methods.

`<?php

namespace App\Utilities;

use ClickNow\Money\Money as ClickNowMoney;
use ClickNow\Money\Currency;

class Money extends ClickNowMoney
{
    /**
     * Override parseAmount.
     *
     * @param mixed $amount
     * @param bool  $convert
     *
     * @throws \UnexpectedValueException
     *
     * @return int|float
     */
    protected function parseAmount($amount, $convert = false)
    {
        $amount = $this->parseAmountFromString($this->parseAmountFromCallable($amount));

        if (is_int($amount)) {
            return (int) $this->convertAmount($amount, $convert);
        }

        if (is_float($amount)) {
            return (float) round($this->convertAmount($amount, $convert), $this->getCurrency()->getPrecision());
        }

        throw new UnexpectedValueException('Invalid amount "'.$amount.'"');
    }

    /**
     * Override convert.
     *
     * @param \ClickNow\Money\Currency $currency
     * @param int|float                $ratio
     * @param int                      $roundingMode
     *
     * @throws \InvalidArgumentException
     * @throws \OutOfBoundsException
     *
     * @return \ClickNow\Money\Money
     */
    public function convert(Currency $currency, $ratio, $roundingMode = self::ROUND_HALF_UP)
    {
        $this->assertOperand($ratio);
        $this->assertRoundingMode($roundingMode);

        return new self(round($this->amount * $ratio, $currency->getPrecision(), $roundingMode), $currency);
    }
}`

**Comment by o---** [comment]
Totally in favour of getting this fixed. I followed your steps and the price is coming as expected at my end as well.

**Comment by denisdulici** [comment]
I can confirm this and will try to handle in the 1.1 version.
