### ISSUE TITLE
DoubleEntry Installed Version compare

### ISSUE THREAD

**Issue by bdanieljames** [akaunting/akaunting#730]
There is a version error. Installed: 1.0.18, Latest: 1.017 ?? It keeps showing update available.

![version_error](https://user-images.githubusercontent.com/44407304/51232459-c3fbd100-19a1-11e9-8672-a509b7564135.JPG)

**Comment by cuneytsenturk** [comment]
This must be related to Double Entry. Please, use the contact form at the bottom of our site for app support.
