### ISSUE TITLE
Currency balance issue

### ISSUE THREAD

**Issue by Aido21** [akaunting/akaunting#732]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

1. Create the new currency (i created IDR with the currency rate to USD 0.00007143)
2. Set the opening balance for the new account in this currency I set to Rp62.965.905,92
2. Save the account

### Expected result
Current balance must be equal to the opening balance

### Actual result
Current balance is 10000 times more - Rp629.659.059.200,00
See the screenshots

### System information (Akaunting, PHP versions)

Akaunting Version 1.3.10 
PHP 7.3

### Additional comments

![image](https://user-images.githubusercontent.com/21156215/51401057-da15b700-1b84-11e9-82df-9471100c6592.png)
![image](https://user-images.githubusercontent.com/21156215/51401073-e4d04c00-1b84-11e9-8a7c-669bfc4fb5b5.png)

**Comment by denisdulici** [comment]
This happens on some custom PHP versions, check my reply here https://akaunting.com/forum/discussion/general/currency-issue?page=3
