### ISSUE TITLE
Invoice Attachment is not being sent in emails

### ISSUE THREAD

**Issue by AvlSEONinja** [akaunting/akaunting#733]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
- Create a new invoice
- Attach File to invoice
- Save / Send
- The recipient of the email is only receiving a notification email with the invoice as a pdf attachment but not the additional attached file that was attached when creating the invoice.

### Expected result
- The recipient would receive the Invoice and the file that was attached when the invoice was made.

### Actual result
- The email only contains the invoice

### System information (Akaunting, PHP versions)
- Akaunting 1.3
- PHP 7.2
- SMTP 
- SSL
- NameCheap Shared Hosting

### Additional comments
Thank y'all for making such a wonderful software :)

**Comment by denisdulici** [comment]
I'm not sure if this is a bug as atm it's not expected to send the attachment via email. Should it really?

**Comment by boumanb** [comment]
Maybe it's a nice feature to add? I could make a pull request for this one I guess. I can imagine it would be nice to have something like this in some cases.

**Comment by denisdulici** [comment]
It's not really a bug so feel free to create a discussion on the Ideas category of forum so that community could discuss about.
