### ISSUE TITLE
Installer doesn't start 

### ISSUE THREAD

**Issue by darrahts** [akaunting/akaunting#736]
Hello, following the installation guide I come to the last step  

> Finally, launch the installer

and 

>Open the link: http://your-domain/akaunting-directory in your browser. It will start the installation wizard.

No installation wizard starts. my browser only displays the contents of `index.php`

### Expected result

I expected an istallation wizard to start.

### Actual result
my browser displays

```
<?php
/**
 * @package     Akaunting
 * @copyright   2017-2018 Akaunting. All rights reserved.
 * @license     GNU GPL version 3; see LICENSE.txt
 * @link        https://akaunting.com
 */

// Define minimum supported PHP version
define('AKAUNTING_PHP', '5.6.4');

// Check PHP version
if (version_compare(PHP_VERSION, AKAUNTING_PHP, '<')) {
    die('Your host needs to use PHP ' . AKAUNTING_PHP . ' or higher to run Akaunting');
}

// Register the auto-loader
require(__DIR__.'/bootstrap/autoload.php');

// Load the app
$app = require_once(__DIR__.'/bootstrap/app.php');

// Run the app
$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);
```

### System information (Akaunting, PHP versions)
Apache2
php7.0

**Comment by mmendoza000** [comment]
If your browser displays the php file then you don't have PHP 7.0 properly added to Apache2. 

Make sure to have well configured your apache2 to run php 7. Or check how to enable php7 on apache2 `https://stackoverflow.com/questions/35988990/how-to-enable-php7-module-in-apache.`

**Comment by darrahts** [comment]
Thank you. Now I get the following

> The requested URL /auth/login was not found on this server.

My apache2 server serves from the directory `/var/www`
which contains the unzipped akaunting files. I have verified this is the true directory by temporarily moving all files and creating an index.html file that is correctly served in my browser. 

I see that `/auth/login` is located in `/app/Http/Controllers/` ...

**Comment by denisdulici** [comment]
Timothy, I'm not able to reproduce such an issue. Feel free to use the forum for further help.
