### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by m2ura** [akaunting/akaunting#737]
Hello,

I get the following error when running Akaunting on my localhost http://localhost/accounting
Not Found (Error 404)
The requested URL /accounting was not found on this server.
Apache/2.4.37 (Debian) Server at localhost Port 80

and my apache2 server config 

ServerName accounting.conf
	ServerAlias accounting.conf

	ServerAdmin webmaster@localhost

	DocumentRoot /var/www/laravel/akaunting/public

	<Directory /var/www/laravel/akaunting/public>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
    </Directory>

**Comment by denisdulici** [comment]
The document root is wrong, you should remove the `public` part. Feel free to use the forum for further support.

**Comment by Magentron** [comment]
May I ask why it was decided to not use `public` as the document root as in the default Laravel application?
