### ISSUE TITLE
wrong profit

### ISSUE THREAD

**Issue by abhitheawesomecoder** [akaunting/akaunting#740]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Expected result
i purchased a product for Rs 350 sold it for Rs 439 Tax is 18% its showing profit Rs 6

372.03 - 350 = 22.03

profit should be Rs 22.03

**Comment by denisdulici** [comment]
Please, use the forum for support.
