### ISSUE TITLE
not working from subdirectory 

### ISSUE THREAD

**Issue by abhitheawesomecoder** [akaunting/akaunting#742]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
http://68.183.88.58/accounting/auth/login

is not working from sub directory with nginx
![accounting error](https://user-images.githubusercontent.com/3944526/51924235-a6535080-2412-11e9-8537-f0befe8dc960.png)

**Comment by cuneytsenturk** [comment]
This is not Akaunting software issue, You can check configuration and your ngnix setting.Feel free to use the forum for further help.
