### ISSUE TITLE
App Page Requests take a long time when Akaunting.com is unreachable

### ISSUE THREAD

**Issue by johnnyq** [akaunting/akaunting#743]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
If akaunting.com is unreachable or overloaded it makes the akaunting app wait for a response before going to the next page or action in the akaunting app

### Expected result

The akaunting App should not call home on every page refresh, and if akaunting.com is unreachable then the app take at least 40 secs to get to the next page or task

### System information (Akaunting, PHP versions)
Akaunting 1.3.10 php 7.2

### Additional comments

This happened to me  today, I thought my akaunting app was corrupt so I retored from backup and same thing occured pages would take forever to load. I then attempted to goto akaunting.com and the ite was not coming up. So I assumed the app was making a request to akaunting during any app page request.

**Comment by xMohammedx** [comment]
same problem here, i think the app connecting to https://akaunting.com/api/ when it's unreachable.

**Comment by jleu84** [comment]
Yes, same here. Can`t use my local Akaunting at moment.

**Comment by gkipouros** [comment]
Yep, site is down for more than two days now. 

Quick fix:
Edit the files app/Traits/Modules.php and app/Traits/SiteApi.php and remove the connection to the API

**Comment by xMohammedx** [comment]
> 
> 
> Yep, site is down for more than two days now.
> 
> Quick fix:
> Edit the files app/Traits/Modules.php and app/Traits/SiteApi.php and remove the connection to the API

yes it's works i change $base to my domain name.
but it's not working to get latest update.

**Comment by denisdulici** [comment]
We're having a network problem within our server and working hard to fix it asap. Sorry for this inconvenience.

**Comment by rouing** [comment]
@denisdulici :fearful:
