### ISSUE TITLE
Package Installation Problem with Composer - league/url is abandoned

### ISSUE THREAD

**Issue by bansalvinay** [akaunting/akaunting#747]
Accounting not installing with latest version. Used composer to install dependencies. While installing dependencies, following error was shown : 

Package league/url is abandoned, you should avoid using it. Use league/uri instead.
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.

### Steps to reproduce the issue
Clone akaunting, and run composer install

### Expected result
All dependencies should have been installed.

### Actual result

Error : Package league/url is abandoned, you should avoid using it. Use league/uri instead.
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.

### System information (Akaunting, PHP versions)
PHP version : 7.2.12 (cli) (built: Nov 15 2018 01:06:07) ( NTS )
OS Mac (Latest)
Akaunting cloned from master (also tried with stable source 1.3.10)

**Comment by denisdulici** [comment]
Vinay, I just tried a clean git clone and composer install and it worked fine for me.
