### ISSUE TITLE
Income and Expense Summary Report doesn't include 31st of the Month

### ISSUE THREAD

**Issue by jimlovetm** [akaunting/akaunting#750]
In the reports tab, I have tried to retrieve the report for income summary and expense summary but i notice it doesn't show the values entered on the 31st of any month. I entered an income for  31st December 2018 for instance and it couldn't show up on the income summary report. same with expense. I believe it's an issue with the whole of the Reports tab menus

**Comment by cuneytsenturk** [comment]
Hi @jimlovetm,

We already solved it, this issue #716
