### ISSUE TITLE
banking/transactions gives whoops - new install

### ISSUE THREAD

**Issue by ospevack** [akaunting/akaunting#755]
### Steps to reproduce the issue
Install new akaunting instance, raise dummy sales and purchase invoices, pay and receive both to cash account.

go to Banking > Transactions

get whoops

### Expected result
Transactions screen

### Actual result

ErrorExceptionUndefined property: stdClass::$column_name
--
in MySqlProcessor.php line 16
at HandleExceptions->handleError(8, 'Undefined property: stdClass::$column_name', 'C:\\Users\\ospev\\Laragon\\Sites\\aktest\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Processors\\MySqlProcessor.php', 16, array('result' =>object(stdClass)))in MySqlProcessor.php line 16
at MySqlProcessor->Illuminate\Database\Query\Processors\{closure}(object(stdClass))
at array_map(object(Closure), array(object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass),object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass)))in MySqlProcessor.php line 17
at MySqlProcessor->processColumnListing(array(object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass),object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass)))in MySqlBuilder.php line 36
at MySqlBuilder->getColumnListing('ynx_bill_payments')in Builder.php line 86
at Builder->hasColumn('bill_payments', 'paid_at')in Sortable.php line 138
at Model->columnExists(object(BillPayment), 'paid_at')in Sortable.php line 77
at Model->queryOrderBuilder(object(Builder), array('sort' => 'paid_at', 'order' => 'desc'))in Sortable.php line 29
at Model->scopeSortable(object(Builder), array('paid_at' => 'desc'))in Builder.php line 934
at Builder->callScope(array(object(BillPayment), 'scopeSortable'), array(object(Builder), array('paid_at' => 'desc')))in Builder.php line 1247
at Builder->__call('sortable', array(array('paid_at' => 'desc')))in Model.php line 94
at Model->scopeCollect(object(Builder), array('paid_at' => 'desc'))in Builder.php line 934
at Builder->callScope(array(object(BillPayment), 'scopeCollect'), array(object(Builder), array('paid_at' => 'desc')))in Builder.php line 1247
at Builder->__call('collect', array(array('paid_at' => 'desc')))in Model.php line 1374
at Model->__call('collect', array(array('paid_at' => 'desc')))in Model.php line 1386
at Model::__callStatic('collect', array(array('paid_at' => 'desc')))in Transactions.php line 40
at Transactions->index()
at call_user_func_array(array(object(Transactions), 'index'), array())in Controller.php line 55
at Controller->callAction('index', array())in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(Transactions), 'index')in Route.php line 203
at Route->runController()in Route.php line 160
at Route->run()in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in LaratrustPermission.php line 56
at LaratrustPermission->handle(object(Request), object(Closure), array('read-banking-transactions'))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in LaratrustPermission.php line 56
at LaratrustPermission->handle(object(Request), object(Closure), array('read-admin-panel'))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AdminMenu.php line 209
at AdminMenu->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SetLocale.php line 94
at SetLocale->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in LoadCurrencies.php line 27
at LoadCurrencies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in LoadSettings.php line 27
at LoadSettings->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddXHeader.php line 18
at AddXHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in RedirectIfNotInstalled.php line 21
at RedirectIfNotInstalled->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Request.php line 111
at Request->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 27

### System information (Akaunting, PHP versions)
Clone of most recent master on github (4/2/19) - PHP 7.1.7, MySQL 8.0.13

**Comment by batuhawk** [comment]
@ospevack  I tested this issue with your steps but i don't get this problem. I guess you've had a momentary glitch. Don't worry u can use right now clearly.

**Comment by htschannerl** [comment]
@batuhawk I had the same problem.

![screenshot from 2019-02-04 12-16-37](https://user-images.githubusercontent.com/13104346/52214069-ef266180-2877-11e9-9f7c-c337fad30ff2.png)

**Comment by shahalpk** [comment]
In the file `/Users/macuser/gitrepos/shahalpk/akaunting/vendor/laravel/framework/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php`, inside function `compileColumnListing()`, change the SQL as below

    select column_name as "column_name" from information_schema.columns where table_schema = ? and table_name = ?

This is a known issue with MySQL 8 in Laravel.

laravel/framework#20190
