### ISSUE TITLE
Bug with different currencies

### ISSUE THREAD

**Issue by jaja8** [akaunting/akaunting#758]
There is a serious bug if different currencies are used. I have two accounts - rubles and dollars. There are two expense transactions on 05 Feb 2019:

- $ 900.00

- 9.000,00 ₽

In https://app.akaunting.com/expenses/payments everything is ok. However, on the main dashboard page in "TOTAL EXPENSES" and in the "Cash Flow" chart, both currencies are counted in the same amount.

Attached screenshots:

Cash Flow screenshot https://pp.userapi.com/c844418/v844418013/19cb35/Q-4IhVeeDKw.jpg

TOTAL EXPENSES Screenshot https://pp.userapi.com/c844418/v844418013/19cb3e/5bLZSdd9yyE.jpg

**Comment by denisdulici** [comment]
Already replied on forum.

Please, don't create the same issue in different places, it doesn't help.
