### ISSUE TITLE
Duplicate category : when you create category from /incomes/revenues/create 

### ISSUE THREAD

**Issue by gopalrathod131** [akaunting/akaunting#760]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

When you create category from '/incomes/revenues/create' or '/expenses/payments/create'   sections without refreshing the page then it create a duplicate categories number of times. I solved this an issue, so please check and update accordingly.
1. open link Expenses>> Payments >> click on 'Add New'
2. Click on plush(+) sign on category select Box to open popup.
3. Enter category name and Save to store data.
 DON'T REFRESH PAGE
4.  Again, repeat step 2 and 3 to create duplicate categories

### Expected result
1.  First time create a single category,
2. Second time create two duplicate category

### Actual result
1. Its create a single category every times

### System information (Akaunting, PHP versions)
\resources\views\modals\categories\create.blade.php line number:  45

 Remove the code :
    //$(document).on('click', '#button-create-category', function (e) {
Add this code: 
$('#button-create-category').on('click', function (e) {

### Additional comments
Document found multiple times so its create duplicate category.

**Comment by denisdulici** [comment]
Gopal, could you please send a pull request with your fix?

**Comment by gopalrathod131** [comment]
I try to commit but face git error.
Please replace code with new code on line 45.

Existing code :  $(document).on('click', '#button-create-category', function (e) {
New code : $('#button-create-category').on('click', function (e) {
