### ISSUE TITLE
Bank account and chart of account discrepencies

### ISSUE THREAD

**Issue by jarehart** [akaunting/akaunting#761]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

1. Create bank account
2. Setup double-entry accounting
3. Journal entry to initially fund bank account from an equity account

### Expected result

Increase bank balance by the amount of the deposit. Reflect an increase in equity account.

### Actual result

Duplicate deposit entries including a random entry for accounts receivable. Also, the amount shows up as a deposit and is included in profit & loss. An equity deposit created by a journal entry should not show up on a profit & loss statement.

### System information (Akaunting, PHP versions)

Akaunting 1.3.11
Double Entry 1.0.23

### Additional comments

I deleted the bank account from the chart of accounts with no issue. The bank account is still listed under Banking -> Accounts, however. I tried to delete the bank account from this page and receive an error: "Warning: You are not allowed to delete [account name] because it has company related. "

**Comment by denisdulici** [comment]
Please, use the ticket system for app support https://akaunting.com/support
