### ISSUE TITLE
Loading Time issue

### ISSUE THREAD

**Issue by anoopmb** [akaunting/akaunting#763]
Its taking so much time to load pages even in localhost

**Comment by sausin** [comment]
@anoopmb  If you're not using any modules then you can add the below to your hosts file and it you should feel improvement in loading times
![image](https://user-images.githubusercontent.com/11542923/52525574-94ef2b80-2cd1-11e9-97b6-b41af81177a5.png)

**Comment by denisdulici** [comment]
Please, use the forum for support.
