### ISSUE TITLE
Arabic invoice

### ISSUE THREAD

**Issue by xMohammedx** [akaunting/akaunting#764]
### Steps to reproduce the issue
add invoice and try to print it in Arabic language

### Expected result
printed RTL.

### Actual result
printed LTR and it's unreadable.
![image](https://user-images.githubusercontent.com/12001629/52539084-21115980-2d8b-11e9-85d6-e75aebd6832a.png)

### System information (Akaunting, PHP versions)
 Version 1.3.11 

Thank you for the great system.

**Comment by denisdulici** [comment]
Unfortunately, RTL support is not available at moment.
