### ISSUE TITLE
Wrong translation af items

### ISSUE THREAD

**Issue by Dafnie** [akaunting/akaunting#765]
### Steps to reproduce the issue
Set locale to danish

### Expected result
"Items" should be translated to "Varer"

### Actual result
"Items" is translated to "Elementer"

### System information (Akaunting, PHP versions)
Akaunting v1.3.11

**Comment by denisdulici** [comment]
Carsten, you can contribute to the translation via Crowdin https://crowdin.com/project/akaunting
