### ISSUE TITLE
Should define page direction in layouts.

### ISSUE THREAD

**Issue by AGhasemzadeh** [akaunting/akaunting#77]
Hello,
Some languages are Right To Left and some other LTR.
In layouts we need to change `<html>` tag and add `<html dir="trans('general.direction')">`

**Comment by denisdulici** [comment]
Hello,

Add just that attribute won't make the layout RTL. Full RTL support will come in the next releases.

Regards

**Comment by linuxjuggler** [comment]
@denisdulici  when anyone downloads the release file `Akaunting_x.x.x-Stable.zip` the file contain no `composer.json` file at all, check this video https://cl.ly/o1Ml
I think its the case even when you download the file from the website too.
