### ISSUE TITLE
New install will not allow cash account to change currency

### ISSUE THREAD

**Issue by kerrsmith** [akaunting/akaunting#772]
### Steps to reproduce the issue

Fresh install
Settings -> General -> Defaults -> set currency to British Pound
Banking -> Accounts -> Cash ->Edit

Currency is still dollars, change to British Pound
Save
error:  Warning: You are not allowed to disable or change the currency of Cash because it has company related.

Work around:
Banking -> Accounts -> Add New
add a temporary account

Settings -> General -> Defaults -> set default account to temporary one just created
Banking -> Accounts -> Cash ->Edit
now change Cash account to British Pounds

Settings -> General -> Defaults -> set default account back to Cash
Banking -> Accounts -> Temporary account -> delete

### Expected result

When you set the default currency on a fresh install the Cash account should also be set to the chosen currency

### Actual result

The Cash account stays as dollars and will not allow a change as it is already linked to a company

### System information (Akaunting, PHP versions)

Akaunting: Version 1.3.12
PHP: 7.2.2
Apache/2.4.10 (Debian)

**Comment by keithlaikf** [comment]
To workaround this, you can 
1) You must create another account
2) Go to Settings -> General, select the Defaults tab
3) Change the Default account from Cash to your new account
4) Go to Banking -> Accounts, edit the Cash
5) Change the currency from USD to your currency
