### ISSUE TITLE
Cannot open the Settings->General after upgrade to 1.3.12

### ISSUE THREAD

**Issue by keithlaikf** [akaunting/akaunting#774]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Login - Open Settings - General
Undefined index 'financial_year' error

### Expected result
Can Open setting general

### Actual result
Undefined index: financial_start (View: C:\xampp724\htdocs\akaunting\resources\views\settings\settings\edit.blade.php)
CompilerEngine->handleViewException(object(ErrorException), 1)
in PhpEngine.php line 44

### System information (Akaunting, PHP versions)
Akaunting: 1.3.12
PHP 7.2.4
After upgrade to 1.3.12

### Additional comments
Found that the table settings, the key general.financial_start is missing

**Comment by denisdulici** [comment]
Closing as duplication of forum.
