### ISSUE TITLE
Calculation of total for european invoices

### ISSUE THREAD

**Issue by jstaerk** [akaunting/akaunting#775]
### Steps to reproduce the issue
I want to write an invoice with a german sender and a german recipient on a german locale.

I create a euro invoice with two items.
Item 1: Quantity 1.1, 19%VAT, price 0.05.
Item 2: Quantity 1.1, 19%VAT, price 0.05 as well.

### Expected result
Two lines, each with a line total of 0.06 (0.055 rounded) and a net invoice total of the sum of the lines= 0.12.
A line which indicates 12 cent as base amount for 19% VAT, 2 cent as VAT and a grant total of 14 cent.

### Actual result
In euro invoices /german locale I can apparently not enter 0.05 as amount, so I have to enter 0,05.
When I use 1,1 as qty and 0,05 as amount I get a line total of 0.05 each and a net total of 0.10 and a gross total of 0.12. 

Apparently I have to use 1.1 as qty and 0,05 as amount, which is inconsistent and should be considered another issue. In that case, the line total is 0.06 (correct) and the net invoice total is 0.11 (incorrect) and a gross total of 0.13.
The 2 cent VAT are there and are correct but in both cases the invoice lacks the base amount for the invoice calculation.

### System information (Akaunting, PHP versions)

Akaunting 1.3.12, PHP 7.1.25.
German locale of the chrome browser and the server os.

### Additional comments

The invoice calculation should IMO be based on CEN's core invoice, https://www.cen.eu/work/areas/ICT/eBusiness/Documents/CWA%2016356-2.pdf .

The calculation of VAT (sec 4.3) requires that a line total exists, which is qty*net, and which is rounded (sec. 4.9) to 2 decimal amounts. All lines of each applicable VAT rate are added, then the VAT percentage is applied and the resulting VAT rate amount is again rounded to two decimals. The total VAT amount is then the sum of all VAT rate amounts.  The gross invoice total in the example should be the sum of the line amounts plus the total VAT amount.

The line indicating the base amount for the vat calculation is IMO required per §14 UStG https://www.gesetze-im-internet.de/ustg_1980/__14.html

The remark in your issue #688 that the VAT is calculated incorrectly might refer to this issue.

**Comment by JBtje** [comment]
I read section 4.3 of the CWA 16356-2, but bases on what they say, your expectation is incorrect.

The proper way of calculating VAT, is by adding all values that have the same vat amount, then multiply that number by the vat amount.
In the CWA 16356-2 they do:

| Product | Amount | Price | VAT category | VAT % |
| --- | --- | --- | --- | --- |
| 1 | 1 | 125 | T01 | 20% |
| 2 | 1 | 24 | T02 | 10% |
| 3 | 1 | 136 | T01 | 20% |
| 4 | 1 | 95 | T02 | 10% |
| Charge| ~| 20 | T01 | 20% |

VAT Taxable amount for T01: (1 * 125) + (1 * 136) + 20 = 281
High VAT amount: 281 * (20/100) = 56.20

VAT Taxable amount for T02: (1 * 24) + (1 * 95) = 119
Low VAT amount: 119 * (10/100) = 11.90

VAT total = sum = 56.20 + 11.90 = 68.1


Based on your example, the correct values are:

Invoice w/o VAT: ((1.1 * €0.05) + (1.1 * €0.05)) = €0.11
VAT amount: round( €0.11 * 0.19 ) = €0.02
Total invoice amount: €0.11 + €0.02 = €0.13

So, based on the values you gave, the VAT calculation is correct

**Comment by denisdulici** [comment]
Closed based on @JBtje calculation approval.
