### ISSUE TITLE
Downloaded Invoice does not include Invoice number in filename.

### ISSUE THREAD

**Issue by johnnyq** [akaunting/akaunting#779]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Download an invoice

### Expected result

invoice should be renamed to the current invoice number fex invoice_100 or could be something like invoice_2019-02-18_Client Name_002.pdf or maybe have a setting for custom name.

### Actual result

when you download an invoice. The file name is Invoice_UNIXTIMESTAMP.pdf This makes it difficult when you want to attach pdf to email and the invoice number is no where to be found in the filename.

### System information (Akaunting, PHP versions)
Akaunting 1.3.12

PHP-7.2

**Comment by mocig** [comment]
https://github.com/akaunting/akaunting/pull/1403

**Comment by denisdulici** [comment]
Now available.
