### ISSUE TITLE
Add composer package

### ISSUE THREAD

**Issue by AGhasemzadeh** [akaunting/akaunting#78]
Hello,
I want to add some new composer package, But I can't find composer.json.

**Comment by denisdulici** [comment]
Hello,

That is already available.

Regards

**Comment by linuxjuggler** [comment]
@denisdulici when anyone downloads the release file `Akaunting_x.x.x-Stable.zip` the file contain no `composer.json` file at all, check this video https://cl.ly/o1Ml
I think its the case even when you download the file from the website too.

**Comment by linuxjuggler** [comment]
Also, it would great if you guys can commit the `composer.loc` file to the repo, even if you have the versions set as the exact match in `composer.json` file. as this file will be so helpful for everyone.

thanks

**Comment by denisdulici** [comment]
@linuxjuggler Release files are for end-users and they don't need it. Will add `composer.lock` asap.

**Comment by linuxjuggler** [comment]
@denisdulici  it would be great if you guys can add a readme file to the stable file explaining that this is intended for the end users so it has no `composer.json` and if they need to add anything its better to get the source code.
