### ISSUE TITLE
I can't create any new users

### ISSUE THREAD

**Issue by cjvaland** [akaunting/akaunting#783]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Click on user logo > select users > click add new
Fill new user details assign a role
leave either enabled or not
click save
page refreshes with no error or message to say it completed successfully

### Expected result
Click on user logo > select users 
You should see the new user listed

### Actual result
Click on user logo > select users 
It doesn't list the new user

### System information (Akaunting, PHP versions)
Latest Cloud version

**Comment by denisdulici** [comment]
Please, use the forum for cloud related issues.
