### ISSUE TITLE
I can't create new company from companies page

### ISSUE THREAD

**Issue by cjvaland** [akaunting/akaunting#784]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
As per the documentation https://akaunting.com/docs/user-manual/companies

### Expected result
When you login to a given company, in the left top corner, when you select switch company, it takes you to the companies page. there should be an + add new button

### Actual result
+ new button does not appear

### System information (Akaunting, PHP versions)
Latest cloud verson

### Additional comments
You get the option to create a new company after you logout from all session and log back in.
only from the main page, once you go past that page the expected location under companies still does not show the + add new button to add new companies

**Comment by denisdulici** [comment]
You should use the Get Started page for Cloud company creation https://akaunting.com/start
