### ISSUE TITLE
Invalid Pagination Path

### ISSUE THREAD

**Issue by kbhagchandani** [akaunting/akaunting#788]
Pagination path is not being generated properly in sub components like customers.

### Steps to reproduce the issue
1. Go to Incomes -> Customers
2. Click on customer name. (You must be having 26 transaction for the selected customer. In my example I am marking customer id **1**)
3. Click on the page 2 link on the transactions list.

### Expected result
The link must be: _"incomes/customers/**1**/?page=2"_

### Actual result
Link being generated: _"/?page=2"_

### System information (Akaunting, PHP versions)
Akaunting Version 1.3.14
PHP Version 7.3

**Comment by denisdulici** [comment]
Please, try this again with 2.0 version.
