### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by turkeryildirim** [akaunting/akaunting#792]
Hello,
Thanks for your efforts and make this open source project available. I saw this project in DigitalOcean's app list. Installed to my local dev environment and then wanted send a PR to fix a listed bug but then i'm little confused what to do next. Is there any coding standard that i'd follow, do i need to make changes on "chagelog" file, does it even exist? like so on. So here we are...

I believe it's a good practice to include a "Contributing" file that describes how to contribute this project and which steps i'd follow before sending a PR like write & run tests, check coding standards, update readme, changelog etc.

e.g: 
https://github.com/thephpleague/fractal/blob/master/CONTRIBUTING.md
https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/CONTRIBUTING.md
https://github.com/Dealerdirect/phpcodesniffer-composer-installer/blob/master/CONTRIBUTING.md
https://github.com/mozilla/nunjucks/blob/master/CONTRIBUTING.md

I'm not sure how you manage releases but i think there should be public dev branch in any case .e.g to merging PRs

Türker.

**Comment by denisdulici** [comment]
Glad to see you liked Akaunting. You can check the read me file for details on [contributing](https://github.com/akaunting/akaunting#contributing).
