### ISSUE TITLE
Need the ability to add credit notes for customer returns 

### ISSUE THREAD

**Issue by floreich** [akaunting/akaunting#794]
Hey, 
I'm sorry to post this in the issues section, but in the forums I didn't get a reply for 14 days.

We need the ability to add credit notes for invoices, for example if a customer is refunded, I need to create a new invoice of type credit note linked to the first invoice but with negative amounts

**Comment by denisdulici** [comment]
I'm sorry but such a feature is not available. Feel free to post it to the Ideas section for future versions.

**Comment by floreich** [comment]
Read it carefully. I've added a post 3 weeks ago but nobody got back to me. Not having a such essential feature renders your whole software useless

**Comment by ldgbc** [comment]
Saying that the whole software is useless is bit harsh. Yes the forum is quite inactive with the user. Those that do post on the forum to keep it alive get spam trigger.

Currently there isn't even a refund system (negative value) you will need more than just Credit Notes feature.
