### ISSUE TITLE
Error in Calculation in P/L Report

### ISSUE THREAD

**Issue by makvital** [akaunting/akaunting#798]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
- Change the "Financial Year Start" under "Settings > General > Localization" to 01-04(April)
- Go to "Reports > P/L Report" 
- You could see a wrong calculation of Gross Profit and Total Expense. 
- Net Profit is calculated correctly though. 

### Expected result
- It should calculate the line items under Apr-Jun column. 

### Actual result
- But it was calculated the line items under Jan-Mar column. 

### System information (Akaunting, PHP versions)
Akaunting - 1.3.14
PHP - 7.1

### Additional comments
- Net Profit is correct though. 
- You can see the error explained in the pic https://ibb.co/QPdVLrW

**Comment by cuneytsenturk** [comment]
Thanks  @makvital
