### ISSUE TITLE
Bug in returning Invoice resource

### ISSUE THREAD

**Issue by andrey-kokoev** [akaunting/akaunting#801]
### Steps to reproduce the issue
Attempt to open any invoice on app.akounting.com
E.g., https://app.akaunting.com/incomes/invoices/57062

### Expected result
See the invoice form

### Actual result
Returns message "Whoops, looks like something went wrong."
Request URL: https://app.akaunting.com/incomes/invoices/57062
Request Method: GET
Status Code: 500 
Remote Address: [2606:4700:30::681b:b178]:443

### System information (Akaunting, PHP versions)
app.akounting.com

**Comment by denisdulici** [comment]
Please, use the forum for cloud support.

**Comment by andrey-kokoev** [comment]
Thank you. I shall
