### ISSUE TITLE
New Company Wizard not called after two companies are created

### ISSUE THREAD

**Issue by mgschwan** [akaunting/akaunting#809]
### Steps to reproduce the issue
* Create at least 3 companies (including the first company that is automatically created)
* Complete the wizard for the second company
* Switch to the third company

### Expected result

Wizard for setting up the third company should be shown

### Actual result

No wizard is shown and the company is not set up properly

### System information (Akaunting, PHP versions)

Akaunting 1.3.15

### Additional comments
The wizard can be called manually by going to /wizard

**Comment by cuneytsenturk** [comment]
Hi,

We've solved this issue this commit (https://github.com/akaunting/akaunting/commit/1086eab6742e1e74d509d93ae69cd673e1802702)
