### ISSUE TITLE
Cannot access General Settings on some of the business

### ISSUE THREAD

**Issue by thunoldolsen** [akaunting/akaunting#810]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
I can access only general settings in one of the registered businesses in Akaunting. Its my own business. The other business gives me the message "Whoops, looks like something went wrong." This does also happen to the user of that business. We cant access the general settings.

### Expected result
We can access general settings

### Actual result
Message "Whoops, looks like something went wrong" when we click on General.

### System information (Akaunting, PHP versions)
PHP-FPM 7.2, Nginx, Akaunting v1.3.15. Mysql v5.7.25-0ubuntu0.18.04.2

**Comment by orlydonx** [comment]
Hi, 
This might be of help.
I also encountered this scenario, by clicking "Settings > General" ... having this , so i enabled development mode . .ENV file, and got this exception.
----------------------------------------
 (1/2) ErrorException
Undefined index: financial_start
----------------------------------------
(2/2)  ErrorException  Undefined index: financial_start (View: C:\xampp\htdocs\akaunting\resources\views\settings\settings\edit.blade.php)
--
in Collection.php line 1563

Here is the code lines that's casues the exception:
` <div class="tab-pane tab-margin" id="localisation">
                        {{ Form::textGroup('financial_start', trans('settings.localisation.financial_start'), 'calendar-check-o', ['id' => 'financial_start', 'class' => 'form-control', 'data-inputmask' => '\'alias\': \'dd-mm\'', 'data-mask' => '', 'autocomplete' => 'off'], $setting['financial_start']) }}

                        {{ Form::selectGroup('timezone', trans('settings.localisation.timezone'), 'globe', $timezones, null, []) }}

                        {{ Form::selectGroup('date_format', trans('settings.localisation.date.format'), 'calendar', $date_formats, null, ['autocomplete' => 'off']) }}

                        {{ Form::selectGroup('date_separator', trans('settings.localisation.date.separator'), 'minus', $date_separators, null, []) }}

                        {{ Form::selectGroup('percent_position', trans('settings.localisation.percent.title'), 'percent', $percent_positions, null, []) }}
                    </div>

`

Hope to get answers soon.

Thanks.

**Comment by mgschwan** [comment]
This is related to Issue #804 and Issue #808 

The problem is that several settings are not created in the database for new companies. I for myself fixed it by adding the missing settings directly in the settings table in the database, but that is not an official solution just a quick hack.
