### ISSUE TITLE
How to change Tax Number To GST Number For Front End.

### ISSUE THREAD

**Issue by kumarsahilkumar** [akaunting/akaunting#811]
How to change Tax Number To GST Number For Front End.

Please help me regards this.
Thank You..

**Comment by denisdulici** [comment]
Please, use the forum for such requests.

**Comment by ldgbc** [comment]
You simply can't at the moment. I briefly found that you may be able to do it through the Module system but it not very documents nor is there enough activity on the forum to provide you with that support or discussion.

Otherwise you would have to manually edit it at each update.
