### ISSUE TITLE
Users roles Flawed Hierarchy

### ISSUE THREAD

**Issue by vplaya** [akaunting/akaunting#812]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. Create a new company
2. Create a user as a manager and assign manager only to the new the new company
3. Give the manager the permission to update users

### Expected result
Manager should only have access to users only to the company he is managing or assigned to and should not be able to edit or modify users from other companies he/she does not belong to.

### Actual result
Manager is able to view, edit or modify profiles of users including administrators from companies he/she is not part of or assigned to.

### System information (Akaunting, PHP versions)
Akaunting, 1.3.16 stable version, PHP Version 7.1

### Additional comments
When "Read Auth Users" is disabled for the manager by administrator, the manager is unable to modify his own profile as the page get redirected to the dashboard.

**Comment by denisdulici** [comment]
Users are on top of Companies.

**Comment by vplaya** [comment]
Hi Denis,

So as you close this case, do you imply that the point I am making is not valid?
