### ISSUE TITLE
Financial Start Year (Previous Year)

### ISSUE THREAD

**Issue by ldgbc** [akaunting/akaunting#814]
### Steps to reproduce the issue

Self hosted Version 1.3.16
1. Set up your company (using Wizard)
2. Go into Settings > General > Localization.
3. Under Financial Year Start. Choose any date from previous year (e.g. 01/01/2018).
4. Click Save.
5. Go into Settings > General > Localization.
6. Choose Financial Year Start. Date is automatic changed back to 01/01/2019.

### Expected result

Can choose last year financial years for example 01/07/2018 to 30/06/2019. 

### Actual result

Can't choose any Financial year prior to 01/01/2019. For example: 01/12/2018.

### System information (Akaunting, PHP versions)

PHP 7.0
Akaunting Version 1.3.16

### Additional comments

Akaunting should have a Demo or Developer version hosted by Akaunting. That way we can reproduce these issue to confirm whether it is User error or bug in Akaunting system.

**Comment by denisdulici** [comment]
You're reading the option wrongly, the correct one says `Financial Year Start`. Meaning you select the start of the year, not the year to start.

Here you can test Akaunting as you wish https://marketplace.digitalocean.com/apps/akaunting

**Comment by ldgbc** [comment]
@denisdulici hi Denis,

Thank you for your reply. That what I thought and understand as well. But it is still a bug, albeit a different but instead. Not sure if it still part of this issue or I should make a new one.

Tried using DigitalOcean but it require a credit card information to create a project. I will explain the issue again in response:

Please see attached image for our Country starting financial year.

1. I set financial year of 01-July 2019 (since I can't do 01-July-2018).
![1](https://user-images.githubusercontent.com/1805303/55787437-984c3b00-5af9-11e9-9d6a-81f7bf939b60.png)
2. Click Save and go to Dashboard. As you can see my data/graph will start at 01-July-2019. Today is the 9th of April (or 8th of April depending on your country). So no data is graphed. Nothing will be shown here until 3 month later when it is 01-July-2019. 
![2](https://user-images.githubusercontent.com/1805303/55787467-ad28ce80-5af9-11e9-90cb-8080583338b3.png)
3. As a temporary fix (since I can't choose 2018), I decide to ignore my financial year and just choose 01-Jan-2019.
![3](https://user-images.githubusercontent.com/1805303/55787615-085ac100-5afa-11e9-9e8e-29f5f29512b2.png)
4. Look it working now. It will show all my data since 01-Jan-2019. But sadly I can't see any data relating to July-2018, August, September, October, November or December 2018. Our current financial year is July-2018 to June 2019.
![4](https://user-images.githubusercontent.com/1805303/55787708-37713280-5afa-11e9-8f17-22b0dd26b46a.png)

Please feel free to ask me if there any other question.
