### ISSUE TITLE
Invoice cancellation

### ISSUE THREAD

**Issue by lglconslt** [akaunting/akaunting#819]
I am trying to use this software thanks for keeping it free, i am not an accountant but the interface is friendly. i have a question

When i have created a invoice of 1000USD (example), the customer pays it. Thn i have to written it back and cancel the payment of 1000USD(for some reason) which was earlier marked as PAID invoice.

Why on the dashboard the Total Income and Total Profit is not recalculated after the cancelling of the payment?is there any bug or i have not understood it correctly?

Your explanation will be appreciated, i like the software and want to use it for my company.

**Comment by denisdulici** [comment]
Feel free to use the forum for support.
