### ISSUE TITLE
/api/customers doesn't return anything in 1.0.8

### ISSUE THREAD

**Issue by minusplusminus** [akaunting/akaunting#82]
Hi here again,

I cannot get any customer response from the api. When I do `/api/users`, it returns a full array. Even when I define an id (number or email)` /api/customers/1` nothing back. 

Next to that, i've mentioned that when I want to post an user, I must need an token. It's not needed for adding a customer:

     function addCustomer(cb) {
            request
                .post(root_url + 'customers')
                .accept('application/json')

                .field('name', user.name)
                .field('email', user.email)
                .field('tax_number', user.tax_number)
                .field('phone', user.phone)
                .field('address', user.address)
                .field('website', user.website)
                .field('currency_code', 'EUR')
                .field('enabled', 1)

                .end(cb);
        }

        function addUser(cb) {
            
            request
                .post(root_url + 'users')
                .accept('application/json')
               .field('_token','1tqhopS0lWJq1KtVMi74CvsT2S60fmE1dwTmq5zS')
                .field('name', user.name)
                .field('email', user.email)
                .field('password', user.password)
                .field('password_confirmation',user.password)
                .field('locale', user.locale)
               // .field('picture', 'http://google.com/logo.png')
                .field('enabled', 1)
                .field('companies',['1'])
                .field('roles',['1'])
                .end(cb);
        }

**Comment by denisdulici** [comment]
Hi Martijn. Everything within Akaunting is company based, except users, roles, permissions, and companies itself. So you should add the `company_id` field to your request.

Here you can find more about companies https://akaunting.com/blog/getting-started-companies

**Comment by denisdulici** [comment]
By the way, would you consider translating Akaunting in Dutch? https://crowdin.com/project/akaunting

**Comment by minusplusminus** [comment]
oh yes, removed company_id accidentally. But the problem still exists. When I output `App/Http/Controllers/Auth/Users.php store' I get this:

` Array ( 
         [_token] => 1tqhopS0lWJq1KtVMi74CvsT2S60fmE1dwTmq5zS 
         [name] => grge 
         [email] => grerg@hohiogr.com 
         [password] => test12345 
         [password_confirmation] => test12345 
         [locale] => en-GB 
         [companies] => Array ( 
         [0] => 1 ) 
         [roles] => Array ( 
         [0] => 3 ) 
         [enabled] => 1 )`
without the `_token` I cannot create an user. But I can create an customer

**Comment by denisdulici** [comment]
You should not send `_token` to API.

Even though, Dutch translation would be appreciated by Akaunting community.
