### ISSUE TITLE
Old reconciliations keep transactions blocked

### ISSUE THREAD

**Issue by hernanpuente** [akaunting/akaunting#823]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
I have zero bank reconciliations in my Akaunting instance.
I create a few bank reconciliations for certain ranges of dates (let's say, for each month).
Delete all the bank reconciliations created so far.

### Expected result
I expect all the transactions to be unlocked for edition.

### Actual result
A few transactions are still blocked even if there are no reconciliations remaining in the platform.

### System information (Akaunting, PHP versions)
Online Version 1.3.17

### Additional comments
I need to edit those transactions that have been blocked by a reconciliation, but now I can't because for some reason they remain blocked. I exported the transaction list and these transactions have a '1' in the 'reconciled' column (as expected).

**Comment by denisdulici** [comment]
Closed due to out of date version.
