### ISSUE TITLE
Why is index.php relocated from the /public/ folder to the root folder?

### ISSUE THREAD

**Issue by Pawnerd** [akaunting/akaunting#824]
Laravel was originally made with the intend that any system critical files are not available in the path of the domain. However, Akaunting expects the server hoster to put the whole project on a public domain. Index.php should actually be in the /public/ folder, so why did the developers of Akaunting move it outside?

The only thing holding people back from accessing files that they shouldn't are permissions. If someone screws up the permissions of the .git folder or any other folder/configuration/executable file, the security of the whole server might be at danger.

Would it be helpful if I do a pull request to put index.php back in the public folder with all links fixed?

**Comment by Pawnerd** [comment]
I understand that this could help people get this running in a shared hosting environment where their root access is actually also the public folder. Maybe it would be possible to make it possible to both run the site from / and /public/ ?

**Comment by sausin** [comment]
The [nginx.conf](https://github.com/akaunting/akaunting/blob/master/nginx.example.com.conf) file and [.htaccess](https://github.com/akaunting/akaunting/blob/master/.htaccess) file for the webserver configuration, which are provided with akaunting for reference, exclude access to the folders which should not be accessibly publicly.

On the other hand, it would've been easier if the `index.php` were to remain in its stock laravel location.

**Comment by denisdulici** [comment]
Thanks for the suggestion but we don't intend to make such a change atm.

**Comment by bernhardh** [comment]
This behaviour is really weird.

- It's not common practice
- It's not laravel like
- It's a possible security issue

I really don't understand why you don't let it as it is in laravel (and all common framworks), change it and then make an affort to workaround the problems you just created with this by excluding directories by hand in htaccess.
