### ISSUE TITLE
Numbers need to manually cleared from the input fields

### ISSUE THREAD

**Issue by binaryfire** [akaunting/akaunting#825]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
One example- create an invoice, add an item and click the "Price" field. Same thing occurs with any price field, however

### Expected result
The field is blank and the user can just type the amount. The $0.00 should be light grey background text, not actually pre-filled into the field

### Actual result
$0.00 is pre-filled into the field. The user has to manually delete it before they can enter the amount. Gets confusing and not very user friendly / polished.

### Additional comments
Would be great to get this fixed- I think it's a major UI issue which makes the otherwise very nice interface feel broken or like it's still in development

**Comment by cuneytsenturk** [comment]
This issue solved latest package.
Thank you your feed back.
