### ISSUE TITLE
Recurring invoice is not working

### ISSUE THREAD

**Issue by vplaya** [akaunting/akaunting#826]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Create invoice and set it to recurring

### Expected result
an invoice is expected to be automatically created on the next selected date 

### Actual result
no invoice is automatically created

### System information (Akaunting, PHP versions)
Akaunting Version 1.3.17 and php 7.2

### Additional comments
If this is fixed, it could be great for recurring invoice to automatically email to client instead of being in draft mode because the purpose of recurring is to automate the process.

**Comment by denisdulici** [comment]
You should add the cron command, check out the Setting docs on the site.
