### ISSUE TITLE
Invoice Issue

### ISSUE THREAD

**Issue by ArrodanDDK222** [akaunting/akaunting#827]
Hi there

I've been usning Akaunting for quite some time and love the program.

I recently updated mine to version 1.3.17

And for some reason nothing works on my invoicing.
I can't pull a PDF, I can't send a email, I can't even print one.

Please assist ASAP.

I'm not sure what additional data needs to be sent to you, I will submit whatever you ask for?

**Comment by hd1080** [comment]
I have the same issue. Nginx shows me as error "504 Gateway Time-out". The same happens for bills as well.
