### ISSUE TITLE
No way to edit status of invoice after paid, no way to test payments.

### ISSUE THREAD

**Issue by jhughes2112** [akaunting/akaunting#828]
I have just started using Akaunting, so perhaps I missed something, but as I am new to the program I created my first invoice and then was looking at it while it was in Draft status.  There was a drop-down button for how someone might pay the invoice.  I clicked Cash, then I clicked Paypal (which gave me an error because it's not set up right, I guess), and I clicked Bank Transfer, which didn't seem to do anything.

Although I was in Draft mode, this actually inserted transactions into the DB which were erroneous.  It also automatically set the status of the invoice to Paid.  

I ended up logging straight into MySQL and changing the status, removing the two transactions, and various other small tweaks to clean up the mistake, because there did not appear to be any way to remove a payment, nor was there any way to directly set the payment status of an invoice.  To be clear, I never received any money (from myself), so the status should be manually set until my bank account has the payment in it.  This seems really broken.

Bugs: 
* Status was set to paid just by clicking the payment type drop-downs, but there was no successful payment.
* Payment entries were inserted into DB without actually receiving payment.
* Longer date formats don't fit in the invoice PDF nicely.  "13 Jun 2019" looks good, longer ones do not.

Feature requests:
* Need manual control over Invoice Status.
* Status of an invoice should be set to 'Claimed Paid' not 'Paid', until the operator verifies the funds are present.
* Payment entries should be possible to remove without resorting to hand-editing DB.
* Need a simple way to test payment methods without messing up the database.

Thank you very much for the software.  I know it's not perfect (no software is), but I really like it so far.  It has a lot of potential!

**Comment by denisdulici** [comment]
Please, use the Ideas category in forum for feature requests.
