### ISSUE TITLE
Cannot sign up

### ISSUE THREAD

**Issue by tcurdt** [akaunting/akaunting#829]
### Steps to reproduce the issue

Go to https://akaunting.com/register
Use a @vafer.org email address.

### Expected result

Being able to sign up.

### Actual result

`Oh snap! Email provider is not accepted. Please, try another address.`

### System information (Akaunting, PHP versions)

NA

### Additional comments

Who controls the "Email provider" and where is this in the source code/configured?

**Comment by denisdulici** [comment]
Not related to the repo, feel free to use the contact form.

**Comment by tcurdt** [comment]
@denisdulici It is related to this repo in that sense that I would like to know where the email verification is handled/configured.
