### ISSUE TITLE
api/settings doesn't exist

### ISSUE THREAD

**Issue by minusplusminus** [akaunting/akaunting#83]
Hi. I have another one. 

`{
    "message": "Class App\\Http\\Controllers\\Api\\Settings\\Settings does not exist",
    "code": -1,
    "status_code": 500,
    "debug": {
        "line": 729,
        "file": "/opt/akaunting/vendor/laravel/framework/src/Illuminate/Container/Container.php",
        "class": "ReflectionException",
        "trace": [
            "#0 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('App\\\\Http\\\\Contro...')",
            "#1 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\\Container\\Container->build('App\\\\Http\\\\Contro...')",
            "#2 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Contro...')",
            "#3 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\\Container\\Container->make('App\\\\Http\\\\Contro...')",
            "#4 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Route.php(217): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Contro...')",
            "#5 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Route.php(747): Illuminate\\Routing\\Route->getController()",
            "#6 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Route.php(708): Illuminate\\Routing\\Route->controllerMiddleware()",
            "#7 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Router.php(585): Illuminate\\Routing\\Route->gatherMiddleware()",
            "#8 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Router.php(565): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))",
            "#9 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))",
            "#10 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))",
            "#11 /opt/akaunting/vendor/dingo/api/src/Routing/Adapter/Laravel.php(81): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#12 /opt/akaunting/vendor/dingo/api/src/Routing/Router.php(513): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
            "#13 /opt/akaunting/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#14 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#15 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#16 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#17 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#18 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#19 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#20 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#21 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#22 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#23 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#24 /opt/akaunting/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#25 /opt/akaunting/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
            "#26 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#27 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#28 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#29 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#30 /opt/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
            "#31 /opt/akaunting/index.php(19): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
            "#32 {main}"
        ]
    }
}`

**Comment by denisdulici** [comment]
Thanks Martijn for reporting it, confirmed 😉
