### ISSUE TITLE
Base table or view not found: 1146 Table 'pos.companies' doesn't exist

### ISSUE THREAD

**Issue by EgyptianM** [akaunting/akaunting#833]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
install a fresh copy of Akaunting_1.3.17-Stable

follow the steps of the installer till it comes to company info and hit next

### Expected result
display login page or dashboard I don't know what's the correct flow.

### Actual result
displaying an error saying 

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pos.companies' doesn't exist (SQL: insert into `companies` (`domain`, `updated_at`, `created_at`) values (, 2019-05-30 20:43:43, 2019-05-30 20:43:43))
--
 

it seems that the script doesn't use the prefix that it had put in the .env file.
the script trying to reach table names without a prefix as the error says above.

### System information (Akaunting, PHP versions)
Akaunting_1.3.17-Stable 
php 5.6

### Additional comments
Using Ampps 3.8 on windows 7 as a local host

**Comment by EgyptianM** [comment]
Version 1.3.16-Stable works fine on the same machine.

**Comment by denisdulici** [comment]
Not able to reproduce the issue and 1.3.17 version has been installed by thousands of users. Feel free to use the forum for further help.
