### ISSUE TITLE
Importing Bills gives "ErrorException Trying to get property 'label' of non-object (View: /home/vagrant/code/resources/views/expenses/bills/index.blade.php)"

### ISSUE THREAD

**Issue by baradhili** [akaunting/akaunting#834]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
in default Akaunting 1.3.17 install..
go to bills, select import
download sample spreadsheet 
go to bills, import, upload sample spreadsheet (note no changes)

### Expected result
upload successful, test bill appear in bill listing

### Actual result

ErrorExceptionTrying to get property 'label' of non-object (View: /home/vagrant/code/resources/views/expenses/bills/index.blade.php)
--
in 126753a4cc5ef98d4af97341f1c5b17886c461d0.php line 65
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php line 44
at PhpEngine->evaluatePath('/home/vagrant/code/storage/framework/views/126753a4cc5ef98d4af97341f1c5b17886c461d0.php', array('__env' =>object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'bills' => object(LengthAwarePaginator), 'vendors' => object(Collection), 'categories' => object(Collection), 'statuses' => object(Collection), 'auth_user' => object(User), 'date_format' => 'd M Y', 'limits' => array('10', '25', '50', '100'), 'this_year' => 2019, 'years' => array(2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012)))in CompilerEngine.php line 59
at CompilerEngine->get('/home/vagrant/code/resources/views/expenses/bills/index.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'bills' => object(LengthAwarePaginator), 'vendors' => object(Collection), 'categories' => object(Collection), 'statuses' =>object(Collection), 'auth_user' => object(User), 'date_format' => 'd M Y', 'limits' => array('10', '25', '50', '100'), 'this_year' => 2019, 'years' => array(2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012)))in View.php line 137

### System information (Akaunting, PHP versions)
Akaunting 1.3.17, php 7.3

**Comment by themazim** [comment]
can you please provide the example xlsx, can't find it.

**Comment by baradhili** [comment]
This is the standard xlsx file that is offered on the bill import page

**Comment by themazim** [comment]
Ok, just tried it myself. Mine is working just fine.
[invoices.xlsx](https://github.com/akaunting/akaunting/files/3250775/invoices.xlsx)

**Comment by denisdulici** [comment]
It works fine for me. Please, use the forum for support.
