### ISSUE TITLE
Number of Labels in Expenses Tab in Dashboard

### ISSUE THREAD

**Issue by edelrost** [akaunting/akaunting#835]
Dear developers,

I want to ask if there is a way to show more than 6 Labels for the Pie/Doughnut Chart at the Dashboard. 

I don´t have that many expense categorys and want to see them all represented in the pie chart.
Is there a way to get this to work? Right now only the 6 Expenses Categorys with the highest amount of spent money is shown.

Regards,
edel

**Comment by denisdulici** [comment]
Please, use the forum for feature requests.
