### ISSUE TITLE
[Question] Is Akaunting Free Software?

### ISSUE THREAD

**Issue by asddsaz** [akaunting/akaunting#836]
**Question**: Is Akaunting fully free software?
Is all the source code here? Is it all [free'ly licensed](https://www.wikipedia.org/wiki/Free_software_license)?

I understand that Akaunting states it is [open-source](https://www.wikipedia.org/wiki/Open_source_software) and [free-from-charge](https://www.wikipedia.org/wiki/Freeware), but is it free as in [Free Software](https://www.wikipedia.org/wiki/Free_Software)?

**Comment by denisdulici** [comment]
Not an issue.
