### ISSUE TITLE
[Feature] LibreJS Compliance

### ISSUE THREAD

**Issue by ghbjklhv** [akaunting/akaunting#837]
**Feature**: Become LibreJS Compliant/Compatible
**Description**: Set your JS free using LibreJS.
**How?**: https://www.gnu.org/software/librejs/free-your-javascript.html

__________________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75139593-feature-librejs-compliance)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by denisdulici** [comment]
Not an issue.
