### ISSUE TITLE
Rupee Symbol breaks in Downloaded invoice (PDF)

### ISSUE THREAD

**Issue by technoknol** [akaunting/akaunting#838]
### Steps to reproduce the issue

1. Set Currency of bank account to INR
2. Generate an Invoice
3. Download Invoice PDF.

### Expected result

1. In PDF Rupee Symbol '' should appear properly. 

### Actual result
1. Attached Image 
![image](https://user-images.githubusercontent.com/6429418/59159150-0a81d180-8ae3-11e9-818a-ece5f54f5edd.png)

### System information (Akaunting, PHP versions)
Navigate this link : https://app.akaunting.com/signed/invoices/115196?company_id=35268&expires=1562676365&signature=5b1f353da76a73031579bed2b7e96052

Akaunting Software : https://app.akaunting.com/
Version : 1.3.17

**Comment by denisdulici** [comment]
Works fine in 2.0 version.
