### ISSUE TITLE
Login to Dashboard

### ISSUE THREAD

**Issue by kocuubirasap** [akaunting/akaunting#842]
when I login to dashboard, but get error, below the error screenshot on my browser
![error login akaunting application](https://user-images.githubusercontent.com/47787361/59448274-fdd8e280-8e2e-11e9-8c38-87fbed6cb521.png)

**Comment by themazim** [comment]
Did you follow the installation instructions? https://akaunting.com/docs/installation

Pretty sure it's related to your testseed #841 You will run into errors like this. You are on your own do a fresh install with a new DB and check again.

**Comment by kocuubirasap** [comment]
When I unzip installation and open my browser with url akaunting.test, the inly page login i found not like guide installation

**Comment by kocuubirasap** [comment]
Inly => only

**Comment by kocuubirasap** [comment]
Oy, I run this application on laradock, so the first I set .env file

**Comment by denisdulici** [comment]
Please, follow these installation instructions https://akaunting.com/docs/installation
