### ISSUE TITLE
Invoice attachment not sending

### ISSUE THREAD

**Issue by marcodings** [akaunting/akaunting#849]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Create an invoice, add an attachment.
Send the invoice

### Expected result

Recipient receives email with pdf invoice AND attached attachment

### Actual result

Email is sent, however only the invoice pdf seems attached

### System information (Akaunting, PHP versions)

sending and receiving through gmail accounts

**Comment by denisdulici** [comment]
Marco, that is how the system is designed to work at the moment but would appreciate if you could add this as an idea in the forum https://akaunting.com/forum
