### ISSUE TITLE
Access Denied for vendor

### ISSUE THREAD

**Issue by jayGorio** [akaunting/akaunting#850]
Cannot access css and js when deploying on heroku.  I am getting 403 for css and js. How to fix this?

**Comment by a5a351e7** [comment]
Sounds like a problem of the web server you are using. Could you provide more information of your setup?

**Comment by Myced** [comment]
Try looking at file permissions too. Its a common problem that occurs with web applications.
I have experienced this with wordpress. 
A file might have a permission of 777 but then if the owner is say **root**  and the normal server user is **heroku-112** then loading the assets might give you a 404 or 403 error
