### ISSUE TITLE
Typo in app/Http/Controllers/Expenses/Bills.php

### ISSUE THREAD

**Issue by hd1080** [akaunting/akaunting#853]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. Create a bill
2. Mark bill as paid
3. Open bill, expand histories
4. See under Description the text "bills.mark_recevied"

### Expected result
It should show the translation

### Actual result
It shows the variable

### System information (Akaunting, PHP versions)
Latest version, PHP 7.2

### Additional comments
Typo must be fixed in line 331 to:
'description' => trans('bills.mark_received'),

**Comment by jmurphy45** [comment]
Submitted a PR #857 to fix typo

**Comment by denisdulici** [comment]
Thanks Joseph, will check the PR.
