### ISSUE TITLE
slow website on Local Domain in LAN

### ISSUE THREAD

**Issue by FahadMaqbool** [akaunting/akaunting#855]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

I have installed the app in a local domain PC to use it as web server. the website is slow when the PC is on the local domain network and works fine when I unplug the cable or disable the Ethernet. 

### Expected result

As the app works fine when PC is not on the network. It should work fine when it is on the network and part of the local domain

### Actual result

but it gives slow response and waits for the localhost for more than 25 seconds. 

### System information (Akaunting, PHP versions)

PHP latest, Akaunting latest version.

**Comment by FahadMaqbool** [comment]
Hi, You are closing the issue, but it still persists. kindly help me out in figuring this issue. Thanks

**Comment by themazim** [comment]
This is probably due to akaunting phoning home (version updates etc) and your local timeout for requests is set to 30s.

**Comment by FahadMaqbool** [comment]
Local timeout of On Aug 29, 2019 10:23 PM, mazim <notifications@github.com> wrote:This is probably due to akaunting phoning home (version updates etc) and your local timeout for requests is set to 30s.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
It loads fine within 1 or 2 seconds when not connected to domain network. Only connecting the webapp server to the local domain network causes this issue.

**Comment by asxcom** [comment]
Hello. How did you solve this problem? Could you share with us? I also go through this problem and it is almost impossible to use the system. It is clear that the problem is not with the hosting server I have, as other applications of similar complexity work without problems. Can anyone help to increase the performance? "xdebug" is disabled and so is the debug configuration (APP_DEBUG and DEBUGBAR_ENABLED)
