### ISSUE TITLE
Sending an invoice sets the wrong "sent date"

### ISSUE THREAD

**Issue by justsomebody42** [akaunting/akaunting#861]
### Steps to reproduce the issue
Create a draft invoice.
Wait at least one day.
Go to invoice detail screen
Press "mark as sent"

### Expected result
Sent date of invoice matches the date of the day, when the button "mark as sent" has been pressed.

### Actual result
Sent date of invoice matches the created date.

### System information (Akaunting, PHP versions)
Akaunting Version 1.3.17

### Additional comments
![image](https://user-images.githubusercontent.com/2913127/63511805-740a5d00-c4e2-11e9-8030-e70c082c0664.png)

**Comment by denisdulici** [comment]
That's right, it uses the [`created_at`](https://github.com/akaunting/akaunting/blob/master/resources/views/incomes/invoices/show.blade.php#L103) field as there is no `sent_at` field.

**Comment by justsomebody42** [comment]
Wouldn't it be better to use the current date?
The purpose for drafts is to create them prior to sending them and probably send them days later.
I would assume that the date is correct, if an invoice is sent by akaunting itself, but as the templates are currently unusable for me, I need to send them separately and hit the "mark as sent" button, when I did.
