### ISSUE TITLE
Postgresql support still not working - 1.3.17 - and will not working

### ISSUE THREAD

**Issue by pongraczi** [akaunting/akaunting#864]
History/background, still issue (closed due to missing feedback from me): #625 

I just started the installation again and I have to say, the latest release (1.3.17) still does not support postgresql out of the box. I assume, there are more problem than just rewrite ```app/Utilities/Installer.php``` to force use Postgresql.  

* First I tried to install blindly, so, copy, extract, visit the installation link, select language (1/3) -> Next, set up DB connection (2/3) -> failed.
* I searched the net, found a post about Installer.php, so, I started to force use my postgresql (diff will be shown below) -> failed again with no visible details.
* I checked the .env, it created but with default mysql, so, I rewrite .env to have valid postgresql -> 2/3 still failed.
* I checked the postgresql log, seems PGSQL does not understand utf8mb4 (four bytes), but PGSQL use the common utf8 terminus technicus for utf8 with 1-4 bytes, so, utf8mb4 -> utf8.
* Now the installation process went further, but failed again, due to database migration, because of this behaviour:
```sql
    ERROR:  column "enabled" cannot be cast automatically to type boolean
    HINT:  You might need to specify "USING enabled::boolean".
    STATEMENT:  ALTER TABLE fpt_currencies ALTER enabled TYPE BOOLEAN
    ERROR:  current transaction is aborted, commands ignored until end of transaction block
```
* At this moment I stuck again.

I assume, regarding to @denisdulici if one creates a .env with postgresql data, it will be not enough to support postgresql, so, I should modify the Features and set Postgresql support to experimental, as it seems, nobody really checked postgresql support, except some lunatics, like me :)

---------------
```diff
--- Installer.php_original	2019-03-09 18:46:14.000000000 +0100
+++ Installer.php_forced_pgsql	2019-08-29 08:28:36.196647865 +0200
@@ -153,13 +153,13 @@
     public static function isDbValid($host, $port, $database, $username, $password)
     {
         Config::set('database.connections.install_test', [
-            'host'      => $host,
-            'port'      => $port,
-            'database'  => $database,
-            'username'  => $username,
-            'password'  => $password,
-            'driver'    => env('DB_CONNECTION', 'mysql'),
-            'charset'   => env('DB_CHARSET', 'utf8mb4'),
+            'host'      => '192.168.2.31',
+            'port'      => '5432',
+            'database'  => 'adb',
+            'username'  => 'aer',
+            'password'  => 'aer',
+            'driver'    => env('DB_CONNECTION', 'pgsql'),
+            'charset'   => env('DB_CHARSET', 'utf8'),
         ]);
 
         try {
@@ -179,24 +179,24 @@
         $prefix = strtolower(str_random(3) . '_');
 
         // Update .env file
-        static::updateEnv([
+/*        static::updateEnv([
             'DB_HOST'       =>  $host,
             'DB_PORT'       =>  $port,
             'DB_DATABASE'   =>  $database,
             'DB_USERNAME'   =>  $username,
             'DB_PASSWORD'   =>  $password,
             'DB_PREFIX'     =>  $prefix,
-        ]);
+        ]); */
 
-        $con = env('DB_CONNECTION', 'mysql');
+        $con = env('DB_CONNECTION', 'pgsql');
 
         // Change current connection
         $db = Config::get('database.connections.' . $con);
 
-        $db['host'] = $host;
-        $db['database'] = $database;
-        $db['username'] = $username;
-        $db['password'] = $password;
+        $db['host'] = '192.168.2.31';
+        $db['database'] = 'adb';
+        $db['username'] = 'aer';
+        $db['password'] ='aer';
         $db['prefix'] = $prefix;
 
         Config::set('database.connections.' . $con, $db);
```

**Comment by pongraczi** [comment]
References and hints, background check about boolean in mysql vs. postgresql:  
* https://akaunting.com/tr/forum/discussion/installation-update/using-postgresql
* https://akaunting.com/forum/discussion/installation-update/installation-wizard-with-postgresql
* https://github.com/laravel/laravel/pull/767
* http://www.postgresqltutorial.com/postgresql-boolean/
* https://github.com/crocodic-studio/crudbooster/issues/992
* https://stackoverflow.com/questions/44642309/laravel-postgre-invalid-text-representation

**Comment by pongraczi** [comment]
### Some progress:  
* I changed all ```boolean``` into ```smallinteger``` under database/migrations
* In the Installer.php I removed table prefix generator, because of the modifications I made in that file and I was lazy to restore and start clean ```         $prefix = strtolower(str_random(3) . '_');```

### Results:  
* Installation finished without problem.
* Problem occures every time, when a boolean variable  (Yes/No in the UI for example during the Wizard after logging in as company) want to be stored in the database, due to that, smallint is not boolean and due to that, storing a true of false from the laravel code turns to "" (empty) value and cannot be stored. ```ERROR:  invalid input syntax for integer: ""```

### Verdict
* At this point I give up again, due to that very basic problem, laravel/mysql threat boolean as integer instead of real boolean and due to that all the logic behind how boolean threated must be different.

### Thoughts
* I can see the same issue with several laravel based applications and I still wonder, why one write that, postgresql supported, when it is just not true, at least out of the box.
* Probably it would be relatively easy to rewrite everything related to this very issue and get it working, but mysql/postgresq/sqlite support out of the box is not true.
* Laravel developers seems do not even give a sh*t about this issue (seems completely ignore this).
* Manual changes to get it work means it is not possible to use a common codebase and needs to fork, manually modify base code to get a specific version to work with pgsql.
* In every release one should do the same again and again to get a recent version work with pgsql.
* I recommend to drop postgresql support and write down explicitely, pgsql not supported on the front page.
* If you (akaunting) are able to manage to modify all the codebase to support all mysql/postgresql out of the box, please do it.
* I did not want to be offensive and I really respect all the developers/contributors of Akaunting, really, I just wanted to be clear for future lunatic with questions about postgresql support.

### Final thought
I saw this "Postgresql supported" feature on several projects, where laravel used and I run into this really stupid problem almost all the time, so I had to modify the query and/or data model to really work with pgsql, so, this problem is not Akaunt specific, developers just use laravel as framework and assumed, the framework will work out of the box with pgsql. It just doesn't.  
I think, the best approach would be to modify the the framework to get pgsql supported out of the box and to achieve this, laravel framework developers should be under pressure from the developer community (if anybody even care about this feature).

**So, in 28/08/2019, I have to say, Akaunting will not work on Postgresql and not recommended to modify the code to get it work, due to resource requirements of the maintenance.**

**Comment by denisdulici** [comment]
Thanks István for your detailed feedback, will definitely consider it.

**Comment by pongraczi** [comment]
I have to say, after some cold blood thinking and back to the start, it is possible to handle the installation test without modifying the Installation.php, but prefilling the .env file with suitable values.

So, before starting the installation, you should copy the .env.example -> .env and modify the database settings like this:

```php
DB_CONNECTION=pgsql
DB_HOST=192.168.2.31
DB_PORT=5432
DB_DATABASE=adb
DB_USERNAME=aer
DB_PASSWORD=aer
DB_PREFIX=
DB_CHARSET=utf8
```

In this case the mysql and utf8mb4 problems are gone.

Of course, boolean type still an issue, but in general, it is a step better than jumping into the code and messing with as I did before.

The boolean handling question still open.

Hint: the following table shows the valid values for boolean in PGSQL.

True | False
-- | --
true | false
‘t’ | ‘f ‘
‘true’ | ‘false’
‘y’ | ‘n’
‘yes’ | ‘no’
‘1’ | ‘0’

**Comment by pongraczi** [comment]
As I dig deeper, it turns out, I was too upset to see, the real reason of the error message was that, only one column type changed from tinyInteger into boolean.

To solve this error message during the installation, I had to change only the following line:  
```diff
--- aka/database/migrations/2017_09_01_000000_create_currencies_table.php	2017-10-25 18:51:56.000000000 +0200
+++ akaunt/database/migrations/2017_09_01_000000_create_currencies_table.php	2019-08-29 14:02:03.682166762 +0200
@@ -18,7 +18,7 @@
             $table->string('name');
             $table->string('code');
             $table->double('rate', 15, 8);
-            $table->tinyInteger('enabled')->default(0);
+            $table->boolean('enabled')->default(0);
             $table->timestamps();
             $table->softDeletes();
```

This is because later during the migration the type and the default value of this column will change, so, in this case the type should be boolean from the beginning, that is why the modification was necessary.

With this I was able to finish the installation and login as administrator to start setting up the system.

Of course, the story not ends with this, as I added new Currency during the wizard, I got error message in the DB log and nothing changes in the UI:  
```sql
ERROR:  invalid input syntax for integer: ""
```
![Kijelölés_126](https://user-images.githubusercontent.com/5891983/63939444-99a9e000-ca67-11e9-9800-04327dacd720.png)


### Important
So, when I assumed, it will never work with pgsql and there are serious issues supporting postgresql, I was wrong.  
It turned out, I just missed some fundamentals due to that, I am not an experienced developer using laravel framework and as I run into the very same/similar situation with several laravel based projects, I thought, the problem exists in the framework.  
Instead, it seems implementing such a system, which supports both pgsql/mysql needs more effort to achieve by application developers, than assumed. I guess, if nobody tried to install/setup/test for example Akaunting with pgsql, maybe it will not work as expected.  
I was wrong before, so, maybe it is possible to solve this fresh issue by only settings, or with minimal programming effort.  

Sorry for the false alarm and early action, I try to avoid it in the future. It took me some time to investigating this issue, but was necessary to see it by myself.
