### ISSUE TITLE
Postgresql 9.6 + Aka 1.3.17

### ISSUE THREAD

**Issue by pongraczi** [akaunting/akaunting#865]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
* Install 1.3.17 with PGSQL following the #864
* After login as admin and wizard started, try to add HUF as new currency, saving does not work.
![Kijelölés_126](https://user-images.githubusercontent.com/5891983/63942702-88180680-ca6e-11e9-996f-80c50964a279.png)

* Deleting an existing currency also doesn't work.
* Skipping the wizard, goes to the Dashboard-> Item, add new Item -> try to save -> 
![Kijelölés_127](https://user-images.githubusercontent.com/5891983/63942680-7a628100-ca6e-11e9-858f-cb42bd0b151e.png)

### Expected result
Working as expected.

### Actual result
DB error messages, it seems about enabled columnt, which is boolean:
```ERROR:  invalid input syntax for integer: ""```

This message appears in both cases, so, it should be a common reason.

### System information (Akaunting, PHP versions)
Aka 1.3.17, php 7.2, PGSQL 9.6

### Additional comments
#864

**Comment by shawn-w-berney** [comment]
I understand that this software may only use MySQL now that I've reviewed the issues and comments. That said, you really need to take off the PostgreSQL as a supported database within the documentation. I'll can install MySQL, but this wasted several hours of time.
