### ISSUE TITLE
Install - ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by nobicycle** [akaunting/akaunting#871]
Hello,

Post install, following choosing language, the following url produces the error
http://akaunting.localdomain/install/database

Logs and version information below.

best wishes

 php -v
PHP 7.3.9 (cli) (built: Aug 29 2019 12:55:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies

$ nginx -v
nginx version: nginx/1.16.1

[nginx-conf.txt](https://github.com/akaunting/akaunting/files/3594437/nginx-conf.txt)
[install-log.txt](https://github.com/akaunting/akaunting/files/3594438/install-log.txt)
![2019-09-10 15 54 48 akaunting localdomain a4ddb30e945b](https://user-images.githubusercontent.com/1372447/64594894-770eb400-d3e3-11e9-8a11-bf234c479f6e.png)
![2019-09-10 15 54 31 akaunting localdomain f488be65f8cc](https://user-images.githubusercontent.com/1372447/64594895-770eb400-d3e3-11e9-9bfd-de019cf5e250.png)

**Comment by denisdulici** [comment]
Please, use the forum for technical support.
