### ISSUE TITLE
Can't print or save as pdf invoices

### ISSUE THREAD

**Issue by hd1080** [akaunting/akaunting#872]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. Create new income - invoice
2. Click Print button

### Expected result
I can print the invoice

### Actual result
I get timeout from nginx.

From firefox developer console I see error:
Source map error: request failed with status 403
Resource URL: https://akaunting.example.local/vendor/almasaeed2010/adminlte/bootstrap/css/bootstrap.min.css
Source Map URL: bootstrap.min.css.map

### System information (Akaunting, PHP versions)
Akaunting 1.3.17
PHP 7.3.7

### Additional comments
Akaunting runs in a docker container. Database is MariaDB also in a container.

**Comment by AhtishamShahid** [comment]
Check in Laravel logs 
gd Library extension not available with this PHP and install php-gd Extention 
Same issue faced by me and fixed by installing that extension.

**Comment by denisdulici** [comment]
Please, use the forum for support requests.
