### ISSUE TITLE
Language Choice Display on Installation

### ISSUE THREAD

**Issue by bkmgit** [akaunting/akaunting#879]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

The language choice menu does not appear correctly on Firefox Quantum 69.0 running on Fedora Linux 30

### Expected result

Should see next result, an image is shown from Konqueror browser.

![ScreenshotAkauntingKonqueror](https://user-images.githubusercontent.com/1679477/65385947-bcb17200-dd3d-11e9-8ce4-5ee08233495f.png)

### Actual result

Image of hidden next button is shown 
![Screenshot_AkauntingFirefox](https://user-images.githubusercontent.com/1679477/65385942-a6a3b180-dd3d-11e9-9d80-dc1d215ae1d9.png)

### System information (Akaunting, PHP versions)

Akaunting 1.3.17
PHP 7.3.9
Fedora 30 server

**Comment by denisdulici** [comment]
Please, test this again with 2.0 version.
