### ISSUE TITLE
User profile not working

### ISSUE THREAD

**Issue by tarikcayir** [akaunting/akaunting#88]
Gravatar not working. 

![screenshot_1](https://user-images.githubusercontent.com/1753036/33056228-874dc928-ce95-11e7-8297-a033e1320c22.png)
![screenshot_2](https://user-images.githubusercontent.com/1753036/33056242-91924210-ce95-11e7-98fb-a779b9669252.png)

**Comment by denisdulici** [comment]
Thanks Tarık 😉
