### ISSUE TITLE
$auth_user not found

### ISSUE THREAD

**Issue by scchethu** [akaunting/akaunting#880]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
php artisan config:cache

### Expected result
$auth_user not found in view dashboard.php
even i can't able access auth page

### Actual result

Admin Dashboard loading normally

### System information (Akaunting, PHP versions)
PHP 7.1

**Comment by denisdulici** [comment]
This has been fixed in 2.0 version.
