### ISSUE TITLE
Dashboard "Cash Flow" not correct

### ISSUE THREAD

**Issue by jleu84** [akaunting/akaunting#883]
After an import of all my invoices, the dashboard does not show any Income on the "Cash Flow" dashboard. On the reports all the numbers are OK.

### Steps to reproduce the issue
- Create an invoice
- Export the invoice
- Delete the created invoice
- Import the invoice.

### Expected result
Dashboard "Cash Flow" should show the income of the imported invoice

### Actual result
Dashboard "Cash Flow" does not show the income of the imported invoice

### System information (Akaunting, PHP versions)
Akaunting version 1.3.17
PHP version 7.2

**Comment by denisdulici** [comment]
You should add payments to those invoices https://akaunting.com/docs/user-manual/dashboard

Feel free to use the forum for further support.
