### ISSUE TITLE
db:seed don't respond 

### ISSUE THREAD

**Issue by amineameur** [akaunting/akaunting#884]
can someone please attach a simple database with few users so i can open the system cause when i make db:seed nothing happens
thank you

**Comment by walidabou** [comment]
Try run these two commands:

`php artisan db:seed --class="Database\Seeds\TestCompany"`
`php artisan company:seed {company_id}`

`company_id` is the id of the company that was created by the first command (likely 1). check the 'companies' table in database and to get the id.

**Comment by amineameur** [comment]
that's work for me thank you walidabou
