### ISSUE TITLE
[Feature request] Item tags

### ISSUE THREAD

**Issue by aydin41k** [akaunting/akaunting#886]
For the accountants it is important to group items, include/exclude them from reports, make custom reports for certain type of items, etc. A flexible way of grouping the items would be to tag them. So, it would be very helpful to add a "Tags" field to the item adding/editing view.
If the repo owner/s like the idea, I can submit a PR for this feature.
Cheers

**Comment by denisdulici** [comment]
Please, use the forum for feature requests.
