### ISSUE TITLE
Undefined variable: date_format Undefined variable: $auth_user

### ISSUE THREAD

**Issue by amineameur** [akaunting/akaunting#887]
hi 
after login i get this too messages :
Undefined variable: date_format 
Undefined variable: $auth_user

**Comment by denisdulici** [comment]
This has been fixed in 2.0 version.

**Comment by irvine48** [comment]
comment out these line in `app\Http\ViewComposers\All.php`

>     public function compose(View $view)
>     {
>         // Make sure it's installed
>         // if (!env('APP_INSTALLED') && (env('APP_ENV') !== 'testing')) {
>         //     return;
>         // }
> 
>         // Share user logged in
>         $auth_user = auth()->user();
> 
>         // Share date format
>         $date_format = $auth_user ? $this->getCompanyDateFormat() : 'd F Y';
> 
>         $view->with(['auth_user' => $auth_user, 'date_format' => $date_format]);
>     }

look like two loading lines at the bottom block by the installer.
