### ISSUE TITLE
Tax Rates do not store decimal rates...

### ISSUE THREAD

**Issue by georgemr** [akaunting/akaunting#888]
I have an account in app.akaunting.com. Akounting version is 1.3.17.

I need to insert a tax rates of 6.5%. The app keeps rounding it at 6. 

I have installed the app in a local server and with the same version of akounting and it works.(https://user-images.githubusercontent.com/9483995/67112041-fc556780-f1de-11e9-9cff-cd12d4f57dcb.png)
The problem is I need the live app as it is accessible from the internet.

Can you please advice on how to store decimal number as a tax rate in the on-line app?
![local akounting tax rates]

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue, feel free to use the forum for further support.
