### ISSUE TITLE
Companies Disapear

### ISSUE THREAD

**Issue by angelmartz** [akaunting/akaunting#889]
Example

UserA create CompanyA
UserA create new user UserB as manager 

UserB login and can manage CompanyA
UserB create new CompanyB
UserB can switch between CompanyA and CompanyB

The issue come if
UserA edit UserB, save changes.

Then
UserB didnt see CompanyB, and only can manage CompanyA
CompanyB disssapearing from UserB

**Comment by genilto** [comment]
Same here!!

**Comment by Douglasproglima** [comment]
Same here!!

**Comment by denisdulici** [comment]
Please, use the forum for such support issues.

**Comment by angelmartz** [comment]
This is not a support request is a big bug in your code
