### ISSUE TITLE
Ödeme yöntemi - tablolarda gösterme

### ISSUE THREAD

**Issue by yunusciftci** [akaunting/akaunting#891]
Merhabalar,

Tahsilat ve ödeme alırken işaretlediğimiz ödeme yöntemini ( nakit, banka transferi) tahsilatlar, ödemeler, tedarikçi detayında ve müşteri detayındaki sayfalardaki tablolara basmak istiyorum 

`<td class="hidden-xs">{{ !empty($item->payment_method) ? $item->payment_method : trans('general.na') }}</td>`

`<td class="hidden-xs">{{ !empty($item->payment_method) ? $item->payment_method : trans('general.na') }}</td>`

İlgili sayfalarda bu tarz yazdık arkadaşımla tablolarda göründü ama Nakit yerine offlinepayment.cash şeklinde yazmakta bunu nasıl Nakit olarak göstere biliriz ?

Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

**Comment by denisdulici** [comment]
Duplicate of forum.
