### ISSUE TITLE
White screen no error code when sending email

### ISSUE THREAD

**Issue by tpebic** [akaunting/akaunting#893]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Filled in email server settings on settings page.

Filled out invoice, 

White screen after sending email. No email sent. 

### Expected result
Email sent 

### Actual result
Receive a white screen, with no email sent

### System information (Akaunting, PHP versions)
Using latest version of safari web browser, 
Using latest version of Akaunting

### Additional comments
Not sure is the right place to post. Many people have experienced this issue under the Akaunting support forum. Most people’s advice or suggestions have not fixed the problem.

**Comment by denisdulici** [comment]
Please, use the forum for support requests.
