### ISSUE TITLE
Docker Access Denied

### ISSUE THREAD

**Issue by mattswann** [akaunting/akaunting#894]
I've added Akaunting to a docker container. 

When I compose it I get the following error...

Pulling web (akaunting:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling web (akaunting:)...
ERROR: pull access denied for akaunting, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Could you advise how to access this repo?

**Comment by denisdulici** [comment]
Please, open this to https://github.com/akaunting/docker repo.
