### ISSUE TITLE
Installer "Language" POST action returns a JSON response instead of redirecting to next step

### ISSUE THREAD

**Issue by josepostiga** [akaunting/akaunting#903]
### Steps to reproduce the issue
1. Clone the repository
2. Follows install instructions
3. Open akaunting dev url (on my machine is http://akaunting.test)
4. Choose a language (the first step in the install procedure)

### Expected result

The POST action redirects to the next step automatically.

### Actual result

After I click on "Next ->" I get the following screen:

![imagem](https://user-images.githubusercontent.com/5563554/68998457-79413300-08aa-11ea-890c-80e09e642bea.png)

### System information (Akaunting, PHP versions)

Akauting: 2.0
PHP: 7.2.23

### Additional comments

Since that behavior, of sending the next step's link as a JSON response, is also in another install related controllers (like `Database` and `Settings`) I thought it would be some bug in the Vue components. However, when looking at the `Language.vue` file, it's basically submitting the form and not expecting any JSON response.

I could help out but I need to understand if the Vue file is supposed to wait for the response and act upon it or if the Controller should simply redirect to the next screen?

**Comment by mehmetcoban** [comment]
Did you run the "npm run dev" command when following the instructions? @josepostiga

**Comment by josepostiga** [comment]
@mehmetcoban At the time of opening this issue that was not part of the install instructions. However, even after doing that, and with the fork synced with master, I'm still having the same issue. In fact, when I go to the dev URL, I see only this screen:

![imagem](https://user-images.githubusercontent.com/5563554/70850848-ae7b7980-1e86-11ea-8e05-4b80afeb3876.png)

**Comment by denisdulici** [comment]
This happens when you don't install npm. Follow the installation instructions plz https://github.com/akaunting/akaunting#installation

**Comment by josepostiga** [comment]
Hey, @denisdulici, I don't want to be rude but you're wrong! I've followed the instructions and installed all npm dependencies. Several times, actually.

Here's the node_modules folder:
![imagem](https://user-images.githubusercontent.com/5563554/70851592-c6ef9200-1e8e-11ea-9854-a0d3d5cc929f.png)

Here's the ouput of npm install:
![imagem](https://user-images.githubusercontent.com/5563554/70851588-be975700-1e8e-11ea-9287-2771a5331fd8.png)

And it's the same result.

Closing the issue with the assumption that I didn't follow the instructions is a little rude. I stated that I followed the install instructions. If you can't replicate this in your end, that's ok, I'll try to figure out what's really happening whenever I have more time.

**Comment by Ross-C** [comment]
> Hey, @denisdulici, I don't want to be rude but you're wrong! I've followed the instructions and installed all npm dependencies. Several times, actually.
> 
> Here's the node_modules folder:
> ![imagem](https://user-images.githubusercontent.com/5563554/70851592-c6ef9200-1e8e-11ea-9854-a0d3d5cc929f.png)
> 
> Here's the ouput of npm install:
> ![imagem](https://user-images.githubusercontent.com/5563554/70851588-be975700-1e8e-11ea-9287-2771a5331fd8.png)
> 
> And it's the same result.
> 
> Closing the issue with the assumption that I didn't follow the instructions is a little rude. I stated that I followed the install instructions. If you can't replicate this in your end, that's ok, I'll try to figure out what's really happening whenever I have more time.

Hi, I don't know if this is the same issue I had.  But I had a very similar problem when I moved from my local machine to a server.  For me running "npm rebuild node-sass" corrected the problem.  I was then able to run "npm run dev" successfully again and the redirects worked properly again.

**Comment by alex-phillips** [comment]
I am getting the same issue with all installer steps returning JSON `redirect` payload instead of redirecting to the next step.

**Comment by alex-phillips** [comment]
So the redirect issue is still a problem, but installing the the artisan command works instead.
