### ISSUE TITLE
Reports in multiple currencies

### ISSUE THREAD

**Issue by uniqby** [akaunting/akaunting#915]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. Add several bank accounts with different currency
2. Add Payments/Revenues in different currencies (bank accounts)
3. Open Reports.

### Expected result
Totals should be converted into the main currency with the conversion rate.

### Actual result
All sums calculated as main currency without conversion

### System information (Akaunting, PHP versions)
Akaunting 2.0
php 7.2
mysql 5.7

**Comment by SevanNerse** [comment]
As you see below screenshots, reports work on converted amounts into the main currency.
Could you recheck your environment? or could you give more detailed information, please?

Currencies

![image](https://user-images.githubusercontent.com/16224533/69076546-c48f4900-0a44-11ea-83c4-e5ee1da080c4.png)

Accounts

![image](https://user-images.githubusercontent.com/16224533/69076773-3d8ea080-0a45-11ea-9b55-5d60ba841ed8.png)

Payments

![image](https://user-images.githubusercontent.com/16224533/69076846-6020b980-0a45-11ea-99f3-f52db4023c56.png)

Expense Summary Report

![image](https://user-images.githubusercontent.com/16224533/69076960-9d854700-0a45-11ea-98f2-225abfd2945d.png)

**Comment by uniqby** [comment]
What I'm doing wrong?

![Снимок экрана 2019-11-18 в 22 35 32](https://user-images.githubusercontent.com/1488394/69085072-800ca900-0a56-11ea-839e-2c422ce4e261.png)
![Снимок экрана 2019-11-18 в 22 38 56](https://user-images.githubusercontent.com/1488394/69085073-800ca900-0a56-11ea-999d-b2891e05f012.png)
![Снимок экрана 2019-11-18 в 22 39 58](https://user-images.githubusercontent.com/1488394/69085074-800ca900-0a56-11ea-8426-b693844580d0.png)

**Comment by SevanNerse** [comment]
Also, Could you share your currency definitions?

**Comment by uniqby** [comment]
![Снимок экрана 2019-11-19 в 11 05 09](https://user-images.githubusercontent.com/1488394/69128075-9e0cf480-0abc-11ea-92aa-b609db29735c.png)

**Comment by SevanNerse** [comment]
Sorry, but I could not implement an issue like yours in my local environment.
