### ISSUE TITLE
2.0.0 = to send a bill by e-mail is not possible

### ISSUE THREAD

**Issue by tognit** [akaunting/akaunting#916]
### Steps to reproduce the issue
Send invoice by e-mail

### Expected result
Send invoice by e-mail

### Actual result
Dompdf\Exception
Frame not found in cellmap

Dompdf\Cellmap::get_frame_position:350
vendor/dompdf/dompdf/src/Cellmap.php:350

### System information (Akaunting, PHP versions)
Akaunting 2.0.0
PHP 7.2.24

**Comment by denisdulici** [comment]
Are you able to download the PDF file?

**Comment by tognit** [comment]
No, I can not download a pdf

Dompdf\Exception
Frame not found in cellmap
http://demo.com/incomes/invoices/1/pdf

Dompdf\Cellmap::get_frame_position:350
vendor/dompdf/dompdf/src/Cellmap.php:350

**Comment by denisdulici** [comment]
This has been fixed in master.
