### ISSUE TITLE
2.0.0 =  Can not install modules

### ISSUE THREAD

**Issue by tognit** [akaunting/akaunting#917]
### Steps to reproduce the issue
Install modules via app-store

### Expected result
Install Module

### Actual result
Facade\Ignition\Exceptions\ViewException
Call to a member function can() on null (View: /home/public_html/demo2/resources/views/layouts/admin.blade.php)

App\Http\ViewComposers\Header::compose:30
app/Http/ViewComposers/Header.php:30

### System information (Akaunting, PHP versions)
Akaunting 2.0.0
PHP 7.2.24

**Comment by denisdulici** [comment]
Modules are still under development, we should give some time to devs to make them compatible.
