### ISSUE TITLE
Asset Loading 

### ISSUE THREAD

**Issue by muhammadmahindar** [akaunting/akaunting#93]
The assets(Css/JS) file are not loading even though the files are present in the location getting a 404 not found error in browser console.Trying the project on local

**Comment by denisdulici** [comment]
Any screenshot Muhammad?

**Comment by muhammadmahindar** [comment]
![capture](https://user-images.githubusercontent.com/21039068/33240056-4d4eba6c-d2d1-11e7-8e85-86e2e179dbca.PNG)

What i did was saved the project in xamp and did composer install and composer dump then i changed the index.php to server.php and run php artisan server

**Comment by denisdulici** [comment]
You should not change index or run any artisan command. Here you can find the installation steps for end-users https://akaunting.com/docs/installation

Also, make sure the `APP_URL` value of your `.env` file is correct.
