### ISSUE TITLE
Invoice Screen hang

### ISSUE THREAD

**Issue by monir-dev** [akaunting/akaunting#932]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1. There should be no customer in table.
2. Go to create invoice page
3. In select customer dropdown  there will be "Add New Customer"
4. Click "Add New Customer"
that's it.

### Expected result
Invoice screen hang
![Capture](https://user-images.githubusercontent.com/27449783/69438283-f408c300-0d6e-11ea-974d-75a3f2defca3.PNG)

In console: POST http://localhost/open/akaunting/common/items/total 422 (Unprocessable Entity)

### Actual result
Invoice screen hung 

### System information (Akaunting, PHP versions)
7.3.11

**Comment by cuneytsenturk** [comment]
This issue fixed.  refs: https://github.com/akaunting/akaunting/issues/1075
