### ISSUE TITLE
Unable to init from given url

### ISSUE THREAD

**Issue by jeffebido** [akaunting/akaunting#958]
Receive the following error after printing an invoice:

> Intervention\Image\Exception\NotReadableException
> Unable to init from given url (http://localhost/sistema-strauto/public/img/company.png).
> http://localhost/sistema-strauto/incomes/invoices/1/print

**Comment by jeffebido** [comment]
I believe this problem is related to the company logo, however I send the company logo and the system does not apply. Image upload also doesn't work on products, I don't get any errors when uploading the image, I only get a success message.

**Comment by denisdulici** [comment]
This is fixed in the latest commits.
