### ISSUE TITLE
Class 'AppReportsExpenseSummary' not found

### ISSUE THREAD

**Issue by spinzar** [akaunting/akaunting#962]
Symfony\Component\Debug\Exception\FatalThrowableError
Class 'AppReportsExpenseSummary' not found
http://localhost/akaunting/common/reports

App\Utilities\Reports::getClassInstance
:86
C:\laragon\www\akaunting\app\Utilities\Reports.php:86

    public static function getPeriods()

    {

        return [

            'monthly' => trans('general.monthly'),

            'quarterly' => trans('general.quarterly'),

            'yearly' => trans('general.yearly'),

        ];

    }

 

    public static function getBasises()

    {

        return [

            'accrual' => trans('general.accrual'),

            'cash' => trans('general.cash'),

        ];

    }

 

    public static function getCharts()

    {

        return [

            '0' => trans('general.disabled'),

            'line' => trans('reports.charts.line'),

        ];

    }

 

    public static function getClassInstance($report, $get_totals = true)

    {

        return (new $report->class($report, $get_totals));

    }

}

**Comment by spinzar** [comment]
![class](https://user-images.githubusercontent.com/12146118/69912680-0c17cb00-1470-11ea-8208-4b37555a2a4c.JPG)

**Comment by spinzar** [comment]
https://flareapp.io/share/Lm8pAdmv#F92

**Comment by denisdulici** [comment]
How did you get it?

**Comment by spinzar** [comment]
http://localhost/akaunting/common/reports
Reports +Add New
http://localhost/akaunting/common/reports/create
New Report 
Group By 
change category By Vendors
Edit reports
http://localhost/akaunting/common/reports

**Comment by spinzar** [comment]
![appReportsExpenseSummary](https://user-images.githubusercontent.com/12146118/69932008-c9580080-150c-11ea-98e1-2c4031c2b68b.JPG)

**Comment by denisdulici** [comment]
I've attached what I get. Please, fill the issue template correctly so we could understand the problem.

![screenshot](https://user-images.githubusercontent.com/5254835/69938090-7589ef00-14ed-11ea-9a94-1bbd6eb9a34f.png)
