### ISSUE TITLE
App\Http\ViewComposers\Header::compose :30

### ISSUE THREAD

**Issue by spinzar** [akaunting/akaunting#965]
https://flareapp.io/share/omwAqz7E#F50

**Comment by spinzar** [comment]
http://localhost/akaunting/common/reports
Reports +Add New
http://localhost/akaunting/common/reports/create
New Report
Group By 
category

https://flareapp.io/share/omwAqz7E#F50

**Comment by spinzar** [comment]
![f](https://user-images.githubusercontent.com/12146118/69932288-d2959d00-150d-11ea-8c06-5f46adb34e24.JPG)

**Comment by spinzar** [comment]
A filter crash occurs

**Comment by denisdulici** [comment]
Please, fill the issue template so we could understand the problem better.
