### ISSUE TITLE
Dashboard Customer after logging get errors

### ISSUE THREAD

**Issue by anhphamt** [akaunting/akaunting#97]
Hi, 

I got this issue with customer log in. 

```
Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function url() on null in /Applications/XAMPP/xamppfiles/htdocs/bas/modules/OfflinePayment/Events/Handlers/OfflinePaymentAdminMenu.php:20
Stack trace:
#0 [internal function]: Modules\OfflinePayment\Events\Handlers\OfflinePaymentAdminMenu->handle(Object(App\Events\AdminMenuCreated))
#1 /Applications/XAMPP/xamppfiles/htdocs/bas/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(367): call_user_func_array(Array, Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/bas/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(199): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('App\\Events\\Admi...', Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/bas/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(446): Illuminate\Events\Dispatcher->dispatch('App\\Events\\Admi...')
#4 /Applications/XAMPP/xamppfiles/htdocs/bas/app/Http/Middleware/AdminMenu.php(184): event(Object(App\Events\AdminMenuCreated))
```

The customer account is created with default permission and I installed the latest release. 

Can you take a look at it? 

Thank you

**Comment by cuneytsenturk** [comment]
@anhphamt  Which version are you using?

I am testing at v1.0.12, I can not get the same error

Thank you for feedback

**Comment by anhphamt** [comment]
Hi

I'm also using v1.0.12 download from release. 

Admin account is working fine. 
Admin creates 1 customer account (Customer type)
Customer logins successfully and get error on Dashboard page. 

Thank you

**Comment by anhphamt** [comment]
I will try with new release 1.1.0. Hope it can be fixed.

**Comment by minusplusminus** [comment]
The stacktrace is non related to the issue. There are several things i've mentioned. 

One is that when you add an user thru the `admin > user` option, it caused me difficulties when logging in. 

When I add an user by `incomes > Customers` and create the user, the issue was gone. 
An other thing i've mentioned is that I can add multiple users with the same email address, which caused an login error.

**Comment by denisdulici** [comment]
Now you can't `create` customer from `user` page.

**Comment by anhphamt** [comment]
Thanks a lot
