### ISSUE TITLE
Radio group does not working

### ISSUE THREAD

**Issue by ysfkaya** [akaunting/akaunting#980]
The radio buttons not working when saved the state. So actually any located radio group in setting page when click to "No" value and save it and then seems again "Yes" state.

### Steps to reproduce the issue

1. Open the "Schedule Setting" page.
2. Change the invoice reminder status to "No"
3. Save it

### Expected result

It should seems "No" state the invoice reminder field.

### Actual result

The field seems "Yes" state again.

### System information (Akaunting, PHP versions)

- Akaunting : 2.0.1
- PHP: 7.2

**Comment by denisdulici** [comment]
Fixed https://github.com/akaunting/akaunting/pull/998
