### ISSUE TITLE
Import Transaction sample file missing

### ISSUE THREAD

**Issue by bernhardh** [akaunting/akaunting#986]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

Just go to /common/import/banking/transactions and click on the "download" link for the sample file

### Expected result

Getting the example file from /public/files/import/transactions.xlsx

### Actual result

The file is not found

The complete public/files directory is missing (compare it with https://github.com/akaunting/akaunting/tree/1.3.17/public/files/import)

### System information (Akaunting, PHP versions)

Latest version of akaunting

**Comment by denisdulici** [comment]
Confirmed, thanks for reporting

**Comment by bernhardh** [comment]
Btw. the linked `transactions.xlsx` is also missing in `1.3.17` as well.
