### ISSUE TITLE
Import Payments

### ISSUE THREAD

**Issue by spinzar** [akaunting/akaunting#997]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
http://localhost/akaunting/common/import/expenses/payments
Allowed file types: XLS, XLSX. Please, download the sample file.
choose file 
Payments .xlsx

### Expected result

here we need to **Import** instead of **download** on **blue  color  area**

Allowed file types: XLS, XLSX. Please,  Import the sample file.
![import](https://user-images.githubusercontent.com/12146118/70816244-6753a100-1e12-11ea-9ad1-2047f735c1b5.JPG)

click import 
.

### Actual result
Error Page 500 Internal Server Error
![error](https://user-images.githubusercontent.com/12146118/70816282-82261580-1e12-11ea-8e12-490193e188d9.JPG)

when .env APP_DEBUG=false to true
it shows 
Symfony\Component\Debug\Exception\FatalThrowableError
Class 'App\Imports\Expenses\Payments' not found

### System information (Akaunting, PHP versions)
Akaunting Version 2.0.1 PHP 7.2

**Comment by mj-isip23** [comment]
Submitted [PR](https://github.com/akaunting/akaunting/pull/1000) for this fix.
