### ISSUE TITLE
Unable to create invoice

### ISSUE THREAD

**Issue by kbuzby** [akaunting/akaunting#999]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
1) Go to invoice page
2) click create

OR 

1) Click "+" at top of screen
2) Click invoice

### Expected result
Go to invoice creation page

### Actual result
Web page displays "Whoop, looks like something went wrong"

### System information (Akaunting, PHP versions)
This happens on both my local instance, as well as the hosted instance at app.akaunting.
Both versions are 1.3.17 based on lower right corner.

My server is running Apache 2.2 and PHP 7.0 on Synology DSM

**Comment by denisdulici** [comment]
You can enable debug to see more details: https://akaunting.com/docs/developer-manual/debug

Feel free to use the forum for further support.

**Comment by kbuzby** [comment]
Not sure why this was closed without getting the debug information - also, this affects **your** hosted instance at app.akaunting.com

I'm getting the following error on my instance when trying to create an invoice:
```
htmlspecialchars() expects parameter 1 to be string, object given (View: /volume1/web/accounting/resources/views/incomes/invoices/create.blade.php) 
```

**Comment by kbuzby** [comment]
Adding additional information back here in case anyone else either finds this, or if you want to add a fix for this:
The cause was that the "quantity" field name was null and causing the view to not be able to render. It was null because I had apparently set it to "Custom" but did not enter a value. Changing it back to "quantity" worked. 
This was additionally hard to find because once I did not have an additional name entered for the custom value, navigating back to the settings page did not show the custom value field any longer, it only showed the drop down.

The fix that could be made is making the custom name required when "custom" is selected, additionally, it should show the empty field when navigating back to that page if it was empty.
